### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [nerfstudio-project/nerfstudio#1011]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+%^@]|-(?!>)|&(?!&)|\|(?!\|)|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Aktivitäten/nerfstudio/lokal -name '*.py')
```

:crystal_ball: How will the development interests evolve further also according to update candidates in 25 lines of this software?

**Comment by tancik** [comment]
I think you need to be a bit careful with using augmented assignments and pytorch since they are not equivalent,
ie. https://crazyoscarchang.github.io/2018/10/04/in-pytorch-not-the-same/

We will however happily consider PRs with these changes (assuming it is demonstrated that the code still works).

**Comment by elfring** [comment]
:thought_balloon: Will the support ever grow also for applications of in-place data modifications?

:thinking: Would you like to influence such an implementation detail by a corresponding software build option?

Do you find any change possibilities reasonable?
