### ISSUE TITLE
Fbx Import for Camera Tracking

### ISSUE THREAD

**Issue by MarMar54321** [nerfstudio-project/nerfstudio#1016]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**

It would be great if you could make it possible to import fbx animations from blender for example to nerfstudio as camera path. Some other Nerf generating application is able todo so and this makes things easier.

**Describe alternatives you've considered**

**Additional context**

**Comment by tancik** [comment]
This would be a nice feature to include. Do you know of other nerf libraries that have this support that we can reference?

**Comment by MarMar54321** [comment]
Hi,Yes there is one that allow that and you can export an animation From Blender as fbx and import directly to there. It is https://lumalabs.aiNot sure if this answers your question.BRMarkusAm 28.11.2022 um 00:39 schrieb Matthew Tancik ***@***.***>:﻿
This would be a nice feature to include. Do you know of other nerf libraries that have this support that we can reference?

**Comment by tancik** [comment]
Thanks for the extra info! Luma is unfortunately closed source so there isn't much we can gleam from them. There doesn't seem to be an easy to use python FBX library that I can find. Autodesk FBX library doesn't have a pypi package and py-FBX appears to be an unfinished project. I'll keep searching...

**Comment by tancik** [comment]
Yea, that could work, can you provide examples of other python based software doing this?

**Comment by vincepapaix** [comment]
A software like the foundry nuke can import fbx/abc camera system and in the attributes of the camera it converts xyz position rotation to world matrix  
from there you can use the scritping panels to write some code to export out a camera_path.json that can be imported in nerfstudio 

there is non commercial nuke here
https://www.foundry.com/products/nuke-family/non-commercial

Hope it helps

**Comment by tancik** [comment]
We will add a blender workflow which will hopefully capture this workflow in #1218

**Comment by bhack** [comment]
> A software like the foundry nuke can import fbx/abc camera system and in the attributes of the camera it converts xyz position rotation to world matrix
from there you can use the scritping panels to write some code to export out a camera_path.json that can be imported in nerfstudio

Can we re-open this? A direct fbx/abc export it will have a more universal integration coverage.

**Comment by tancik** [comment]
We weren't sure how to add this functionality in practice. Do you have any ideas?

**Comment by bhack** [comment]
You can use the python API https://docs.alembic.io/python/examples.html
