### ISSUE TITLE
experience setting for real scenes

### ISSUE THREAD

**Issue by cv-lab-x** [nerfstudio-project/nerfstudio#1018]
hi, thanks for your great work！ could you share some experiance about the config settings to improve the rendering quality of the training and testing imgs.  what params should we try to improve the quality.
looking forward to your reply, thanks! @tancik

**Comment by tancik** [comment]
How well you capture the scene impacts the quality more than anything else. All of our post on twitter use the default training setting - https://twitter.com/nerfstudioteam.
Are there specific artifacts that you are trying to improve? If you are seeing rippling, you can try increasing the following in the config.yml prior to running `ns-render`.

```
    num_nerf_samples_per_ray: 48
    num_proposal_iterations: 2
    num_proposal_samples_per_ray: !!python/tuple
      - 256
      - 96
```
to 
```
    num_nerf_samples_per_ray: 96
    num_proposal_iterations: 2
    num_proposal_samples_per_ray: !!python/tuple
      - 400
      - 128
```

**Comment by cv-lab-x** [comment]
> How well you capture the scene impacts the quality more than anything else. All of our post on twitter use the default training setting - https://twitter.com/nerfstudioteam. Are there specific artifacts that you are trying to improve? If you are seeing rippling, you can try increasing the following in the config.yml prior to running `ns-render`.
> 
> ```
>     num_nerf_samples_per_ray: 48
>     num_proposal_iterations: 2
>     num_proposal_samples_per_ray: !!python/tuple
>       - 256
>       - 96
> ```
> 
> to
> 
> ```
>     num_nerf_samples_per_ray: 96
>     num_proposal_iterations: 2
>     num_proposal_samples_per_ray: !!python/tuple
>       - 400
>       - 128
> ```

thanks for your reply
