### ISSUE TITLE
ns-process-data insta360 does not support the single-file format used by the insta360 X3

### ISSUE THREAD

**Issue by cnsumner** [nerfstudio-project/nerfstudio#1019]
**Describe the bug**
ns-process-data insta360 throws an error looking for a second file when given single-file 360 footage (both sensor's data in a single file). does not support 360 video where footage from both sensors is in the same file.

**To Reproduce**
1. Record 360 footage with a camera that records to a single file instead of two files. 
    _Note that: Insta360 X3 records to a single file (only 00) in normal video mode and only uses two files (00 and 10) for certain modes, like HDR and TimeShift._
2. Attempt to process data: `ns-process-data insta360 --data .\VID_20220925_113615_00_190.insv --output outputs`
3. See error `FileNotFoundError: Could not find VID_20220925_113615_10_190.insv`

**Expected behavior**
ns-process-data should support single-file 360 footage and an error should not be thrown by `ns-process-data insta360 --data .\VID_20220925_113615_00_190.insv --output outputs` when a second file does not exist (if the single file contains data from two sensors.

**Screenshots**
Here is an example of what the expected two-file format looks like:
Note how there are two separate 1:1 aspect ratio files with "00" and "10" in the files names. This is what ns-process-data is looking for.
![image](https://user-images.githubusercontent.com/3620968/203854306-a595b2e6-779f-40a5-b5bf-ad4ad9a8dd64.png)

Whereas here is what a single-file (seemingly the new standard for insta360 cameras) 360 video looks like:
Note how it's a single file, which is 2:1 aspect ratio, and this one file has "00" in the name. This should be supported.
![image](https://user-images.githubusercontent.com/3620968/203854497-dbf3c354-df31-4241-8329-a6bbd7226e54.png)

**Additional context**
This single file format appears to be the new standard way that insta360 records videos, at least in the new X3 camera.

**Comment by tancik** [comment]
When I originally added support for insta360 I did not realize the had multiple camera setups/models (such as the one you mention here). I think we need a more scalable approach to generally handling fisheye images. Now that our nerfstudio dataparser can handle masks, I plan on adding the ability to specify a "circle" mask when using the `images` or `video` data process images. This should allow anyone with a 360 camera to use our data processing scripts. They next step will be to update the insta360 logic to be a wrapper around the video or image data processing calls. We can then create an argument option `--camera-model` where users can specify their specific insta360 camera model.

**Comment by cnsumner** [comment]
That sounds like a good approach. Hopefully my minor changes to get it working in it's current state will be helpful to someone in the meantime!
