### ISSUE TITLE
why sequential success while vocabtree and exhaustive fail during colmap bundle adjustment

### ISSUE THREAD

**Issue by zhu-yuefeng** [nerfstudio-project/nerfstudio#1021]
I took a video of road scene with front camera when driving forward, and then put these frames (as images) into pipeline. I expect the COLMAP preprocess to get good result for such simple scene, regardless of hyperparameters. However, during bundle adjustment, only 10% images are preserved if exhaustive or vocab_tree are assigned. In contrary, sequential keeps about 90% images. Does anyone have any idea about the reason?

**Comment by tancik** [comment]
We only include a simple wrapper on top of COLMAP. You may get better support asking the COLMAP team directly - https://github.com/colmap/colmap

**Comment by zhu-yuefeng** [comment]
OK. Thank you! @tancik
