### ISSUE TITLE
Error while building wheel for tinycudann

### ISSUE THREAD

**Issue by Klabautermann95** [nerfstudio-project/nerfstudio#1023]
Hello there

I am trying to get nerfstudio running on my device. 
Environment is created and conda installed, 
Python 3.8. active
CUDA 11.3 is set up and tested with the samples
VS 2019 installed
Pytorch versions installed as mentioned in the documentation

Now when it comes to the second step of the dependencies:
_pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch_

I get the errors shown in the screenshot. (I already tried it with a cloned, local repo, same error)
It seems to be a problem with the setup.py in the sub-process and the building of the wheels crashes. If anybody could help me or give me hints on a possible solution, would be very appreciated! 

Thanks in advance

![Screenshot 2022-11-25 232024](https://user-images.githubusercontent.com/102353180/204060524-d42f3612-6a00-40aa-a3e1-4b40aae0bfbf.jpg)

**Comment by MaxPalmer-UH** [comment]
I get this exact issue. What was the solution please?

**Comment by aboutyy** [comment]
I got this same error, any explanation?

**Comment by MaxPalmer-UH** [comment]
I raised this issue on a thread on Discord. Someone else in that thread thought it's related to the version of CUDA you have installed and was recommending 11.6. I haven't had a chance to try this myself. Please let me know if this works for you. https://discordapp.com/channels/1025504971606724712/1026948888936059011/1053276252859011083
