### ISSUE TITLE
BARF-style "annealing" with hash encoding

### ISSUE THREAD

**Issue by lkskstlr** [nerfstudio-project/nerfstudio#1025]
Hi all,

thank you very much for the awesome code :)

Do you have some experience or opinion on using the hash map together with BARF-style annealing of the features? Are you by chance planning on implementing this feature?

I would imagine that one could just activate the levels one after another in a similar fashion as BARF (see screenshot from BARF). However, it might be, that this has unintended consequences due to the higher number of collisions in the coarser levels? I just want to avoid re-doing this myself if you happen to have experience or even an implementation.

Cheers
Lukas

![Screenshot from 2022-11-25 18-28-48](https://user-images.githubusercontent.com/14993470/204069286-72d97908-8fc6-4d1b-8322-f2f6788b6ec9.png)

**Comment by maturk** [comment]
We have implemented a few BARF algorithms here [BARF-nerfstudio](https://github.com/maturk/BARF-nerfstudio). This also includes a hash grid annealing type of BARF implementation called "barf-hash".
