### ISSUE TITLE
Is nerfstudio using depth or distance?

### ISSUE THREAD

**Issue by lkskstlr** [nerfstudio-project/nerfstudio#1028]
**Describe the bug**
This is not a bug in the classical sense, more a question about convention.

Nerfstudio seems to use the word "depth" or "depth map" for quantities that are not a depth map (distance map). To the best of my knowledge, the standard terminology is that depth means the `z` coordinate of the object and distance means the actual Euclidean distance. In that terminology one has `depth <= distance` with `depth==distance` for the principal point.

This is clearest in these two lines: https://github.com/nerfstudio-project/nerfstudio/blob/aac7aa4786f6a6a7ba5da7acfc79db73359d6b28/nerfstudio/model_components/exporters.py#L93-L94

If `depth` were an actual depth map, then it would have to be multiplied by a vector `v` with `v[2] == 1` and not `norm(v) == 1`, however, I think directions always have `norm(directions) == 1`.

**Expected behavior**
If nerfstudio uses `depth` for what is IMHO commonly referred to as `distance` then a note in the README and the `--help` would be good :)

However, the library is great and this overall issue is more a question/nit and not a complaint!

**Comment by kevinddchen** [comment]
As you have correctly pointed out, this is technically the "range" or "distance" using the conventional CV terminology. (Un)fortunately, "depth" is used synonymously with "range/distance" in many NeRF implementations/literature, so this confusing at times.

**Comment by lkskstlr** [comment]
Thanks :)
