### ISSUE TITLE
How to run visualization code in doc?

### ISSUE THREAD

**Issue by HrsPythonix** [nerfstudio-project/nerfstudio#1038]
When I check https://docs.nerf.studio/en/latest/nerfology/model_components/visualize_samples.html, I try to run the visualization code in my nerfstudio env, but it fails with:

`ImportError: cannot import name 'plotly' from 'nerfstudio.utils'`

Any idea what I should do to run the visualization code?

**Comment by tancik** [comment]
You will need to install the following to build the docs,

`pip install -e .[docs]`
and
`conda install -c conda-forge pandoc`

More info here - https://docs.nerf.studio/en/latest/reference/contributing.html

**Comment by HrsPythonix** [comment]
> You will need to install the following to build the docs,
> 
> `pip install -e .[docs]` and `conda install -c conda-forge pandoc`
> 
> More info here - https://docs.nerf.studio/en/latest/reference/contributing.html

I do the installation as you say, but it still throws this error, I find out that it exists error in the doc, for example in  https://docs.nerf.studio/en/latest/nerfology/model_components/visualize_samples.html

`from nerfstudio.utils import plotly as vis` should be `from nerfstudio.utils import plotly_utils as vis`
