### ISSUE TITLE
Does Nerfacto allows for masking moving objects?

### ISSUE THREAD

**Issue by vincepapaix** [nerfstudio-project/nerfstudio#1052]
Hi

Instant-ngp allows to add a dynamic_mask_xyz.png for any training image xyz.* . This file must be in PNG format, where non-zero pixel values indicate masked-away regions.

This is helping a lot for removing unwanted moving object from the training phase.

=> Does Nerfacto have a similar feature? 
I didn't find any information on this topic for Nerfacto.

thanks

**Comment by Zunhammer** [comment]
Yes it does, you need to provide the masks and have a "mask_filename", holding the path and name, in the transforms.json for every frame.

**Comment by vincepapaix** [comment]
Thanks for your reply Nicolas,

can you please clarify if it's a separate file that needs to be added to the transforms.json? or can the alpha be embedded in the main RGB image?

example in my transforms.json file I have:
            "file_path": "xyz.jpg", 

do I need to add something like this
            "file_path": "xyz.jpg", 
            "mask_filename": "xyz_mask.png" //where xyz_mask.png is a RGBA black and white image, white pixel values will removed from training?

If you have any docs that explain this part, I'd love to read it.

thanks

**Comment by swtyree** [comment]
Hi, I just tried this masking method, but the masks didn't seem to be applied to the images, nor were they reflected in the resulting scene. I appending `"mask_path"` to the entry for each frame, and I tried setting the valid/invalid regions to both 0/255 and 255/0, but neither seemed to work. Can you provide any further hints? Thanks!

**Comment by Zunhammer** [comment]
Make sure you're suing the latest version (not release!) as there was a bug in handling masks which I think will be added in 0.1.13. Besides, if you have the mask_path and the script is not complaining it should also use them, black is btw the color to mask out, not white. In the GUI you won't see masks.

**Comment by swtyree** [comment]
Thanks for the quick reply, @Zunhammer! To clarify, the mask be encoded in a 3 channel PNG, with 255 for pixels to keep and 0 for pixels to discard? And does the data loader matter (e.g. `nerfstudio-data`), or any other settings?

**Comment by Zunhammer** [comment]
No, one channel (grayscale). A 3 channel should give an error when loading. I'm using nerfstudio-data, no experiance with the others. Yes 255 to keep, 0 do discard.

**Comment by vincepapaix** [comment]
Thanks for the clarification Zunhammer

I got the mask_path to work, however the quality of my output is significantly less good than if I didn't use the mask. 

Is that expected? 

I'm masking a fast moving object that is very small and I don't expect this to influence the quality of the rest of the image.

**Comment by vincepapaix** [comment]
is it possible to double check the command to launch a training that will be using a mask

do we need to add a flag? or just the regular command?

`ns-train nerfacto --data data/mydata`

**Comment by Zunhammer** [comment]
You shouldn't notice any quality loss, probably your masks are wrong or extremely oversized? Masks should really only mask out the pixels of unwanted objects, in my case I'm using exact masks on pixel level and dilate them for 2 pixels to be safe.
And again, be sure to use the latest version of the repo, not release, to have them working correctly.

**Comment by vincepapaix** [comment]
Thanks Nicolas,
My mask are small (very small black circles to remove fast moving object on the images)

can you please confirm the command you use to launch a training that will be using mask?
I'll double check but so far if I train with this
`ns-train nerfacto --data data/mydata`
it fails and won't train, I'll check what version I have of nerstudio

thanks

**Comment by vincepapaix** [comment]
Thanks Nicolas for all the help
Everything is now working. 

Masking can be an important part of a good looking nerf, there is a lot of good information in this ticket, here is a quick summary:
- need to ask `"mask_path": "masks/12.png", ` in the transforms.json
- mask file needs to be only 1 channel
- mask value 0=disregard 1=keep value for training (which is the opposite of any compositing software btw)
- Mask and training images need the same resolutions
- Use the latest version of nerfstudio, hoping to be added to the next release.

it can be a good idea to mention this in the nerfstudio doc. 

closing issue

**Comment by krahets** [comment]
@Zunhammer @vincepapaix Thanks for the great explanations! Could I use masks filtering the sky to get more clear rendering output? Or Is there a better way to remove "floaters" produced by the sky background?

**Comment by rulke** [comment]
> Thanks Nicolas for all the help Everything is now working.
> 
> Masking can be an important part of a good looking nerf, there is a lot of good information in this ticket, here is a quick summary:
> 
> * need to add  in the transforms.json`"mask_path": "masks/12.png", `
> * mask file needs to be only 1 channel
> * mask value 0=disregard 1=keep value for training (which is the opposite of any compositing software and the opposite of masking in nvidia instant-ngp)
> * Mask and training images need the same resolutions
> * Use the latest version of nerfstudio, hoping to be added to the next release.
> 
> it can be a good idea to mention this in the nerfstudio doc.
> 
> closing issue

Hello, may I ask if the effect can achieve the similar effect of ngp after applying the mask?Thank you

**Comment by vincepapaix** [comment]
Hi rulke

i wont comment in the code side. But about the output, yes the masked pixels won’t be used during the training phase and it results in a cleaner nerf output.
