### ISSUE TITLE
Colab notebook downloading and processing data access denied

### ISSUE THREAD

**Issue by moritztng** [nerfstudio-project/nerfstudio#1062]
Hey, when I choose the poster scene in the downloading and processing data section I get the following error:

```
Access denied with the following error:

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1dmjWGXlJnUxwosN6MVooCDQe970PkD-1
```

I can still download it manually, but I just wanted you to know!

**Comment by tancik** [comment]
Yea, we are hitting download limits on google drive.

**Comment by moritztng** [comment]
Yeah, it's an awesome project so demand is high 🚀

**Comment by ry85** [comment]
The following command solved the problem for me,
!pip install --upgrade --no-cache-dir gdown

**Comment by puzzlefish** [comment]
From what I see the problem isn't due to download limits - @ry85's fix worked for me.

**Comment by akristoffersen** [comment]
@puzzlefish @ry85 Thank you for bringing this up. Sorry I didn't notice this fix earlier.

#1140 should fix the gdown errors, and we have started hosting some of the data on our own servers as well.
