### ISSUE TITLE
mipnerf broken on test datasets

### ISSUE THREAD

**Issue by VelocityRa** [nerfstudio-project/nerfstudio#1071]
**Describe the bug**
Training mipnerf on the `poster` dataset results in this error:
```
FileNotFoundError: [Errno 2] No such file or directory: 'data\\nerfstudio\\poster\\transforms_train.json'
```
There is only a `transforms.json` there, not a `transforms_train.json`.

**To Reproduce**
1. Download the poster dataset
2. Try to run via `ns-train mipnerf --data ./data/nerfstudio/poster`

**Expected behavior**
For the dataset to work, or if that's not meant to work: **for there to be any documentation on how to generate `transforms_train.json`** via COLMAP or whatever.

**Solutions tried**
1) Running `pip install tyro==0.3.33` as suggested in the issue below, it did not help.

**Context**
I just tried nerfstudio for the first time, I wanted a higher quality result, saw `mipnerf` in `ns-train --help`, tried that with the dataset that the docs suggest, and it doesn't work.
If there's a different way of getting high quality results (different nerfacto settings?) that would be good to know.
I don't care about training/rendering speed.

Related to #996, opened as a separate issue because the test datasets provided here don't work either, not just custom datasets (I did not test that myself).

**Comment by tancik** [comment]
Mipnerf defaults to using the blender dataparser. To run on real data the nerfstudio dataparser is necissary.
You can try the following command
`ns-train mipnerf nerfstudio-data --data ./data/nerfstudio/poster`

**Comment by VelocityRa** [comment]
Thanks!

**Comment by VelocityRa** [comment]
Though I tried it on an RTX 3080 Ti with 12 GB of VRAM and it crashed because run out of VRAM, any way to reduce the usage?
