### ISSUE TITLE
ns-train semantic-nerfw (friends dataset) output goes and stays black between step 82000 and 84000

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#1072]
**Describe the bug**
ns-train semantic-nerfw (friends dataset) output goes and stays black between step 82000 and 84000

**To Reproduce**
1. Download or manually copy the friends dataset.
2. `ns-train semantic-nerfw --trainer.save-only-latest-checkpoint False`
3. Open the Web interface to see what's going on
4. **At/after step 84000 (not exactly, perhaps a bit before; takes quite a while to get there) render is black, aargh**
5. `ns-train semantic-nerfw --trainer.load-dir outputs\data\friends\TBBT-big_living_room\semantic-nerfw\YOUR_TIMESTAMP_HERE\nerfstudio_models --viewer.start-train False --trainer.load-step 82000`
6. Open / refresh the Web interface to see what's going on
7. Notice that render is fine (not black)

**Expected behavior**
render should not have gone black...

**Comment by tancik** [comment]
This is related to #873 
Until the NAN error is resolved, we do not recommend training past 30k iters.

**Comment by machenmusik** [comment]
thanks - then perhaps max-num-iterations should be lowered temporarily?

**Comment by machenmusik** [comment]
Closed via #1074
