### ISSUE TITLE
Google Colab not working, default is now Python 3.8

### ISSUE THREAD

**Issue by akristoffersen** [nerfstudio-project/nerfstudio#1077]
**Describe the bug**
The tinycudann install is failing because Colab recently changed to python 3.8, not 3.7

To fix, we should either update the wheel or add an if-case depending on what python version colab is using right now. This would be in case the roll-out isn't immediate for everyone.

**Comment by elloza** [comment]
In the meantime, you can use the runtime fallback version. 

This is available from the Command Palette via the "Use fallback runtime version"

Ref: https://github.com/googlecolab/colabtools/issues/3246

**Comment by puzzlefish** [comment]
Actually, I also had to comment out the condacolab installation, simply reverting to the fallback runtime version did not work for me.

See [my fixed version of the demo notebook](https://github.com/puzzlefish/nerfstudio_demo_issue_1077/blob/main/nerfstudio_demo_issue_1077.ipynb).

The condacolab installation restarts the runtime, which falls back to Python 3.8 per default, hence the tiny cuda installation still fails.

**Comment by akristoffersen** [comment]
@puzzlefish  I just made a PR for this. I spend a good while trying to get a new wheel to work, but with no dice. But luckily the default pip install works fine. Let me know if it works for you!

**Comment by puzzlefish** [comment]
The tinycudann install works in your fix, thanks! 

The only thing is that it takes considerably longer (maybe 13min longer), but given its a temporary fix I guess that's not really an issue.

Unfortunately, the notebook as a whole still fails at the data download part, though due to the unrelated issue #1062, which is, in my opinion unjustly, marked as closed.

**Comment by akristoffersen** [comment]
> The only thing is that it takes considerably longer (maybe 13min longer), but given its a temporary fix I guess that's not really an issue.

@puzzlefish  just created a PR to fix this. Had to bring the tinycuda version down to v1.5, but now its a wheel which should be much faster.

On the data downloading, we are looking into possible solutions to this outside of just reposting the data on google drive. Sorry for the delay on this!
