### ISSUE TITLE
[Question] How to reduce mipnerf VRAM usage

### ISSUE THREAD

**Issue by VelocityRa** [nerfstudio-project/nerfstudio#1078]
I tried the `poster` dataset on an RTX 3080 Ti with its hefty 12 GB of VRAM and it crashed because it run out, any way to reduce the usage?

Is it a function of the training images amount/resolution? I wasn't able to find any such info on the mipnerf repo.

Command used: `ns-train mipnerf nerfstudio-data --data ./data/nerfstudio/poster`
Error: `RuntimeError: CUDA out of memory. Tried to allocate 1.11 GiB (GPU 0; 12.00 GiB total capacity; 9.96 GiB already allocated; 0 bytes free; 10.86 GiB reserved in total by PyTorch)`

---
Also, given that it can't even seem to run on a 3080 Ti, is mipnerf just not used much? Would I get equally high quality results using nerfacto with more steps / different settings?

Thank you.

**Comment by VelocityRa** [comment]
> Is it a function of the training images amount/resolution? I wasn't able to find any such info on the mipnerf repo.

Update: it does not seem to be - I reduced the dataset to just 6 images and it run out of VRAM again (>11GB usage).

**Comment by krahets** [comment]
Please try decreasing the batch size using `--pipeline.datamanager.train-num-rays-per-batch 1024` argument.

**Comment by pooncs** [comment]
For mipNerf, you probably have to reduce the batch size significantly, it takes up alot of vram. Correct me if I'm wrong, but it think it is this arg --pipeline.datamanager.train-num-rays-per-batch. Try dropping it from the default (8192) to 2048 or something.

**Comment by tancik** [comment]
Yes, @pooncs is correct. In the latest github version, we lowered the defaults.

**Comment by VelocityRa** [comment]
Fixed, thanks!

**Comment by qhdqhd** [comment]
Hello， I find this mipnerf behave bad on poster dataset, did you successfully train it? Thank you.

**Comment by VelocityRa** [comment]
@qhdqhd I don't remember, I stopped trying to use mipnerf, as there is not much point for practical usage compared to nerfacto. Use nerfacto if you just want good results in most usecases.

**Comment by tancik** [comment]
@qhdqhd Similar to the [paper](https://jonbarron.info/mipnerf/), mipnerf is only setup to work well with the blender synthetic data. Real world data like the poster scene have additional complications that are not considered in mipnerf.
