### ISSUE TITLE
Consider CUDA 11.3 --> 11.6 to support newer hardware

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#1080]
(As per https://github.com/nerfstudio-project/nerfstudio/issues/1012#issuecomment-1327046261)

**Comment by machenmusik** [comment]
In trying this from scratch with 11.6 instead of 11.3, I notice errors around pybind11 e.g.

```
2 errors detected in the compilation of "C:/(redacted)/lib/site-packages/nerfacc/cuda/csrc/ray_marching.cu".
```
...
```
c:\(redacted)\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

c:\(redacted)\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here
```

**Comment by machenmusik** [comment]
I will have to check later, there are some related GH issues on other projects with various suggestions.  What version of VS2019 did you have working?

**Comment by machenmusik** [comment]
E g. https://github.com/facebookresearch/pytorch3d/issues/1024

**Comment by minsoo5403** [comment]
![image](https://user-images.githubusercontent.com/16278227/207760818-783e7a3b-f95a-4300-86c2-9d08e91877dd.png)

**Comment by minsoo5403** [comment]
I will share the instructions after reinstalling.

**Comment by minsoo5403** [comment]
conda create --name nerfstudio -y python=3.8
conda activate nerfstudio
python -m pip install --upgrade pip

pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 -f https://download.pytorch.org/whl/torch_stable.html
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch

git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .

![image](https://user-images.githubusercontent.com/16278227/207762854-8946d574-5b17-44b7-abf5-7a9e1c0952b7.png)

**Comment by machenmusik** [comment]
Thanks! 

I inadvertently misstated when the compilation issue arises; it doesn't happen during nerfstudio pip install, but rather when training with instant-ngp, and only after some time trying to use viewer, images can be seen but the scene is never rendered.  It appears to be something compiled on demand (perhaps for nerfacc and CUDA?) which fails.  Note that nerfacto training and viewing works fine.

I have tried VS2019 Version 16.11.20 `Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30146 for x64`.
From https://github.com/facebookresearch/pytorch3d/issues/1024#issuecomment-1007347129 it appears that downgrading to VS2019 16.9.6 may solve it, but that is quite old, and does not seem like the best solution.

**Comment by machenmusik** [comment]
It appears from https://github.com/pytorch/pytorch/issues/69460 that CUDA 11.7 fixes it, but there doesn't seem to be a torch 1.12.1 with CUDA 11.7 and nerfstudio doesn't seem to like torch 1.13

**Comment by minsoo5403** [comment]
During several Ubuntu installations, we found that high C++ compiler versions could cause problems between CUDA/TCNN and CUDA/Pytorch.

So I deliberately lowered the C++ version to build it when I installed Windows.

For Ubuntu: 
Use CUDA-11.3 and fail compile on GCC-11.
Use CUDA-11.3 and successfully compile on GCC-9.

**Comment by machenmusik** [comment]
Note that using VS2019 BuildTools 16.9.6 does not appear to solve the issue with CUDA 11.6 and instant-ngp :-/

**Comment by machenmusik** [comment]
I'm going to abandon this for now, it doesn't seem worth the effort for instant-ngp with Windows, and otherwise it seems to work for others.
