### ISSUE TITLE
How to move bound boxes in mesh export ??

### ISSUE THREAD

**Issue by minsoo5403** [nerfstudio-project/nerfstudio#1081]
Can I apply the movement of bound_box in TSDF or Position method on exporter.py? 

When bound_box is 1, 1, 1  it works very fast, but as the size increases, the consumption time increases exponentially. (Xatlas does not end)

I want to fix the size of the Bound_box size to 1 or 2 and move the position of the box to perform mesh several times.

**Comment by tancik** [comment]
The two arguments,  `--bounding-box-min FLOAT FLOAT FLOAT` and `--bounding-box-max FLOAT FLOAT FLOAT` define the min and max corners of the box. If you add the same offset to each of these arguments it will translate the box.

**Comment by tancik** [comment]
Closing issue, feel free to reopen if my answer doesn't make sense.
