### ISSUE TITLE
Is the instant-ngp compatible for export with the reference implementation

### ISSUE THREAD

**Issue by reynoldscem** [nerfstudio-project/nerfstudio#1088]
Hi,

I'm looking to extend `instant-ngp`, and would like to do it using the implementation built into this project. However, once the model is trained I'd like to be able to export it and render frames out from the reference `nvidia` implementation of it. I was wondering if this is at all possible, if it's natively supported already, or if not, whether the representation is such that this would be easily achievable?

Thank you

**Comment by tancik** [comment]
These two systems backends are quite different from each other, nerfstudio is pytorch, instant-ngp is a custom c++ implementation. Creating a conversion script would likely involve a fair amount of work.

**Comment by reynoldscem** [comment]
Thanks, I suspected this might be the case. Cheers for confirming.
