### ISSUE TITLE
Rendering looks quite poor for emissive lights, and reflective surfaces

### ISSUE THREAD

**Issue by dragonlong** [nerfstudio-project/nerfstudio#1102]
**Describe the bug**
Hi, I tried to use nerfstudio 0.1.11 to capture a small room, in which I used my Iphone to walk around the room slowly. About 1.8k images are used to train the nerfacto variant for 40k steps. Surprisingly even though that I am getting good PSNR metrics of training:evaluation=31dB:23dB, the rendering (the right one the screenshots) looks quite blurred, especially for the clock with glasses surface (we cannot even see the numbers), and the ceiling bulb which is an emissive lighting source. I am wondering whether this is a normal performance even for SOTA nerfs methods, or it is a bug/feature that we need to improve. Thanks!

**Screenshots**
<img width="1753" alt="image" src="https://user-images.githubusercontent.com/8425887/206543418-4691e247-e140-4d2e-a7fc-770a8c8410a4.png">
<img width="1749" alt="image" src="https://user-images.githubusercontent.com/8425887/206543548-16702cc2-a6e4-42ab-b8e9-5b3d02a97a52.png">

**Comment by tancik** [comment]
Much of the quality of NeRF depends on the input data. If there is noise in the poses it can lead to blurry results (the roof-tile lines looks like there might be some pose issues). Did you use COLMAP for finding the poses, or another method? Also, though not always the case, having too many input images can sometimes degrade the quality. I've personally found that targeting ~300-500 images to work the best.

**Comment by dragonlong** [comment]
Thanks Matthew for the suggestions! I just used the default Record3D poses, maybe in this way maybe I could also give Colmap poses a try.  I remembered that Instant-ngp also recommends using only ~150 images, I am wondering the intuitions behind on "many input images can sometimes degrade the quality", is that mainly due to inaccurate poses make the model 'confused' given dense frames? Or is it due to less chance of being sampled for each frame?

**Comment by tancik** [comment]
Record3D poses are often not great, I would recommend using Polycam or COLMAP. My intuition on why it is worse is a combination of both, aggregated pose inaccuracies and less sampling.

**Comment by dux915hhh** [comment]
> having too many input images can sometimes degrade the quality

Do you know why having too many input images can sometimes degrade the quality? I run the code and got 'COLMAP only found poses for 1.06% of the images. This is low. This can be caused by a variety of reasons, such poor scene coverage, blurry images, or large exposure changes." Thank you.

**Comment by maturk** [comment]
> > having too many input images can sometimes degrade the quality
> 
> Do you know why having too many input images can sometimes degrade the quality? I run the code and got 'COLMAP only found poses for 1.06% of the images. This is low. This can be caused by a variety of reasons, such poor scene coverage, blurry images, or large exposure changes." Thank you.

Hey @dux915hhh, if colmap does not find poses for the images, this means that the texture or image quality is poor for the shift feature matching in colmap. Colmap is responsible for the poses of the training images, which is very important for good reconstructions with nerf. Also, when training a nerf, quality of images is more important than the number of images. You want good images with little motion blur and good texture information. Hope this can guide your work.

**Comment by dux915hhh** [comment]
> > > having too many input images can sometimes degrade the quality
> > 
> > 
> > Do you know why having too many input images can sometimes degrade the quality? I run the code and got 'COLMAP only found poses for 1.06% of the images. This is low. This can be caused by a variety of reasons, such poor scene coverage, blurry images, or large exposure changes." Thank you.
> 
> Hey @dux915hhh, if colmap does not find poses for the images, this means that the texture or image quality is poor for the shift feature matching in colmap. Colmap is responsible for the poses of the training images, which is very important for good reconstructions with nerf. Also, when training a nerf, quality of images is more important than the number of images. You want good images with little motion blur and good texture information. Hope this can guide your work.

Thank you so much. I also found the default of Maximum number of training images to display in the viewer in nerfstudio, it is 512, and I tried 511 and 513 to prove it worked.
