### ISSUE TITLE
Training ETA (estimated time of arrival)

### ISSUE THREAD

**Issue by VelocityRa** [nerfstudio-project/nerfstudio#1112]
`ns-render` shows an ETA, would be nice if `ns-train` did as well.

**Comment by TheCob11** [comment]
I might be totally silly (I'm new here) but it looks like there's code for that in here?
https://github.com/nerfstudio-project/nerfstudio/commit/2144fd152710e02dc3b15c35f570b1c8d826e78f

**Comment by THE-COB** [comment]
Hi, I made a PR for this [https://github.com/nerfstudio-project/nerfstudio/pull/1203](https://github.com/nerfstudio-project/nerfstudio/pull/1203)

LMK if this is wanted/needed/correct @tancik @VelocityRa

**Comment by VelocityRa** [comment]
Thanks!
