### ISSUE TITLE
ImportError: version Qt_5 not defined in file libQt5Xml.so.5 with link time reference

### ISSUE THREAD

**Issue by tojiboyevf** [nerfstudio-project/nerfstudio#1121]
**Describe the bug**
I run following command to obtain the point cloud in colab demo:
```
ns-export pointcloud --load-config outputs/data-nerfstudio-poster/nerfacto/2022-12-13_194317/config.yml --output-dir exports/pcd/ --num-points 1000000 --remove-outliers True --estimate-normals False --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1
```

But it's showing the next error:
```
Traceback (most recent call last):
  File "/usr/local/bin/ns-export", line 5, in <module>
    from scripts.exporter import entrypoint
  File "/usr/local/lib/python3.8/site-packages/scripts/exporter.py", line 20, in <module>
    from nerfstudio.exporter import texture_utils, tsdf_utils
  File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/texture_utils.py", line 36, in <module>
    from nerfstudio.exporter.exporter_utils import Mesh
  File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/exporter_utils.py", line 29, in <module>
    import pymeshlab
  File "/usr/local/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
    from .pmeshlab import *
ImportError: /usr/local/lib/python3.8/site-packages/pymeshlab/lib/libmeshlab-common.so: symbol __cxa_throw_bad_array_new_length version Qt_5 not defined in file libQt5Xml.so.5 with link time reference
```

**Comment by borjatur** [comment]
I was getting this same error when using latest docker image 0.1.13, finally got this fixed by building my own image as follows 
```
FROM dromni/nerfstudio:0.1.13
USER root
RUN apt remove libqt* qt* -y
USER user
```

**Comment by gowriaddepalli** [comment]
> **Describe the bug** I run following command to obtain the point cloud in colab demo:
> 
> ```
> ns-export pointcloud --load-config outputs/data-nerfstudio-poster/nerfacto/2022-12-13_194317/config.yml --output-dir exports/pcd/ --num-points 1000000 --remove-outliers True --estimate-normals False --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1
> ```
> 
> But it's showing the next error:
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/ns-export", line 5, in <module>
>     from scripts.exporter import entrypoint
>   File "/usr/local/lib/python3.8/site-packages/scripts/exporter.py", line 20, in <module>
>     from nerfstudio.exporter import texture_utils, tsdf_utils
>   File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/texture_utils.py", line 36, in <module>
>     from nerfstudio.exporter.exporter_utils import Mesh
>   File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/exporter_utils.py", line 29, in <module>
>     import pymeshlab
>   File "/usr/local/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
>     from .pmeshlab import *
> ImportError: /usr/local/lib/python3.8/site-packages/pymeshlab/lib/libmeshlab-common.so: symbol __cxa_throw_bad_array_new_length version Qt_5 not defined in file libQt5Xml.so.5 with link time reference
> ```
@tojiboyevf how did you resolve this in colab?

**Comment by gowriaddepalli** [comment]
> I was getting this same error when using latest docker image 0.1.13, finally got this fixed by building my own image as follows
> 
> ```
> FROM dromni/nerfstudio:0.1.13
> USER root
> RUN apt remove libqt* qt* -y
> USER user
> ```
> 
> EDIT: BTW this breaks the command ns-process-data, I was only interested in training though

This solution doesn't work on colab @borjatur . Please let me know any alternative solution if you have that can help it work on colab. Thanks.

**Comment by tojiboyevf** [comment]
> > **Describe the bug** I run following command to obtain the point cloud in colab demo:
> > ```
> > ns-export pointcloud --load-config outputs/data-nerfstudio-poster/nerfacto/2022-12-13_194317/config.yml --output-dir exports/pcd/ --num-points 1000000 --remove-outliers True --estimate-normals False --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But it's showing the next error:
> > ```
> > Traceback (most recent call last):
> >   File "/usr/local/bin/ns-export", line 5, in <module>
> >     from scripts.exporter import entrypoint
> >   File "/usr/local/lib/python3.8/site-packages/scripts/exporter.py", line 20, in <module>
> >     from nerfstudio.exporter import texture_utils, tsdf_utils
> >   File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/texture_utils.py", line 36, in <module>
> >     from nerfstudio.exporter.exporter_utils import Mesh
> >   File "/usr/local/lib/python3.8/site-packages/nerfstudio/exporter/exporter_utils.py", line 29, in <module>
> >     import pymeshlab
> >   File "/usr/local/lib/python3.8/site-packages/pymeshlab/__init__.py", line 11, in <module>
> >     from .pmeshlab import *
> > ImportError: /usr/local/lib/python3.8/site-packages/pymeshlab/lib/libmeshlab-common.so: symbol __cxa_throw_bad_array_new_length version Qt_5 not defined in file libQt5Xml.so.5 with link time reference
> > ```
> 
> @tojiboyevf how did you resolve this in colab? cc: @tancik @akristoffersen

Hi! @gowriaddepalli. Right now I am using a Docker image. That's why I've not tried to solve this issue in colab

**Comment by gowriaddepalli** [comment]
Thanks a lot.

**Comment by akristoffersen** [comment]
@gowriaddepalli  @tojiboyevf 
Looks like I was able to fix the issue by recommendation from [this github issue.](https://github.com/stepjam/PyRep/issues/76#issuecomment-559099448) 

After training and copying down the export command, run `!conda remove --force qt-main` to remove conda's version of Qt. Then run the export command in a cell as you normally would.

This might have issues with training, so I would only run this after you've done your model training.

**Comment by gowriaddepalli** [comment]
> !conda remove --force qt-main

@akristoffersen Thanks for the reply. Its moved ahead since the past issue `✅ Unwrapped mesh with xatlas method
Creating texture image by rendering with NeRF...` It is stuck here, do you know how much time does it take to get past this? Thanks a lot for your help @akristoffersen
