### ISSUE TITLE
transforms.json file is not generated.

### ISSUE THREAD

**Issue by amir-opal** [nerfstudio-project/nerfstudio#1127]
When I process data, no transforms.json file is generated. Folders named images, images_2, images_4, and images_8 are generated with images. However, the folder named colmap is empty.
What should I do to get the transforms.json file?

**Comment by tancik** [comment]
The `ns-process-data` script should produce the `transforms.json` file. Did you see any errors when you ran it? Can you post the full set of output logs from the script.

**Comment by amir-opal** [comment]
I didn't get any error. I run the code on colab. Below is the output.
When I run Processing Data:
`(    ● ) Copying images...[10:40:30] 🎉 Done copying images.`
When I run Start Training:
`Error: Data processing did not complete`

**Comment by ethansmith2000** [comment]
I am having the same issue

**Comment by tancik** [comment]
It looks like the processing data script did not complete successfully. Unfortunately there is a limitation (bug?) with colab where the full output is not printed to the terminal which makes debugging a bit harder. Here is another case where this has occurred (https://github.com/nerfstudio-project/nerfstudio/issues/1113#issuecomment-1347198569)
Most likely COLMAP failed to complete. How many images are you processing and what is the resolution? I would target 150-300 images with a resolution ~1000x1000

**Comment by ethansmith2000** [comment]
ah that could be part of it, my images are 1024x1024, but there are only 4 of them.
