### ISSUE TITLE
Error running ns-export in docker

### ISSUE THREAD

**Issue by gowriaddepalli** [nerfstudio-project/nerfstudio#1129]
I have cloned this repo [https://github.com/nerfstudio-project/nerfstudio] and i was trying to build the docker file within the repo (successful) and while doing `ns-export` on terminal, i get the following error which i fail to resolve: "Cannot mix incompatible Qt library (5.12.8) with this library (5.15.2)" Can you please help me resolve this issue. 

The only change i made in the docker file was to change `ENV TCNN_CUDA_ARCHITECTURES=86` to `ENV TCNN_CUDA_ARCHITECTURES=80` to get `ns-train` to work.

**Comment by gowriaddepalli** [comment]
I get the following error: `$ ns-train
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/home/user/nerfstudio/scripts/train.py", line 50, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/home/user/nerfstudio/nerfstudio/configs/method_configs.py", line 45, in <module>
    from nerfstudio.field_components.temporal_distortions import TemporalDistortionKind
  File "/home/user/nerfstudio/nerfstudio/field_components/_init_.py", line 17, in <module>
    from .encodings import Encoding, ScalingAndOffset
  File "/home/user/nerfstudio/nerfstudio/field_components/encodings.py", line 34, in <module>
    import tinycudann as tcnn
  File "/home/user/.local/lib/python3.8/site-packages/tinycudann/_init_.py", line 9, in <module>
    from tinycudann.modules import free_temporary_memory, NetworkWithInputEncoding, Network, Encoding
  File "/home/user/.local/lib/python3.8/site-packages/tinycudann/modules.py", line 33, in <module>
    if _C is None:
NameError: name '_C' is not defined` when i do `ns-train` and i had to change `ENV TCNN_CUDA_ARCHITECTURES=86 to ENV TCNN_CUDA_ARCHITECTURES=80 `to get ns-train to work.

**Comment by akristoffersen** [comment]
I think I've also seen this in the Google Colab. The fix there was to revert to Tinycudann v1.5. Could you try that possibly?

Also feel free to submit you fixed docker image as a PR, it looks like people have been having trouble with the Docker lately.

**Comment by gowriaddepalli** [comment]
> I think I've also seen this in the Google Colab. The fix there was to revert to Tinycudann v1.5. Could you try that possibly?
> 
> Also feel free to submit you fixed docker image as a PR, it looks like people have been having trouble with the Docker lately.

@akristoffersen @tancik isn't the tinycudann already being used in colab: `!pip install tinycudann-1.5-cp38-cp38-linux_x86_64.whl` let me know if there is something else to change.
