### ISSUE TITLE
ns-export

### ISSUE THREAD

**Issue by gowriaddepalli** [nerfstudio-project/nerfstudio#1152]
I am trying to do a `ns-export` on lego blender dataset and it is stuck or moving ahead, i don't know. I am using `tsdf` based method and it did generate the file `tsdf_mesh.ply` and it seems stuck on "creating texture image by rendering with nerf.." Is this normal? @tancik please let me know. Thanks.

**Comment by akristoffersen** [comment]
Hi @gowriaddepalli, please see [this solution to another issue](https://github.com/nerfstudio-project/nerfstudio/issues/1121#issuecomment-1360501564) for a possible solution. Please let me know if you hit any other issues, thanks!

**Comment by gowriaddepalli** [comment]
> I am trying to do a `ns-export` on lego blender dataset and it is stuck or moving ahead, i don't know. I am using `tsdf` based method and it did generate the file `tsdf_mesh.ply` and it seems stuck on "creating texture image by rendering with nerf.." Is this normal? @tancik please let me know. Thanks.

I am facing this in my docker file not in google colab, so i wanted to know more about it.

**Comment by akristoffersen** [comment]
@gowriaddepalli are you up-to-date with the current docker image? I think there was something merged recently that fixed the docker ns-exporting.

**Comment by gowriaddepalli** [comment]
I shall look into it and get back to you @akristoffersen thanks.

**Comment by gowriaddepalli** [comment]
@akristoffersen i see that when i run the same as above on` blender data ` with the command `ns-train instant-ngp-bounded --data data/nerf_synthetic/lego blender-data` and do `ns-export tsdf --load-config config.yml --output-dir output-dir` it seems stuck on "creating texture image by rendering with nerf.." while the same` ns-export` runs quickly and completes when i run on poster data (nerfstudio data format) . I see both these observations on google colab. @akristoffersen Please let me know. Thanks.

**Comment by dozeri83** [comment]
@tancik @gowriaddepalli  ,this hang is originated from ray_marching method in nerfacc package from the C code. so it seems to me like a potential bug in nerfacc.

**Comment by tancik** [comment]
@dozeri83 Thanks for digging into this!

**Comment by gowriaddepalli** [comment]
Thanks a lot @dozeri83 for this.

**Comment by gowriaddepalli** [comment]
@dozeri83 i see the pull request 136 merged in nerfacc. Just to confirm, there will be some more work needed to upgrade nerfstudio with this fix of nerfacc? Thanks.

**Comment by dozeri83** [comment]
I think so, This is related to #1147

**Comment by gowriaddepalli** [comment]
Thanks @dozeri83

**Comment by gowriaddepalli** [comment]
@tancik @dozeri83 is this bug fixed in google colab too?
