### ISSUE TITLE
aabb crop for rendering a cropped nerf

### ISSUE THREAD

**Issue by vincepapaix** [nerfstudio-project/nerfstudio#1161]
Implement a similar function as nvidia instant-ngp crop aabb as seen in Jonathan's video at 6min20
https://www.youtube.com/watch?v=k67qHXRhdY4

Preference will be to have that for all nerf models, but ideally nerfacto.

=> this will be beneficial to crop out unwanted 'floaties in the FG of the video
=> bonus, if we can export the nerf with a matte (alpha), to be composited on other videos.

thanks

**Comment by tancik** [comment]
Now supported.
