### ISSUE TITLE
Render in google collab

### ISSUE THREAD

**Issue by MagomedKaziev** [nerfstudio-project/nerfstudio#1182]
Where i have to use command to render video if I use google col
<img width="1470" alt="Screenshot 2022-12-28 at 13 45 28" src="https://user-images.githubusercontent.com/111250316/209777719-7f66e361-5988-4f87-ad9d-31932ded4d41.png">
ab?

**Comment by tancik** [comment]
Stop the training cell, then run the last cell.
<img width="821" alt="image" src="https://user-images.githubusercontent.com/3310961/209846376-2eeef536-05b2-4e7f-9e1a-f4c30ffbf69c.png">

**Comment by MagomedKaziev** [comment]
genius:)
thank u!
happy new year! 👍
