### ISSUE TITLE
ERROR when installing tiny-coda-nn

### ISSUE THREAD

**Issue by Cerf-Volant425** [nerfstudio-project/nerfstudio#1186]
When I install tiny-coda-nn on my remote server,
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
but I got this
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/79494908/210013141-27f91340-9065-4a7d-9e37-59224446561f.png">

Here is the version of my pip 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/79494908/210019765-a906500e-7493-4020-8b69-8c7d7524bc49.png">

Any help would be highly appreciated, thanks in advance.

**Comment by tancik** [comment]
It looks like your server isn't able to access github.com/NVlabs/tiny-cuda-nn
Do you by anychance have a firewall that would prevent github access?

**Comment by Cerf-Volant425** [comment]
Thanks for your reply, I solve this problem by resetting the proxy.
