### ISSUE TITLE
Include "--vis viewer" in sample "ns-train" command on the README

### ISSUE THREAD

**Issue by UPstartDeveloper** [nerfstudio-project/nerfstudio#1194]
**Describe the bug**

On the [README](https://github.com/nerfstudio-project/nerfstudio), it implies the `ns-train` command will launch the web viewer by default. However when I tried it today it just launched WanB. I believe this is due to the `--vis` option being set to `wandb` by default, not `viewer` (although in the future, it'd be nice to be able to use both simultaneously.

Anyway, I got confused and I figured it might be worth updating the README to include the `--vis viewer` arg, so that the user can see the viewer while training runs. 

**To Reproduce**
Steps to reproduce the behavior: just following the first-time setup instructions on the README:
```bash
conda create --name nerfstudio -y python=3.8
conda activate nerfstudio
python -m pip install --upgrade pip
conda create --name nerfstudio -y python=3.8
conda activate nerfstudio
python -m pip install --upgrade pip
pip install nerfstudio
# I have a custom dataset, and I trained using TensoRF
ns-train tensorf --data data/engine_6_ds/
```

**Expected behavior**
When I go to https://viewer.nerf.studio/?websocket_url=ws://localhost:7007 after running `ns-train nerfacto --data data/nerfstudio/poster`, it should show the viewer is connected. 

**Screenshots**

<img width="1246" alt="Screen Shot 2022-12-31 at 7 51 34 PM" src="https://user-images.githubusercontent.com/35160126/210158399-bfd66d57-0dd9-413f-8542-a2bab66e5aca.png">

**Additional context**
- I just tried `nerfstudio` for the first time today. So I'm not if this could just be an issue with the latest version (I installed using `pip`).
- this was tested on Google Chrome

Thanks for creating this project! It is so helpful to have all these tools in one place.

**Comment by HI6HPIN6** [comment]
were you able to solve it? I am having the same issue.

**Comment by brentyi** [comment]
This looks like a tensorf-specific default config value.

cc @terrancewang does it make sense to set the default vis method for tensorf to `viewer`? Is it fast enough?

**Comment by terrancewang** [comment]
Oh yeah looks like the default for tensorf is set to wandb right now. tensorf is fast enough to work with the viewer on my machine and should be fine in general. I'll set it to the viewer, thanks for pointing this out!
