### ISSUE TITLE
Why training speed of MipNeRF is so slow? Is NeRFACC used?

### ISSUE THREAD

**Issue by qhdqhd** [nerfstudio-project/nerfstudio#1207]
My GPU is RTX6000 (24GB), cuda is 11.3, nvidia driver is 525.
![2R8OL8_`JJZ)K1{250E9XAI](https://user-images.githubusercontent.com/42370719/210916759-fd77c306-dd31-461a-82a7-8b2f4ec79646.png)

 I train nerfstudio/poster data using mipnerf. I use default training parameters without any changes.
After 12 hours training, it seems  finished 23%.
![)1$18WKNKWQEJ)NOP5P~6 3](https://user-images.githubusercontent.com/42370719/210916376-9386e061-98ad-4769-b697-b06a87dc029a.png)

![40$6C)FPGTNE28TWZXH)9](https://user-images.githubusercontent.com/42370719/210916593-95a4bed9-ee59-4616-806e-1c60030166fb.png)
And the result seems bad...
![W@5U( E86)X2H}{P)XGWFN2](https://user-images.githubusercontent.com/42370719/210917050-348d4d2a-660e-4455-b617-1b3957c6eb30.png)

**Comment by tancik** [comment]
The mipnerf model is based off of the mipnerf paper which came out before all of the speed optimizations. Multiday training times is expected. It is also only set up to work on the blender synthetic data, not the real data (similar to the paper).

**Comment by qhdqhd** [comment]
> mipnerf 模型基于在所有速度优化之前发表的 mipnerf 论文。预计需要多天的培训时间。它也只设置为处理 blender 合成数据，而不是真实数据（类似于论文）。
 Thanks for your fast reply!
I wonder if Nerfacc or other tools are used to speed up mip-nerf?

**Comment by tancik** [comment]
It's hard to say, mipnerf effectively stores each region of space at a continuous set of resolutions. This makes is a bit tricky when using fixed resolution voxel based speedups like nerfacc. Not saying it's impossible, but some extra care is needed.

**Comment by qhdqhd** [comment]
https://github.com/KAIR-BAIR/nerfacc/issues/88
Look, I find this.


> 很难说，mipnerf 有效地以一组连续的分辨率存储每个空间区域。这使得在使用像 nerfacc 这样的基于固定分辨率体素的加速时有点棘手。并不是说这是不可能的，但需要格外小心。
