### ISSUE TITLE
How to create dataset with mask?

### ISSUE THREAD

**Issue by HrsPythonix** [nerfstudio-project/nerfstudio#1208]
Hello, I'd like to try to train the model with masked dataset, the mask can handle the transient object in the scene, how can I do that? what is the requirement for the mask?

**Comment by tancik** [comment]
The following will eventually be added to the docs, posting for reference now
<img width="944" alt="image" src="https://user-images.githubusercontent.com/3310961/210928320-4a1b246f-26f2-4259-b256-ff29b2a52067.png">

Note the way we handle masks right not is not efficient. You may find that memory usage increases and training speed decreases.

**Comment by HrsPythonix** [comment]
> The following will eventually be added to the docs, posting for reference now <img alt="image" width="944" src="https://user-images.githubusercontent.com/3310961/210928320-4a1b246f-26f2-4259-b256-ff29b2a52067.png">
> 
> Note the way we handle masks right not is not efficient. You may find that memory usage increases and training speed decreases.

Two problems,
1. Should each of the frame have an individual mask? if we do not need to mask a frame, should we assign an white empty mask?
2. I tried simply adding mask to all the frames, but it shows CUDA out of memory, the dataset size is 305, normally it will cost several GB of GPU memory without mask, but adding mask make it says `RuntimeError: CUDA out of memory. Tried to allocate 50.92 GiB (GPU 0; 22.06 GiB total capacity; 1.90 GiB already allocated; 19.34 GiB free; 1.91 GiB reserved in total by PyTorch) `, is that normal?

**Comment by HrsPythonix** [comment]
in this line:
`
nerfstudio/nerfstudio/data/pixel_samplers.py", line 65, in sample_method
    nonzero_indices = torch.nonzero(mask[..., 0], as_tuple=False)
`

**Comment by tancik** [comment]
Yes, each image need a mask, use white if unnecessary.
And yea, there it is currently very memory inefficient. Fixing this is a larger change that requires some lower level refactoring.

**Comment by HrsPythonix** [comment]
> Yes, each image need a mask, use white if unnecessary. And yea, there it is currently very memory inefficient. Fixing this is a larger change that requires some lower level refactoring.

ok, then I have to move this operation to CPU, looking forward to fix this in future

**Comment by edwardchenomni** [comment]
Any suggestion on dealing with `RuntimeError: CUDA out of memory.` error?
How can I adjust the batch size of the training? or this do not help?
How can I make the training code work on CPU only?

**Comment by tancik** [comment]
Currently there is not a great solution for masking.

**Comment by tobiasfshr** [comment]
@tancik why not index the mask tensor directly instead of calling `nonzero` on it?
```python
        if isinstance(mask, torch.Tensor):
            sampled_indices = []
            while sum([len(i) for i in sampled_indices]) < batch_size:
                indices = torch.floor(
                    torch.rand((batch_size, 3), device=device)
                    * torch.tensor([num_images, image_height, image_width], device=device)
                ).long()
                keep_mask = mask[indices[:, 0], indices[:, 1], indices[:, 2]].squeeze(-1)
                indices = indices[keep_mask]
                sampled_indices.append(indices)

            indices = torch.cat(sampled_indices)[:batch_size]
```
This should only need a few iterations to complete the batch sampling even with heavy masking and has solved my memory issues.

**Comment by pierremerriaux-leddartech** [comment]
Hi guys,
Just a update, to know if something move on mask and GPU memory consumption.
If I need to drill down, is the @tancik proposal still the favorite one ?
thanks
