### ISSUE TITLE
Progressively add training data

### ISSUE THREAD

**Issue by RafailFridman** [nerfstudio-project/nerfstudio#1209]
Hi!
Is it possible to progressively add training data with nerfstudio?
Starting, for example, from a single image + depth, fitting a model to it, adding a new frame+depth and fine-tuning on it, and so on. 
Ideally, I would like to still use the viewer for visualizing the training progress, and also be able to add more frames while it is training.

**Comment by tancik** [comment]
There isn't currently a prebuilt method to do this, but it should be possible by subclassing the dataloader with a custom one.

**Comment by tancik** [comment]
Take a look at https://github.com/javieryu/nsros_bridge for an example.
