### ISSUE TITLE
Bad perpomance on nerfstudio dataset (kitchen dataset) using mipnerf and vanilla-nerf.

### ISSUE THREAD

**Issue by qhdqhd** [nerfstudio-project/nerfstudio#1211]
After 2 days of training, I still get bad rendering result.
![wandb ai_qhd_nerfstudio-project_runs_93vrlfah_workspace=user-qhd](https://user-images.githubusercontent.com/42370719/211237349-736c2c78-1451-45df-85ab-20c1ff029352.png)

**Comment by tancik** [comment]
mipnerf isn't set up to work well with real scenes. It is optimized for blender scenes. If you want to reconstruct real-scenes, we reccomend using the nerfacto model.
