### ISSUE TITLE
Possibly outdated training instructions in Quickstart

### ISSUE THREAD

**Issue by Mason-McGough** [nerfstudio-project/nerfstudio#1222]
Just a minor issue, but I noticed that when executing the following instructions from section [2: Training your first model!](https://github.com/nerfstudio-project/nerfstudio/#2-training-your-first-model) of the Quickstart:

```bash
# Download some test data:
ns-download-data --dataset nerfstudio --capture-name=poster
# Train model
ns-train nerfacto --data data/nerfstudio/poster
```

I receive the following error:

```bash
ns-download-data --dataset nerfstudio --capture-name=poster
usage: ns-download-data [-h] {blender,friends,nerfstudio,record3d,dnerf,phototourism}

 
ns-download-data: error: unrecognized arguments: --dataset
```

Using `ns-download-data -h` was helpful and I was able to fix it with the modification:

```bash
ns-download-data nerfstudio --capture-name=poster
```

Are these instructions simply out of date? If so, I can create a quick fix and make a PR.

**Comment by nlml** [comment]
Seems you are right to me - make the PR!

**Comment by Mason-McGough** [comment]
A fix has been committed. Closing this. Thank you!
