### ISSUE TITLE
can't using metashape .xml file with processing

### ISSUE THREAD

**Issue by minsoo5403** [nerfstudio-project/nerfstudio#1224]
**Describe the bug**
I try to use python process_data.pymetashape, but I get the following error:

  File "/home/k/nerfstudio/nerfstudio/process_data/metashape_utils.py", line 62, in metashape_to_json
    raise ValueError("Only one sensor is supported for now")
ValueError: Only one sensor is supported for now

In MetaShape 1.8.4 / 2.0.0 the sensor is not included even if XML is printed.

**Screenshots**
![image](https://user-images.githubusercontent.com/16278227/212096756-d29331c0-e2a3-41bf-8a54-7022c3599ae8.png)

**Comment by satpalsr** [comment]
Did you figured it out? Facing same problem.

**Comment by rockywind** [comment]
Hi, @minsoo5403 @benji-york 
I met the same error.
````
ocess_data_utils.py:179
[20:42:24] 🎉 Done downscaling images.                                                         process_data_utils.py:292
Traceback (most recent call last):
  File "/home/zongmu/anaconda3/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/process_data.py", line 797, in entrypoint
    tyro.cli(Commands).main()
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/process_data.py", line 682, in main
    metashape_utils.metashape_to_json(
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/process_data/metashape_utils.py", line 62, in metashape_to_json
    raise ValueError("Only one sensor is supported for now")
ValueError: Only one sensor is supported for now
````
This my xml file.
![image](https://user-images.githubusercontent.com/14838781/216048931-b5b317d8-d13c-4f9a-8a3e-b32d54849f32.png)

**Comment by tancik** [comment]
Do you have more than one sensor?

**Comment by rockywind** [comment]
The data is captured by one camera, but the training data is generated by colmap.

**Comment by tancik** [comment]
I'm a bit confused. Was the data processed with metashape or colmap?

**Comment by rockywind** [comment]
Sorry, 
The data was processd with metashape.
The data was captured by one camera.

**Comment by tancik** [comment]
It seems like the xml files that metashape produces aren't consistent (perhaps it is due to the version). I haven't found any good documentation defining the format. Unfortunately I think we are in the situation where we will need to keep updating the parser to handle these edge cases as they emerge. Feel free to create a PR if you figure out how to modify the data loading to work with your xml.

**Comment by rockywind** [comment]
Thank you!
