### ISSUE TITLE
What is the meaning of this line? Thanks!

### ISSUE THREAD

**Issue by qhdqhd** [nerfstudio-project/nerfstudio#1227]
https://github.com/nerfstudio-project/nerfstudio/blob/86d8118b6d02da538373e661efa0ddc5645b1f59/nerfstudio/fields/nerfacto_field.py#L235

**Comment by tancik** [comment]
The spatial distortion forces all of the points into a +-2 box. This then normalizes those values to fall in the range [0,1]

**Comment by qhdqhd** [comment]
Thank you!
