### ISSUE TITLE
c2w matrices cannot have 0 translation vector?

### ISSUE THREAD

**Issue by sagesimhon** [nerfstudio-project/nerfstudio#1228]
**Describe the bug**
One of my cameras is located at the origin: [tx, ty, tz] = [0,0,0], hence the last column of the matrix in my frame['transform_matrix'] in transforms.json is the column vector [0,0,0,1]. This causes an 'nan' in the poses matrix from the scale factor becoming infinity [here](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L218).

This might be a bug in the way the scale factor is being computed, since the scale factor should be the value of the [:,3,3]th elements of the c2w matrices, for homogeneous coordinates, but the current implementation drops the last row.

**Comment by tancik** [comment]
It seems like the pose will only go to `nan` if all of the cameras a located at the origin (which is not supported by NeRF). I just tested by setting one position to [0,0,0] and the code seemed to run fine. Can you post your `transforms.json` file?

**Comment by tancik** [comment]
Closing as this appear stale, feel free to reopen if it is still and issue.
