### ISSUE TITLE
What's the unit of near_plane and far_plane and the camera poses?

### ISSUE THREAD

**Issue by yimingzhou1** [nerfstudio-project/nerfstudio#1247]
What is the unit of `near_plane` and `far_plane` in `nerfacto`? Is it `meter`? Should I change the default value (`near_plane=0.05`, `far_plane=1000`) when I have a different scene?

Also I noticed that when the camera poses obtained from `COLMAP` is loaded, they are scaled. Are the raw poses supposed to be in `meter`? Thanks!

**Comment by tancik** [comment]
The data is scaled such that the scene cameras fit into a +-1 cube. It is therefore not tied to a specific unit, it is scene dependent. You can add `nerfstudio-data --auto-scale-poses False `--scene-scale CUSTOM_SCALE`` if you don't want it to auto scale the scene but rather by a fixed amount (the quality will change depending on the scale). There is also a `dataparser_transforms.json` file saved in the output folder that tells you what scale was used.

**Comment by yimingzhou1** [comment]
Thanks for the clarification. However, I didn't see where `near_plane` and `far_plane` are scaled. Are they absolute w.r.t. to the +- 1 cube?

**Comment by yimingzhou1** [comment]
Thank you!

**Comment by yimingzhou1** [comment]
Hi, thanks for the explanation above but I still have some questions. Is the output camera poses of COLMAP (before `auto-scale-poses`) in the unit of meter ?(I don't think so because I believe COLMAP has some built-in scaling of the output camera poses).

**Comment by tancik** [comment]
I'm not sure what COLMAP does but my impression was that the units are not meaningful unless you provide specific metric info.

**Comment by Len-Li** [comment]
Hi, 

I am confused about the meaning of `near_plane and far_plane`. As they are with respect to the +- 1 cube, and the rays hit the AABB will get `hit_near and hit_far`. It seems that the `hit_near and hit_far` will actually work most of the time rather than `near_plane and far_plane`. Is my understanding correct？

Many thanks
