### ISSUE TITLE
Render disconnected

### ISSUE THREAD

**Issue by Holmes-Alan** [nerfstudio-project/nerfstudio#1256]
A couple of weeks ago, I successfully ran the code and get good 3D rendering results. However, recently when I ran the same code, I could not get a render view on the web, like

![image](https://user-images.githubusercontent.com/15608099/213337994-f9bf2a2a-87da-4ed3-b879-998d411910ab.png)

I also found that the vis Ray does not computer every second.
![image](https://user-images.githubusercontent.com/15608099/213338107-e6ddf3ef-5e6c-45ab-a810-64effe38ac73.png)

I tested that the model is well-trained. I can get the 3D mesh from the trained file. It is just I cannot see the render view when training.

**Comment by Holmes-Alan** [comment]
resolved. add "--viewer.skip-openrelay True" and wait for a few seconds

**Comment by rockywind** [comment]
Hi,
I want to resume the model to get the 3D rendering result, using the below script.
````
ns-train nerfacto  \
                --pipeline.model.predict-normals True \
                --experiment-name data_10_31_undis_600_normal \
                --data data/own_data/data_10_31_undis \
                --load_dir outputs/data_10_31_undis_600_normal/nerfacto/2023-02-06_120749/nerfstudio_models \
                --viewer.skip-openrelay True \
                --viewer.start-train False
````
But, the viewer show "render Disconnected".
![image](https://user-images.githubusercontent.com/14838781/216918373-ba304f82-67af-40b8-a5b2-23a5e4c15e03.png)

**Comment by tancik** [comment]
@rockywind Try waiting a few minutes. Also try removing `--viewer.skip-openrelay True`.

**Comment by rockywind** [comment]
Hi, @tancik 
why my 3D rendering result always is white?
I can't see any 3D rendering results even the render conneting.
![image](https://user-images.githubusercontent.com/14838781/218829502-29b9b52f-2510-4138-9b77-c8f74515eeb9.png)

**Comment by rockywind** [comment]
Hi,
This is my script.
````
export CUDA_VISIBLE_DEVICES=0
ns-train nerfacto  --viewer.websocket-port=7001 \
                --machine.num-gpus 1 \
                --experiment-name 20230201-15-13-45_200_refine \
                --data data/own_data/20230201-15-13-45 \
                --load_dir outputs/20230201-15-13-45_500_old_pose/nerfacto/2023-02-14_183919/nerfstudio_models \
                --viewer.start-train False 
````
I don't set the `viewport`, I think the `viewport` should be default.

**Comment by tancik** [comment]
Disregard my last message. My guess is that the websocket is being blocked since it is not wss (websocket secure). As a result, some browsers (safari) may block the websocket. If you aren't already, try using chrome.

**Comment by rockywind** [comment]
Hi, @tancik 
I using the chrome brower.

**Comment by tancik** [comment]
At the top of the window, can you press `Viewport` instead of `Render View` and send a screenshot.

**Comment by rockywind** [comment]
Hi, @tancik 
I don't know why the Render Viewer can't connect again?
![Uploading image.png…]()

**Comment by tancik** [comment]
The image you linked appears to be broken.

**Comment by tancik** [comment]
You are likely experiencing this issue - https://github.com/nerfstudio-project/nerfstudio/issues/765

**Comment by rockywind** [comment]
Thanks, 
I will have a try!

**Comment by rockywind** [comment]
Hi,
the render view still cannot be displayed.
VIEWPORT
![image](https://user-images.githubusercontent.com/14838781/219537885-4ebabbc1-0968-4353-8909-a66dfe84550a.png)

RENDER VIEW
![image](https://user-images.githubusercontent.com/14838781/219537974-4d67d431-28bd-4b8a-a2e6-e669ab86022d.png)

**Comment by tancik** [comment]
This is the same as https://github.com/nerfstudio-project/nerfstudio/issues/765
