### ISSUE TITLE
Insta360 workflow

### ISSUE THREAD

**Issue by Tobe2d** [nerfstudio-project/nerfstudio#1263]
Any Suggestion for insta360 videos workflow?

**Comment by trungswat** [comment]
Hi,

Hopefully you managed yourself to figure it out , but I would suggest a workflow that I'm practicing;

- Firstly, record a 360 clip with insta360 devices.
- Using ffmpeg to convert clip to several still equirectangle images.
- Next, convert those equirectangle images to cube-map with **py360convert** library. You can find it easily on Google.
- You split cubemaps to 6 single images _top, bottom, left, right, front, behind by using another library, it's called **cubemap_splitter**.
- Now you have a bunch of images, those are ready to using colmap to extract camera poses.
- Finally, you can proceed to training stage in nerfstudio.

**Comment by Tobe2d** [comment]
@trungswat Thanls for the detailed workflow. Much appreciated.

**Comment by Tobe2d** [comment]
@trungswat Regarding cubemap_splitter, I found https://github.com/paulburgess1357/Cubemap-Splitter
is this the one you mentioned? or you have other recommendations?

**Comment by machenmusik** [comment]
(There is now direct equirectangular input support in the latest, FYI.)
