### ISSUE TITLE
Option to disable webviewer

### ISSUE THREAD

**Issue by MaroonAmor** [nerfstudio-project/nerfstudio#1269]
Dear authors,

Is there an option to fully disable webviewer from training?

I'd like to run a training job in Kubernetes with a VPN connection on A100 GPU. For some reason, the training speed (`nerfacto`) was around 10x slower than what is benchmarked in the README (e.g., much smaller than "183.05 K Train Ray / Sec").

My guess would be that the VPN connection issue may slow down the training progress, since the viewer is updated iteratively during training. Would it be possible to fully disable the viewer?

Thanks. @tancik

**Comment by tancik** [comment]
If the website isn't opened, it won't start rendering so the overhead is low. Is there any chance your machine is CPU bottlenecked? Some the of the data pre-processing is CPU intensive and we have seen this result in a bottleneck when the GPU is fast. Alternatively, slower speeds have also been observed when TCNN has had errors during install. If you want to disable the viewer, you can set `--vis tensorboard`.

**Comment by MaroonAmor** [comment]
Hi @tancik Thanks a lot for the clarification. I can try again with `--vis tensorboard`.

- Regarding your question, what do you mean by GPU being bottlenecked? The demo poster data already has been pre-processed, right?
- The CPUs in our Kubernetes also have a decent performance. Could you elaborate more?
- For TCNN, I did change the env variable to `TCNN_CUDA_ARCHITECTURES=80`, since the CUDA architecture for A`100 GPU is sm_80. Are you saying TCNN complied on A100 GPU could be the issue of slow training?

**Comment by tancik** [comment]
Loading batches of pixels uses more CPU than it should which can slow down the training process. 
> Are you saying TCNN complied on A100 GPU could be the issue of slow training?
It has happened before, not sure that is what is happening here though.

**Comment by MaroonAmor** [comment]
@tancik Thanks for the input.

Your insight is correct. It is due to the CPU bottleneck: the running job created a lot of threads in K8s, since it can see all CPU cores in K8s (also mentioned [here](https://thoth-station.ninja/j/mkl_threads.html)), which leads to a lot of contention. The issue has been resolved by specifying the number of threads in the Dockerfile (to match the number of allocated CPU cores).
