### ISSUE TITLE
Where is the "viewer" when I use "mipnerf" to train?

### ISSUE THREAD

**Issue by XinyueZ** [nerfstudio-project/nerfstudio#1287]
I do not see the viewer anymore when I run "ns-train mipnerf".

Is there doc to talk about this?

**Comment by tancik** [comment]
You can add `--vis viewer` to the command. `mipnerf` defaults to w&b logging since it is a slow method. Since it is so slow, it will probably very low res in the viewer.

**Comment by XinyueZ** [comment]
This is not cool, because the nerfacto shows links to viewers obviously, however the mipnerf doesn't.
Even there isn't official document that point out this.
Need improve.

**Comment by tancik** [comment]
We have a note about it the intro documentation, 
https://docs.nerf.studio/en/latest/quickstart/first_nerf.html#tensorboard-wandb
