### ISSUE TITLE
Eval Ray Generator uses train camera optimizer

### ISSUE THREAD

**Issue by williamshen-nz** [nerfstudio-project/nerfstudio#1299]
**Describe the bug**
The eval ray generator in the base datamanager uses the train camera optimizer. However, if there are more eval images then the eval ray generator will try to get the camera adjustments for indices that don't exist in the train camera optimizer.

**To Reproduce**
1. Set the `config.pipeline.datamanager.dataparser.train_split_percentage` in the nerfacto dataparser to something like 0.25 so there's more eval images than train images.
2. Train and wait until an evaluation step, the eval RayGenerator will try to use the train camera optimizer, but there are more eval images than training images so it'll try to access indices that don't exist 
    - https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/datamanagers/base_datamanager.py#L394-L397
4. `CUDA error: device-side assert triggered`

**Expected behavior**
The evaluation shouldn't break.

I would expect the train and eval images to be separate as well, so using the train camera optimizer for the eval images may not make much sense if the camera indices are not consistent between the two?

**Additional context**
I worked around this in the meantime by just creating a separate camera optimizer with `mode = "off"` for the eval ray generator.

Happy to fix and submit a PR! Let me know what's the best fix here.

**Comment by ethanweber** [comment]
Hi @williamshen-nz, I think this should be fixed in an upcoming PR #1139. Do you want to take a look at that code and confirm it solves this issue?

**Comment by williamshen-nz** [comment]
Hey Ethan, thanks for the pointer to the PR. Yes I think that'll work, I'll keep an eye out for the merge and will just use my local fix in the meantime. Thanks!
