### ISSUE TITLE
No macOS compilation available for cu113

### ISSUE THREAD

**Issue by ansonkao** [nerfstudio-project/nerfstudio#1301]
**Describe the bug**
There doesn't seem to be valid path to installing torch + CUDA on macOS, despite the repo generally seeming to have code snippets specifically for supporting macOS.

**To Reproduce**
1. On the following step from the main README.md instructions, when run on macOS, gives this error:
`pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html`
```
ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.12.1+cu113
```

**Additional context**
From [the stable list](https://download.pytorch.org/whl/torch_stable.html), these are the available compilations of cu113 torch, notice that only linux and windows is available:
```
cu113/torch-1.12.0%2Bcu113-cp310-cp310-linux_x86_64.whl
cu113/torch-1.12.0%2Bcu113-cp310-cp310-win_amd64.whl
cu113/torch-1.12.0%2Bcu113-cp37-cp37m-linux_x86_64.whl
cu113/torch-1.12.0%2Bcu113-cp37-cp37m-win_amd64.whl
cu113/torch-1.12.0%2Bcu113-cp38-cp38-linux_x86_64.whl
cu113/torch-1.12.0%2Bcu113-cp38-cp38-win_amd64.whl
cu113/torch-1.12.0%2Bcu113-cp39-cp39-linux_x86_64.whl
cu113/torch-1.12.0%2Bcu113-cp39-cp39-win_amd64.whl
cu113/torch-1.12.1%2Bcu113-cp310-cp310-linux_x86_64.whl
cu113/torch-1.12.1%2Bcu113-cp310-cp310-win_amd64.whl
cu113/torch-1.12.1%2Bcu113-cp37-cp37m-linux_x86_64.whl
cu113/torch-1.12.1%2Bcu113-cp37-cp37m-win_amd64.whl
cu113/torch-1.12.1%2Bcu113-cp38-cp38-linux_x86_64.whl
cu113/torch-1.12.1%2Bcu113-cp38-cp38-win_amd64.whl
cu113/torch-1.12.1%2Bcu113-cp39-cp39-linux_x86_64.whl
cu113/torch-1.12.1%2Bcu113-cp39-cp39-win_amd64.whl
```

**Expected behavior**
The README.md should either correctly support macOS installation, or otherwise indicate that macOS is not supported.

**Comment by tancik** [comment]
Nerfstudio requires CUDA which is provided with Nvidia GPUs. Most mac systems do no have nvidia GPUs and will therefore not work.

**Comment by eirikwah** [comment]
@tancik Is the CUDA requirement because of a dependency to pytorch only?

The reason I ask, is that it would be nice to be able to use Nerf studio on macOS (Apple silicon). And if the CUDA requirement is only because of pytorch, I am motivated to try to make a PR for Apple silicon mac compatability, for example using this approach: <https://towardsdatascience.com/installing-pytorch-on-apple-m1-chip-with-gpu-acceleration-3351dc44d67c>

**Comment by brentyi** [comment]
@eirikwah it's more than just PyTorch: the recommended nerfacto model depends on `tiny-cuda-nn`, which (as the name suggests) only supports CUDA. Some other models rely on `nerfacc`, which is also CUDA-only.

As of #1936 you should, however, be able to get a slower version of the model running on non-CUDA torch installations via
the `--pipeline.model.implementation torch` argument.
