### ISSUE TITLE
Why is there a 90° rotation between the image saved by ns-render and the original image?

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1315]
Hi,
This is the picture saved by ns-render.
![00000](https://user-images.githubusercontent.com/14838781/215733708-b0d7c37f-283d-47cb-9ef2-5ac581e53ab2.png)
This is the original image.
![0001](https://user-images.githubusercontent.com/14838781/215734808-08912f98-c86a-4cfe-9a64-300c6e2e844c.jpg)
This is the script below.
````
ns-render \
--load-config outputs/-DATA2-xiaoquan.wang-nerfstudio-data-own_data-pk2_230/nerfacto/2023-01-31_162355/config.yml \
--traj spiral \
--output-path renders/render_output_pk3_nerffacto.mp4 \
--output-format images
````

**Comment by tancik** [comment]
The `spiral` trajectory is pretty arbitrary and often not very good for real scenes. I'd recommend making your own trajectory using either the viewer or the blender plugin.

**Comment by rockywind** [comment]
Thank you for your help!
Why do they have some noise at the edge of the image? The trajectory is made using the viewer.
I set the camera FOV value to 50 because I don't know the real the camera FOV value.
![image](https://user-images.githubusercontent.com/14838781/215842120-a527b346-ec92-48ea-b531-71f56e46d4f0.png)
![image](https://user-images.githubusercontent.com/14838781/215842281-2ef48850-761e-4aa3-bb11-8b091db9e8b7.png)

**Comment by tancik** [comment]
Those are regions that arn't supervised well, so the nerf just add noise.

**Comment by rockywind** [comment]
Thank you for your 
Any methods to solve this problem? Can I add more training data from multi-trips?

> Those are regions that arn't supervised well, so the nerf just add noise.

**Comment by tancik** [comment]
When you capture the scene, try to make sure that every point in space that you want to reconstruct is visible in ~5 images that are viewing the point from multiple angles.

**Comment by rockywind** [comment]
Thank you very much!
