### ISSUE TITLE
Need better way to handle adding colormap on output images for Visualizer

### ISSUE THREAD

**Issue by evonneng** [nerfstudio-project/nerfstudio#132]
I added some func to handle the colormap stuff
https://github.com/plenoptix/pyrad/blob/069cf2c40fb3ab68c483501f18713992b3c00d8a/pyrad/graphs/instant_ngp.py#L148-L162

And set it as a base class thing to get everything to work:
https://github.com/plenoptix/pyrad/blob/069cf2c40fb3ab68c483501f18713992b3c00d8a/pyrad/graphs/base.py#L139-L145

But i dont think this is best way to handle, so need to figure out a more robust way of handling this across implementations

This is where the function is referenced in visualizer code:
https://github.com/plenoptix/pyrad/blob/069cf2c40fb3ab68c483501f18713992b3c00d8a/pyrad/viewer/server/viewer_utils.py#L79

**Comment by tancik** [comment]
Updated in #1348
