### ISSUE TITLE
odd width and/or height prevent viewer from using H264 instead of VP8 

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#1325]
https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/viewer/server/viewer_utils.py#L694
is hardcoded to select VP8 as video encoder.
I wanted to explore using H264 which is often hardware accelerated in decoders and encoders.

However, in doing so I noticed: 
- the selected encoder was x264 not NVENC et al. (which will likely be slower)
- errors from width and/or height having odd values (I wonder whether this could explain memory leaks)

**Comment by tancik** [comment]
I don't really know much about encoders so I just chose VP8 since it seemed to work. x264 also worked when I forced the render resolution to be even. Not sure if one is better than another, I'm open to updating this to improve efficiency/quality.

**Comment by machenmusik** [comment]
NVENC should be much faster than x264, since we need CUDA anyway.
It's easy to force video/H264, but doesn't seem easy to force NVENC instead of x264.

Interestingly, changes to https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/viewer/server/viewer_utils.py#L834 forcing even width and height are NOT sufficient to prevent odd width and height from getting to x264... ?!?

**Comment by tancik** [comment]
That's odd. Can you check the resolution here - https://github.com/nerfstudio-project/nerfstudio/blob/cf1794acb16b01796f3d1fcb7501df47a6219df0/nerfstudio/viewer/server/viewer_utils.py#L713

**Comment by machenmusik** [comment]
No need... here is an example of the error when moving about
`[libx264 @ 00000235b9546040] width not divisible by 2 (205x120)`

It may be due to image_height being used but not image_width here
```
        # Calculate camera pose and intrinsics
        try:
            image_height, image_width = self._calculate_image_res(camera_object, is_training)
        except ZeroDivisionError as e:
            self.vis["renderingState/log_errors"].write("Error: Screen too small; no rays intersecting scene.")
            time.sleep(0.03)  # sleep to allow buffer to reset
            print(f"Error: {e}")
            return

        if image_height is None:
            return

        intrinsics_matrix, camera_to_world_h = get_intrinsics_matrix_and_camera_to_world_h(
            camera_object, image_height=image_height
        )
```
