### ISSUE TITLE
Tensorboard and Viewer at the same time during training

### ISSUE THREAD

**Issue by ManuConcepBrito** [nerfstudio-project/nerfstudio#1353]
**Describe the bug**
When I try to run tensorboard and the viewer during the same training instance, the viewer doesn't launch. Another problem is that tensorboard doesn't launch automatically. I need to go to the log directory and run: ```tensorboard --logdir=.```

**To Reproduce**
``` ns-train depth-nerfacto --data /path-to-data --vis tensorboard --viewer.websocket-port 7007 nerfstudio-data ```

I tried altering the position of the --vis argument (as it seems that order matters) but no luck. Is this the expected behaviour?

**Comment by wuzirui** [comment]
It seems(?) NeRFStudio does not support using multiple viewer methods (e.g using tensorboard and viewer at the same time) currently. Will it be a future feature?

**Comment by tancik** [comment]
Added in #1474
