### ISSUE TITLE
What's the difference among the output render type, such as normal, pred_normals, prob_depth_0 and prob_depth_1?

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1355]
Hi,
 I'm confused that what's the difference between the pred_normals, normal, prob_depth_0, prob_depth_1 and accumulation?\
![image](https://user-images.githubusercontent.com/14838781/216915391-4195a4b5-0026-412e-a3fb-71deceeacf64.png)

**Comment by tancik** [comment]
accumulation: The sum of the color weights along the ray (how much density was accumulated).
normals: The geometry normals of the scene computed using density gradients
pred-normals: The predicted geometry normals computed using an mlp supervised on density normals (with other losses)
prop_depth_0: The depths predicted from the first proposal network (same as mipnerf-360)
prop_depth_1: The depths predicted from the second proposal network

**Comment by rockywind** [comment]
Thank you very much!
