### ISSUE TITLE
Tensors of type TensorImpl do not have strides

### ISSUE THREAD

**Issue by fanwei360** [nerfstudio-project/nerfstudio#1356]
**Describe the bug**
when I train model by the following command: ns-train nerfacto --data data/nerfstudio/poster
tinycudann raise error
RuntimeError: Tensors of type TensorImpl do not have strides
Where's the problem?

**Screenshots**
![image](https://user-images.githubusercontent.com/108925643/216934593-68d628b0-9044-4671-9ff8-2ab2c8c91be7.png)

**Comment by tancik** [comment]
Looks like it is relate to this - https://github.com/NVlabs/tiny-cuda-nn/issues/117

**Comment by fanwei360** [comment]
thanks for your reply. it seems to be a compatibility problem with tiny-cudann1.7. I already fixed it by built a new conda environment.
