### ISSUE TITLE
does tensorf model actually need blender datasets?

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#1360]
Let's say we want to compare `tensorf` to `instant-ngp` and `nerfacto` using same dataset.
The same `ns-process-data` output can be used for both `instant-ngp` and `nerfacto` -- great.
But `tensorf` appears to need a Blender dataset which has different format/conventions.
Is there any actual reason?  

If it needs method/model-specific parameters, I would expect it to use its own data parser, rather than Blender.
If it doesn't, and the choice was arbitrary, then I would expect behavior more like (`instant-ngp` and) `nerfacto` -- perhaps by using the nerfacto dataparser instead of Blender.

**Comment by tancik** [comment]
You can add `nerfstudio-data` at the end of the command to use the nerfstudio dataset. It was defaulted to blender because that is the dataset it was tuned to work well on. This is similar to `vanilla-nerf` which also defaults to the blender dataset.

**Comment by machenmusik** [comment]
Got it, thank you.  FWIW, it seems to me that the dataset defines which parser(s) should be used, not the model, so it might be better to keep model behavior uniform, and/or to have the dataparser selected from quickly looking at the data in use.  That could be as simple as path/naming convention when not explicit, e.g. `data/blender` should use Blender, `data\friends` should use semantic-nerfw, etc. - in which case nerfstudio would presumably become the default.
