### ISSUE TITLE
Loading data batch Killed

### ISSUE THREAD

**Issue by rohitdhote111** [nerfstudio-project/nerfstudio#1365]
I am training custom data in linux 20 "ns-train nerfacto --data [data path] " and getting below error

The viewer bridge server subprocess failed. Please check the log file outputs/destdir/nerfacto/2023-02-07_074307/viewer_log_filename.txt.
You likely have to modify --viewer.zmq-port and/or --viewer.websocket-port in the config to avoid conflicting ports.
Try modifying --viewer.websocket-port 7007

**Comment by tancik** [comment]
That means something is probably already running on port 7007. Try adding `--viewer.websocket-port 7008` to your command.

**Comment by rohitdhote111** [comment]
Thanks for the reply 
Now, I understood the problem that it was using 7007 port as I was running training command multiple times  as It was not working in the first time.

First time training process atuomatically stops without any error it is just showing Killed while loading data command output shown below

Sending ping to the viewer Bridge Server...
Successfully connected.
Sending ping to the viewer Bridge Server...
Successfully connected.
[NOTE] Not running eval iterations since only viewer is enabled. Use --vis wandb or --vis tensorboard to run with eval
instead.
Disabled tensorboard/wandb event writers
[08:38:35] Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:314
           Skipping 0 files in dataset split train.                                         nerfstudio_dataparser.py:165
           Skipping 0 files in dataset split val.                                           nerfstudio_dataparser.py:165
Setting up training dataset...
Caching all 288 images.
Loading data batch ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  31% 0:00:39Killed

**Comment by tonyyu0822** [comment]
What is the correct way to end training for a certain port?

**Comment by tancik** [comment]
The server should be killed when the training process ends (ctrl + c), however in some rare cases when the training crashes the server doesn't get closed. When that happens, I just work with a different port ;), not sure the best way to kill that process when that happens.

**Comment by tonyyu0822** [comment]
Thanks for the prompt response. I tried ctrl + c on several ports and none of them was closed properly and the port becomes unusable :(
How many other ports could we possibly use?

**Comment by machenmusik** [comment]
The nuclear option is killall -9 python, or on Windows, taskkill /im python exe /f

**Comment by runningneverstop** [comment]
> Thanks for the reply Now, I understood the problem that it was using 7007 port as I was running training command multiple times as It was not working in the first time.
> 
> First time training process atuomatically stops without any error it is just showing Killed while loading data command output shown below
> 
> Sending ping to the viewer Bridge Server... Successfully connected. Sending ping to the viewer Bridge Server... Successfully connected. [NOTE] Not running eval iterations since only viewer is enabled. Use --vis wandb or --vis tensorboard to run with eval instead. Disabled tensorboard/wandb event writers [08:38:35] Auto image downscale factor of 1 nerfstudio_dataparser.py:314 Skipping 0 files in dataset split train. nerfstudio_dataparser.py:165 Skipping 0 files in dataset split val. nerfstudio_dataparser.py:165 Setting up training dataset... Caching all 288 images. Loading data batch ━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━━ 31% 0:00:39Killed
> 
> Please help me resolving this issue

How you finally solve this problem?
