### ISSUE TITLE
Could not find ffmpeg. Please install ffmpeg. error for custom dataset

### ISSUE THREAD

**Issue by sumanttyagi** [nerfstudio-project/nerfstudio#1367]
i am trying to train my own custom dataset which are images still i am facing below error i have already installed ffmpeg even it is required only for the video, i am using below command line 
_ns-process-data images --data "/bmxla" --output-dir "/output_biuilding"_

Could not find ffmpeg. Please install ffmpeg.
See https://ffmpeg.org/download.html for installation instructions.
ffmpeg is only necessary if using videos as input.

![image](https://user-images.githubusercontent.com/63983323/217250827-27bac4f1-b150-4abd-8a6a-b449c20673f5.png)

**Comment by tancik** [comment]
What do you see if you run `ffmpeg -version`

**Comment by tancik** [comment]
Thats odd. You could try commenting out these lines of code and see if it works, https://github.com/nerfstudio-project/nerfstudio/blob/8c9c2ba2ab052317ff47f2f93d0ff5e0c7655471/nerfstudio/utils/install_checks.py#L28-L32

**Comment by tancik** [comment]
a) Just close the interface, then the colmap script will proceed.
b) That means that the script didn't complete. Did you have any errors?
c) Add `--num-downscales 1` to the end of the command.

**Comment by vrahnos3** [comment]
> i am trying to train my own custom dataset which are images still i am facing below error i have already installed ffmpeg even it is required only for the video, i am using below command line _ns-process-data images --data "/bmxla" --output-dir "/output_biuilding"_
> 
> Could not find ffmpeg. Please install ffmpeg. See https://ffmpeg.org/download.html for installation instructions. ffmpeg is only necessary if using videos as input.
> 
> ![image](https://user-images.githubusercontent.com/63983323/217250827-27bac4f1-b150-4abd-8a6a-b449c20673f5.png)

I had the same issue, I had installed ffmpeg on my virtualenv and had the same problem. When I installed ffmpeg on system with `sudo apt install ffmpeg` problem solved. Just mentioned for someone maybe will face the same problem.
