### ISSUE TITLE
building from source doesn't seem to install commands properly or all the necessary packages

### ISSUE THREAD

**Issue by j93hahn** [nerfstudio-project/nerfstudio#1374]
Hi, I tried building nerfstudio from source via cloning the github repo, but running `pip install -e .` did not seem to install the nerfstudio command line interface, nor did it install a lot of the dependencies that nerfstudio required. Only running `pip install nerfstudio` seems to get the job done.

I understand that accessing the nerfstudio command line requires installation of the nerfstudio package, but I just tried to run it directly myself like `python scripts/completions/install.py` and it returned a `ns-install-cli` command not recognized error. It was only resolved when I installed `pip install nerfstudio`. Is this a common problem? I'm not sure why `pip install -e .` did not seem to install all of the required packages and CLI perks that comes with `pip install nerfstudio`.

**Comment by tancik** [comment]
That should work. Maybe try `pip uninstall nerfstudio` before calling `pip install -e .`. Also make sure that you are in the nerfstudio directory before calling pip install. Can you post the output to `pip install -e .`

**Comment by j93hahn** [comment]
`(base) [jjahn@slurm nerfstudio]$ ls
colab  Dockerfile  docs  LICENSE  nerfstudio  nerfstudio.egg-info  pyproject.toml  README.md  scripts  setup.cfg  tests
(base) [jjahn@slurm nerfstudio]$ pwd
/share/data/pals/jjahn/nerfstudio
(base) [jjahn@slurm nerfstudio]$ pip install -e .
Obtaining file:///share/data/pals/jjahn/nerfstudio
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: opencv-python==4.6.0.66 in /share/data/pals/jjahn/mc3/lib/python3.10/site-packages (from nerfstudio==0.1.16) (4.6.0.66)
Requirement already satisfied: ipywidgets>=7.6 in /share/data/pals/jjahn/mc3/lib/python3.10/site-packages (from nerfstudio==0.1.16) (8.0.4)
Requirement already satisfied: requests in /share/data/pals/jjahn/mc3/lib/python3.10/site-packages (from nerfstudio==0.1.16) (2.28.1)
ERROR: Could not find a version that satisfies the requirement open3d>=0.16.0 (from nerfstudio) (from versions: none)
ERROR: No matching distribution found for open3d>=0.16.0
(base) [jjahn@slurm nerfstudio]$ ns-train --help
-bash: ns-train: command not found`

I had previously run `pip uninstall nerfstudio` and have only installed the source code via `pip install -e .` It returns an error with no finding `open3d` but pip doesn't seem to have the distribution packaging for this particular requirement. 

The `ns-train` command at the bottom returned that message.

**Comment by j93hahn** [comment]
The tab completions mechanism is still in place because I've sourced it in my `~/.bashrc` file, but it seems unable to interpret the nerfstudio CLI. Even running the original python script like `python scripts/completions/install.py` returns an error message that `ns-install-cli` is an unrecognized command.

**Comment by j93hahn** [comment]
I noticed that `pip install nerfstudio` installs everything, but `pip install -e .` only seems to install a small subset of the total required packaging.

**Comment by tancik** [comment]
Can you create a new environment, I wonder if there are other things in `base` that are messing with the installation.
ie try
```
conda create --name nerfstudio -y python=3.8
conda activate nerfstudio
python -m pip install --upgrade pip
pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 -f https://download.pytorch.org/whl/torch_stable.html
pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
pip install --upgrade pip setuptools
pip install -e .
```

**Comment by j93hahn** [comment]
The issue lied in the installation of Open3d. I'm on CentOS Linux, for which PyPI does not have support of Open3D installation. Removing this from the requirements fixed this issue. However, I wanted to ask -- is Open3D a requirement for nerfstudio to be fully functional?

**Comment by tancik** [comment]
It is necessary for exporting meshes. Everything else should work fine.

**Comment by j93hahn** [comment]
Great, thanks!

**Comment by Mskycoder** [comment]
Rolling back to python 3.8.10 seems to fix the problem for me.
