### ISSUE TITLE
"    assert ray_bundle.times is not None, "Time not provided." AssertionError: Time not provided."

### ISSUE THREAD

**Issue by rockywind** [nerfstudio-project/nerfstudio#1375]
Hi,
When I rendered the video in default setting, I met the error below.
This is the train script.
````
export CUDA_VISIBLE_DEVICES=0
ns-train nerfplayer-nerfacto --viewer.websocket-port=7004 \
--machine.num-gpus 1 \
dycheck-data --data data/dy_check_data/apple \
--vis wandb  \
--experiment-name dy_check_apple
````
This is the render script.
````
ns-render \
--load-config outputs/data-dy_check_data-apple/nerfplayer-nerfacto/2023-02-08_113917/config.yml \
--traj spiral \
--output-path renders_dy_check/render_nerfplayer-nerfacto_apple.mp4
````
This is the detailed log.
````
🎥 Rendering 🎥 ━━━━━━━━━━━   0% ? --:--
Traceback (most recent call last):
  File "/home/zongmu/anaconda3/envs/nerfstudio/bin/ns-render", line 8, in <module>
    sys.exit(entrypoint())
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/render.py", line 325, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/render.py", line 309, in main
    _render_trajectory_video(
  File "/DATA2/xiaoquan.wang/nerfstudio/scripts/render.py", line 112, in _render_trajectory_video
    outputs = pipeline.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
  File "/home/zongmu/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/models/base_model.py", line 177, in get_outputs_for_camera_ray_bundle
    outputs = self.forward(ray_bundle=ray_bundle)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/models/base_model.py", line 139, in forward
    return self.get_outputs(ray_bundle)
  File "/DATA2/xiaoquan.wang/nerfstudio/nerfstudio/models/nerfplayer_nerfacto.py", line 175, in get_outputs
    assert ray_bundle.times is not None, "Time not provided."
AssertionError: Time not provided.
````

**Comment by tancik** [comment]
@lsongx There looks to be an issue with rendering nerfplayer since time isn't included by default in the raybundle.

**Comment by lsongx** [comment]
Yes, `ns-render` needs to be adapted. let me fix this asap

**Comment by lsongx** [comment]
Hi @rockywind , thanks for reporting this. I created a PR to add time in the script. Do you mind trying the PR?

**Comment by tancik** [comment]
Fixed in #1391

**Comment by rockywind** [comment]
Thanks, I have a try!

**Comment by rockywind** [comment]
Hi,
Why the images looked strange in the viewer.
I do't kown how to set the camera path.
![image](https://user-images.githubusercontent.com/14838781/217995850-f117d006-cac9-453e-9a21-8377b720de01.png)

**Comment by rockywind** [comment]
Hi, 
When I want to export the point cloud, it get stuck.
This is export script.
````
ns-export pointcloud --load-config outputs/data-dy_check_data-apple/nerfplayer-nerfacto/2023-02-08_113917/config.yml \
--output-dir exports/pcd_dy_apple/ --num-points 3000000 --remove-outliers True --estimate-normals False \
--use-bounding-box True --bounding-box-min -5 -5 -5 --bounding-box-max 5 5 5
````
This is the log.
````
split test not found, using split train
Setting up training dataset...
Caching all 475 images.
Setting up evaluation dataset...
Caching all 475 images.
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
outputs/data-dy_check_data-apple/nerfplayer-nerfacto/2023-02-08_113917/nerfstudio_models/step-000029999.ckpt
nerfstudio field 
components: CUDA 
set up, loading 
(should be quick)
☁ Computing Point C
☁ Computing Point Cloud ☁   
☁ Computing Point Cloud ☁ ━━━━━━   0% 
☁ Computing Point Cloud ☁ ━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 
````

**Comment by lsongx** [comment]
> Hi, When I want to export the point cloud, it get stuck. This is export script.
> 
> ```
> ns-export pointcloud --load-config outputs/data-dy_check_data-apple/nerfplayer-nerfacto/2023-02-08_113917/config.yml \
> --output-dir exports/pcd_dy_apple/ --num-points 3000000 --remove-outliers True --estimate-normals False \
> --use-bounding-box True --bounding-box-min -5 -5 -5 --bounding-box-max 5 5 5
> ```
> 
> This is the log.
> 
> ```
> split test not found, using split train
> Setting up training dataset...
> Caching all 475 images.
> Setting up evaluation dataset...
> Caching all 475 images.
> Loading latest checkpoint from load_dir
> ✅ Done loading checkpoint from 
> outputs/data-dy_check_data-apple/nerfplayer-nerfacto/2023-02-08_113917/nerfstudio_models/step-000029999.ckpt
> nerfstudio field 
> components: CUDA 
> set up, loading 
> (should be quick)
> ☁ Computing Point C
> ☁ Computing Point Cloud ☁   
> ☁ Computing Point Cloud ☁ ━━━━━━   0% 
> ☁ Computing Point Cloud ☁ ━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 
> ```

Seems that point cloud exporting does not support dynamic scenes. Let me check that

**Comment by rockywind** [comment]
Hi, @lsongx 

> The images are dense with small baselines. For camera path, did you mean 'export camera' in the viewer?

Yes, I don't know how to set the camera path in the viewer.

**Comment by rockywind** [comment]
Hi,
@lsongx 
> Seems that point cloud exporting does not support dynamic scenes. Let me check that.

Thanks.

**Comment by rockywind** [comment]
Thanks, 
I have a try.
