### ISSUE TITLE
ffmpeg required for images (custom dataset)

### ISSUE THREAD

**Issue by tonyyu0822** [nerfstudio-project/nerfstudio#1382]
Hi, I am trying to use colmap on custom image dataset 
and specified in command: ns-process-data images ......... and also commented the check_install.py file 
However, ffmpeg is still required when running command 
( ●    ) Copying images...──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: ffmpeg -y -noautorotate -i 
"/home/by12/Datasets/OMMO/05/After/images/frame_%05d.jpg" -q:v 2 -vf crop=iw-0:ih-0 
"/home/by12/Datasets/OMMO/05/After/images/frame_%05d.jpg"
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
/bin/sh: 1: ffmpeg: not found

**Comment by tancik** [comment]
It looks like `ffmpeg` isn't installed. Can you try installing it and rerun the script.

**Comment by trungswat** [comment]
Hello,

Whether you managed yourself to figure out the solution or not. I would give you my solution after had spent a few hours on struggling to install colmap and ffmpeg as well.
you can manually download the packages and put them in external folder, for example:
**externals\ffmpeg\ffmpeg-master-latest-win64-gpl\bin**
Then you append the location to Path Env:
![image](https://user-images.githubusercontent.com/6658046/222885334-07d9fafd-6e34-4725-b633-57bda648a4b0.png)

**Comment by tancik** [comment]
Thanks for the additional pointers @trungswat

**Comment by Gloamirror** [comment]
could everyone tell me how to solve this problem? I m  trouble in it

**Comment by maturk** [comment]
@Gloamirror `apt install ffmpeg` or `sudo apt install ffmpeg`

**Comment by Gloamirror** [comment]
> ?
ohhh~ you're so quick.
no，suddenly, I found the OS system FFmpeg 's. Edition is 7.4.4, but the nerf studio ns-process-data used the 4.4 version of FFmpeg.  It's so puzzle.!
