### ISSUE TITLE
Access and control number and dimension of layers in nerfacto MLP

### ISSUE THREAD

**Issue by Mehi44** [nerfstudio-project/nerfstudio#1383]
is there an option to access and control the number and dimension of layers in nerfacto MLP or any other model ?

**Comment by tancik** [comment]
You can see the parameters you can modify via command line using `ns-train nerfacto --help`. We expose some of the MLP params, ie `--pipeline.model.proposal-net-args-list.0.num-levels` but these are just for the proposal networks. You would need to modify the code to get access to other params.

**Comment by Mehi44** [comment]
Ah yes, I think also --optimizers.fields.optimizer parameters control the optimizer of the nerf MLP right ? 
Much appreciated :)

**Comment by tancik** [comment]
Yep
