### ISSUE TITLE
nerfacc==0.3.4 has bug

### ISSUE THREAD

**Issue by akaspeh1** [nerfstudio-project/nerfstudio#1405]
**Describe the bug**
Cant use instant-ngp as model due to bug inside nerfacc lib v 0.3.4
https://github.com/KAIR-BAIR/nerfacc/issues/156
`Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/nerfacc/cuda/_backend.py", line 50, in <module>
    from nerfacc import csrc as _C
ImportError: cannot import name 'csrc' from 'nerfacc' (/home/user/.local/lib/python3.10/site-packages/nerfacc/__init__.py)`

**To Reproduce**
1. Install docker container
2. Try train using instant-ngp

**Expected behavior**
Training using instant-gpg should start

**Additional context**
Fix for now is to Temporarily downgrade version insidepyproject.toml to "nerfacc==0.3.3"

**Comment by machenmusik** [comment]
I found that I could install nerfacc 0.3.4 locally from the v0.3.4 tag and things worked properly.  But something appears to be wrong with whatever you get from pip install nerfacc.

**Comment by barney2074** [comment]
I'd be grateful if someone could outline the steps to downgrade nerfacc (I'm a novice)
I'm assuming it needs to be done inside the Docker container ?

thanks 

Andrew

**Comment by machenmusik** [comment]
another option is #1413 if it works for you
