### ISSUE TITLE
Rename train_split_percentage to train_split_fraction?

### ISSUE THREAD

**Issue by devernay** [nerfstudio-project/nerfstudio#1411]
Here:
https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L63

The `train_split_percentage`parameter for the nerfstudio dataparser is actually a fraction (from 0 to 1), not a percentage (from 0 to 100), so the parameter should be named `train_split_fraction` (or simply `train_split`).

Help should read "The fraction (not percent) of images to use for training".

Or it could be done the other way round (percentage instead of fraction, the default being 90).

**Comment by tancik** [comment]
If you would like to make this change, Ill accept a PR.
