### ISSUE TITLE
With nerfacc 0.3.3, repeated lengthy CUDA recompilation on Windows

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#1414]
With nerfacc 0.3.3, lengthy CUDA recompilation on Windows happens repeatedly (every time), rather than only once.

The issue was confirmed to be Windows-specific here: https://github.com/nerfstudio-project/nerfstudio/pull/1277#issuecomment-1402917214

nerfacc 0.3.4 corrects the issue, but unfortunately the available package seems to be broken, so until that is fixed, it needs to be built from github tag.  See #1413

**Comment by machenmusik** [comment]
good news, new nerfacc 0.3.5 with wheels - 
https://github.com/KAIR-BAIR/nerfacc/issues/156#issuecomment-1442836400
maybe bump nerfacc version in pyproject.toml now @tancik ?

**Comment by liruilong940607** [comment]
Close as this is fixed now.
