### ISSUE TITLE
Is there some difference between ns-train and python scripts/train.py

### ISSUE THREAD

**Issue by 07hyx06** [nerfstudio-project/nerfstudio#1420]
Hi, thanks for the great effort! 

I plan to play around with this project using the vscode debug mode to find out its code logic. In the document, it suggests using ns-train or some other command beginning with `ns` to run the project. I wonder is there any difference between the `ns-train` and the python command `python scripts/train.py`?

**Comment by tancik** [comment]
They are the same. He are the mappings
https://docs.nerf.studio/en/latest/reference/cli/index.html
