### ISSUE TITLE
completeness of nerfplayer implementation

### ISSUE THREAD

**Issue by TheSoulOfCorn** [nerfstudio-project/nerfstudio#1429]
Hello, I was wondering if the current code for NeRFPlayer is complete? 
I noticed the TemporalGridEncoder extending time dimension, but didn't find the implementation of the whole pipeline (newness field, decomposition field, etc.)

**Comment by lsongx** [comment]
Hi @TheSoulOfCorn  Yes you are right! 
I didn't make the decomposition work on the nerfstudio framework, and I got NaN (similar to https://github.com/nerfstudio-project/nerfstudio/issues/873) after some steps. Adding decomposition requires more training steps to converge.
Besides, I found that decomposition brings marginal improvements if good supervision are presented (like multi-camera in Google's Deepview or depth in DyCheck). Decomposition is needed when we work on single camera (like Hypernerf) or low-framerate settings (some ablations are presented in the paper).
That being said, I will continuously check the NaN issues and update if needed.
