### ISSUE TITLE
When will Mip-NeRF 360 be re-added?

### ISSUE THREAD

**Issue by CSU-NXY** [nerfstudio-project/nerfstudio#1437]
Hi, I noticed mip-nerf 360 is removed from this repo. Do you have any plan to add it back?

**Comment by tancik** [comment]
mipnerf-360 was never added to the repo. We chose to focus development on nerfacto since nerfacto contains many of the improvements that mipnerf-360 introduced while also being significantly faster to train.

**Comment by CSU-NXY** [comment]
I see. Thank you very much.
