### ISSUE TITLE
About auto tunnel establishing

### ISSUE THREAD

**Issue by XinyangHan** [nerfstudio-project/nerfstudio#1451]
I am using a remote server connected using ssh and vscode as editor. I successfully go through other operations in the quick start, and I can observe the port forward being automatically launched in the vscode. But when I open the browser with the url locally, there is nothing being rendered. (Not training images or the rendering scene) I guess it might be due to the port is not open for forwarding, but do not have a direct idea to fix this without root access.

![image](https://user-images.githubusercontent.com/86959032/219936964-2fbeb8f8-1317-41ba-b5ae-e91e561d1207.png)
![image](https://user-images.githubusercontent.com/86959032/219936969-9294414a-77b4-4283-ba42-b31ff71f0aae.png)

**Comment by tancik** [comment]
Is this browser in vscode? If so, maybe try opening the viewer in chrome. You can also try starting a [localtunnel](https://theboroer.github.io/localtunnel-www/) to expose the port.

**Comment by XinyangHan** [comment]
Unfortunately, the chrome does not work either. After trails with telnet, I found out maybe it is due to that some ports like 7007 on the server is not opened, and only port 22 is opened but failed to run the script either.
![1676835106233](https://user-images.githubusercontent.com/86959032/219970762-f22d6647-0e21-4e97-8b73-70319b47bd04.png)
![1676835242275](https://user-images.githubusercontent.com/86959032/219970892-7c3cc134-201e-4fb4-b01d-0dbc620df0b0.png)
![1676835270483](https://user-images.githubusercontent.com/86959032/219970908-54f1413b-67a6-4b7e-a0af-9556a5287f41.png)

**Comment by XinyangHan** [comment]
Problem solved, it is the problem of slurm.

**Comment by Paralelopipet** [comment]
@XinyangHan I have the same problem and I am using HPC which runs on slurm as well. I would appreciate if you could share in more detail what you did to resolve the problem.

**Comment by rwn17** [comment]
Hi @XinyangHan, I'm also trying to use nerfstudio on slurm cluster and experiencing the same issue you mentioned. I'd really appreciate it if you could share how to solve it.

**Comment by Paralelopipet** [comment]
Hi @rwn17. For me it was the following problem: i have two active nodes on slurm, one utilizing lets call it gpu_node and one being loginnode with terminal. The problem i encountered is that gpunode on my slurm wasn't able to forward the port to my localhost, simply set up this way. I found two solutions:

1. Forwarding the port to gpunode->loginnode and then loginnode->localhost
2. Connecting gpu to the login node and forwarding the port to the localhost. In my case command for connecting GPU looks something like this
> sintr -N1 -A OZTIRELI-SL3-GPU -p ampere -t 1:0:0 --gres=gpu:1 --qos=INTR

Hope this helps clarify the issue!
