### ISSUE TITLE
Camera editing

### ISSUE THREAD

**Issue by barney2074** [nerfstudio-project/nerfstudio#1463]
Hi

Just getting started with nerfstudio- loving it so far & thank you.
Apologies if these are obvious Q&As- I've looked through the documentation & can't see anything

1. Is there any way I can edit the camera rotation in the GUI i.e pitch, yaw, roll or camera tilt ?
Same applies to to the camera target. Looking at the camera path json- I'm guessing it would be possible to edit the matrix coordinates, although not easy

2. Is there any way to return to the position of an exisiting camera in the 'viewport' view, and then edit/update the camera
The eye icon in the render view takes you to that camera view, but 'add camera' adds the new cam in the position of the 'viewport' view

thanks again for the great work

Andrew

**Comment by tancik** [comment]
https://user-images.githubusercontent.com/3310961/220264055-d2a4df63-cd2b-41cd-8a37-fa2eff438a78.mov

For more fine grain camera control, I recommend using the [blender plugin](https://docs.nerf.studio/en/latest/quickstart/blender_addon.html) to make camera paths.

**Comment by barney2074** [comment]
thanks for the quick reply- I completely miseed the rotate button in the top right of the viewport window- that answers my point 1.

Yes, I'm planning to try out the Blender plugin- wondering if there is any plan to make it available on Linux ??
I'm thinking the best workflow is to create a rough camera path in nerfstudio, export & fine tune in Blender & bring back into nerfstudio


Andrew

**Comment by tancik** [comment]
I'll double check, but I think the blender plugin should work in linux.

**Comment by barney2074** [comment]
thanks @tancik 

Yes, I confirm the plugin works on Linux (the doc indicates just Mac & Windows)  
![image](https://user-images.githubusercontent.com/25944617/220781084-5045eef0-dab0-4681-912b-8243bfeae6bf.png)
Blender has obviously got sophisticated camera controls- so I'd recommend this to anyone

I did notice some strangeness with the FOV/focal length setting in nerfstudio

- If I import the camera path from Blender and don't mess with anything, it works fine, but says the camera focal length is 38mm
- My Blender camera is 28mm

So for example- in this animation- the left is from Blender (28mm camera) and the right is nerfstudio (38mm camera)
It's not a big deal for me- but might matter to someone compostiting

https://user-images.githubusercontent.com/25944617/220784324-a8145714-0896-45cb-8e27-3ddbfdacbd33.mp4



Andrew

**Comment by tancik** [comment]
I think it has to do with horizontal vs vertical focal length.

@cvachha

**Comment by barney2074** [comment]
thanks @tancik 

I don't understand it very well- except to know it is complicated & FOV--<>focal length is not a simple thing

I did have a look in the camera path exported from JSON- which didn't really help
My 28mm Blender lens shows a FOV of 39 (should be more like 75degrees HFOV)
I thought it might be half of HFOV, but yes VFOV might make sense

![image](https://user-images.githubusercontent.com/25944617/220793445-a274afcc-bf6f-4b0d-a589-cd06707a8fe3.png)

**Comment by cvachha** [comment]
Hello,
The FOV written in the Nerfstudio camera path json is the vertical FOV of the Nerfstudio camera. Blender handles FOV differently and doesn't have a direct way to enter vertical FOV comparable to the Nerfstudio FOV.  
The focal length, FOV, and aspect ratio from Blender camera are used to calculate the Nerfstudio camera FOV. 

Is there an issue with the alignment with FOV in Blender or Nerfstudio?

**Comment by barney2074** [comment]
thanks @cvachha 

No it aligns perfectly.
I'd assumed that the focal length in the nerfstudio gui would be the same as in Blender

So just to confirm- the FOV shown in nerfstudio GUI is VFOV ?

thanks

Andrew

**Comment by cvachha** [comment]
Yes, I think the nerfstudio GUI shows Vertical FOV
