### ISSUE TITLE
About the train_camera_optimizer used in both train_ray_generator and eval_ray_generator.

### ISSUE THREAD

**Issue by MaxChanger** [nerfstudio-project/nerfstudio#1470]
I have a little doubt why `self.train_camera_optimizer` is used in both `train_ray_generator` and `eval_ray_generator`.
`train_camera_optimizer `

The size of  `self.pose_adjustment = torch.nn.Parameter(torch.zeros((num_cameras, 6), device=device))` is determined by `num_cameras=self.train_dataset.cameras.size`. 
It can be considered that only the train image camera pose is optimized, and the eval image pose is not optimized.

But why is it necessary to index an optimization variable based on image_idx during eval.

Thanks in advance.

https://github.com/nerfstudio-project/nerfstudio/blob/0d336a181e76588f3b3cb6ba6419d7efc2bcf297/nerfstudio/data/datamanagers/base_datamanager.py#L382-L388

https://github.com/nerfstudio-project/nerfstudio/blob/0d336a181e76588f3b3cb6ba6419d7efc2bcf297/nerfstudio/data/datamanagers/base_datamanager.py#L403-L408

**Comment by ethanweber** [comment]
Good catch, I'll merge a PR to correct this -- #1473.
