### ISSUE TITLE
poor results on nerfstudio-data and mipnerf360 datasets

### ISSUE THREAD

**Issue by cv-lab-x** [nerfstudio-project/nerfstudio#1471]
HI, thanks for your great work,  i got very poor results on nerfstudio datasets and mipnerf 360 datasets when i use the default config params.   Can your share your config params to reproduce the results on your paper [Nerfstudio: A Modular Framework for Neural Radiance Field Development](https://arxiv.org/abs/2302.04264) 
looking forward to your reply, thanks!  @tancik @machenmusik @ethanweber @tancik @evonneng

**Comment by tancik** [comment]
This branch has the exact code that was used in the paper - https://github.com/nerfstudio-project/nerfstudio/pull/1139

**Comment by jkulhanek** [comment]
I just tried the "garden" scene with the current `main` branch and it worked well. I haven't run any quantitative analysis, though. Can you provide some more details on how "poor" the results are?

I am attaching a picture I am getting (after 10k iterations of nerfacto model).
![image](https://user-images.githubusercontent.com/4222114/221362935-f31a47b8-7949-418e-b4ac-eb55a3cdcaaa.png)

**Comment by cv-lab-x** [comment]
> I just tried the "garden" scene with the current `main` branch and it worked well. I haven't run any quantitative analysis, though. Can you provide some more details on how "poor" the results are?
> 
> I am attaching a picture I am getting (after 10k iterations of nerfacto model). ![image](https://user-images.githubusercontent.com/4222114/221362935-f31a47b8-7949-418e-b4ac-eb55a3cdcaaa.png)

i use the default colmap results in mipnerf360 datasets, and the default config in nerfacto, the eval psnr is less than 22, it's much more blur than your results.
here's my train scripts
`ns-train nerfacto --data data/360_v2/garden/nerfstudio  --output-dir outputs/mipnerf360 --steps-per-eval-batch 500 --steps-per-eval-image 500 --steps-per-eval-all-images 5000 --max-num-iterations 60001 --experiment-name garden_noappearance --pipeline.model.predict-normals False --vis viewer+tensorboard --viewer.skip-openrelay True --viewer.websocket-port 7040    --pipeline.model.use-average-appearance-embedding False nerfstudio-data `

**Comment by jkulhanek** [comment]
How did you process the dataset (generated transforms.json)?
________________________________

**Comment by jkulhanek** [comment]
I can sent you my transforms.json so you can try if the problem is with data processing. Do you want me to send it to your email?

**Comment by cv-lab-x** [comment]
> I can sent you my transforms.json so you can try if the problem is with data processing. Do you want me to send it to your email?

thank your for your reply, i think the problem is the camera pose optimizer. Once i turn off the camera pose optimizer, the training img psnr would improve from 22 to 26, and the test imgs would be more sharp
