### ISSUE TITLE
Rendering images using ns-render --output-format

### ISSUE THREAD

**Issue by at82** [nerfstudio-project/nerfstudio#1472]
I want to render images using ns-render --output-format option. No matter how many cameras I put in the scene, the number of images rendered is 96. I'd like to be able to control how many images per degree of rotation I can render. How can I do that? Thanks!

**Comment by tancik** [comment]
Can you post the full command that you are using?

**Comment by at82** [comment]
Here is the full command: 

ns-render --load-config "path-to-config.yml" --traj filename --camera-path-filename "path-to-camera-path-file" --output-format images   --output-path "output-directory-path"

**Comment by tancik** [comment]
The number of frames will depend on the number of seconds you choose when creating the camera path in the viewer. Can can retroactively modify it if you open the camera_path.json file and search for `seconds`

**Comment by tancik** [comment]
You can modify the length by changing the `duration` and `seconds` in the viewer. They default to 4 and 24 (hence 4*24=96)
<img width="366" alt="image" src="https://user-images.githubusercontent.com/3310961/220720599-be7cc275-dacd-4535-a207-a57f8c426b89.png">

**Comment by at82** [comment]
Thanks! I have tried to use argument --seconds with ns-render to change the duration of the video, but it didn't work. I'm going to modify the camera_path.json manually as you suggested.

**Comment by tancik** [comment]
The json contains all of the cameras (the render script doesn't do any interpolation). So all the camera need to be created at the time of the creation of the json.
