### ISSUE TITLE
New here so help needed on Google Colab

### ISSUE THREAD

**Issue by baloo710** [nerfstudio-project/nerfstudio#1477]
Hi Im hoping someone could help. I am very new to this area and using a Colab. I go through each step and I see the occasional warning but I think Im doing everything right but when it comes to starting the training I dont see anything in the viewer like a set of images or model coming together. I refresh the page like it says in the viewer but still nothing.

Ive attached a screenshot of the steps with the code that comes up

Any help would be great
![Code_text](https://user-images.githubusercontent.com/116604947/220752397-5eabed70-f25a-4220-88f0-c3653165e501.png)

**Comment by tancik** [comment]
The `Start Training` cell should be running when you refresh the viewer. It looks like that cell completed in 15second, this implies that the training must have failed. Is there an error at the end of the cells outputs?

**Comment by tancik** [comment]
Ahh, this is where colab can be frustrating, it sometimes clips the outputs. Very likely the training is failing, but it is not showing the error. This also make is hard to debug...

**Comment by baloo710** [comment]
Ok, have any suggestions on what to try next or is it likely I just cant use this Colab?

**Comment by tancik** [comment]
I just tried it, I am running into the same issue. It appears to be a couple of issues.

First there is an issue with the tinycudann installation:

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/3310961/220982579-ded3ffaa-c881-46aa-b18f-3f91ec12b467.png">

As a workaround, you can run the following code prior to the training cell (note it will take a few minutes),
`pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`

However... there seems to be other issues, the training doesn't appear to start.

**Comment by whitschroder** [comment]
The above solution worked for me.

**Comment by baloo710** [comment]
Thanks how would I add that code, could you show me a screen shot of where to add it and what to copy or write

Thanks

**Comment by m0o0scar** [comment]
> I just tried it, I am running into the same issue. It appears to be a couple of issues.
> 
> First there is an issue with the tinycudann installation:
> 
> <img alt="image" width="1475" src="https://user-images.githubusercontent.com/3310961/220982579-ded3ffaa-c881-46aa-b18f-3f91ec12b467.png">
> 
> As a workaround, you can run the following code prior to the training cell (note it will take a few minutes), `pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch`
> 
> However... there seems to be other issues, the training doesn't appear to start.

Hi @tancik thanks for the reply. I'm having the same issue and tried installing tinycudann following this method, but it stuck at `Building wheels for collected packages: tinycudann` for a long time. Any suggestion what should I do? Thanks :)

**Comment by tancik** [comment]
@m0o0scar It takes quite a while to build, maybe 10min. That's why we provided a prebuilt wheel (though it seems to have broken). We will update it soon.
