### ISSUE TITLE
Use pycolmap for all platforms

### ISSUE THREAD

**Issue by pwais** [nerfstudio-project/nerfstudio#1480]
`pycolmap` currently does not build very easily for Windows, and there's no public compiled wheel.  This ticket documents progress and related issues.  Eventually when windows wheels become available, search for this issue number in code to port fully to `pycolmap`. 

References:
 * Historical issue: https://github.com/nerfstudio-project/nerfstudio/issues/263
 * pycolmap added to docker for hloc support: https://github.com/nerfstudio-project/nerfstudio/pull/1478
 * Attempt to build windows wheels: https://github.com/colmap/pycolmap/pull/114
 * Request for help from COLMAP team: https://github.com/colmap/colmap/issues/1810

**Comment by pwais** [comment]
closing this, notes in https://github.com/colmap/pycolmap/issues/111#issuecomment-1633078069

**Comment by VasuAgrawal** [comment]
FYI, it seems `pycolmap` has Windows wheels now: https://pypi.org/project/pycolmap/#files
