### ISSUE TITLE
 "verbose" param is misinterpreted as "crop_border_pixels" positionally and cause unexpected cropping of images.

### ISSUE THREAD

**Issue by edwardchenomni** [nerfstudio-project/nerfstudio#1485]
**Describe the bug**
Erroneous positional assignment of _verbose_ parameter is causing unwanted cropping behavior due to being misinterpreted as _crop_border_pixels_.

https://github.com/nerfstudio-project/nerfstudio/blob/a91b92f89d401115b42e6ad295a8b850e02ee86f/nerfstudio/process_data/process_data_utils.py#L262

https://github.com/nerfstudio-project/nerfstudio/blob/a91b92f89d401115b42e6ad295a8b850e02ee86f/nerfstudio/process_data/process_data_utils.py#L153

**To Reproduce**
1. run `ns-process-data images` with --verbose flag
2. the copied images are resized with 2 pixels less.

**Additional context**
Someone should review all positional assigned parameters.

**Comment by tancik** [comment]
Thanks for catching!
