### ISSUE TITLE
Why the empty `setup.cfg` file ?

### ISSUE THREAD

**Issue by SauravMaheshkar** [nerfstudio-project/nerfstudio#1489]
I'm sorry but I'm unable to understand the reason behind the empty `setup.cfg` file 😓

**Comment by tancik** [comment]
Great question. I think it was added at some point to prevent pip from complaining during installation. But it doesn't seem like it is necessary (I'm a novice at packaging). If it is indeed not necessary, I'm fine with it being removed.

**Comment by SauravMaheshkar** [comment]
Yes, the `setup.cfg` isn't necessary and does not affect packaging.

**Comment by SauravMaheshkar** [comment]
Made a PR (#1495) to delete `setup.cfg`
