### ISSUE TITLE
zmq.error.ZMQError:Operation cannot be accomplished in current state

### ISSUE THREAD

**Issue by ldzhuang** [nerfstudio-project/nerfstudio#1493]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by machenmusik** [comment]
(Closing in favor of #1494.)

**Comment by ldzhuang** [comment]
![EC372D40-2BA4-4874-9F01-AA2CA09A6799](https://user-images.githubusercontent.com/64113233/221327963-9bf9cc24-2f84-406f-a627-73a805d03d92.png)
