### ISSUE TITLE
Running on WIndows outside conda or docker

### ISSUE THREAD

**Issue by SoftologyPro** [nerfstudio-project/nerfstudio#1506]
I am trying to get a batch file working to install and run nerfstudio on Windows without needing conda or docker.
This is the install batch file

```
@echo off
if exist nerfstudio\. rd /S /Q nerfstudio
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
python -m venv .venv
call .venv\scripts\activate.bat
python.exe -m pip install --upgrade pip
pip install wheel
pip install --upgrade pip setuptools
pip install -e .
pip uninstall -y torch
pip install --no-cache-dir --ignore-installed --force-reinstall --no-warn-conflicts torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116
python scripts\downloads\download_data.py nerfstudio --capture-name=poster
python scripts\train.py nerfacto --data data/nerfstudio/poster
```

That installs a clean copy of nerfstudio and shows the URL to open, but because it auto-exits at the end of the batch file the web page front end complains "Server disconnected" and "Render disconnected".

What python command should I use to start nerfstudio once the install is finished?  Start and "stay resident" so the web UI still sees the local server.

Why?  Because I have had requests to add support for this into Visions of Chaos and if it can be run without conda or docker that is one less thing for users to install.

Thanks.

**Comment by tancik** [comment]
I'm a bit confused by your question. Does it start training for you? And while it is training does it show you the url?

**Comment by SoftologyPro** [comment]
OK, so basically I want to be able to start and run the Web UI interface after the above installation.
When I run that batch file last 2 lines downloads poster.zip and then train.py runs and shows
[Public] Open the viewer at https://viewer.nerf.studio/versions/23-02-3-0/?websocket_url=ws://localhost:7007
After that the batch file exits back to a command prompt, so when I open that URL it complains "Server disconnected"

So, how can I start the URL without it complaining about the server being disconnected?

Hope that makes sense?

Thanks.

**Comment by tancik** [comment]
So is the training is still happening when the batch file exits? Also when you open the url, do you see anything show up in the 3d view (ignore the `server disconnected` message, its not always accurate)?

**Comment by SoftologyPro** [comment]
OK, I am not really sure.  I think I need to fix tcnn first though.  This is the last output I get from
`python scripts\train.py nerfacto --data data/nerfstudio/poster`

```
========================================================================================================================
[Public] Open the viewer at https://viewer.nerf.studio/versions/23-02-3-0/?websocket_url=ws://localhost:7007
========================================================================================================================

Sending ping to the viewer Bridge Server...
Successfully connected.
Sending ping to the viewer Bridge Server...
Successfully connected.
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
Disabled tensorboard/wandb event writers
[13:16:12] Auto image downscale factor of 2                                                 nerfstudio_dataparser.py:314
           Skipping 0 files in dataset split train.                                         nerfstudio_dataparser.py:165
           Skipping 0 files in dataset split val.                                           nerfstudio_dataparser.py:165
Setting up training dataset...
Caching all 204 images.
Setting up evaluation dataset...
Caching all 22 images.
Printing profiling stats, from longest to shortest duration in seconds
Traceback (most recent call last):
  File "D:\NerfStudio\nerfstudio\scripts\train.py", line 256, in <module>
    entrypoint()
  File "D:\NerfStudio\nerfstudio\scripts\train.py", line 247, in entrypoint
    main(
  File "D:\NerfStudio\nerfstudio\scripts\train.py", line 233, in main
    launch(
  File "D:\NerfStudio\nerfstudio\scripts\train.py", line 172, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "D:\NerfStudio\nerfstudio\scripts\train.py", line 86, in train_loop
    trainer.setup()
  File "D:\NerfStudio\nerfstudio\nerfstudio\engine\trainer.py", line 153, in setup
    self.pipeline = self.config.pipeline.setup(
  File "D:\NerfStudio\nerfstudio\nerfstudio\configs\base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "D:\NerfStudio\nerfstudio\nerfstudio\pipelines\base_pipeline.py", line 237, in __init__
    self._model = config.model.setup(
  File "D:\NerfStudio\nerfstudio\nerfstudio\configs\base_config.py", line 59, in setup
    return self._target(self, **kwargs)
  File "D:\NerfStudio\nerfstudio\nerfstudio\models\base_model.py", line 82, in __init__
    self.populate_modules()  # populate the modules
  File "D:\NerfStudio\nerfstudio\nerfstudio\models\nerfacto.py", line 152, in populate_modules
    self.field = TCNNNerfactoField(
  File "D:\NerfStudio\nerfstudio\nerfstudio\fields\nerfacto_field.py", line 140, in __init__
    self.direction_encoding = tcnn.Encoding(
NameError: name 'tcnn' is not defined
```

And tcnn won;t compile because of this 
`fatal error C1083: Cannot open include file: 'crtdefs.h': No such file or directory`
but the file is there in the path.

Anyway, maybe just close this issue until I can fix tcnn.  If I get all that working and nerfstudio does not work I will be back with a hopefully easier to explain problem.
