### ISSUE TITLE
Don't crean custom method

### ISSUE THREAD

**Issue by MoZhenJ** [nerfstudio-project/nerfstudio#1521]
Hello, when I creat new nerf pipelines, join it to method_configs, it has a error "Argument of type "CirtusParserConfig" cannot be assigned to parameter "dataparser" of type "AnnotatedDataParserUnion" in function "__init__"", and I don't compile with the command "ns-install-cli":
 AssertionError: `pipeline.datamanager.dataparser` was provided a default value of type <class                
           'nerfstudio.data.dataparsers.Cirtus_datapaser.CirtusParserConfig'> but no matching subcommand                
           was found.
How can I fix it. Thanks you very much.

**Comment by Tao-11-chen** [comment]
Hello, can you figure out what problem it is?
