### ISSUE TITLE
ns-train error

### ISSUE THREAD

**Issue by wangmingyang4** [nerfstudio-project/nerfstudio#1534]
dear,
the work is so great!
but i I encountered a problem

error：
terminate called after throwing an instance of 'std::runtime_error'
  what():  /home/w/nerf/ngp_pl/tiny-cuda-nn/include/tiny-cuda-nn/multi_stream.h:83 cudaEventRecord(m_event, m_stream) failed with error an illegal memory access was encountered
已放弃 (核心已转储)

env：
CUDA11.7
torch 1.13.1
tinycudann 1.7
ubuntu 20.04
rtx2080super 8G

I tried to change the version of CUDA, Torch and Tinycudann . The same error.

**Comment by wangmingyang4** [comment]
I was able to successfully run nerstudio in the past, but the old env was deleted.

**Comment by tancik** [comment]
I've been able to replicate using a fresh install. Looking into it now.

**Comment by tancik** [comment]
Can you try
`pip uninstall tinycudann`
`pip install git+https://github.com/NVlabs/tiny-cuda-nn.git@e4c147e36893bef3a065b1e5db69706951ea4d56#subdirectory=bindings/torch`

**Comment by krrish94** [comment]
I ran into the same issue recompiling nerfstudio today. This fix works on my end

**Comment by rwijmashell** [comment]
> Can you try `pip uninstall tinycudann` `pip install git+https://github.com/NVlabs/tiny-cuda-nn.git@e4c147e36893bef3a065b1e5db69706951ea4d56#subdirectory=bindings/torch`

Hi, I was getting the same error after a new install. Same env except using a 2080 Ti. This did fix the error, thanks!

**Comment by tancik** [comment]
Should be fixed in the main tinycudann branch now - https://github.com/NVlabs/tiny-cuda-nn/issues/272
I'm going to close this issue, reopen if it is still an issue.

**Comment by iszihan** [comment]
Hi, I'm running into the same error even with this reinstallation of tinycudann. I'm on Ubuntu 22.04, torch 2.0.1+cuda118, tinycudann 1.7
