### ISSUE TITLE
Is there a way to save checkpoints to a customized path?

### ISSUE THREAD

**Issue by yimingzhou1** [nerfstudio-project/nerfstudio#1536]
Hi,

Currently the trained model ckpt is saved in the `outputs` folder by default indexed by model name, dataset name and current date/time. Is there a easy way to save the checkpoint in a customized folder instead of change the source code? Or are you open to a PR that adds such a feature? Thanks!

**Comment by tancik** [comment]
You can modify `--output-dir`, `--method-name`, `--experiment-name` and `--timestamp` via CLI. Is this enough?

**Comment by yimingzhou1** [comment]
Yes! This is very helpful. Thanks!
