### ISSUE TITLE
In a multi GPU machine, how  to set (or pass)  the GPU id while startting a training session?

### ISSUE THREAD

**Issue by karun2016** [nerfstudio-project/nerfstudio#1550]
I have a linux machine with multiple GPUs (ids 0 through 3). When I start a training session like 
_$ns-train nerfacto --data data/nerfstudio/poster_, by default it uses GPU 0. But I want to select a specific GPU like GPU 1  or GPU 2. How to pass it  via the command line?.  
I know that  there is a parameter _--machine.num-gpus 2_ to specify the total number of GPUs to use. But I want to start  with a specific GPU id like _gpu id = 2_ and _--machine.num-gpus 2_ for using 2 GPUs GPU 2 and 3.
Is there a way to specifiy the GPU id ?

**Comment by tancik** [comment]
You can specify the GPU the program has access to by adding `CUDA_VISIBLE_DEVICES=0` before the `ns-train` command.

**Comment by karun2016** [comment]
Thanks a lot. Works now.
