### ISSUE TITLE
What's the output from ns-export?

### ISSUE THREAD

**Issue by Scolymus** [nerfstudio-project/nerfstudio#1559]
I want to open the 3D cloud of points to see if I can do some maths to optimize the path I will use to render later NERF. Therefore, I'm using:

`ns-export pointcloud --load-config myyaml.yml --output-dir mypath --estimate-normals True`

However, I have some questions:

1. What exactly means to print "normals" from a point? Is it just normalized distances or refering to a vector?
2. If I open the output:
```
from plyfile import PlyData, PlyElement

plydata = PlyData.read('point_cloud.ply')
print(len(plydata.elements))
print(plydata.elements[0].data[0])
```

I see elements only have one row, where this row is full of rows containing the following structure:

(-0.11864859, -0.48700908, -0.26703912, 0.70632357, 0.19765326, -0.6797354, 105, 102, 102)

I understand the last 3 are RGB. What exactly are the first 6 points? If I remove normals the output would be just X, Y, Z, R, G, B?

3. When making later the rendering, are points always from -1 to 1 in their dimension?

thanks!

**Comment by tancik** [comment]
1. The are the estimated geometry normals for that location. It call this under the hood - http://www.open3d.org/docs/0.7.0/tutorial/Basic/pointcloud.html#vertex-normal-estimation
2. If you open the .ply, it will list the `property _type_ NAME` at the top for each column. My guess in this case is, X,Y,Z,normal_x,normal_y,normal_z,R,G,B
3. Depends on the crop box that you choose, defined by `--bounding-box-min` and `--bounding-box-max` - https://docs.nerf.studio/en/latest/reference/cli/ns_export.html#pointcloud

**Comment by Scolymus** [comment]
If someone needs it, I'm loading now with http://www.open3d.org/docs/0.7.0/tutorial/Basic/pointcloud.html#vertex-normal-estimation, which is fastest and simplest.
