### ISSUE TITLE
Problems with PIP installing nerfstudio

### ISSUE THREAD

**Issue by JRopes** [nerfstudio-project/nerfstudio#1576]
**Describe the bug**
I am setting up nerfstudi for Windows with CUDA 11.7 and VS 2022, as described in the docs. When I run "pip install nerfstudio" it successfully installs everything, however, for some reason it seems to uninstall PyTorch with CUDA 11.7, which I just installed in the previous step. At the end, I am able to preprocess data with nerfstudio but as soon as I try to train a model I get an error:

`OSError: Unknown compute capability. Ensure PyTorch with CUDA support is installed.`

I am quite confused by this because I did install it as instructed, but then pip installing nerfstudio seems to uninstall it again as indicated by this line:

`Attempting uninstall: torch
    Found existing installation: torch 1.13.1+cu117
    Uninstalling torch-1.13.1+cu117:
      Successfully uninstalled torch-1.13.1+cu117`

What could be causing this? Am I doing anything wrong?

**To Reproduce**
Follow [these steps](https://docs.nerf.studio/en/latest/quickstart/installation.html) for Windows > 11.7 with VS 2022

**Expected behavior**
A clean installation of nerfstudio.

**Comment by JRopes** [comment]
Update: This problem has been solved by simply installing Torch with CUDA again. However, for the future this should be changed as it seems counter-productive to instruct an installation of something just for an installer to later uninstall it.

**Comment by tancik** [comment]
Hmm, I'm not sure why it tried to uninstall pytorch. Do you know what it installed in its place?
