### ISSUE TITLE
Render doesnt work for Vanilla Nerf

### ISSUE THREAD

**Issue by manasi9610** [nerfstudio-project/nerfstudio#1580]
I am running the following command with reference to a vanilla nerf model I trained- 
`ns-render --load-config /home/ubuntu/nerfstudio/outputs/unnamed/vanilla-nerf/2023-03-10_091341/config.yml`

I am however getting this error-
![Screenshot 2023-03-10 at 3 21 43 PM](https://user-images.githubusercontent.com/90911390/224284658-58c55737-5b7f-4163-a6cb-b609945c16cb.png)

Note- this is only the case for the vanilla nerf model, it works as expected for the rest.

**Comment by tancik** [comment]
Add `--rendered_output_name rgb_fine` to the end of the command.
