### ISSUE TITLE
Is there an easy way to render train images to files?

### ISSUE THREAD

**Issue by cpeng93** [nerfstudio-project/nerfstudio#1590]
**Is your feature request related to a problem? Please describe.**
It would be great if we can have a simple way to render the train images for experimental purposes. Not sure if this is something that has already existed but I haven't been able to figure it out. 

**Describe the solution you'd like**
Adding some option in ns-render to render train images/all provided images. 

**Describe alternatives you've considered**
I've tried to fiddle with the config file to make evaluation/ns-render to render all images instead of just the eval set. Nothing super straightfoward can be done cause the train/eval split also determines some of the model parameters. 

Alternatively can perhaps transform the original transforms.json file into a camera_path.json file, but the camera poses are likely optimized by nerfacto. 

**Additional context**

**Comment by qhdqhd** [comment]
How to render eval set? Is there any instructions or commands? thanks

**Comment by hturki** [comment]
https://github.com/nerfstudio-project/nerfstudio/pull/2135 should allow you to render eval images with ns-eval --render_output_path
