### ISSUE TITLE
pytorch 2.0 no longer supports six

### ISSUE THREAD

**Issue by julianrendell** [nerfstudio-project/nerfstudio#1610]
First installation, trying to run 

```
ns-download-data nerfstudio --capture-name=poster
```

resulted in:
```
ImportError: cannot import name 'string_classes' from 'torch' (xxxx\nerfstudio\lib\site-packages\torch\__init__.py)
```

Found that `six` is now deprecated in pytorch (https://github.com/pytorch/pytorch/pull/94709.)

I edited `nerfstudio\nerfstudio\data\utils\nerfstudio_collate.py`
and removed `from torch._six import string_classes` and replaced the usage of `string_classes` with `str` in line 121.

I'm not sure if this is the correct fix, but the script now starts- but now crashes with  

```
.conda\envs\nerfstudio\lib\site-packages\torch\cuda\amp\grad_scaler.py", line 368, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
```

**Comment by julianrendell** [comment]
Note; hit this issue following the instructions for the Torch 1.13.1 with CUDA 11.7
dependencies. I think the installation instructions should read 
```pip install torch==1.13.1 torchvision functorch --extra-index-url https://download.pytorch.org/whl/cu117```

instead of:

```pip install torch torchvision functorch --extra-index-url https://download.pytorch.org/whl/cu117```

**Comment by julianrendell** [comment]
Verified that adding  the explicit torch version gets things working (for me). Minor doc change: https://github.com/nerfstudio-project/nerfstudio/pull/1611

**Comment by ksnzh** [comment]
same issue https://github.com/nerfstudio-project/nerfstudio/issues/1613

**Comment by tancik** [comment]
Set the requirements to be < 2, should avoid this issue going forward.
