### ISSUE TITLE
Problems with installing nerfstudio v0.1.19

### ISSUE THREAD

**Issue by JRopes** [nerfstudio-project/nerfstudio#1617]
**System**
Windows 10 64-Bit
Python 3.8
VS2019 with CUDA 11.3

**Describe the bug**
There seems to be a conflict with nerfstudio requiring matplotlib>=3.5.3 and nuscenes-devkit requiring matplotlib<=3.5.2, which I am unable to resolve.

**To Reproduce**
1. Create a fresh Conda Env
2. Attempt to 'pip install nerfstudio==0.1.19'

**Additional context**
I got nerfstudio==0.1.9 working already but am having trouble upgrading it. I tried this with different Python versions, more relaxed version requirements (nerfstudio>=0.1.17), and by installing it from the source code. I know this is technically not a bug but probably a problem on my side but I cannot get it resolved and would really like a newer nerfstudio version that supports the dynamic scene models. Any help is appreciated!

<img width="759" alt="Conflict" src="https://user-images.githubusercontent.com/50622010/225626401-e045c2b6-3527-4600-8659-56d8634e22e3.PNG">

**Comment by JRopes** [comment]
Resolved by trying different combinations of libraries and reinstalling everything

**Comment by ZeroSaturn** [comment]
I need help to solve this. How do you fix it ? what did you do? is there an easy way to fix?
