### ISSUE TITLE
Unable to run demo.ipynb on google collab

### ISSUE THREAD

**Issue by somyamehta24** [nerfstudio-project/nerfstudio#1625]
I am trying to run the demo file on collab but no view is being loaded on the viewer.
Can anyone please help me out. It's showing training is finished but I can't see anything in the viewer.
![image](https://user-images.githubusercontent.com/62494153/225929617-d2f80009-0f40-4556-84f8-3488e4a4429c.png)

**Comment by tancik** [comment]
Did you refresh the viewer?

**Comment by somyamehta24** [comment]
I refreshed it at that time but then also it didn't work but now I ran the collab again and it's working fine now.
