### ISSUE TITLE
502 Bad Gateway of web viewer

### ISSUE THREAD

**Issue by StarsTesla** [nerfstudio-project/nerfstudio#1632]
Hi, there

I follow the installation instruction and I ran the first train model, when I try to visit the web ui, the problem occurs:

0: I run this on my server and the train process has been done
1: I forward the port by ssh both for 7007 and 7018
`ssh -L 7018:localhost:7018 -p xxxx  root@172.16.xx.xx`
2: I visit the url in chrome
`https://viewer.nerf.studio/versions/23-03-9-0/?websocket_url=ws://localhost:7018`
3: the chrome shows:
`502 Bad Gateway`

![image](https://user-images.githubusercontent.com/45264423/226116687-e75961d5-2fc1-44e0-9ad7-9885a54c6858.png)
![image](https://user-images.githubusercontent.com/45264423/226117194-7e4a2017-6fbb-4bb5-aff7-98fd3a5500b6.png)
![image](https://user-images.githubusercontent.com/45264423/226117014-6cd40bdb-1079-4e25-ba73-4fbeb58c9e69.png)

**Comment by StarsTesla** [comment]
And also for pure http visit shows:
![image](https://user-images.githubusercontent.com/45264423/226117143-9686de5b-a175-4be3-a658-e58e5bf2a39a.png)

**Comment by cyhhhhhhit** [comment]
hey, i have encountered the same problem today, and it can work before.

**Comment by ZhenhuiL1n** [comment]
I encountered it just now, and it worked fine this afternoon. idk why

**Comment by tancik** [comment]
https://viewer.nerf.studio/ is down, looking into it

**Comment by tancik** [comment]
Should be back up now.

**Comment by StarsTesla** [comment]
Yes, the webpage is back, while I see nothing, even I retrained the model @tancik 

![image](https://user-images.githubusercontent.com/45264423/226147935-7c49e5d7-cb50-4978-a0cd-42282fc9a2b0.png)

**Comment by tancik** [comment]
Is this training on a local or remote server? If remote, do you have port 7007 forwarded? Have you tried refreshing the page?

**Comment by StarsTesla** [comment]
Thanks for that, seems termius is not fit for the port forward, I use the native windows terminal and ssh command line, now it works fine.
