### ISSUE TITLE
Orthographic camera for rendering?

### ISSUE THREAD

**Issue by vahidEtt** [nerfstudio-project/nerfstudio#1637]
I was wondering what's the easiest way to render with orthographic projection. Only changing camera intrinsics and extrinsic in camera_path.json is enough? or does it need some code modification too? thanks in advance!

**Comment by tancik** [comment]
It would require code modification. You would need to add a new camera model to https://github.com/nerfstudio-project/nerfstudio/blob/81e39cb276e4600100ef3115b2c41dee163d60f2/nerfstudio/cameras/cameras.py#L650-L681

**Comment by vahidEtt** [comment]
OK. Thanks for the tip.
