### ISSUE TITLE
failed to install tiny-cuda--nn on windows11

### ISSUE THREAD

**Issue by Jalim19** [nerfstudio-project/nerfstudio#1642]
**Describe the bug**
I had followed the all  instructions in github, but I still failed at the step of installing tiny-cuda-nn. While I started to run "pip install git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch"   sometimes powershell stuck and sometimes powershell stoped by giving the feedback "No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7' ". 

**Screenshots**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/55941263/226530958-84c8b80f-905a-42a1-81c3-cb4564985d8c.png">

**Additional context**
Please help me. I tried everything I could do to it but failed.

**Comment by rwijmashell** [comment]
You should set the TCNN_CUDA_ARCHITECTURES variable as stated in the error log. This is your GPUs compute capability without the "." (e.g. 7.0 -> 70)
