### ISSUE TITLE
ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by hameleon-ed** [nerfstudio-project/nerfstudio#1647]
**Describe the bug**
When I try to use Colab in the Start Training block, the error "ModuleNotFoundError: No module named 'torch._six'" happens.

`/content
Traceback (most recent call last):
  File "/usr/local/bin/ns-train", line 5, in <module>
    from scripts.train import entrypoint
  File "/usr/local/lib/python3.9/site-packages/scripts/train.py", line 49, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/usr/local/lib/python3.9/site-packages/nerfstudio/configs/method_configs.py", line 28, in <module>
    from nerfstudio.data.datamanagers.base_datamanager import VanillaDataManagerConfig
  File "/usr/local/lib/python3.9/site-packages/nerfstudio/data/datamanagers/base_datamanager.py", line 64, in <module>
    from nerfstudio.data.utils.dataloaders import (
  File "/usr/local/lib/python3.9/site-packages/nerfstudio/data/utils/dataloaders.py", line 34, in <module>
    from nerfstudio.data.utils.nerfstudio_collate import nerfstudio_collate
  File "/usr/local/lib/python3.9/site-packages/nerfstudio/data/utils/nerfstudio_collate.py", line 26, in <module>
    from torch._six import string_classes
ModuleNotFoundError: No module named 'torch._six'`

**To Reproduce**
1. In Colab, run all codes as it is,
2. Start Training block shows the error.

**Additional context**

Install Conda block shows
`WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

Install Nerfstudio and Dependencies block shows

`Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (23.0.1)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
functorch 2.0.0 requires torch<2.1,>=2.0, but you have torch 1.12.1+cu113 which is incompatible.
Successfully installed torch-1.12.1+cu113 torchvision-0.13.1+cu113
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

`ERROR: tinycudann-1.6-cp37-cp37m-linux_x86_64.whl is not a supported wheel on this platform.`

`Successfully installed torch-2.0.0 torchvision-0.15.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv`

**Comment by hu-po** [comment]
I was able to solve this issue by [looking at this other issue ](https://github.com/nerfstudio-project/nerfstudio/issues/1610)

**Comment by jkulhanek** [comment]
Addressed by this PR: #1713
