### ISSUE TITLE
raise ConstructorError("while constructing a Python object", mark, yaml.constructor.ConstructorError: while constructing a Python object

### ISSUE THREAD

**Issue by Relif-me** [nerfstudio-project/nerfstudio#1672]
**Describe the bug**
When I run the commend：

ns-render --load-config outputs/desolation/nerfacto/2023-03-28_201618/config.yml --traj filename --camera-path-filename desolation/camera_paths/2023-03-28_201618.json --output-path renders/desolation/2023-03-28_201618.mp4

I meet the error:

raise ConstructorError("while constructing a Python object", mark,
yaml.constructor.ConstructorError: while constructing a Python object
cannot find 'ExponentialDecaySchedule' in the module 'nerfstudio.engine.schedulers'
  in "<unicode string>", line 77, column 18:
            _target: !!python/name:nerfstudio.engine. ... 
                        ^
Is this a problem with my pyyaml package?
pyyaml version: 6.0

![image](https://user-images.githubusercontent.com/124853470/228248105-cde27a2b-14c1-4501-9774-a7059dbfb383.png)

**Comment by Relif-me** [comment]
> Did you train the model on a different version of nerfstudio?

Thanks for your reply！

I solved this problem by reinstalling pyyaml.
I did try to use different versions of nerfstudio for training and rendering the first time this issue came up.

**Comment by eeex-diouf** [comment]
> > Did you train the model on a different version of nerfstudio?
> 
> Thanks for your reply！
> 
> I solved this problem by reinstalling pyyaml. I did try to use different versions of nerfstudio for training and rendering the first time this issue came up.

which version of pyyaml will be fine.
Thanks,
