### ISSUE TITLE
A question about the num_level the proposal network

### ISSUE THREAD

**Issue by YZsZY** [nerfstudio-project/nerfstudio#1676]
Hello author, I note that in the docs you mentioned that using two different proposal networks to speed resample process can have a better result, I would like to ask if there is any quantitative analysis or comparison of the effect related to two resampling with only one proposal network, thanks a lot!

**Comment by tancik** [comment]
We have quality numbers for a single proposal network in the paper. Still images generally look good, but you seed banding artifacts from aliasing when the camera moves (thin objects disappear and reappear). There is a marginal speedup from using one prop network, but generally the prop networks is pretty quick relative to everything else.

<img width="899" alt="image" src="https://user-images.githubusercontent.com/3310961/229380147-ecc05d9a-d270-4bae-85f8-7f44c113ae8e.png">

**Comment by YZsZY** [comment]
> We have quality numbers for a single proposal network in the paper. Still images generally look good, but you seed banding artifacts from aliasing when the camera moves (thin objects disappear and reappear). There is a marginal speedup from using one prop network, but generally the prop networks is pretty quick relative to everything else.
> 
> <img alt="image" width="899" src="https://user-images.githubusercontent.com/3310961/229380147-ecc05d9a-d270-4bae-85f8-7f44c113ae8e.png">

Get that! Thanks a lot~
