### ISSUE TITLE
ns-train: error: unrecognized arguments

### ISSUE THREAD

**Issue by YueYin27** [nerfstudio-project/nerfstudio#1677]
I am able to successfully train a model when using commands like `ns-train nerfacto blender-data --data data\blender\lego`. However, when I added `--vis wandb`, it raised an error: `ns-train: error: unrecognized arguments: --vis wandb`.
![image](https://user-images.githubusercontent.com/75305926/229036346-e89ba1e0-e5bb-43b9-8188-fc397787f154.png)

I've also tried other additional arguments shown in the help message below, but whichever argument I added after `--data`, it raised the 'unrecognized arguments' error.
![3T5P6OV HCZ N{R6U1{RRUG](https://user-images.githubusercontent.com/75305926/229036007-c6e7972a-753e-4abc-90e7-6ebc2923220d.png)

I'm using Windows11, torch 1.13.1 with CUDA 11.7. Is there anyone else who also encountered this before?

**Comment by tancik** [comment]
Add `--vis wandb` before the `blender-data`

**Comment by YueYin27** [comment]
> Add `--vis wandb` before the `blender-data`

Thank you so much!!!
