### ISSUE TITLE
the result of render image is so strange, please help me explain this reasons. 

### ISSUE THREAD

**Issue by AIBUWAN** [nerfstudio-project/nerfstudio#1685]
I have some frames from KITTI. like this:

![frame_00001](https://user-images.githubusercontent.com/107452659/229345064-08094e4f-ab9f-4a54-98bd-5cda996f7887.png)

run `ns-train nerfacto xxxx`  and ` ns-render --load-config xxx`

There is no information around the image, only the center of the image has reconstruction information.

What can I do to solve this situation？

The result like this:

![00000](https://user-images.githubusercontent.com/107452659/229345265-9cf30cd6-1f72-422b-bf4f-b1b5bc420676.png)

**Comment by tancik** [comment]
Did any of the training data view the scene outside the center?

**Comment by AIBUWAN** [comment]
> Did any of the training data view the scene outside the center?

the camera pose like this. It's egocentric video capture

![2023-04-03 09-59-59 的屏幕截图](https://user-images.githubusercontent.com/107452659/229395086-1163fc43-080c-430f-9274-338fd427226e.png)

**Comment by tancik** [comment]
That result looks expected then. If the outside regions are never observed, it will just produce noise.
