### ISSUE TITLE
dataparser has wrong data path in config.yml

### ISSUE THREAD

**Issue by gilureta** [nerfstudio-project/nerfstudio#1700]
Hi,

nerfstudio version v0.1.19

I noticed that when training using the follow call
```
ns-train  nerfacto --data My/Custom/Data
```
the resulting config.yml has the wrong value for `pipeline.datamanager.dataparser.data`, it is set to the default "data/nerfstudio/poster" instead of "My/Custom/Data". 

Looking at all the data entries in the config.yml, the top-level `data` is correct and the `pipeline.datamanager.data` points to it, but the `pipeline.datamanager.dataparser.data` is wrong.
```yalm
data: &id002 !!python/object/apply:pathlib.PosixPath
- My
- Custom
- Data
pipeline:
   datamanager:
       data: *id002
       dataparser:
           data: !!python/object/apply:pathlib.PosixPath
           - data
           - nerfstudio
           - poster
```

The datamanager one is correct because the train.py script writes the datamanager.data before calling `save_config()`. But the datamanager sets the dataparser.data after the config is save (I didn't track down when this is call, but that would explain the error in the config.yml).

https://github.com/nerfstudio-project/nerfstudio/blob/835a0151f28d45424dbab6d0cf507d67cebf428b/scripts/train.py#L223
https://github.com/nerfstudio-project/nerfstudio/blob/835a0151f28d45424dbab6d0cf507d67cebf428b/scripts/train.py#L231
https://github.com/nerfstudio-project/nerfstudio/blob/835a0151f28d45424dbab6d0cf507d67cebf428b/nerfstudio/data/datamanagers/base_datamanager.py#L406

**Comment by tancik** [comment]
Since we are modifying the config on the fly in python (hacky... but allows us to allow users to skip adding `nerfstudio-data` to every command) this issue arrises. I've created a short PR that defaults the dataparser to use an empty path. This will at-least avoid having the weird `data/nerfstudio/poster` in the config.
