### ISSUE TITLE
Low training speed, with high CPU utilization, but low GPU utilization (defaultly train on CPU?)

### ISSUE THREAD

**Issue by w2690831985w** [nerfstudio-project/nerfstudio#1712]
**Describe the bug**

When I was training nerfacto, I got **low training speed, with high CPU utilization, but low GPU utilization**, and I guess the GPU is not working properly.
**CPU and GPU information**
CPU: Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
GPU: Nvidia RTX 2080 Ti

**Command:** CUDA_VISIBLE_DEVICES=1 ns-train nerfacto --data data/nerfstudio/floating-tree
**No other kwargs are changed.**

**training status:** (high Train Iter (time), low Train Rays / Sec)
![230760284-9e034af0-c292-4df0-b8a6-b74c17fb2140](https://user-images.githubusercontent.com/130275500/230761860-31a7a424-2d21-463b-82f8-05f07271a279.png)

**CPU status:** (high %CPU)
![230760459-3c4d5c9c-af08-4e23-8a9f-786eefd8fad9](https://user-images.githubusercontent.com/130275500/230761864-169ab3a8-c369-463b-9838-3d4c1370e4ef.png)

**GPU status:** (GPU1, low GPU-Util)
![230760592-acc5f91b-c2cc-48b8-9e09-60c2eca9954e](https://user-images.githubusercontent.com/130275500/230761872-534510ce-d3d7-4a50-8da9-f5562240264f.png)

and has **no trouble displaying**:
![image](https://user-images.githubusercontent.com/130275500/230760657-af28b6dd-a4ae-4610-b392-76871eba9f13.png)

After this I started training another nerfacto **simultaneously** using another two GPU and viewer.websocket-port. I got this

**Command:** CUDA_VISIBLE_DEVICES=4,5 ns-train nerfacto --data data/nerfstudio/bww_entrance --machine.num-gpus 2 --viewer.websocket-port 7018

**training status:** (high Train Iter (time), low Train Rays / Sec)
![230761038-250fee64-3255-4ba6-ab7d-a39972b6323e](https://user-images.githubusercontent.com/130275500/230761880-410ab783-888c-4bac-8464-9e25d0bd42a2.png)

**CPU status:** (high %CPU)
![230760993-f32b0810-002d-4d49-9e9b-0c61e54de1e8](https://user-images.githubusercontent.com/130275500/230761887-9bfff4ac-f7e1-42a5-b8cc-77b26c1bc782.png)

**GPU status:** (GPU1,4,5, low GPU-Util)
![230761495-6f4b8e97-958f-48e6-9c51-de1f2d681ee8](https://user-images.githubusercontent.com/130275500/230761892-93182363-9819-4d17-8faf-573a5be3c3ee.png)

When I train two nerfactos at the same time, they **shared the CPU usage**, so the one that **starts first got even slower**. And when I adjust the _Train util._ and _Max Res._ on the viewer, the GPU util. changes, but the training status (high Train Iter (time), low Train Rays / Sec) displayed in the terminal does not change. So I infer from this that the **training is carried out on the CPU**, and the GPU is only used for the rendering of the viewer during training. 

Has anyone seen such a problem? I want to train on the GPU, but the program may not call the GPU correctly, so how to make sure training is on the GPU to make it reach the normal speed?

**Or, dose it defaultly train on CPU, but not GPU?**

**Expected behavior**
Training run on the GPU.

**Comment by w2690831985w** [comment]
python -c "import torch; print(torch.cuda.is_available())"
It shows True

I modyfied anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/models/base_model.py
![image](https://user-images.githubusercontent.com/130275500/230856785-a88954f2-f082-4fca-81cd-263693a73a3f.png)
(add "print(...)")
it shows cuda:0 in terminal (CUDA_VISIBLE_DEVICES=1 ??? why cuda0 ???)

But is this (in sceenshots above) a normal speed on RTX 2080 Ti ?

**Comment by w2690831985w** [comment]
This is because inappropriate CPU allocation, and dataloading being inefficient.

**Comment by MHz777** [comment]
I have also encountered this problem. How did you solve it?

**Comment by gregogalante** [comment]
@w2690831985w how did you solve the issue?

**Comment by DEVECLOVER** [comment]
@w2690831985w  I ran into the same problem, how do you solve this problem?
@gregogalante  I changed the CPU threads to improve the training speed to some extent, the instructions are as follows:

>  OMP_NUM_THREADS=4 NUMEXPR_NUM_THREADS=4 MKL_NUM_THREADS=4 ns-train ……

**Comment by MHz777** [comment]
感谢您的回复，期待更加深入的交流

**Comment by w2690831985w** [comment]
The CPU usage of nerfstudio during training is very high, so allocate as much CPU resources to it as possible.
@DEVECLOVER @gregogalante @MHz777
