### ISSUE TITLE
When trying to train with depth supervision: "can't open/read file: check file path/integrity"

### ISSUE THREAD

**Issue by matyja256** [nerfstudio-project/nerfstudio#1725]
Hi, a wonderful project!
I want to train with depth supervision, so I provide a depth_file_path for each frame in `transforms.json`, like this:
![914f58d323dffcff02ea6be3ba19403](https://user-images.githubusercontent.com/81960409/231389660-c3ab6313-b950-4b8b-b952-ec30bdfb3f73.png)
My training set is like this:
![724c94d9f9c6213d7b0b11e7c08fa8a](https://user-images.githubusercontent.com/81960409/231389959-d445a50b-c883-4ea8-be6e-cb62da5217ef.png)
Then run the command, using the method depth-nerfacto:
`ns-train depth-nerfacto --data ./scan1`
But it came to an error:
![208051d2827cb977f9faaeec889cf59](https://user-images.githubusercontent.com/81960409/231392836-d8dd64be-b18b-4c11-8f4d-d742ead7190e.png)
It seems that the depth map file was not found. The path to depth maps I give in `transforms.json` is `depth_png/********.png`, but in the error message, it shows that it is looking for depth maps from the path `depths_2/********.png`. Why is this happening? Where is `depths_2` from? Could you give me some answers, please? 
Thanks a lot.

**Comment by HrsPythonix** [comment]
Because you are training with scale "2", which might be automatically set when your training image size is big, try specify the `--downscale-factor 1` after nerfstudio-data, or make downscaled training depth such as depth_png, depth_png_2, depth_png_4, depth_png_8

**Comment by matyja256** [comment]
That works.
Thank you for your help.

**Comment by Irving87** [comment]
> nscaled trainin

May I ask how to automatically add “depth_file_path” to transforms.json? Is there any scripts in nerfstudio? I can only find ns-process-data command in nerfstudio docs...
