### ISSUE TITLE
NeusFacto Custom Data Instructions

### ISSUE THREAD

**Issue by MvWouden** [nerfstudio-project/nerfstudio#1732]
**Is your feature request related to a problem? Please describe.**
Hi, I saw that NeusFacto got merged in the last day.
I tried running the model, but ended up with some issues in getting it to work on my data.
It seems it requires some pre-processing steps from sdfstudio, but I cannot find the proper documentation for this.

**Describe the solution you'd like**
A small piece of documentation or a (brief) explanation on how I can pre-process custom data to be used with the newly merged NeusFacto.

**Suggestion**
If provided with a (brief) explanation, I would be willing to document this process somewhere if that helps the project.

**Comment by pablovela5620** [comment]
Hi so you are correct, currently the SDF based models (NeuS and NeuS Facto) require some pre-processing for custom data to work (as of this point they will only work with the sdfstudio-demo-data download). I had written a script for this over at the SDFStudio that you can find [here](https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py). I plan on bringing this over and integrating it directly into ns-proccess-data (not totally clear as to how I'll do this yet). For now you're welcome to use the script over at the SDFstudio repo to get things preprocessed.

**Comment by pablovela5620** [comment]
You don't need to but it helps in some cases (especially for indoor scenes), what command did you use exactly and what did the dataset/output look like? Most of my testing has been with indoor room enviroments

**Comment by cian0** [comment]
Hi, how do I know what to put in pretrained_models and omnidata-path for that script? 

https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py

**Comment by MvWouden** [comment]
> Hi, how do I know what to put in pretrained_models and omnidata-path for that script?
> 
> https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py

I believe that is only required when you want to extract mono-prior depths and normals.
If that's not needed, you can simply do:
```shell
python3 scripts/datasets/process_nerfstudio_to_sdfstudio.py --data <path/to/data/dir> --output-dir <path/to/output/dir> --data-type <colmap/polycam> --scene-type <indoor/object/unbound>
```

**Comment by MvWouden** [comment]
@pablovela5620 I was able to train a Neusfacto model on custom data recently.
For this, I did not extract monocular depth and normal cues.
I did encounter some issues, which I'll highlight below.

## Issue 1

After using your conversion script, I encountered an error when training a Neusfacto model.
The error was triggered by the following lines:

```python
# file: nerfstudio > data > dataparsers > sdfstudio_dataparser.py

# lines 90-91
depth_filename = self.config.data / frame["mono_depth_path"]    # KeyError since key not present
normal_filename = self.config.data / frame["mono_normal_path"]  # KeyError since key not present
```

## Fix 1

Before:

```python
# file: nerfstudio > data > dataparsers > sdfstudio_dataparser.py

# lines 90-91
depth_filename = self.config.data / frame["mono_depth_path"]    # KeyError since key not present
normal_filename = self.config.data / frame["mono_normal_path"]  # KeyError since key not present 

# lines 98-99
depth_filenames.append(depth_filename)
normal_filenames.append(normal_filename)
```

After:

```python
# file: nerfstudio > data > dataparsers > sdfstudio_dataparser.py

# lines 90-91
depth_filename = self.config.data / frame.get("mono_depth_path", [])
normal_filename = self.config.data / frame.get("mono_normal_path", [])

# lines 98-99
depth_filenames.extend(depth_filename)
normal_filenames.extend(normal_filename)
```

Let me know if you think I should create a PR for this, I'd love to.

## Issue 2

The results are not what I would have expected, which I'll visualize here.
Perhaps you know what is going wrong here?

Neusfacto (GT left, render right):
![Neusfacto](https://github.com/nerfstudio-project/nerfstudio/assets/56082205/b3d28f10-4763-417d-9e38-6f525741a94f)

Nerfacto for comparison (GT left, render right):
![Nerfacto](https://github.com/nerfstudio-project/nerfstudio/assets/56082205/037f947c-93fb-435f-895e-ca33f0aec518)

**Comment by MvWouden** [comment]
Some other interesting thing I found with `Neus` is that the ETA is nearly twice as long with `--pipeline.datamanager.train-num-rays-per-batch 1024` as when I use `--pipeline.datamanager.train-num-rays-per-batch 512`, which seems odd to me.

**Comment by MvWouden** [comment]
Will close this issue since issues are mainly due to initialization and sensitivity to hyperparameters.
