### ISSUE TITLE
How to use nerfstudio to directly render the pose of the training set and export the video？

### ISSUE THREAD

**Issue by Bin-ze** [nerfstudio-project/nerfstudio#1733]
I want to use nerfstudio to render the images of the training set, but I found that the format of the transforms.json used for training is different from the format of the camera_path.json used for rendering. How can I convert them to each other to export the rendered video of the training set, or use The pose of the training set is smoothed

**Comment by XianSifan** [comment]
Hello, I also have this need, may I ask how to solve this problem

**Comment by RebekkaBaertheleTHWS** [comment]
Same here, did you find something useful @Bin-ze ?
