### ISSUE TITLE
Any plan to improve speed of image masks in Nerfacto ?

### ISSUE THREAD

**Issue by Tao-11-chen** [nerfstudio-project/nerfstudio#1747]
Hello, i noticed that the current implementation of masking is inefficient.
In my use case, the situation is even worse, it may take more than three days to train a Nerfacto.
Are there any plans to improve speed of image masks? 
If no, is there any suggestions for me to make it faster in addition to using more threads to load data batch?
(I have ample memory but a relatively weak CPU)
Here is the running time of my program before and after using masks:

w/o mask:
CacheDataloader._get_batch_list: 0.2384
Trainer.train_iteration: 0.0339
VanillaPipeline.get_train_loss_dict: 0.0209

w/ mask:
CacheDataloader._get_batch_list: 0.6013
Trainer.train_iteration: 0.6127
VanillaPipeline.get_train_loss_dict: 0.5986

**Comment by machenmusik** [comment]
Related to #1465 ?

**Comment by Tao-11-chen** [comment]
Make pixel_sampler with masks run in parallel can be a help, i'll create a PR later.

**Comment by Tao-11-chen** [comment]
Solved in new version.
