### ISSUE TITLE
Address Dependabot security warnings

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#1773]
It appears Dependabot has flagged some packages as requiring security updates.

**Comment by tancik** [comment]
I fixed the easy ones. If you know how to fix any of the remaining ones, please go for it

**Comment by machenmusik** [comment]
Thanks.  Looks like they are all stuck on react-scripts 5.0.1 - not sure if there is newer that can be used

**Comment by machenmusik** [comment]
#1799 fixes them for machenmusik/nerfstudio - but could use more testing.
