### ISSUE TITLE
Thinking about how to improve the performance of instruct-NeRF2NeRF?

### ISSUE THREAD

**Issue by ZixunHuang1997** [nerfstudio-project/nerfstudio#1777]
I tried instruct-NeRF2NeRF, and tried to convert a Lego panda into this week. 
Here is my initial trained NeRF and prompt I used.
<img width="1440" alt="Screenshot 2023-04-17 at 2 59 57 PM" src="https://user-images.githubusercontent.com/106426767/233172954-e4fc0c17-97fb-4a08-a9ac-f85cc1fbf0f0.png">

`ns-train in2n-tiny --data {PROCESSED_DATA_DIR} --load-dir {outputs/.../nerfstudio_models} --pipeline.prompt {"turn the Lego panda into a grizzly bear"} --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 1.5`

Here is the GPU I used:
<img width="564" alt="Screenshot 2023-04-19 at 12 05 23 PM" src="https://user-images.githubusercontent.com/106426767/233175301-2f7b5ccd-f584-4bf0-aabb-68ce1eabe484.png">

And here is the result NeRF I got:
<img width="1440" alt="Screenshot 2023-04-19 at 11 25 23 AM" src="https://user-images.githubusercontent.com/106426767/233173034-d8c602b3-e4a6-4f1d-87bd-fbb3a0877e27.png">

As you can see in the above image, Instruct-NeRF2NeRF not only convert the Lego panda into a grizzly bear, but also convert the 
aruco markers into "grizzly markers".

Shall we have a texture-less background when using this tool to do re-texturing?

**Comment by ayaanzhaque** [comment]
Cool result! InstructPix2Pix tends to edit more than just the single object you specify. You can try the edit in 2D and see if you can get a prompt that only edits the Lego Bear, but I also found this as a limitation while experimenting.

**Comment by AitoD** [comment]
One way how to improve this would be to implement image segmentation with grounded segment-anything.
Doing this, the edit could be applied to just the spesific parts of the image based on the prompt, with minimal loss in performance

**Comment by ayaanzhaque** [comment]
Ya we are thinking abt incorporating some sort of segmentation to improve the editing results! If you would like to implement something, go for it!
