### ISSUE TITLE
need help. how to combine script to blender ??

### ISSUE THREAD

**Issue by zuixiaosanlang** [nerfstudio-project/nerfstudio#1780]
![image](https://user-images.githubusercontent.com/20105627/233290374-69201ce8-1e8a-4c52-ad6b-ff9064d01163.png)

i install blender  and have downloaded the script,  
but i cannot find 'Nerfstudio add-ons',   
how to process the scipt， steps above say nothing.

my blender:
![image](https://user-images.githubusercontent.com/20105627/233293238-5f75286a-c58f-473e-b74c-ddfee6f94862.png)

**Comment by cvachha** [comment]
On the Blender Preferences Add-ons page, select the "Install..." button, then select the downloaded Nerfstudio add-on python script in the file view, and then click "Install Add-on". Then, it should show up on the Add-ons page.
