### ISSUE TITLE
Implementation of `urban_radiance_field_depth_loss` and `ds_nerf_depth_loss` are wrong?

### ISSUE THREAD

**Issue by nlml** [nerfstudio-project/nerfstudio#1793]
**Describe the bug**

At least in the way that I am using these loss terms, I am pretty sure there is a fundamental error in the way they are implemented.

In both of these depth loss functions, the general setup/aim is:
- We have a ground truth depth value for each ray (from the provided depth map)
- We look at the samples along each ray, and increase the weight values at samples whose depth is close to the ground truth depth
- (In `urban_radiance_field_depth_loss` case, we additionally reduce weight values at samples with depth < ground truth depth)

The **problem** for me with the current implementation is that I think we compare samples on ALL rays to ground truth depth values on ALL rays. This seems wrong: shouldn't we be comparing a ray's ground truth depth only to the samples on that ray?

**To Reproduce**

Here is a toy example illustrating the problem, with just one part of the `urban_radiance_field_depth_loss` function.

```python
import torch

sigma = 0.01
# imagine we have 3 samples for ray 1, then 4 samples for ray 2
steps = [0.9, 1.0, 1.1, 0.8, 0.9, 1.0, 1.1]
# our ground truth depth for our two rays
termination_depth = [1.0, 1.1]
# assume weights are all just 10.0
weights = [10.0] * len(steps)

# Get the shapes consistent with what happens in the code
steps, termination_depth, weights = [torch.FloatTensor(_).unsqueeze(-1) for _ in [steps, termination_depth, weights]]
termination_depth = termination_depth.unsqueeze(-1)

line_of_sight_loss_empty_mask = steps < termination_depth - sigma
print(f"line_of_sight_loss_empty_mask.shape = {line_of_sight_loss_empty_mask.shape}")
line_of_sight_loss_empty = (line_of_sight_loss_empty_mask * weights**2)
print(f"line_of_sight_loss_empty = {line_of_sight_loss_empty[:,:,0]}")
```

Output:
```
line_of_sight_loss_empty_mask.shape = torch.Size([2, 7, 1])
line_of_sight_loss_empty = tensor([[100.,   0.,   0., 100., 100.,   0.,   0.],
                                   [100., 100.,   0., 100., 100., 100.,   0.]])
```

When I run my code and `pdb.set_trace()` in the `urban_radiance_field_depth_loss` function, I can see that `steps` has shape `[num_samples, 1]`, `termination_depth` has shape `[num_rays, 1, 1]`, and `weights` has shape `[num_samples, 1]`.

Thus in the above toy example, I set up the `steps`, `termination_depth` and `weights` variables all to values that would be typical during training.

In this part of the loss function, the goal is to find samples with values less than the ground truth depth (minus sigma). So we have `steps < termination_depth - sigma`. Due to broadcasting, the shape of this ends up being `[2, 7, 1]`, or in general `[num_rays, num_samples, 1]`. This means we are doing the comparison for all rays, against all samples, which doesn't make any sense. We should be comparing the depth value for each ray against only the samples for that ray.

This leads to an incorrect loss being computed. The loss (before averaging) we saw printed above was:

```
line_of_sight_loss_empty = tensor([[100.,   0.,   0., 100., 100.,   0.,   0.],
                                   [100., 100.,   0., 100., 100., 100.,   0.]])
```

But our sampling points were:
`steps = [0.9, 1.0, 1.1, 0.8, 0.9, 1.0, 1.1]`

That is:
`ray_0_steps = [0.9, 1.0, 1.1]`
`ray_1_steps = [0.8, 0.9, 1.0, 1.1]`

And our ground truth depth for the two rays were `1.0` and `1.1`:

In a correct implementation, the loss should (or could) be:

```
line_of_sight_loss_empty = tensor([[100.,   0.,   0.,  nan,  nan,  nan, nan], 
                                   [ nan,  nan,  nan, 100., 100., 100.,  0.]])
```

This way, we are pushing down the weights on the correct samples (those that are < gt_depth - sigma for each ray).

I put the `nan`'s here to illustrate the fact that we should not be comparing samples from ray 0 to the depth from ray 1, and vice-versa. In reality these would be 0's.

_**Note: while the toy example above is just for the `line_of_sight_loss_empty` component of `urban_radiance_field_depth_loss`, the same concept/issue applies to the `line_of_sight_loss_near` component, AND to `ds_nerf_depth_loss`.**_

**Am I missing something**

This seems like a pretty big oversight. Is it possible that the problem is that I am using packed samples and that's not supported properly here?

**Solution**

If we pass in `ray_indices`, then we can use some indexing to compare the correct depth values with each sample value and corresponding weight value. I implemented this and in my case it led to a 3x speedup (plus it probably uses a lot less memory). Interestingly despite these issues the original URF loss still seems to achieve its aims for me (perhaps because all the incorrect loss terms just create noise and cancel each other out), but my 'fixed' version also seems to work just as well or better (plus it's faster). Happy to submit a PR with this version, just thought I would explain the issue first to check I haven't made some mistakes of my own here.

**Comment by YZsZY** [comment]
I have encountered this problem before, urbanNeRF implementation is definitely problematic, because an ideal normal distribution is actually an integral sum equal to 1, and then the weight distribution of NeRF is a weighted sum equal to 1, the former is ∑(weight*delta)=1,the latter is ∑(weight)=1, which makes a big difference in scale between the two. 

So you can try to normalize the weighted sum of the ideal normal distribution (weight/=sum(weight)), or make the weight distribution of NeRF into an integral sum equal to 1 (weight=weight/delta)

**Comment by YZsZY** [comment]
I think as long as the ideal normal distribution is used to constrain the weight distribution, you need to solve this scale problem caused by the integral sum and the weighted sum, otherwise it is all wrong to use

**Comment by nlml** [comment]
I think you're right that there may also be some problems with the way that the distribution is computed and used in URF.

However, the problem that I am talking about is completely independent of this. It appears the code is comparing depth values and weight values across all combinations of rays, when it should only compare the ground truth depth to samples from the ray corresponding to that depth value.

An extreme example: if we have two rays, one from a camera angle that is extremely close to an object (so the depth value is say 0.1), and another ray from an angle very far from an object (with depth value e.g. 5.0). Then the loss in it's current form is going to push most of the weights for the first ray towards 0, even though for that ray, the object is very close and thus very early weights in the ray should have nonzero values.

Moreover, it's going to encourage the second ray (whose weights should all be 0 until depth >= 5.0) to have a very big weight at depth=0.1, which is wrong.

**Comment by YZsZY** [comment]
I got what you mean, you mentioned that the weight of the first near light will interfere with the weight of the light emitted from a distance, but actually NeRF learns weights based on points in space, not points along a ray.

Although the distance of the surface along the light differs from one viewpoint to another, the corresponding spatial position in the world coordinate system is the same

**Comment by Ilyabasharov** [comment]
@nlml could you please describe in details what is the problem in DS-NeRF implementation? when we compute
```python3
import torch
from torchtyping import TensorType
steps: TensorType["num_rays", "num_samples", 1] = torch.rand(100, 50, 1)
termination_depth: TensorType["num_rays", 1] = torch.rand(100, 1)
difference: TensorType["num_rays", "num_samples", 1] = steps - termination_depth[:, None]
````

so we compute for `difference` between steps and depth for each ray for independently. Do you think it is not correct ?

**Comment by tancik** [comment]
Looping in @mpmisko as he implemented these functions.

**Comment by nlml** [comment]
@Ilyabasharov yes the example you provided is fine.

I think maybe the problem is when you are using packed samples, like I am.

Using my dataset, I added a break point in the `ds_nerf` function as follows:

```python
def ds_nerf_depth_loss(
    weights: TensorType[..., "num_samples", 1],
    termination_depth: TensorType[..., 1],
    steps: TensorType[..., "num_samples", 1],
    lengths: TensorType[..., "num_samples", 1],
    sigma: TensorType[0],
) -> TensorType[..., 1]:
    """Depth loss from Depth-supervised NeRF (Deng et al., 2022).

    Args:
        weights: Weights predicted for each sample.
        termination_depth: Ground truth depth of rays.
        steps: Sampling distances along rays.
        lengths: Distances between steps.
        sigma: Uncertainty around depth values.
    Returns:
        Depth loss scalar.
    """
    depth_mask = termination_depth > 0

    loss = -torch.log(weights + EPS) * torch.exp(-((steps - termination_depth[:, None]) ** 2) / (2 * sigma)) * lengths
    loss = loss.sum(-2) * depth_mask
    import pdb
    pdb.set_trace()
    return torch.mean(loss)
```
And here are some outputs:

```python
(Pdb) weights.shape
torch.Size([552117, 1])
(Pdb) termination_depth.shape
torch.Size([256, 1])
(Pdb) steps.shape
torch.Size([552117, 1])
(Pdb) lengths.shape
torch.Size([552117, 1])
(Pdb) sigma.shape
torch.Size([1])
(Pdb) (steps - termination_depth[:, None]).shape
torch.Size([256, 552117, 1])
(Pdb) 552117/256
2156.70703125
```

So you can see my `steps.shape` is not `["num_rays", "num_samples", 1]` but rather `[sumOverRays_i("num_rays"_i * "num_samples"_i), 1]`

Each ray has a different number of samples, so the current implementation can't work in this case I don't think.

So I guess the problem is that I am using packed samples?

**Comment by mpmisko** [comment]
If the shapes you pass into the function do not match the shapes in the type spec, the code won't work as intended. For weights you need a 'num_samples' dimension since that's what we compare the depth with for each ray.

That being said, the way the code is currently written is also not correct with respect to the type spec. We should ideally write termination_depth[..., None, :] when we add the 'num_samples' dim. However, it will work as long as there is only one batch dim. This will not fix your problem but it's probably worth refactoring the code a bit.

**Comment by Ilyabasharov** [comment]
@mpmisko I have also 2 questions about current implementation of Depth losses.
1) [URF](https://urban-radiance-fields.github.io/images/go_urf.pdf) loss consider using 3 components of sight loss - empty, near and dist  [see eq. 15], but you implement only empty and near. So for me it seems like adding:
```python3
def urban_radiance_field_depth_loss(
    weights: TensorType[..., "num_samples", 1],
    termination_depth: TensorType[..., 1],
    predicted_depth: TensorType[..., 1],
    steps: TensorType[..., "num_samples", 1],
    sigma: TensorType[0],
) -> TensorType[..., 1]:
    """Lidar losses from Urban Radiance Fields (Rematas et al., 2022).

    Args:
        weights: Weights predicted for each sample.
        termination_depth: Ground truth depth of rays.
        predicted_depth: Depth prediction from the network.
        steps: Sampling distances along rays.
        sigma: Uncertainty around depth values.
    Returns:
        Depth loss scalar.
    """
    depth_mask = termination_depth > 0
    
    # Expected depth loss
    expected_depth_loss = (termination_depth - predicted_depth) ** 2
    
    # Line of sight losses
    target_distribution = torch.distributions.normal.Normal(0.0, sigma / URF_SIGMA_SCALE_FACTOR)
    termination_depth = termination_depth[:, None]
    
    # near mask
    line_of_sight_loss_near_mask = torch.logical_and(
        steps <= termination_depth + sigma, steps >= termination_depth - sigma
    )
    line_of_sight_loss_near = (weights - torch.exp(target_distribution.log_prob(steps - termination_depth))) ** 2
    line_of_sight_loss_near = (line_of_sight_loss_near_mask * line_of_sight_loss_near).sum(-2)
    
    # empty + dist mask
    line_of_sight_loss_empty_dist_mask = torch.logical_or(
        steps < termination_depth - sigma, steps > termination_depth + sigma
    )
    line_of_sight_loss_empty_dist = (line_of_sight_loss_empty_dist_mask * weights**2).sum(-2)
    line_of_sight_loss = line_of_sight_loss_near + line_of_sight_loss_empty_dist
    
    loss = (expected_depth_loss + line_of_sight_loss) * depth_mask
    return torch.mean(loss)
```

2) In real training depth losses are very noisy and I think where is the mistake. Also URF loss completely diverges. My first idea that scaling real depth (in meters) to nerf space is not totally correct. Now we just multiply meters to `self._dataparser_outputs.dataparser_scale` [here](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/data/datasets/depth_dataset.py#L49) (poses scaler) and if `is_euclidean = False` we also multiply to direction norm [here](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/model_components/losses.py#L302). Finally it looks like that
```python3
termination_depth *= directions_norm * _dataparser_outputs.dataparser_scale
```
This is not what nerf learns. So I think to trainable scaling params like in [NoPe NeRF](https://arxiv.org/pdf/2212.07388.pdf) [see eq. 4] to make it more robust. What do you think?

**Comment by YZsZY** [comment]
> @mpmisko I have also 2 questions about current implementation of Depth losses.
> 
> 1. [URF](https://urban-radiance-fields.github.io/images/go_urf.pdf) loss consider using 3 components of sight loss - empty, near and dist  [see eq. 15], but you implement only empty and near. So for me it seems like adding:
> 
> ```python
> def urban_radiance_field_depth_loss(
>     weights: TensorType[..., "num_samples", 1],
>     termination_depth: TensorType[..., 1],
>     predicted_depth: TensorType[..., 1],
>     steps: TensorType[..., "num_samples", 1],
>     sigma: TensorType[0],
> ) -> TensorType[..., 1]:
>     """Lidar losses from Urban Radiance Fields (Rematas et al., 2022).
> 
>     Args:
>         weights: Weights predicted for each sample.
>         termination_depth: Ground truth depth of rays.
>         predicted_depth: Depth prediction from the network.
>         steps: Sampling distances along rays.
>         sigma: Uncertainty around depth values.
>     Returns:
>         Depth loss scalar.
>     """
>     depth_mask = termination_depth > 0
>     
>     # Expected depth loss
>     expected_depth_loss = (termination_depth - predicted_depth) ** 2
>     
>     # Line of sight losses
>     target_distribution = torch.distributions.normal.Normal(0.0, sigma / URF_SIGMA_SCALE_FACTOR)
>     termination_depth = termination_depth[:, None]
>     
>     # near mask
>     line_of_sight_loss_near_mask = torch.logical_and(
>         steps <= termination_depth + sigma, steps >= termination_depth - sigma
>     )
>     line_of_sight_loss_near = (weights - torch.exp(target_distribution.log_prob(steps - termination_depth))) ** 2
>     line_of_sight_loss_near = (line_of_sight_loss_near_mask * line_of_sight_loss_near).sum(-2)
>     
>     # empty + dist mask !!!!
>     line_of_sight_loss_empty_dist_mask = torch.logical_or(
>         steps < termination_depth - sigma, steps > termination_depth + sigma
>     )
>     line_of_sight_loss_empty_dist = (line_of_sight_loss_empty_dist_mask * weights**2).sum(-2)
>     line_of_sight_loss = line_of_sight_loss_near + line_of_sight_loss_empty_dist
>     
>     loss = (expected_depth_loss + line_of_sight_loss) * depth_mask
>     return torch.mean(loss)
> ```
> 
> 2. In real training depth losses are very noisy and I think where is the mistake. Also URF loss completely diverges. My first idea that scaling real depth (in meters) to nerf space is not totally correct. Now we just multiply meters to `self._dataparser_outputs.dataparser_scale` [here](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/data/datasets/depth_dataset.py#L49) (poses scaler) and if `is_euclidean = False` we also multiply to direction norm [here](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/model_components/losses.py#L302). Finally it looks like that
> 
> ```python
> termination_depth *= directions_norm * _dataparser_outputs.dataparser_scale
> ```
> 
> This is not what nerf learns. So I think to trainable scaling params like in [NoPe NeRF](https://arxiv.org/pdf/2212.07388.pdf) [see eq. 4] to make it more robust. What do you think?

I have tried the first proposal, in fact, adding or not adding far loss has little effect on the final result

**Comment by Ilyabasharov** [comment]
@YZsZY okay, what about scaling? Is your loss also noisy as mine?

**Comment by YZsZY** [comment]
Here is a comparison of my before and after results using UrbanRF depth supervision
![image](https://user-images.githubusercontent.com/117158282/233779080-a3c9e759-980f-4790-8693-3f285b8aa8a8.png)
![image](https://user-images.githubusercontent.com/117158282/233779093-1d6d377c-9529-4339-b668-2e4690614ea3.png)
You can see that only RGB supervision learns the wrong geometry for details such as the road surface, but adding deep supervision generates the correct geometry
![image](https://user-images.githubusercontent.com/117158282/233779066-89515918-321b-410d-8b18-01f4a1a79ae4.png)
![image](https://user-images.githubusercontent.com/117158282/233779106-946499b2-f365-418b-ace8-f2fd859e3491.png)

**Comment by Ilyabasharov** [comment]
@YZsZY Looks cool! How do you scale the depth in real meters to nerf space? Does your loss converge well?

**Comment by YZsZY** [comment]
> @YZsZY okay, what about scaling? Is your loss also noisy as mine? I use depth in real meters
Depth supervision I tried down to achieve good results need to make your sampling points as dense as possible, so as to generate a better ideal normal distribution to constrain, generally want to achieve dense sampling a way to increase the sampling points, another way is to reduce the size of your whole scene, so that you can focus more on the near field sampling (if the scene is too large, piece-wise sampling although still in the near field to pick more, but relatively speaking is not so dense)

You can visualize your sampling along the rays and the ideal depth distribution, you will see that if you have a large scale, the sampling is not very dense in the close view, when you scale down, the sampling will be more dense, here is a code you can test：
```python:
import math
weights = rays_info["weights"][0].detach().cpu().numpy()
tdist = rays_info["tdist"][0].detach().cpu().numpy()
tdist = 0.5 * (tdist[:-1] + tdist[1:])
        
depth_mean=depth_mask_gt[:, 0][0].detach().cpu().numpy()
y=(1. / math.sqrt(2 * np.pi*0.1) * np.exp(-0.5 * (tdist-depth_mean)**2)/0.1) # this is the ideal distribution
        
from matplotlib import pyplot as plt
plt.plot(tdist, weights, "c-", label="weight")
plt.plot(tdist, y, "b-", label="weight")
plt.show()

**Comment by Ilyabasharov** [comment]
To summarise, you suggested to:
- increase number of sampled points
- sample more points near the truth depth
- use near field sampling to make the distribution more dense

Did I understand correctly what you meant?

**Comment by YZsZY** [comment]
> To summarise, you suggested to:
> 
> * increase number of sampled points
> * sample more points near the truth depth
> * use near field sampling to make the distribution more dense
> 
> Did I understand correctly what you meant?
In fact, only adjusting the scale can make the distribution more concentrated

Another important thing you should be aware of is that when you're supervising Weight with the ideal depth distribution, you better make a visualization of the ideal distribution you're using and the Weight distribution to make sure they're on the same scale, which is important!

Also set a weight for near_loss,empty_loss can also improve the quality, for example, I use 0.1

**Comment by Ilyabasharov** [comment]
@YZsZY So, you said that you use [auto_scale_poses](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L234) + additional [scale_factor](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L235), which less than one. Right?

I just want to understand pipeline how should i adjust scale_factor to make well aligned ground-truth depth distribution with predicted weights distributuion

**Comment by YZsZY** [comment]
> @YZsZY So, you said that you use [auto_scale_poses](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L234) + additional [scale_factor](https://github.com/nerfstudio-project/nerfstudio/blob/11eea11f1e482f706e65192f3de32dc7f4097f73/nerfstudio/data/dataparsers/nerfstudio_dataparser.py#L235), which less than one. Right?
> 
> I just want to understand pipeline how should i adjust scale_factor to make well aligned ground-truth depth distribution with predicted weights distributuion

If you have a sparse point cloud, then use the distance between the farthest point and the center point cloud as scale_factor, if only pose, then use the distance between the farthest pose and the center pose, and then set the scale of the peripheral bbox to 15, finally try down the effect is not bad

**Comment by Ilyabasharov** [comment]
Thank you very much!

**Comment by YZsZY** [comment]
> I have encountered this problem before, urbanNeRF implementation is definitely problematic, because an ideal normal distribution is actually an integral sum equal to 1, and then the weight distribution of NeRF is a weighted sum equal to 1, the former is ∑(weight*delta)=1,the latter is ∑(weight)=1, which makes a big difference in scale between the two.
> 
> So you can try to normalize the weighted sum of the ideal normal distribution (weight/=sum(weight)), or make the weight distribution of NeRF into an integral sum equal to 1 (weight=weight/delta)

@Ilyabasharov And notice this problem like I just mentioned, you would better visualize the weight and the ideal distribution you used befo add the depth supervision~

**Comment by nlml** [comment]
@mpmisko should I close this issue then?

Regarding refactoring, it might be a good idea to at least throw a warning or error (if possible) when trying to use packed samples with depth supervision.

If you're interested, here is my current implementation of URF with support for packed samples. It's a bit messy, but if you want I can try and do a PR implementing something like this (maybe as a fallback if packed samples are provided?).

```python
def liam_depth_loss(
    termination_depth: TensorType[..., 1],
    ray_indices: TensorType["num_samples"],
    ray_samples: RaySamples,
    weights: TensorType["num_samples", 1],
    sigma: TensorType[0],
    target_weight_distrubition_scaler: float,
    sigma_scale_factor: float,
    line_of_sight_empty_mult: float,
):
    ray_ids_that_have_depth = torch.where(termination_depth[:, 0] > 0)[0]
    keep_rays = torch.where(torch.isin(ray_indices, ray_ids_that_have_depth))[0]
    if keep_rays.shape[0] == 0:
        return torch.FloatTensor([0.0]).mean()

    ray_samples_with_depth = ray_samples[keep_rays]
    ray_indices_with_depth = ray_indices[keep_rays]
    weights_with_depth = weights[keep_rays]

    steps_with_depth = (ray_samples_with_depth.frustums.starts + ray_samples_with_depth.frustums.ends) / 2
    valid_term_depth = termination_depth[ray_indices_with_depth]

    # Line of sight losses
    target_distribution = torch.distributions.normal.Normal(0.0, sigma / sigma_scale_factor)
    line_of_sight_loss_near_mask = torch.logical_and(
        steps_with_depth <= valid_term_depth + sigma, steps_with_depth >= valid_term_depth - sigma
    )
    line_of_sight_loss_near_sel = torch.where(line_of_sight_loss_near_mask[:, 0])[0]

    line_of_sight_loss_near = torch.square(
        weights_with_depth[line_of_sight_loss_near_sel]
        - target_weight_distrubition_scaler  # the value of the exp() here can be ~12000 --> too large?
        * torch.exp(
            target_distribution.log_prob(
                steps_with_depth[line_of_sight_loss_near_sel] - valid_term_depth[line_of_sight_loss_near_sel]
            )
        )
    ).mean()

    # here use ray frustum ends instead of average of [starts,ends]
    line_of_sight_loss_empty_mask = ray_samples_with_depth.frustums.ends < valid_term_depth - sigma
    line_of_sight_loss_empty_sel = torch.where(line_of_sight_loss_empty_mask[:, 0])[0]
    line_of_sight_loss_empty = line_of_sight_empty_mult * (weights[line_of_sight_loss_empty_sel] ** 2)
    line_of_sight_loss_near_mean, line_of_sight_loss_empty_mean = (
        line_of_sight_loss_near.mean(),
        line_of_sight_loss_empty.mean(),
    )
    line_of_sight_loss = line_of_sight_loss_near_mean + line_of_sight_loss_empty_mean

    return torch.mean(line_of_sight_loss)
```

**Comment by Ilyabasharov** [comment]
Yeah, I agree with @nlml to throw an error when input shapes are not correct. But further depth loss works correctly [with small memory and time overhead] and I think it is not needed to realize patch-based version.

I want to make my two suggestions.
1) Count $L_{dist}$ for [URF](https://urban-radiance-fields.github.io/images/go_urf.pdf) loss [See eq. 15].
```python3
line_of_sight_loss_empty_dist_mask = torch.logical_or(
    steps < termination_depth - sigma, steps > termination_depth + sigma
)
```
2) Now we use sigma in meters (see [here](https://github.com/nerfstudio-project/nerfstudio/blob/c256dc2bf95e2ef8d2dcc13403c551700e031df4/nerfstudio/models/depth_nerfacto.py#L42)) but our termination depth not in meters.
```python3
# full depth scale pipeline
termination_depth *= directions_norm * _dataparser_outputs.dataparser_scale
```
I think we should scale sigma in the same way as termination_depth.

**Comment by nlml** [comment]
In my case I have varying numbers of samples per ray, so reshaping isn't possible I don't think.

Looking at equation 18, shouldn't your line above be:

```python
line_of_sight_loss_empty_dist_mask = steps_with_depth > valid_term_depth + sigma
```

In my case though, I think such a term would make things worse. It implicitly assumes the object in front of the ray is always relatively thin and doesn't have anything behind it?
