### ISSUE TITLE
ns-train Lego in nerf_synthetic  and ns-rander, but output is error, but instant-gnp is right

### ISSUE THREAD

**Issue by annci62** [nerfstudio-project/nerfstudio#1806]
**Describe the bug**
ns-train Lego in nerf_synthetic  and ns-rander, but output is error, but training Lego using instant-gnp and output is right

**To Reproduce**
1. rename ./data/nerf_synthetic/Lego/transforms_train.json to transforms.json;
2. /home/arcvideo/.local/bin/ns-train volinga instant-ngp-data --data ./data/nerf_synthetic/lego/
3. /home/arcvideo/.local/bin/ns-render --load-config ./output/unamed/volinga-2023-04-24_145312/config.yml --output-format video --camera-path-filename ./base_cam.json --output-path ./1.mp4
5. output is 
![image](https://user-images.githubusercontent.com/22721741/233946343-1fa1d91c-5bc1-45bb-a82c-052a26a643ec.png)

intant-gnp output is 
![image](https://user-images.githubusercontent.com/22721741/233946655-efb7b558-efd9-40fe-866b-cf6f024ce48e.png)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tancik** [comment]
https://github.com/nerfstudio-project/nerfstudio/issues/806#issuecomment-1284327844

**Comment by annci62** [comment]
thanks!
