### ISSUE TITLE
Export point cloud error with large data: "only one live display may be active at once"

### ISSUE THREAD

**Issue by HungNgoCT** [nerfstudio-project/nerfstudio#1807]
Hi all, @tancik ,

I got error "Only one live display may be active at once" when exported point cloud with large input images.

Reproduce:

I captured a set of large images of a tree with greater than 2000 images

Train: ns-train nerfacto --data <path to json file>, trained and created a rendering video very will.

Then, exited train, web-based rendering then exported data
However, I could not received exported point cloud due to error: "Only one live display may be active at once" when I used command: 

ns-export pointcloud --load-config <config.yml> --output-dir exports/pcd/ --num-points 1000000 --remove-outliers True --estimate-normals False --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1
![image](https://user-images.githubusercontent.com/110378166/234207932-c10b4157-b87f-4c27-9eb3-f66a419b220e.png)

If I used a smaller data images, less than 500 images (this set can load all into RTX 3090), for another tree, it can export point cloud.

Appreciate anybody help me with this.

This is link of data together with json file which I run ns-process-data:
https://drive.google.com/file/d/1RcSGMO-DrUFWDSix00rCMukK9jDb70kt/view?usp=sharing

**Comment by msours** [comment]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/15207127/f18d6d5a-79d5-4a80-b12b-443f21c97246)
I'm running into the same thing as well. Exporting a point cloud with more than ~1000 images and I get this error.

**Comment by msours** [comment]
@HungNgoCT did you find a way around this?

**Comment by HungNgoCT** [comment]
> @HungNgoCT did you find a way around this?

Hi @msours,

Not yet. I just down sampled images to load all the data. So in general, I don't know how to solve this.

**Comment by msours** [comment]
@HungNgoCT, this fixed it for me:
https://github.com/nerfstudio-project/nerfstudio/issues/1913

**Comment by HungNgoCT** [comment]
Thank you @msours 
It worked for me also by following your share.
