### ISSUE TITLE
Indexing error when using custom data

### ISSUE THREAD

**Issue by MvWouden** [nerfstudio-project/nerfstudio#1808]
I would first like to thank the entire team for their amazing efforts and support on this project! ❤️ 

**Describe the bug**
I am trying to use a custom dataset with a `transforms.json` which follows the [Data Conventions](https://docs.nerf.studio/en/latest/quickstart/data_conventions.html#dataset-format), and is inspired by [colmap_to_json](https://github.com/nerfstudio-project/nerfstudio/blob/c256dc2bf95e2ef8d2dcc13403c551700e031df4/nerfstudio/process_data/colmap_utils.py#L388).

When trying to use this data, the data is loaded in (`Nerfstudio` data parser succeeds), but ultimately, I keep triggering the same error when training starts (even with different flags):
```
Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
```

The command run (example):
```shell
ns-train nerfacto --data <path/to/data> --vis tensorboard --experiment_name <experiment_name> --timestamp <timestamp_name> --viewer.quit-on-train-completion True
```

I've trained models before with datasets from `ns-process-data` without issues, so the issue seems to be specific to (my) custom datasets.

**To Reproduce**
Given that the issue seems to be specific to (my) custom datasets:
- The issue may lie in my `transforms.json`, hence I've provided the file (under  'Additional context'). It seems to fully follow the data convention fully, so that's odd.
- The issue may also lie in the folder structure I've used for my dataset, hence I've provided a description of my directory tree, and the full directory output (under  'Additional context'). I could not find any info on the required directory structure for custom data, so I've kept it as close as possible to `ns-process-data` output.
- The issue may also lie in the fact that I've not used any (custom/other) flags than I'd normally use with data from `ns-process-data`, hence I've provided the command used and the full output and trace (under 'Additional context'). Again I couldn't find any documentation stating that I have to use other flags than usual.

If necessary, I would be willing to provide my custom dataset for testing purposes. So let me know! 

**Expected behavior**
The training should work as usual, without throwing errors.

**Additional context**

- The `transforms.json` which fails (renamed to `.txt` since github doesn't allow uploading jsons): [transforms.txt](https://github.com/nerfstudio-project/nerfstudio/files/11310765/transforms.txt)
- The full command, output and trace can be found here: [trace_custom_data_nerfstudio.txt](https://github.com/nerfstudio-project/nerfstudio/files/11310712/trace_custom_data_nerfstudio.txt)
- The full directory tree of the dataset folder: [folder_structure.txt](https://github.com/nerfstudio-project/nerfstudio/files/11310836/folder_structure.txt)
- I've also tried running with `--pipeline.datamanager.camera-optimizer.mode off`, but that simply relocated the error to a different place.

I've kept the folder structure as close as possible to a dataset created with `ns-process-data`:
- `<folder root>/`
  - `images/` - original images
    - `frame_00001.jpeg`
    - `...`
    - `frame_00181.jpeg`
  - `images_2/` - images downscaled by factor of 2
    - `frame_00001.jpeg`
    - `...`
    - `frame_00181.jpeg`
  - `images_4/` - images downscaled by factor of 4
    - `frame_00001.jpeg`
    - `...`
    - `frame_00181.jpeg`
  - `images_8/` - images downscaled by factor of 8
    - `frame_00001.jpeg`
    - `...`
    - `frame_00181.jpeg`
  - `transforms.json`

<html><body>

What | Value
-- | --
Platform | Windows
Nerfstudio version | Latest Source (24th of April 2023)
Python version | 3.10.5
CUDA version | 11.7
PyTorch version | 1.13.1+cu117

</body>
</html>

**Comment**
If it ends up being a universal issue, rather than a 'me' issue, I would be very much open to submitting a PR if I'm guided in what I can  fix.

**Comment by jkulhanek** [comment]
Could it be that the sizes of the downsampled images are rounded in a different way than what nerfstudio expects? Could you post the image sizes for each downscaled version?

**Comment by jkulhanek** [comment]
At least this was the case for me with the mipnerf360 dataset

**Comment by MvWouden** [comment]
Issue was a 'me' issue as expected, and I've managed to find it.
If others run into similar issues, please check the width and height in `transforms.json` and your (resized) image resolutions to see that it matches.
Easy to overlook a flipped width and height.
