### ISSUE TITLE
TSDF mesh camera poses

### ISSUE THREAD

**Issue by nepfaff** [nerfstudio-project/nerfstudio#1820]
Hi, I noticed that only the views in the training dataset are used to render the RGB and depth images for TSDF fusion. Hence, we solely use NeRF as a depth predictor when extracting a mesh.
Apart from potential memory problems, is there a reason that no novel views are used for TSDF fusion? If both RGB and depth predictions are good, I would expect the mesh quality to be better with additional views. Especially, when there are gaps in the input images.

**Comment by tancik** [comment]
The primary reason is that it is difficult to reliably sample novel views that don't intersect with the nerf.

**Comment by nepfaff** [comment]
That makes sense. Thanks!

So we would expect improved results if it were possible to reliably sample novel views (e.g. by having an object of interest bounding box and doing masked training)?

**Comment by tancik** [comment]
Probably... I've never tried, so not sure.

**Comment by nepfaff** [comment]
okay, so time to try :)

Thanks for the answers!
