### ISSUE TITLE
The command to generate Poisson meshes is not visible in the GUI

### ISSUE THREAD

**Issue by salykovaa** [nerfstudio-project/nerfstudio#1831]
**Describe the bug**
The command to generate Poisson meshes is not visible in the GUI (see the screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/63703454/234820780-34e4a896-eaf5-4a98-92b0-dc1288e62f87.png)

**Additional context**
Latest version of nerfstudio, installed using `pip install -e .`

**Comment by ichsan2895** [comment]
I got same problem with `NeRFStudio` 0.2.1

![image](https://user-images.githubusercontent.com/60387342/235317687-87bb301d-6269-43cf-a2d9-11f843362666.png)

**Comment by ichsan2895** [comment]
I got same problem with `NeRFStudio` 0.2.1

![image](https://user-images.githubusercontent.com/60387342/235317722-f325553b-3854-43f5-b790-b7cb768bfab0.png)

**Comment by MvWouden** [comment]
Did you train the model with the flag `--pieline.model.predict-normals True`?

**Comment by salykovaa** [comment]
@MvWouden yes

**Comment by tancik** [comment]
This is a bug that was introduced in the viewer refactor, pushing an update now.
