### ISSUE TITLE
Did something break variable resolution changes in realitycapture and nerfacto?

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#1852]
Did something break variable resolution changes in https://github.com/nerfstudio-project/nerfstudio/pull/1651 ?  An unshareable dataset that worked fine before now matches only 2 of over 100 images...

Reusing the prior ns-process-data results works with ns-train, but reprocessing with ns-process-data images yields many fewer matches.

**Comment by tancik** [comment]
Odd, the reality capture code hasn't really changed. It must be somewhere else.

**Comment by tancik** [comment]
The COLMAP version never handled multiple sensors. So it must be something in the realitycapture pipeline. I don't see any obvious changes that would affect it.

**Comment by machenmusik** [comment]
Closing for now.  Will reopen if needed.
