### ISSUE TITLE
Discord link

### ISSUE THREAD

**Issue by TianyuHuang-000** [nerfstudio-project/nerfstudio#1865]
Hi, thanks for your amazing open source projects.
I want to join the Discord, but the link expired, can someone send me a new link?

**Comment by tancik** [comment]
Where did you find the broken link so that I can update?

The following should work:
https://discord.gg/uMbNqcraFc

**Comment by TianyuHuang-000** [comment]
link in the readme
it's a problem on my end, thanks for replying :)
