### ISSUE TITLE
ns-export: command not found

### ISSUE THREAD

**Issue by TianyuHuang-000** [nerfstudio-project/nerfstudio#1866]
**Describe the bug**
after training the first model, cannot export the point cloud

**To Reproduce**
1. train the model by "ns-train nerfacto --data data/nerfstudio/poster"
2. tried "ns-export --help"
3.see the error "bash: ns-export: command not found"

**Expected behavior**
should provide subcommands

**Screenshots**
<img width="933" alt="截屏2023-05-04 下午4 51 30" src="https://user-images.githubusercontent.com/88012819/236133068-0abceb97-c990-4f3f-9a03-957450d86a5d.png">

**Comment by tancik** [comment]
What version of nerfstudio are you using?

**Comment by TianyuHuang-000** [comment]
(nerfstudio) pip show nerfstudio
Name: nerfstudio
Version: 0.1.8
Summary: All-in-one repository for state-of-the-art NeRFs
Home-page: 
Author: 
Author-email: 
License: Apache 2.0
Location: /home/thhuang/anaconda3/envs/nerfstudio/lib/python3.8/site-packages
Requires: aiohttp, aiortc, appdirs, av, functorch, gdown, h5py, imageio, ipywidgets, jupyterlab, matplotlib, mediapy, msgpack, msgpack-numpy, nerfacc, ninja, opencv-python, plotly, protobuf, pyngrok, python-socketio, requests, rich, tensorboard, torch, torchmetrics, torchtyping, torchvision, tyro, u-msgpack-python, wandb
Required-by:

**Comment by TianyuHuang-000** [comment]
<img width="1512" alt="截屏2023-05-05 下午1 10 23" src="https://user-images.githubusercontent.com/88012819/236370177-c591d9f4-62ca-459b-a5da-1616fbafb1e7.png">
can't install nerfstudio/0.2.2, since no matching version of open3d package

**Comment by tancik** [comment]
open3d 0.17.0 exists - https://pypi.org/project/open3d/
For some reason it looks like your environment isn't properly searching pypi
