### ISSUE TITLE
Rendering multiple camera images in parallel

### ISSUE THREAD

**Issue by Olimoyo** [nerfstudio-project/nerfstudio#1878]
Hi,

Is there an efficient way to render images for a batch of multiple cameras?

I was working on a rendering pipeline similar to the one shown in `render.py`, which loops through `cameras` with something like:

```
for camera_idx in range(cameras.size):
    camera_ray_bundle = cameras.generate_rays(camera_indices=camera_idx)
    outputs = pipeline.model.get_outputs_for_camera_ray_bundle(camera_ray_bundle)
    img = outputs["rgb"].cpu().numpy()
```

I know `generate_rays()` can take a tensor for `camera_indices`, but I was having a hard time understanding if that would allow batch rendering that's more efficient than just looping through the cameras. 

Thank you!

**Comment by tancik** [comment]
Can you create more rays before calling `get_outputs_for_camera_ray_bundle` but note that this function chunks up the rays before actually feeding it through the model,
https://github.com/nerfstudio-project/nerfstudio/blob/ad706f59c414bd7e0f62b78a6a5822e2de70b6b9/nerfstudio/models/base_model.py#L174
So if you have more that `self.config.eval_num_rays_per_chunk` rays, you won't see any speedup.

**Comment by Olimoyo** [comment]
That makes sense to me, thanks for the heads up on `eval_num_rays_per_chunk`!
