### ISSUE TITLE
hloc toolbox

### ISSUE THREAD

**Issue by txirrindulari** [nerfstudio-project/nerfstudio#1884]
I get the following error even though hloc is installed, I get positive feed for pip show pycolmap
Error: To use this set of parameters (superpoint_aachen/superglue/hloc), you must install hloc toolbox!!

Running the following command:
ns-process-data images --data /data/alcazares_hidroaviones/brutos  --output-dir /data/NERFs/output_alcazares/hidroaviones_lhoc/ --sfm-tool hloc --refine-pixsfm --feature-type any --matcher-type any --use-sfm-depth --include-depth-debug --verbose

Ubuntu 22.04
Cuda 12.1
Hierarchical-Localization 1.3
pycolmap Version: 0.4.0
Colmap 3.7
Torch 1.13.1+cu117
Nerfstudio 0.2.2

What am I missing?
Do I need to place hloc folders somewhere in the Nerfstudio enviroment folder?

**Comment by txirrindulari** [comment]
I will answer to myself.
In case someone is in the same situation.
Although hloc is installed on the system, I had not defined the path in ~/bashrc to be accessible by the python environment
export PYTHONPATH=/disc12/nerfstudio_latest/Hierarchical-Localization:$PYTHONPATH

**Comment by vrahnos3** [comment]
Hello @txirrindulari , I have downloaded HLOC on virtualenv and still have the same issue with you. Have you any answer on that?

**Comment by txirrindulari** [comment]
Hi @vrahnos3, I remember all my issues went away adding paths to ~/bashrc. I did not play so much since I posted my question and auto-answer my self here, but I can say I did not find HLOC to have any benefits on my test projects

**Comment by vrahnos3** [comment]
> Hi @vrahnos3, I remember all my issues went away adding paths to ~/bashrc. I did not play so much since I posted my question and auto-answer my self here, but I can say I did not find HLOC to have any benefits on my test projects

Thanks for your reply,
I solved this error on another issue #2065
