### ISSUE TITLE
Median depth or expected depth

### ISSUE THREAD

**Issue by XJay18** [nerfstudio-project/nerfstudio#1912]
Hi, thanks for the great project.

I am new to nerf and I have a question about the `DepthRenderer()`. I notice there are two types of depth renderers, i.e., `median` and `expected`. In literature, I think the definition of rendered depth corresponds to the expected depth renderer in this project. However, the default method nerfacto uses the median depth renderer. I am a little confused about the median depth and wonder which one should be used for rendering depth images or for depth supervision.   

Thanks for your time in advance.

**Comment by AlstonXiao** [comment]
The expected depth is more suitable for depth supervision since the gradient can flow to every ray sample. However, the median is more resistant to outliers for rendering purposes and gives better visually pleasing results.

**Comment by XJay18** [comment]
Got it, thanks!
