### ISSUE TITLE
Export point cloud error with large data: "only one live display may be active at once" from rich console

### ISSUE THREAD

**Issue by msours** [nerfstudio-project/nerfstudio#1913]
When training a large dataset with ~1000 full resolution images, (I use datamanager, train_num_images_to_sample_from = 200, eval_num_images_to_sample_from = 100), I'm able to successfully complete training, but then when attempting to export the point cloud, I run into this error:
![image](https://github.com/nerfstudio-project/nerfstudio/assets/15207127/0c871bc4-5635-4626-bf31-b8fa931dab18)

1. Train dataset with >= ~1000 images, using datamanager to cycle through batches instead of loading all images at once:
ns-train nerfacto --data <'path to dataset'> --pipeline.datamanager.train_num_images_to_sample_from 200 --pipeline.datamanager.train_num_times_to_repeat_images 10 --pipeline.datamanager.eval_num_times_to_repeat_images 3 --pipeline.datamanager.eval_num_images_to_sample_from 100 --pipeline.model.predict-normals True

2. ns-export pointcloud --load-config <config.yml> --output-dir <path to export dir>
All other parameters don't seem to matter; consistently get the error regardless.

Would really appreciate some help here, thanks!

**Comment by tancik** [comment]
Try out https://github.com/nerfstudio-project/nerfstudio/pull/1600
If it work, I can clean up the PR and merge it

**Comment by msours** [comment]
@tancik I appreciate the quick response, the fix seems to solve the issue on my end!
