### ISSUE TITLE
when i pip insall tiny-cuda-nn, raise error?

### ISSUE THREAD

**Issue by liuxin2322** [nerfstudio-project/nerfstudio#1920]
raise EnvironmentError('CUDA_HOME environment variable is not set. '
      OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capability 61 from PyTorch
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jkulhanek** [comment]
Please follow the instructions on how to install tiny-cuda-nn in the following repo:
https://github.com/NVlabs/tiny-cuda-nn

If you experience any errors installing it, open an issue there.
