### ISSUE TITLE
How to render a environment map?

### ISSUE THREAD

**Issue by Relif-me** [nerfstudio-project/nerfstudio#1938]
Excellent project!

When I was looking at the introductory video for the Blender VFX add-on section in the documentation, I learned that nerfstudio can render and generate environment maps, and I wanted to know exactly how

**Screenshots**
![image](https://github.com/nerfstudio-project/nerfstudio/assets/124853470/662d7700-c2ee-4e83-8bac-7858bd3d6d8b)

**Comment by tancik** [comment]
In the viewer you can set it to render equirectangular images
<img width="374" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/3310961/a08ea3e5-52d5-4801-97ba-1ea2d9578c49">

**Comment by Relif-me** [comment]
Got it, thanks!
