### ISSUE TITLE
Eval Image Indices parameter is being ignored

### ISSUE THREAD

**Issue by ManuConcepBrito** [nerfstudio-project/nerfstudio#1963]
**Describe the bug**
The ` --pipeline.datamanager.eval-image-indices` is being ignored at the moment if I understand the functionality right. I understand it as allowing you to choose the images that are to be used during evaluation.

**To Reproduce**
Use the argument in a training pipeline with only one index ` --pipeline.datamanager.eval-image-indices 20`, the datamager ignores it and creates the evaluation dataset without taking it into account.

**Expected behavior**
Only image with index 20 is used for evaluation

**Additional context**
If you check for example the nerfstudio_dataparser.py, I see that you can specify the train/eval split by adding a "val_filenames" and a "train_filenames" but the eval_image_indices is not being passed/ignored

I can take care of it if agreed that this is not the expected behaviour @tancik

**Comment by Chjx395** [comment]
@tancik I have the same question. Could you help answer us?
