### ISSUE TITLE
Project ray samples onto other views

### ISSUE THREAD

**Issue by zhan-xu** [nerfstudio-project/nerfstudio#1974]
**Edit:**
Maybe the example below  is not a good one. My question is how to project ray samples to other frames (cameras).

I assume `ray_samples.frustums.get_positions()` gets points `P_world` in world frame. 
I can use `fx, fy, cx, cy and camera_to_worlds` from `Cameras` class to build the camera matrices.
The I just project points using `K @ E @ P_world`.
Did I miss anything?  For example, do I need to use `transform_matrix` from `DataparserOutputs`?

**Original post:**
I am trying to implement projecting ray samples to other frames, something like IBR.
When I project the same point from world space onto 2 training frames, the projection don't look like correspondence to each other.
A simplest reproducing of the problem could be like:

```
import json, numpy as np

def project_point(point_in, K, E):
    point_out = (E @ point_in)[0:3]
    point_out = K @ point_out
    point_out = point_out[0:2] / point_out[2]
    point_out = np.round(point_out.squeeze()).astype(np.int32)
    return point_out

if __name__ == "__main__":
    with open("data/myseq_processed/transforms.json", encoding="UTF-8") as file:
        meta = json.load(file)
    K = np.eye(3)
    K[0, 0] = meta.fx
    K[1, 1] = meta.fy
    K[0, 2] = meta.cx
    K[1, 2] = meta.cy
    frame1 = cv2.imread(os.path.join("data/myseq_processed", meta["frames"][0]['file_path']))
    frame2 = cv2.imread(os.path.join("data/myseq_processed", meta["frames"][1]['file_path']))
    E1 = meta["frames"][0]['transform_matrix']
    E2 = meta["frames"][1]['transform_matrix']
    E1 = np.linalg.inv(E1) # convert camera_to_world to world_to_camera
    E2 = np.linalg.inv(E2) # convert camera_to_world to world_to_camera

    point_world = np.array([[1.2], [1.0], [0.2], [1.0]])  # find a 3D point that can be observed from both views
    point_frame1 = project_point(point_world, K, E1)
    point_frame2 = project_point(point_world, K, E2)
    
    # visualize
    cv2.circle(frame1, tuple(point_frame1), 5, (0, 0, 255), -1)
    cv2.circle(frame2, tuple(point_frame2), 5, (0, 0, 255), -1)
    cv2.imshow("frame1", cv2.resize(frame1, None, fx=0.5, fy=0.5))
    cv2.imshow("frame2", cv2.resize(frame2, None, fx=0.5, fy=0.5))
    cv2.waitKey(0)
    cv2.destroyAllWindows()
```
The results are
![Screenshot from 2023-05-22 22-31-56](https://github.com/nerfstudio-project/nerfstudio/assets/3896000/14deff4a-61d1-472f-bc2b-e5784d9bfeee)
![Screenshot from 2023-05-22 22-32-04](https://github.com/nerfstudio-project/nerfstudio/assets/3896000/88a24c79-dd39-4e20-89c6-23cc46bf9756)

I also tried to consider distortion, but that only affects a few pixels and doesn't solve the problem.
I am wondering if I missed something. Could someone help?

**Comment by zhan-xu** [comment]
Maybe the above example is not a good one. The fundamental question I have is how to project ray samples to other frames (cameras).

I assume `ray_samples.frustums.get_positions()` getS points in world frame P_world. 
I can use fx, fy, cx, cy and camera_to_worlds from Cameras class to build the camera matrices.
The I just project points using K @ E @ P_world.
Did I miss anything?  For example, do I need to use transform_matrix from DataparserOutputs?

**Comment by kerrj** [comment]
I wonder if the problem could be the training image pose preprocessing? Nerfstudio normalizes camera coordinates to fit in a unit cube and align with the z axis. Checkout `nerfstudio_dataparser.py` line 220:
```
poses, transform_matrix = camera_utils.auto_orient_and_center_poses(
            poses,
            method=orientation_method,
            center_method=self.config.center_method,
        )
```
Maybe you need to additionally transform ray samples by this before projecting? Alternatively if you work with the c2w returned by the datamanager this shouldn't be a problem, but if you use the poses in transforms.json they might not align

**Comment by zhan-xu** [comment]
Thanks @kerrj . I reversed the direction of y and z axis of the rotation of c2w, and seems it works now.
