### ISSUE TITLE
Looking for the implementation of NeRFPlayer

### ISSUE THREAD

**Issue by cegutica** [nerfstudio-project/nerfstudio#1985]
I recently discovered the paper "NeRFPlayer: A Streamable Dynamic Scene Representation with Decomposed Neural Radiance Fields". Where can we find the code related to this paper, if it is available?  @tancik @lsongx

**Comment by lsongx** [comment]
Hi, I am preparing a PR for moving nerfplayer out. If you want to play with it for now, you can use the model nerfplayer-ngp or nerfplayer-nerfacto. Will let you know when the PRs are ready.

**Comment by cegutica** [comment]
That's great! Appreciate it :relaxed: I'm looking forward to it.

**Comment by lsongx** [comment]
Hi @cegutica , sorry for being late. More instructions can be now found at https://github.com/lsongx/nerfplayer-nerfstudio
