### ISSUE TITLE
a simple mistake in ExponentialDecayScheduler

### ISSUE THREAD

**Issue by 1e0nhardt** [nerfstudio-project/nerfstudio#1998]
When training nerfacto with --optimizers.fields.scheduler.warmup-steps 5000, it will crash soon.

**Expected behavior**
The lr should ramps up to 1e-2 in 5000 steps.  However, the lr increase like this.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/132132397/46b10c50-529c-433a-9dfb-078e2f92f714)

**Additional context**
This is caused by a typo in [ExponentialDecayScheduler](https://github.com/nerfstudio-project/nerfstudio/blob/e94d9031ab711bd755655adafba1b986e980f27b/nerfstudio/engine/schedulers.py#LL125C27-L125C27),  
where `lr = self.config.lr_pre_warmup + (1 - self.config.lr_pre_warmup) * np.sin(0.5 * np.pi * np.clip(step / self.config.warmup_steps, 0, 1))` 
should be `lr = self.config.lr_pre_warmup + (lr_init - self.config.lr_pre_warmup) * np.sin(0.5 * np.pi * np.clip(step / self.config.warmup_steps, 0, 1))`

**Comment by tancik** [comment]
Good catch!
