### ISSUE TITLE
No metashape option for ns-process-data

### ISSUE THREAD

**Issue by sungan1** [nerfstudio-project/nerfstudio#2007]
I follow the easy option to download nerfstudio and want to use metashape option to process data.
command line followed:
ns-process-data metashape

usage: ns-process-data [-h] {images,video,insta360,record3d}
ns-process-data: error: argument {images,video,insta360,record3d}: invalid choice: 'metashape' (choose from 'images', 'video', 'insta360', 'record3d')

**Comment by tancik** [comment]
It looks like you are using a old version, can you install the latest?

**Comment by sungan1** [comment]
I see, I will try latest version

**Comment by f-dy** [comment]
@sungan1 is you issue resolved?

**Comment by sungan1** [comment]
Yes, I downloaded the newest version, and it works. Thank you!
