### ISSUE TITLE
Siggraph 2023 result reproduction

### ISSUE THREAD

**Issue by apchenstu** [nerfstudio-project/nerfstudio#2010]
Hi all, thanks for the nice framework! 
We are working on a paper submission, and we noted that you just update the Arxiv version with a new benchmark on the mipnerf360 dataset, would be really helpful if you can provide the benchmark script so that we can re-run them with our 30k iteration setting, thank you in advance ;)
BTW, did you use [this branch](https://github.com/nerfstudio-project/nerfstudio/tree/SIGGRAPH-2023-Code), thanks!

**Comment by ethanweber** [comment]
Hi! It’s indeed that branch! We also created a tag to mark it. The branch should describe how to do this here https://github.com/nerfstudio-project/nerfstudio/tree/SIGGRAPH-2023-Code/projects/nerfstudio_paper. Hopefully that’s a good starting point for you!

**Comment by AlbertHuyb** [comment]
@ethanweber Could you please provide the script for the instant-ngp experiments? I didn't fine that in this python script.
