### ISSUE TITLE
ns-train in2n getting TypeError: __init__() got an unexpected keyword argument 'grad_scaler'

### ISSUE THREAD

**Issue by descobar7** [nerfstudio-project/nerfstudio#2012]
**Describe the bug**
When trying to train in2n tiny a grad scaler error keeps popping up.

C:\Users\User\Documents\nerfstudio\nerfstudio\engine\trainer.py:144 in setup                 

│   141 │   │   │   │   'test': loads train/test datasets into memory                              │
│   142 │   │   │   │   'inference': does not load any dataset into memory                         │
│   143 │   │   """                                                                                │
│ ❱ 144 │   │   self.pipeline = self.config.pipeline.setup(                                        │
│   145 │   │   │   device=self.device,                                                            │
│   146 │   │   │   test_mode=test_mode,                                                           │
│   147 │   │   │   world_size=self.world_size,                                                    │

│ C:\Users\User\Documents\nerfstudio\nerfstudio\configs\base_config.py:57 in setup                 │

│    54 │                                                                                          │
│    55 │   def setup(self, **kwargs) -> Any:                                                      │
│    56 │   │   """Returns the instantiated object using the config."""                            │
│ ❱  57 │   │   return self._target(self, **kwargs)                                                │
│    58                                                                                            │
│    59                                                                                            │
│    60 # Machine related configs                                                                  │

TypeError: __init__() got an unexpected keyword argument 'grad_scaler'

**Comment by 870223050** [comment]
I'm having the same issue, did you fix it, please

**Comment by neronicolo** [comment]
I have the same issue.

**Comment by tancik** [comment]
I believe it has been resolved in the `in2n` repo - https://github.com/ayaanzhaque/instruct-nerf2nerf/issues/37
