### ISSUE TITLE
Exported Camera path coordinate convention question

### ISSUE THREAD

**Issue by AliYoussef97** [nerfstudio-project/nerfstudio#2019]
Hello,

I'm a bit confused about the exported camera path transformation matrices, if they follow the OpenCV format or Blender Format.

In the [documentation](https://docs.nerf.studio/en/latest/quickstart/data_conventions.html), the camera view space follows the Blender/OpenGL coordinate format where +X is right, +Y is up and -Z is in the viewer's direction.

On the other hand, the world space, as in the GUI, follows the OpenCV format, where +Z is up and X and Y are parallel to each other.

I'm a bit confused, the exported camera_path, follows which data convention.

Thank you

**Comment by OrangeSodahub** [comment]
@AliYoussef97 Hi, have you figured it out?

**Comment by AliYoussef97** [comment]
@OrangeSodahub, Hello!

It follows OpenGL convention, you can simply switch betwen the two using the following:

```
def axis_transform(cam_matrix):
        '''
        Transform camera transformation matrix axis.
        '''
        reverse = np.diag([1, -1, -1, 1])
        cam_matrix =  cam_matrix @ reverse
        return cam_matrix
```

Hope that helps :)
