### ISSUE TITLE
How can we use custom mask in nerfacto model 

### ISSUE THREAD

**Issue by TianyuHuang-000** [nerfstudio-project/nerfstudio#2020]
I have added the mask file in the transforms.json
Seems nerafcto model load the mask files but not using it
Is this feature implemented or i need to modify by myself

**Comment by f-dy** [comment]
It works for me.
Maybe you also forgot to downscale the masks?
```python
cat > add_mask_to_transforms_json.py <<EOF
#!/usr/bin/env python
import sys
import json

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} input_transforms.json output_transforms.json")
    sys.exit(1)
with open(sys.argv[1]) as input_file:
    file_contents = input_file.read()
parsed_json = json.loads(file_contents)
for frame in parsed_json["frames"]:
    frame["mask_path"] = "masks/mask.png"
with open(sys.argv[2], "w") as output_file:
    json.dump(parsed_json, output_file, indent=4)
EOF
```
```python
cat > downsize_mask.py <<EOF
#!/usr/bin/env python
import cv2
import sys
import json
from pathlib import Path

if len(sys.argv) != 2:
    print(f"Usage: {sys.argv[0]} path_to/mask.png")
    print(f"Output is path_to/masks_{downscale}/mask.png")
    sys.exit(1)
mask_path = Path(sys.argv[1])
mask = cv2.imread(str(mask_path), cv2.IMREAD_GRAYSCALE)
height, width = mask.shape[:2]
processed_data_dir = mask_path.parent
downscale_factors = [2, 4, 8]
for downscale in downscale_factors:
    mask_path_i = processed_data_dir / f"masks_{downscale}"
    mask_path_i.mkdir(exist_ok=True)
    mask_path_i = mask_path_i / "mask.png"
    mask_i = cv2.resize(
        mask, (width // downscale, height // downscale), interpolation=cv2.INTER_NEAREST
    )
    cv2.imwrite(str(mask_path_i), mask_i)
    print(f"Wrote {mask_path_i}")
EOF
```
And finally,
```sh
mkdir "${PROCESSED_DATA_DIR}/masks"
mv mask.png "${PROCESSED_DATA_DIR}/masks/mask.png"
if [ ! -f "${PROCESSED_DATA_DIR}/transforms_nomask.json" ]; then
  mv "${PROCESSED_DATA_DIR}/transforms.json" "${PROCESSED_DATA_DIR}/transforms_nomask.json"
fi
python add_mask_to_transforms_json.py \
  "${PROCESSED_DATA_DIR}/transforms_nomask.json" \
  "${PROCESSED_DATA_DIR}/transforms_masked.json"
ln -sf "transforms_masked.json" "${PROCESSED_DATA_DIR}/transforms.json"
#ln -sf "transforms_nomask.json" "${PROCESSED_DATA_DIR}/transforms.json"
python downsize_mask.py "${PROCESSED_DATA_DIR}/masks/mask.png"
```

Note that masks use a lot more GPU memory.

Other issues/PRs related to masks:
* https://github.com/nerfstudio-project/nerfstudio/pull/1741
* https://github.com/nerfstudio-project/nerfstudio/issues/1747
* https://github.com/nerfstudio-project/nerfstudio/pull/1819
* https://github.com/nerfstudio-project/nerfstudio/pull/1821

**Comment by TianyuHuang-000** [comment]
thank you so much for your reply, 
previousely i used ns-process-data to scale the masks, seems have some problem at scale 4 and 8
now using the cv2 resize, the boolean value is correct but the program is killed after loading the images

mask specify the tea table in the scene and each image frame corresponding to deffierent mask
![q1](https://github.com/nerfstudio-project/nerfstudio/assets/88012819/3b1e1bee-6dcd-486b-9c4a-e8ecea258f78)
![q2](https://github.com/nerfstudio-project/nerfstudio/assets/88012819/b267a828-9ccf-4e9d-90ed-10606ac9c8e2)
![q3](https://github.com/nerfstudio-project/nerfstudio/assets/88012819/b80135d8-9d40-4180-82d0-94173d5e5ce5)




using command 
ns-train nerfacto --data "~/data/mydata/sofa" instant-ngp-data

**Comment by devernay** [comment]
In nerfstudio, mask are used to ignore parts of the image data (eg a moving person), not (as in instant ngp) to crop the screen (ie accumulated density should be zero outside of the mask).
Nerfstudio could have both kinds of masks, but for now it can just handle the first kind
