### ISSUE TITLE
Exporting depth maps 

### ISSUE THREAD

**Issue by Mehi44** [nerfstudio-project/nerfstudio#2027]
**Describe the bug**
Hello, Thanks for the great work :) I would like to know  if it's possible to export depth maps corresponding to each image after training a nerfacto model. Thanks!

**Comment by tancik** [comment]
Add `--rendered-output-names depth` to the end of your command.
Here are docs for the render command - https://docs.nerf.studio/en/latest/reference/cli/ns_render.html

**Comment by Mehi44** [comment]
Thanks!
