### ISSUE TITLE
Camera Pose Extraction and Matching

### ISSUE THREAD

**Issue by andrewzhang214** [nerfstudio-project/nerfstudio#2031]
Hello! I'm currently using the google colab file for nerfstudio and had a question about camera pose extraction.

My goal is to extend NeRF to work for thermal images. I have a collection of pictures as such:
<img width="249" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/100539292/052bc7b7-ef02-495a-a0b3-4b74e260e9c6">

Unfortunately, I believe COLMAP is failing to extract the camera poses because of the modality, and I'm getting the "Error: Data processing did not complete" message when running the training cell.
Fortunately the thermal camera I used to take the picture took a corresponding RGB picture, which did work on NeRF.
<img width="636" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/100539292/e027085e-b6ce-48bd-845b-33b6cd317d03">

I want to see if I can't manually match each of the extracted camera poses of the RGB image to the corresponding thermal image and see if that works. 
Is there a way for me to do that?

**Comment by brentyi** [comment]
There's a docs page on how processed datasets are stored that you can reference for this: https://docs.nerf.studio/en/latest/quickstart/data_conventions.html

You can probably modify the `file_path` fields to point to your thermal images instead of the color images. Assuming the camera parameters (intrinsics & extrinsics) for the thermal images is close enough to the RGB images it seems to me like this could get you a reasonable result.

**Comment by andrewzhang214** [comment]
> There's a docs page on how processed datasets are stored that you can reference for this: https://docs.nerf.studio/en/latest/quickstart/data_conventions.html
> 
> You can probably modify the `file_path` fields to point to your thermal images instead of the color images. Assuming the camera parameters (intrinsics & extrinsics) for the thermal images is close enough to the RGB images it seems to me like this could get you a reasonable result.

Really appreciate the reply. 
A question on understanding the output of ns-process-data. After I run it on my RGB photos, I get the following additional files.
<img width="249" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/100539292/f649f04d-1b6c-4f3c-a6ce-ec9e68f60eff">
The raw images folder contains my RGB photos, but what file contains the pose information? Would it be enough to simply replace raw_images with my thermal images? And what are the images, images_2, etc. folders exactly? They contain jpgs called frame_0000*, but what are these exactly in relation to COLMAP?

**Comment by andrewzhang214** [comment]
Managed to get it working, for anyone curious the results were hilariously bad haha

![image](https://github.com/nerfstudio-project/nerfstudio/assets/100539292/e89d141d-3e99-4ce9-b122-fd5929890843)
![image](https://github.com/nerfstudio-project/nerfstudio/assets/100539292/31a7aa07-aede-4204-a99d-49dd79bb3716)
