### ISSUE TITLE
ERROR: Failed to parse options: unrecognised option '--output_path'

### ISSUE THREAD

**Issue by Nationarity** [nerfstudio-project/nerfstudio#2032]
I am afraid this is a rudimentary question,
For example, I have a 'video.mp4' stored in '. video.mp4' stored in '/data/nerfstudio/poster2' from 'ns-process-data video', I get the following error.
I am using ubuntu 18.04.6 LTS and can launch the COLMAP GUI from the terminal without any problems. 
I would like to know the cause and solution.

(nerfstudio) N@N:~/nerfstudio$ ns-process-data video --data data/nerfstudio/poster2/video.mp4 --output-dir data/nerfstudio/poster2
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
Number of frames in video: 4606
Number of frames to extract: 308
[10:24:07] 🎉 Done converting video to images.                 process_data_utils.py:173
[10:26:00] 🎉 Done downscaling images.                           process_data_utils.py:361
[10:26:09] 🎉 Done extracting COLMAP features.             colmap_utils.py:131
[10:26:32] 🎉 Done matching COLMAP features.              colmap_utils.py:145
───────────────────────────  💀 💀 💀 ERROR 💀 💀 💀──────────────────────────
Error running command: colmap mapper --database_path data/nerfstudio/poster2/colmap/database.db --image_path 
data/nerfstudio/poster2/images --output_path data/nerfstudio/poster2/colmap/sparse
──────────────────────────────────────────────────────────────────────
ERROR: Failed to parse options: unrecognised option '--output_path'.

**Comment by tancik** [comment]
What version of colmap are you using?
Is the data you are testing with, the data we provide, or your own data?

**Comment by Nationarity** [comment]
Thank you for your response!
I am using COLMAP 3.4.
The data being tested is my data, 1920*1080, about 3 minutes long.


(nerfstudio) N@N:~/nerfstudio$ colmap -h
COLMAP 3.4 -- Structure-from-Motion and Multi-View Stereo
              (Commit Unknown on Unknown without CUDA)
Usage:
  colmap [command] [options]
Documentation:
  https://colmap.github.io/
Example usage:
  colmap help [ -h, --help ]
  colmap gui
  colmap gui -h [ --help ]
  colmap automatic_reconstructor -h [ --help ]
  colmap automatic_reconstructor --image_path IMAGES --workspace_path WORKSPACE
  colmap feature_extractor --image_path IMAGES --database_path DATABASE
  colmap exhaustive_matcher --database_path DATABASE
  colmap mapper --image_path IMAGES --database_path DATABASE --export_path EXPORT
  ...
Available commands:
  help
  gui
  automatic_reconstructor
  bundle_adjuster
  color_extractor
  database_creator
  dense_fuser
  dense_mesher
  dense_stereo
…

**Comment by tancik** [comment]
3.4 is pretty old. Can you try a newer version?

**Comment by yangjiheng** [comment]
> Thank you for your response! I am using COLMAP 3.4. The data being tested is my data, 1920*1080, about 3 minutes long.
> 
> (nerfstudio) N@N:~/nerfstudio$ colmap -h COLMAP 3.4 -- Structure-from-Motion and Multi-View Stereo (Commit Unknown on Unknown without CUDA) Usage: colmap [command] [options] Documentation: https://colmap.github.io/ Example usage: colmap help [ -h, --help ] colmap gui colmap gui -h [ --help ] colmap automatic_reconstructor -h [ --help ] colmap automatic_reconstructor --image_path IMAGES --workspace_path WORKSPACE colmap feature_extractor --image_path IMAGES --database_path DATABASE colmap exhaustive_matcher --database_path DATABASE colmap mapper --image_path IMAGES --database_path DATABASE --export_path EXPORT ... Available commands: help gui automatic_reconstructor bundle_adjuster color_extractor database_creator dense_fuser dense_mesher dense_stereo …

In colmap 3.4, the mapper command is actually like this:
`colmap mapper --image_path IMAGES --database_path DATABASE --export_path EXPORT`

where in later version of colmap (3.8 up to date), the mapper command turned into this:
`colmap mapper --image_path IMAGES --database_path DATABASE --output_path MODEL`

That's why it reported:
`ERROR: Failed to parse options: unrecognised option '--output_path'.`

Since in colmap 3.4, there is no --output-path parameter supported yet. Upgrade to 3.8 will solve this issue.

**Comment by Nationarity** [comment]
I upgraded to 3.8 and the aforementioned error was resolved. Thank you very much.
