### ISSUE TITLE
Support 3d-gaussian-splatting Method

### ISSUE THREAD

**Issue by modoartwork** [nerfstudio-project/nerfstudio#2034]
https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/

Any plans to support 3d-gaussian-splatting??

It is a new paper with high frames and realistic expressions.

It would be great if this were supported.

**Comment by minsoo5403** [comment]
Excellent paper, is there any possibility that NeRFStudio can support it?

**Comment by MohamedAliRashad** [comment]
It will be nice if this paper was added to `nerfstudio`

**Comment by tancik** [comment]
It is something we are looking into.

**Comment by MohamedAliRashad** [comment]
@tancik Any Updates ?

**Comment by tancik** [comment]
In progress!


https://github.com/nerfstudio-project/nerfstudio/assets/3310961/5ec317eb-8267-4f94-970b-f9e818c67c10

**Comment by MohamedAliRashad** [comment]
@tancik 4D Gaussain Splatting is here 😅
https://guanjunwu.github.io/4dgs/
