### ISSUE TITLE
How to integrate a 3d visual hull?

### ISSUE THREAD

**Issue by Learningm** [nerfstudio-project/nerfstudio#2062]
I got a 3D visual hull of an object in 3d tensor format [n, n, n]，I want to integrate into the nerfacto method so that I can render only the object in my image.

I tried some efforts but can not get expected results. I modified the `get_density` method inside nerfacto_field.py,  https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/fields/nerfacto_field.py#L224
I add another selector, to filter the positions not inside my viusal hull according to their normalized positions, but I can't get a good result.

Could you give me some suggestions to achieve my purpose? Thank you.

**Comment by tancik** [comment]
What you are doing seems like it should work. Maybe check that you are correctly taking the spatial distortion into account.
