### ISSUE TITLE
hloc error installation

### ISSUE THREAD

**Issue by vrahnos3** [nerfstudio-project/nerfstudio#2065]
Hello, I have downloaded hloc on my virtualenv of nerfstudio and as I try to run ns-process-data images still I am getting this error:
**Error: To use this set of parameters (superpoint_aachen/superglue/hloc), you must install hloc toolbox!!**

As you can see hloc installation exist on my virtualenv so I will appreciate if anyone can help me.  
![Screenshot_2](https://github.com/nerfstudio-project/nerfstudio/assets/63507675/ad3b3acd-b624-403c-8993-8876124abc4e)

**Comment by vrahnos3** [comment]
Thanks for you reply,
sure I tried it and these are the results. All seems normal.
![Screenshot_3](https://github.com/nerfstudio-project/nerfstudio/assets/63507675/31d1cdfb-8522-4566-bbfb-2f50f0f83191)

**Comment by vrahnos3** [comment]
You are right, 
the problem appears in this command. The output is the following. I am searching for it. If you have any tips I would appreciate.
![Screenshot from 2023-06-14 14-15-39](https://github.com/nerfstudio-project/nerfstudio/assets/63507675/678582f0-aaac-4b17-bffc-378a35f89796)

**Comment by vrahnos3** [comment]
> You are right, the problem appears in this command. The output is the following. I am searching for it. If you have any tips I would appreciate. ![Screenshot from 2023-06-14 14-15-39](https://user-images.githubusercontent.com/63507675/245774589-678582f0-aaac-4b17-bffc-378a35f89796.png)

**I solved it** 
In the mentioned file '/Hierarchical-Localization/hloc/utils/tools.py' that last error appears I made the following changes as they are shown in the picture too:

1. comment the first line: _from torch._six import string_classes_
2. add: 'torch.' to line 9 ---> torch.string_classes 
![2023-06-14_14-36](https://github.com/nerfstudio-project/nerfstudio/assets/63507675/edfc1f67-5601-496b-8f3d-4faf69776b1a)

I will close this issue. Thanks again for your time!!

**Comment by MHz777** [comment]
Hello, I also encountered this situation when installing pixsfm:
**Error: use refine_pixsfm, you must install pixel-perfect-sfm toolbox!!**

I have successfully installed the pixsfm package and can import it in the Python environment:
![image](https://github.com/nerfstudio-project/nerfstudio/assets/40061260/3a82e9ae-3a13-42dc-be49-18fe573cc27d)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/40061260/ee71ccf9-55e9-4efa-845c-7e45a54a16a4)

But when I am running ns-process-data, I will encounter this problem. How can I solve it?

**Comment by vrahnos3** [comment]
Hello, as @tancik mentioned me before, after command 'import pixsfm' try to run this command:
'from pixsfm.refine_hloc import PixSfM' and show us the results.
Your error seems to be here 
https://github.com/nerfstudio-project/nerfstudio/blob/e7fd1aefa29abf3c66c503934af49cd0aaa91c90/nerfstudio/process_data/hloc_utils.py#L45

**Comment by MHz777** [comment]
> 
Thank you for your reply. I will get the following error when trying to use this code:

`from pixsfm.refine_hloc import PixSfM  # type: ignore `

![image](https://github.com/nerfstudio-project/nerfstudio/assets/40061260/cc27a4f6-4721-4669-ae3f-8577d4fb8168)

I tried using source code to build hloc and pixsfm on another Ubuntu, and then using nerfstudio to process the data resulted in the same error. I don't know why this happened,

Additionally, the Ubuntu system I am using is based on WSL.

**Comment by vrahnos3** [comment]
I had the same issue with another git repo.

1. Ensure that you install pixsfm in your virtualenv/conda env
2. import sys
3. Try to sys.path.append('path/to/pixsfm')

I believe its about unknown path, because you are trying to import another package in your file.
