### ISSUE TITLE
masked (mustard) dataset much slower with main than PR2025

### ISSUE THREAD

**Issue by machenmusik** [nerfstudio-project/nerfstudio#2075]
On my machine
- using the mustard dataset with masks (see https://github.com/nerfstudio-project/nerfstudio/issues/1498#issue-1599115766 ) with PR #2025 had default nerfacto iteration times around 80 to 90 ms
- using same dataset with main (currently https://github.com/nerfstudio-project/nerfstudio/commit/d18588d5d43fafa87aa819cdb3dc5b4e09f05549 ) has default nerfacto iteration times around 400 ms
so 4-5x worse.

**Comment by machenmusik** [comment]
Suggested viewer crop settings for mustard:
```
Enable
Crop Min -0.15 -0.20 -0.25
Crop Max 0.15 0.20 0.33
```

**Comment by machenmusik** [comment]
https://github.com/nerfstudio-project/nerfstudio/commit/d4b04376abd46d9bddf8c299d1687177fe027951 is 80 to 90ms
https://github.com/nerfstudio-project/nerfstudio/commit/3b0f7581d8df44045f0a0822f0cbcb7e6c0223b8 is ~400ms

So looks to be a side effect of #1730 for datasets using masks.

**Comment by machenmusik** [comment]
Removing `"mask"` from https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/datasets/base_dataset.py#L45 restores full speed for mustard dataset.

Perhaps there should be a parameter to request masks on GPU that would do the above at runtime.

**Comment by YifuTao** [comment]
I faced similar issue. The training speed drops from 170k/s to 6k/s so more than 20 times slower

**Comment by machenmusik** [comment]
#2110 should resolve this when the new option is used.
