### ISSUE TITLE
Processing custom data error

### ISSUE THREAD

**Issue by SHIELDXIE** [nerfstudio-project/nerfstudio#2078]
**Describe the bug**
I'm trying to process custom data as instructed in the documentation and the terminal reports an error  
``ERROR: failed to create sparse model``  

**To Reproduce**
1. conda activate the env
2. ns-process-data {images, video} --data {DATA_PATH} --output-dir {PROCESSED_DATA_DIR}
3. Scroll down to  
4. [14:43:20] 🎉 Done copying images.                                                             process_data_utils.py:235  
    [14:44:03] 🎉 Done downscaling images.                                                         process_data_utils.py:361``  
    [14:44:23] 🎉 Done extracting COLMAP features.                                                       colmap_utils.py:131  
    [14:44:25] 🎉 Done matching COLMAP features.                                                         colmap_utils.py:145  

5. See error
6. Error running command: colmap mapper --database_path  
    F:\AIToolKit\AI_ToolKit\nerf_dataset\data\nerfstudio\lg\colmap\database.db --image_path  
    F:\AIToolKit\AI_ToolKit\nerf_dataset\data\nerfstudio\lg\images --output_path  
    F:\AIToolKit\AI_ToolKit\nerf_dataset\data\nerfstudio\lg\colmap\sparse --Mapper.ba_global_function_tolerance 1e-6  
    ERROR: failed to create sparse model

**Expected behavior**

**Screenshots**
![image](https://github.com/nerfstudio-project/nerfstudio/assets/37254173/d2b1d556-afed-4809-a6c6-831d52b4d796)

**Additional context**
I am a newcomer in this area, so please forgive me if this is a stupid question. I really don't know what went wrong.  
I installed the non-cuda version of colmap on my computer using vcpkg because the cuda version kept failing to install.
System: Windows 11 22H2
Python: 3.8.16
CUDA ToolKit: 11.8

**Comment by tancik** [comment]
This is likely an issue with the data you are trying to process, there might be too much blur, not enough images, too much motion, etc.

**Comment by SHIELDXIE** [comment]
> This is likely an issue with the data you are trying to process, there might be too much blur, not enough images, too much motion, etc.

Thank you for your reply. In order to run through the process, I haven't used the data I shot, I used the standard LEGO data
![image](https://github.com/nerfstudio-project/nerfstudio/assets/37254173/49aef8e5-88fe-4c2d-a0c5-1ecb6afe2a20)

**Comment by brentyi** [comment]
Closing this because it seems the same as #2604! Will leave a comment there.
