### ISSUE TITLE
[Regression] Nerfacto-huge system memory usage went from 12GB to 175+GB (1200 images)

### ISSUE THREAD

**Issue by SharkWipf** [nerfstudio-project/nerfstudio#2087]
**Describe the bug**
As per https://github.com/nerfstudio-project/nerfstudio/pull/2003#issuecomment-1594261444, a recent change in the nerfacto-huge PR skyrocketed its memory usage.  
Nerfacto-huge's memory usage went from ~12GB on commit 374d7fe4b2f81363b3eeb4b10229aae84ab1a7b5, to 175+GB (before OOM) on commit f3ac598e27bef1fa691ea5623e75841525c30596 (or 4acc06bdb27b26bc0d16ef1fbc2ad96e47ea2265 but that one crashes, so I can't verify).
The problem also happens with lower image counts, 300 images now uses around 60GB RAM.

**To Reproduce**
1. Pull commit 374d7fe4b2f81363b3eeb4b10229aae84ab1a7b5;
2. Run a ns-train nerfacto-huge, take note of the memory usage;
3. Pull commit f3ac598e27bef1fa691ea5623e75841525c30596;
4. Run a ns-train nerfacto-huge, take note of the memory usage. It is several times higher now.

**Expected behavior**
Memory usage stays within sensible bounds

**Screenshots**
N/A

**Additional context**
Command tested with: `ns-train nerfacto --max-num-iterations 100000 --viewer.quit-on-train-completion True --pipeline.model.use_gradient_scaling True --pipeline.model.predict-normals True --data /home/sebastiaan/src/nerf/work/out/colmaps/VID_20230615_163207/1200 --output-dir /home/sebastiaan/src/nerf/work/out/models/VID_
20230615_163207/100000`

The commits mentioned in this issue are from before #2003 was merged, commits from the PR, making it difficult to further bisect this issue without cherry picking commits from the main branch.

Note: This applies to system memory, not GPU VRAM.

**Comment by machenmusik** [comment]
Any better after #2082 ?
