### ISSUE TITLE
Train over all images

### ISSUE THREAD

**Issue by csparker247** [nerfstudio-project/nerfstudio#2097]
I have a sparse image set (about 45 images) that was captured such that all of the images need to be included in the training dataset. If images aren't included, there are known regions of the scene which are unobserved. 

When I run `ns-train nerfacto`, I get the following message:
```
Setting up training dataset...
Caching all 41 images.
Setting up evaluation dataset...
Caching all 4 images.
```

I don't particularly care about evaluation on unseen data in my task, and really just want the reconstruction to be as accurate as possible. However, I can't seem to setup the training dataset so that all 45 images are included. I've tried various combinations of the `--pipeline.datamanager` flags, but they don't appear to change anything. Am I missing something?

**Comment by tancik** [comment]
To the end of your command, add
`nerfstudio-data --train-split-fraction 1`
To see all of the dataparser options, add `nerfstudio-data --help` to the end of your command.

**Comment by csparker247** [comment]
Excellent. Thank you!
