### ISSUE TITLE
ns-process-data not working for custom images?

### ISSUE THREAD

**Issue by sudoku-lord** [nerfstudio-project/nerfstudio#2100]
Hi! I'm trying to run the demo notebook, but every time I hit `ns-process-data`, it only reaches the "Done copying images" step before ending. I've performed all the necessary installations, and it was working a few days ago, so I'm wondering if there have been any relevant changes since then? 

Thanks!

**Comment by tancik** [comment]
Sometimes the notebook is a bit finicky. I would try again to see if there is any difference. Also try using the same data you used before to see if it is related to the data.

**Comment by sudoku-lord** [comment]
@tancik I just ran it again (I've been using the same dataset the whole time), and it's still stopping after the copying images step.

<img width="511" alt="Screenshot 2023-06-20 at 7 30 18 PM" src="https://github.com/nerfstudio-project/nerfstudio/assets/15935019/471cfa99-e091-47aa-b2d0-846c99c3d4ac">

I have also disconnected and reconnected the runtime, to no avail.

**Comment by sudoku-lord** [comment]
Hi, just wondering if there's any update for this? I'm baffled because the same code which ran correctly and included all the processing steps a few days ago is no longer running after "Done copying images". I've been using the same dataset this entire time.

**Comment by tancik** [comment]
It's possible that it is a colab issue, they regularly update package versions without warning that can break things. In this case it is possible that colmap is no longer working. Did you see any errors during the installation steps.

**Comment by sudoku-lord** [comment]
Hi @tancik , 

I created my own notebook, and see no errors during the installation steps at all. I'm using the COLMAP installation process from the demo notebook with no issues, and I reach the "Done copying images" step before stopping there. Are you (or anyone else) able to upload custom data and successfully process it without running into this issue?

**Comment by machenmusik** [comment]
Does it actually end, or simply appear to hang?
If this is first run, I wonder whether it is some one-time lengthy nvcc compilation happening; there used to be nice messages for those, but that may have changed

**Comment by sudoku-lord** [comment]
@machenmusik Thanks for the reply! I think there was a really weird issue with the way the local images were saved, because I tinkered with them a bit and now the training runs just fine. Rendering is an entirely different matter, though... I keep getting "renderer disconnected" and no amount of changing the Python version or rerunning the viewer code has helped.

**Comment by ihorizons2022** [comment]
i face the same issue.
for process custom data, the thread hangs there in colab.
<img width="934" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/121672603/2c3b7b5a-e131-4f55-a3f5-aa2fda0742a1">

**Comment by desifisker** [comment]
I have a similar issue where ns-process-data reaches "Done copying images with prefix 'frame_' and then I get: ValueError: could not convert string to float: '3.9.1'. This seems to be an error with the version of colmap (3.9.1) not being able to be converted to a float, here is the whole error:Traceback (most recent call last):
  File "/home/desiree/miniconda3/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/desiree/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/process_data.py", line 522, in entrypoint
    tyro.cli(Commands).main()
  File "/home/desiree/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 112, in main
    self._run_colmap()
  File "/home/desiree/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py", line 204, in _run_colmap
    colmap_utils.run_colmap(
  File "/home/desiree/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/colmap_utils.py", line 116, in run_colmap
    colmap_version = get_colmap_version(colmap_cmd)
  File "/home/desiree/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/colmap_utils.py", line 61, in get_colmap_version
    return float(version)
ValueError: could not convert string to float: '3.9.1'

**Comment by Vinayrevanuru1** [comment]
@desifisker ,  I too have faced the same problem  as you.  if you are still looking for solution to this.
 you have to go to home/desiree/miniconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/colmap_utils.py folder and chnage the line that says  **return float(line.split(" ")[1])** to   **return line.split(" ")[1]**  it should work fine.

**Comment by vjgpt** [comment]
fix for ns-process-data failing with below error

vi /home/ec2-user/miniconda3/envs/3dgs/lib/python3.8/site-packages/scripts/process_data.py
https://github.com/nerfstudio-project/nerfstudio/issues/2100#issuecomment-1919258519
  File "/home/ec2-user/miniconda3/envs/3dgs/lib/python3.8/site-packages/scripts/process_data.py", line 411, in run_colmap
  

    if colmap_version >= 3.7:
TypeError: '>=' not supported between instances of 'str' and 'float'

Replace the `get_colmap_version` function with below code in process_data


```
import re


def get_colmap_version(default_version: float = 3.8) -> float:
    """Returns the version of COLMAP as a float.

    This function assumes that colmap returns a version string of the form
    "COLMAP 3.8 ..." which may not be true for all versions of COLMAP.

    Args:
        default_version: Default version to return if COLMAP version can't be determined.

    Returns:
        The version of COLMAP as a float.
    """
    output = run_command("colmap", verbose=False)
    assert output is not None
    for line in output.split("\n"):
        if line.startswith("COLMAP"):
            version_str = line.split(" ")[1]
            return parse_version(version_str)
    CONSOLE.print(f"[bold red]Could not find COLMAP version. Using default {default_version}")
    return default_version

def parse_version(version_str: str) -> float:
    """Parses a version string into a float.

    Args:
        version_str: Version string to parse.

    Returns:
        The version as a float.
    """
    match = re.match(r'(\d+)\.(\d+)', version_str)
    if match:
        major, minor = map(int, match.groups())
        return major + minor / 10  # Convert to float, e.g., 3.10 -> 3.1
    return 0  # Return 0 if parsing fails
 ```
