### ISSUE TITLE
Export of generfacto trained models raises AssertionError

### ISSUE THREAD

**Issue by Zunhammer** [nerfstudio-project/nerfstudio#2121]
**Describe the bug**
Training of generfacto works fine using the stablediffusion model and looks visually promising in the viewer. After training is finished,  the geometry exports are not working and raise an AssertionError (tried poisson and pointcloud). Checkpoint seems to be loaded fine though.

**To Reproduce**
1. Train a generafto model (using stabeldiffusion): ```ns-train generfacto --prompt "a high quality photo of a pineapple"```
2. In the viewer click on export -> mesh -> setup your desired settings and copy the command.
3. Paste the command in the terminal to export: ```ns-export poisson --load-config outputs/generfacto/2023-06-23_075243/config.yml --output-dir exports/mesh/ --target-num-faces 500000 --num-pixels-per-side 2048 --normal-method open3d --normal-output-name normals --num-points 1000000 --remove-outliers True --use-bounding-box True --bounding-box-min -1 -1 -1 --bounding-box-max 1 1 1```
I also tried model_output for normals.
4. AssertionError is raised

**Expected behavior**
Successful export of the mesh or pointcloud of the model.

**Screenshots**
![image](https://github.com/nerfstudio-project/nerfstudio/assets/18286310/59a79374-119b-496a-93a3-49d5bd933720)

Using nerfstudio version 0.3.2.

**Comment by Zunhammer** [comment]
Just checked, it is expecting a VanillaDataManagerConfig object but the actual type is nerfstudio.data.datamanagers.random_cameras_datamanager.RandomCamerasDataManager. Anyone knows why this happens?

**Comment by terrancewang** [comment]
> Just checked, it is expecting a VanillaDataManager object but the actual type is nerfstudio.data.datamanagers.random_cameras_datamanager.RandomCamerasDataManager. Anyone knows why this happens?

looking into it rn, will submit a pr to fix later tonight!

**Comment by Zunhammer** [comment]
Thanks, I found that the VanillaDataManager is actually a RandomCamerasDataManager, so importing this one an replacing it in line 288 fixes this problem. However, the RandomCamerasDataManager doesn't have a train_pixel_sampler. I commented out lines 289 and 290 and was able to export a point cloud and mesh as seen below with some weird effects/errors.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/18286310/e59145e5-1899-47b0-8d20-98b86b99c53c)

**Comment by terrancewang** [comment]
> Thanks, I found that the VanillaDataManager is actually a RandomCamerasDataManager, so importing this one an replacing it in line 288 fixes this problem. However, the RandomCamerasDataManager doesn't have a train_pixel_sampler. I commented out lines 289 and 290 and was able to export a point cloud and mesh as seen below with some weird effects/errors. ![image](https://user-images.githubusercontent.com/18286310/248391348-e59145e5-1899-47b0-8d20-98b86b99c53c.png)

I believe this is might because of the horizontal camera warmup in the randomcamerasdatamanager. if you set it to 0 it might fix this. I'll have time later today to fix and push!

**Comment by terrancewang** [comment]
> Thanks, I found that the VanillaDataManager is actually a RandomCamerasDataManager, so importing this one an replacing it in line 288 fixes this problem. However, the RandomCamerasDataManager doesn't have a train_pixel_sampler. I commented out lines 289 and 290 and was able to export a point cloud and mesh as seen below with some weird effects/errors. ![image](https://user-images.githubusercontent.com/18286310/248391348-e59145e5-1899-47b0-8d20-98b86b99c53c.png)

actually I think this will involve writing a new pixel sampler for the random cameras datamanager, so might take me a bit longer, but I'll work on fixing this soon.

**Comment by dberga** [comment]
Also happens with `splatfacto`, will need also to put `FullImageDatamanager` in the assertion, right?

**Comment by dberga** [comment]
Fixed it myself, check the new `exporter.py` here:

https://github.com/dberga/nerfstudio/commit/62603959136511c246475ee2f876317637526947

**Comment by dberga** [comment]
Should you pull-request this @Zunhammer ?

**Comment by Zunhammer** [comment]
@dberga Feel free to do it, thanks for asking and for your efforts :)

**Comment by dberga** [comment]
Just added the pull request here
https://github.com/nerfstudio-project/nerfstudio/pull/3065

**Comment by dberga** [comment]
It has been merged here https://github.com/nerfstudio-project/nerfstudio/pull/3065, you can close the issue

**Comment by Zunhammer** [comment]
Thanks for solving.
