### ISSUE TITLE
How to debug nerfstudio?

### ISSUE THREAD

**Issue by city19992** [nerfstudio-project/nerfstudio#2140]
**Thank you for the nerfstudio, a really nice job. I hope to use and improve it. However, when I started to debug your project using VScode, some problems happened.**

**Problem**
1. I tried to debug process_data.py with Vscode because I want to know what happens when running nerfstudio/process_data.py in detail. but I can not step into some programs like: https://github.com/nerfstudio-project/nerfstudio/blob/d78af5b5699cb343cb46b5163d464e455524040f/nerfstudio/scripts/process_data.py#L408

This will prevent me from understanding and modifying this code. 

2. After modifying the codes like this:
```
class ImagesToNerfstudioDataset(ColmapConverterToNerfstudioDataset):
    def main(self) -> None:
        print('Images To Nerfstudio Dataset')
        ......
```
when debugging **process_data.py**, the console can not print this string. However, when running by **ns-process-data**, the program can indicate this string on the console. I wonder why.

**To Reproduce**
Steps to reproduce problem one:
1. Open and configure the *launch.json* file in VScode.
2. Set a break out point at  ```tyro.cli(Commands).main()```.
3. Start debug **process_data.py** and the program stops at ```tyro.cli(Commands).main()```.
4. Click *step into*, and the program starts to copy images and downscale them but not just run one step.

**Expected reply**
For problem one:
Could you please tell me why this happened and how to debug **process_data.py** with VScode?
I hope the program just runs one step and stops so that I can know what is the next step and understand how the program work, which will further help me modify codes.
Or, maybe you could also give me some advice about debugging,

For problem two:
Could you please tell me why and how to deal with it?

**Comment by city19992** [comment]
After a period of use, I tried to print the information I was interested in and tried to modify it. When I tried to modify the pipeline, I could use the debug function in VScode. Therefore, there is no problem for me to read and modify the codes.

**Comment by tan-tao11** [comment]
Hi! I'm also trying to modify the pipeline. Could you please tell me more details about how to debug it using VScode?

**Comment by city19992** [comment]
FYI: https://code.visualstudio.com/docs/python/debugging
By following the information here, it is easy to debug using VScode.
