### ISSUE TITLE
Uploaded video successfully but the cell is still running

### ISSUE THREAD

**Issue by hyp3rs3a** [nerfstudio-project/nerfstudio#2153]
<img width="1444" alt="Screenshot 2023-06-30 at 22 17 33" src="https://github.com/nerfstudio-project/nerfstudio/assets/137992775/e182fb76-f172-4b83-bd6d-5253a112b155">

The video has finished converting successfully but the cell is still running and has been doing for a while. Should I be doing something else to complete the cell run and move on to the next? Do I need to input a key into the red box to the right?

Thanks

**Comment by tancik** [comment]
Keep waiting, that step can take over 15min.

**Comment by hyp3rs3a** [comment]
Thanks! All sorted
