### ISSUE TITLE
Text2NeRF implementation

### ISSUE THREAD

**Issue by vgrau98** [nerfstudio-project/nerfstudio#2155]
I've seen that some generative models coupled with NeRF are already implemented with generfacto, notably DreamFusion. Text2NeRF has recently been released: https://eckertzhang.github.io/Text2NeRF.github.io/
Are there any plans to implement it?

**Comment by tancik** [comment]
We have no currently plans to implement it, but if anyone does, we would be happy to include it in the docs. Instructions on registering 3rd party methods can be found [here](https://docs.nerf.studio/en/latest/developer_guides/new_methods.html#registering-custom-dataparser-with-nerfstudio).
