### ISSUE TITLE
Make default implementation tcnn

### ISSUE THREAD

**Issue by gtangg12** [nerfstudio-project/nerfstudio#2158]
Hi, can you make all the implementation: [tcnn, torch] arguments default to tcnn (e.g. HashMLPDensityField and nerfacto are not)? Upgraded to the latest nerfstudio and spent quite a while trying to figure out why my code was 4x slower.

**Comment by tancik** [comment]
Yes indeed. Although it seems like the default in nerfacto is already tcnn, do you mind linking where you are referring to?

**Comment by brentyi** [comment]
Maybe the instant-ngp implementation? https://github.com/nerfstudio-project/nerfstudio/blob/6fc588bda3d14d01e824947d67e2e1143a30fa58/nerfstudio/models/instant_ngp.py#L111-L118

**Comment by gtangg12** [comment]
https://github.com/nerfstudio-project/nerfstudio/blob/d6bb8bd8e5d278634b5fa73c18ae8bcc0daad986/nerfstudio/fields/density_fields.py#L34

This one-- might be a tricky one for others who are also upgrading
