### ISSUE TITLE
关于训练数据中的文件 transform.json的来源

### ISSUE THREAD

**Issue by yoker5262** [nerfstudio-project/nerfstudio#2173]
Using your own data, after processing with colmap, error is reported during training because there is no transform.json file. How is this file generated?

**Comment by tancik** [comment]
Are you using `ns-process-data`? Or just colmap alone?

**Comment by yoker5262** [comment]
The colmap approach alone is more helpful to me. It also tells me that ns-process-data is better

**Comment by tancik** [comment]
Support for using just colmap was added a week ago so you will need the latest version on github - https://github.com/nerfstudio-project/nerfstudio/pull/2115 
And add `colmap` to the end of you training command so that it doesn't using the `nerfstudio-data` dataparser.

**Comment by yoker5262** [comment]
ok ,So I git the latest nerfstudio code using colmap-dataparser.py for my current needs? I want to use my own data to generate nerfstudio training data, including transforms.json files

**Comment by yoker5262** [comment]
colmap_dataparser.py   How should I use this file?
