### ISSUE TITLE
Error after run ns-process-data 

### ISSUE THREAD

**Issue by kkennethwu** [nerfstudio-project/nerfstudio#2179]
Hi,

I  ran `ns-process-data images --data /images/ --output-dir images_with_depth/`
and `ns-process-data images --data /images/  --use-sfm-depth  --output-dir images_with_depth/`

Then this core dump error happen on both situations.
I ran this on cuda/11.8 RTX4090. 

> ??????????????????????????????????????????????  ?? ?? ?? ERROR ?? ?? ??  ???????????????????????????????????????????????
> Error running command: colmap feature_extractor --database_path devPhase_01_nerfstudio_with_depth/colmap/database.db 
> --image_path devPhase_01_nerfstudio_with_depth/images --ImageReader.single_camera 1 --ImageReader.camera_model OPENCV 
> --SiftExtraction.use_gpu 1
> ????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
> QObject::moveToThread: Current thread (0x55ab6b85b070) is not the object's thread (0x55ab6b867670).
> Cannot move to target thread (0x55ab6b85b070)
> 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in 
> "/home/kkennethwu/anaconda3/envs/nerfstudio_iccv/lib/python3.8/site-packages/cv2/qt/plugins" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may 
> fix this problem.
> 
> Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, 
> wayland-xcomposite-egl, wayland-xcomposite-glx.
> 
> *** Aborted at 1688578971 (unix time) try "date -d @1688578971" if you are using GNU date ***
> PC: @                0x0 (unknown)
> *** SIGABRT (@0x3ea0003795b) received by PID 227675 (TID 0x7f0f5a22e080) from PID 227675; stack trace: ***
>     @     0x7f0f5e1bd046 (unknown)
>     @     0x7f0f5be42520 (unknown)
>     @     0x7f0f5be96a7c pthread_kill
>     @     0x7f0f5be42476 raise
>     @     0x7f0f5be287f3 abort
>     @     0x7f0f5c690ba3 QMessageLogger::fatal()
>     @     0x7f0f5cd38713 QGuiApplicationPrivate::createPlatformIntegration()
>     @     0x7f0f5cd38c08 QGuiApplicationPrivate::createEventDispatcher()
>     @     0x7f0f5c8c0b17 QCoreApplicationPrivate::init()
>     @     0x7f0f5cd3bb70 QGuiApplicationPrivate::init()
>     @     0x7f0f5d571ced QApplicationPrivate::init()
>     @     0x55ab696533dd colmap::RunFeatureExtractor()
>     @     0x55ab69645499 main
>     @     0x7f0f5be29d90 (unknown)
>     @     0x7f0f5be29e40 __libc_start_main
>     @     0x55ab696483e5 _start
> Aborted (core dumped)
>

**Comment by xuyaojian123** [comment]
I have the same problem.  Don't know how to solve it
![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/1b1dab7a-2af2-4957-84e3-a7298a1cb070)

**Comment by slpmee** [comment]
Hi,
Try this command before running it.

export DISPLAY=:0.0

**Comment by kkennethwu** [comment]
> Hi, Try this command before running it.
> 
> export DISPLAY=:0.0

HI, I've tried it but it didn't work. 
However, when I use cpu to run it it works.
`ns-process-data images --data /images/  --use-sfm-depth  --output-dir images_with_depth/ --no-gpu`

**Comment by tancik** [comment]
This is an issue with the colmap install with gpu support. Of you need the gpu support, I would try installing colmap from source.

**Comment by remmel** [comment]
````
pip uninstall opencv-python
pip install opencv-python-headless
```

Fixes the problem

For me this is not related with colmap, and you probably don't get the error anymore with `--no-gpu` because you don't use opencv the same way. I think that the error is link with opencv which use Qt which has some library missing; that's way I unisntall opencv-python to use opencv-python-headless
