### ISSUE TITLE
Why is the generated mesh always located in a cube?

### ISSUE THREAD

**Issue by Cat-Lover-Yes** [nerfstudio-project/nerfstudio#2181]
Why is the generated mesh always located in a cube?I used my own data set, provided a pose estimated by colmap, and provided a depth image taken by a depth camera when I used depth-nerfacto.But the mesh I generated was always inside a cube, which made part of the scene at the top confusing.

Can I use a parameter to control the range and size of the generated mesh?

**Comment by tancik** [comment]
Yep, the full list of arguments are [here](https://docs.nerf.studio/en/latest/reference/cli/ns_export.html).
Use `--bounding-box-min` and `--bounding-box-max`.
