### ISSUE TITLE
Can I convert the camera pose obtained from ORB-SLAM into a coordinate system format under colmap for use in nerfstudio?

### ISSUE THREAD

**Issue by Cat-Lover-Yes** [nerfstudio-project/nerfstudio#2182]
Can I convert the camera pose obtained from ORB-SLAM into a coordinate system format under colmap for use in nerfstudio?

I used ORB-SLAM to estimate the camera pose of my own data set, using the following steps:

1. Save my input picture in the format of data set, and use RGB-D to track and calculate

2, use System: : SaveKeyFrameTrajectoryTUM () function to generate the key frame camera position

3. Switch poses according to the issue's suggestions https://github.com/colmap/colmap/issues/1184

I then computed the mesh by generating transforms.json from the source content of nerfstudio.

Unfortunately, it turns out that pose was miscalculated.

I would like to ask you, has anyone encountered this problem?How do I switch poses?

**Comment by Cat-Lover-Yes** [comment]
`def orb2colmap1(w2c):
    # c2w = np.linalg.inv(w2c)
    c2w = w2c
    R_o = c2w[:3, :3]
    T_o = c2w[:3, 3]
    R_o = np.transpose(R_o)
    
    T_c = T_o
    # Mirrors the y - and z - coordinates
    T_c[1] *= -1.0
    T_c[2] *= -1.0
    R_c = R_o
    # Changes the sign of some entries.
    R_c[0, 1] *= -1.0
    R_c[0, 2] *= -1.0
    R_c[1, 0] *= -1.0
    R_c[2, 0] *= -1.0
    c2w[:3, :3] = R_c
    c2w[:3, 3] = T_c
    return np.linalg.inv(c2w)


def orb2colmap2(c2w):
    R_o = c2w[:3, :3]
    t_o = c2w[:3, 3]
    R_c = np.transpose(R_o)
    t_c = -R_c.dot(t_o)
    c2w[:3, :3] = R_c
    c2w[:3, 3] = t_c
    return np.linalg.inv(c2w)


def orb2colmap3(c2w):
    ROT_COLMAP_TO_NORMAL = np.diag([1, -1, -1])
    R_o = c2w[:3, :3]
    t_o = c2w[:3, 3]
    R_c = ROT_COLMAP_TO_NORMAL @ R_o @ ROT_COLMAP_TO_NORMAL.T
    t_c = ROT_COLMAP_TO_NORMAL @ t_o
    c2w[:3, :3] = R_c
    c2w[:3, 3] = t_c
    return np.linalg.inv(c2w)


def convertMatrix(c2w):
    # Convert from COLMAP's camera coordinate system (OpenCV) to ours (OpenGL)
    c2w[0:3, 1:3] *= -1
    c2w = c2w[np.array([1, 0, 2, 3]), :]
    c2w[2, :] *= -1
    return c2w`

**Comment by Cat-Lover-Yes** [comment]
def orb2colmap1(w2c):
    # c2w = np.linalg.inv(w2c)
    c2w = w2c
    R_o = c2w[:3, :3]
    T_o = c2w[:3, 3]
    R_o = np.transpose(R_o)
    
    T_c = T_o
    # Mirrors the y - and z - coordinates
    T_c[1] *= -1.0
    T_c[2] *= -1.0
    R_c = R_o
    # Changes the sign of some entries.
    R_c[0, 1] *= -1.0
    R_c[0, 2] *= -1.0
    R_c[1, 0] *= -1.0
    R_c[2, 0] *= -1.0
    c2w[:3, :3] = R_c
    c2w[:3, 3] = T_c
    return np.linalg.inv(c2w)


def orb2colmap2(c2w):
    R_o = c2w[:3, :3]
    t_o = c2w[:3, 3]
    R_c = np.transpose(R_o)
    t_c = -R_c.dot(t_o)
    c2w[:3, :3] = R_c
    c2w[:3, 3] = t_c
    return np.linalg.inv(c2w)


def orb2colmap3(c2w):
    ROT_COLMAP_TO_NORMAL = np.diag([1, -1, -1])
    R_o = c2w[:3, :3]
    t_o = c2w[:3, 3]
    R_c = ROT_COLMAP_TO_NORMAL @ R_o @ ROT_COLMAP_TO_NORMAL.T
    t_c = ROT_COLMAP_TO_NORMAL @ t_o
    c2w[:3, :3] = R_c
    c2w[:3, 3] = t_c
    return np.linalg.inv(c2w)


def convertMatrix(c2w):
    # Convert from COLMAP's camera coordinate system (OpenCV) to ours (OpenGL)
    c2w[0:3, 1:3] *= -1
    c2w = c2w[np.array([1, 0, 2, 3]), :]
    c2w[2, :] *= -1
    return c2w

**Comment by YifuTao** [comment]
One potential issue when passing pose is the convention. `transforms.json` used in NeRF assumes a Computer Graphics convention (x right, y up and z backwards), while COLMAP itself uses Computer Vision convention (x right, y down and z up).

I would visualise the poses to check if the final output is following the NeRF pose convention. If pose convention is right, the issue is probably the accuracy of the pose computed by COLMAP/SLAM.
