### ISSUE TITLE
how to export the render model

### ISSUE THREAD

**Issue by uuu686** [nerfstudio-project/nerfstudio#2185]
hello, I have a question and please give me some suggestion.
I try to train my data use the nerfacto, and I can export the point cloud and the mesh. But both of those look different from the Web viewer. 
Is the point cloud and mess have render ? And how can I export the render 3D model, and I need to put the 3D model to other software(like meshlab), the point cloud and mesh don't look real enough.
Thanks.

**Comment by tancik** [comment]
Any exported mesh or pointcloud will not look the same quality as the web viewer (NeRF). The only option to get the full quality (or better) of the web-viewer is to render out a video.

**Comment by uuu686** [comment]
Thanks for your apply.
And I want to generate a high quality(more real) mess or ply,  is there any solution can solve my problem?

**Comment by tancik** [comment]
Not currently with nerfstudio. Hopefully this functionality will come...

**Comment by danish-javaid01** [comment]
did you find any solution?
