### ISSUE TITLE
ns-process-data command stuck!

### ISSUE THREAD

**Issue by xuyaojian123** [nerfstudio-project/nerfstudio#2188]
I install colmap3.9 from source.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/906a3141-03dd-4df8-8784-1483eead4f3b)

Why am I stuck executing `ns-process-data images --data /home/xuyaojian/myimages/1 --output-dir /home/xuyaojian/own1` command? Thank you！

![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/6c78a81c-a6e5-4f82-b897-19a3a9c5f6c9)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/36ac3b4c-2ed7-4ab6-9d00-c4b496528537)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/5ab03970-89d0-43f9-ad89-24a24261b5ab)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/54a7dadf-d822-4352-8f2a-f07977998f61)

**Comment by xuyaojian123** [comment]
This problem is solved. Because I forget to connect to the Internet. But there's a new problem!

![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/87439af8-db0b-4e8f-ae32-12845981ed30)

**Comment by xuyaojian123** [comment]
This problem is solved. can see [https://github.com/nerfstudio-project/nerfstudio/issues/2078](url)
![af7d405821711ff351e7b7e34ce7aa9](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/79e254b7-a325-4578-83ae-15017bd051d4)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/51220835/1238d9c6-6adc-4342-901b-f2437a187df9)

**Comment by iszihan** [comment]
How did you solve it? The linked issue doesn't provide the solution. I also have the same error with synthetic dataset I rendered.

**Comment by tudorjnu** [comment]
Any update on this?

**Comment by camolina2** [comment]
I also have this problem :(

**Comment by rexainn** [comment]
same problem
