### ISSUE TITLE
rendered views mismatch with input images

### ISSUE THREAD

**Issue by leixiao-ubc** [nerfstudio-project/nerfstudio#2191]
Hi there,

Thanks for this awesome repo. I would like to get your help on the following issue.

I trained "_nerfacto-big_" on my own dataset with colmap and got descent quality reconstruction (with _nerfstudio-0.2.2_). In tensorboard visualization, the rendered images well align with the evaluation images. However, when I use "_ns-render --load-config config.yml --traj interpolate --interpolation-steps 1 --output-format images --output-path renders/output_" to render images, there are small but noticeable shifts in terms of camera poses between the rendered images and corresponding ground-truth images. 

Note that I've already set "_--pipeline.datamanager.camera_optimizer.mode off_" during training.

**Comment by vijendra1125** [comment]
@leixiao-ubc Were you able to figure out why did you observe the reported problem. 
I also see small shift in the rendered images in compare to original images when I use ns-eval and save the rendered images for eval set. I am keeping camera optimization enabled though.

**Comment by halo2718** [comment]
@leixiao-ubc Would you please tell me how you solved this problem? Thank you very much.

**Comment by Schoibi** [comment]
@leixiao-ubc I am currently facing the same issue and would apprectiate it, if you could share how you solved this issue. Please, and Thank you in advance!
