### ISSUE TITLE
Docker default user

### ISSUE THREAD

**Issue by linukc** [nerfstudio-project/nerfstudio#2211]
**Is your feature request related to a problem? Please describe.**
User UID does not always [equal to 1000](https://github.com/nerfstudio-project/nerfstudio/blob/cebe787bedffd4966fdcb067682da64e168b5565/Dockerfile#L102) (for example if you share a server with your colleagues). This leads to annoying permission denied errors when you mount your folder inside nerfstudio docker container and work with files. 

**Describe the solution you'd like**
Add build arguments for user UID (GID).

**Additional context**
Here is an example of how i [solved](https://gist.github.com/linukc/f793b9aa572c64096b5ef4d211870a84) this problem. It would be nice if we can potentially add this feature to the official docker image.

**Comment by tancik** [comment]
Sounds reasonable. If you are up for it, can you create a PR?

**Comment by linukc** [comment]
#2334
