### ISSUE TITLE
AttributeError: 'LERFDataManager' object has no attribute 'fixed_indices_eval_dataloader'

### ISSUE THREAD

**Issue by yoker5262** [nerfstudio-project/nerfstudio#2215]
(alg) k8s@zjm-sz8tney2-qlxvm:~/nerfstudio$ ns-eval --load-config /opt/image-synthesis/algorithm_manage/model_zoo/test_video/lerf/2023-07-13_112928/config.yml --output-path /opt/image-synthesis/eval_output/test_video/lerf.json
[14:26:16] Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:324
Setting up training dataset...
Caching all 15 images.
Using cache found in /home/ubuntu/.cache/torch/hub/facebookresearch_dino_main
Scales: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:22<00:00,  3.19s/it]
/home/ubuntu/miniconda3/envs/alg/lib/python3.10/site-packages/torchmetrics/utilities/prints.py:61: FutureWarning: Importing `PeakSignalNoiseRatio` from `torchmetrics` was deprecated and will be removed in 2.0. Import `PeakSignalNoiseRatio` from `torchmetrics.image` instead.
  _future_warning(
Loading latest checkpoint from load_dir
✅ Done loading checkpoint from 
/opt/image-synthesis/algorithm_manage/model_zoo/test_video/lerf/2023-07-13_112928/nerfstudio_models/step-000028000.ckpt
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ubuntu/miniconda3/envs/alg/bin/ns-eval:8 in <module>                                       │
│                                                                                                  │
│   5 from nerfstudio.scripts.eval import entrypoint                                               │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(entrypoint())                                                                   │
│   9                                                                                              │
│                                                                                                  │
│ /home/ubuntu/miniconda3/envs/alg/lib/python3.10/site-packages/nerfstudio/scripts/eval.py:61 in   │
│ entrypoint                                                                                       │
│                                                                                                  │
│   58 def entrypoint():                                                                           │
│   59 │   """Entrypoint for use with pyproject scripts."""                                        │
│   60 │   tyro.extras.set_accent_color("bright_yellow")                                           │
│ ❱ 61 │   tyro.cli(ComputePSNR).main()                                                            │
│   62                                                                                             │
│   63                                                                                             │
│   64 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /home/ubuntu/miniconda3/envs/alg/lib/python3.10/site-packages/nerfstudio/scripts/eval.py:44 in   │
│ main                                                                                             │
│                                                                                                  │
│   41 │   │   """Main function."""                                                                │
│   42 │   │   config, pipeline, checkpoint_path, _ = eval_setup(self.load_config)                 │
│   43 │   │   assert self.output_path.suffix == ".json"                                           │
│ ❱ 44 │   │   metrics_dict = pipeline.get_average_eval_image_metrics()                            │
│   45 │   │   self.output_path.parent.mkdir(parents=True, exist_ok=True)                          │
│   46 │   │   # Get the output and define the names to save to                                    │
│   47 │   │   benchmark_info = {                                                                  │
│                                                                                                  │
│ /home/ubuntu/miniconda3/envs/alg/lib/python3.10/site-packages/nerfstudio/utils/profiler.py:127   │
│ in inner                                                                                         │
│                                                                                                  │
│   124 │   │   def inner(*args, **kwargs):                                                        │
│   125 │   │   │   self._function_call_args = (args, kwargs)                                      │
│   126 │   │   │   with self:                                                                     │
│ ❱ 127 │   │   │   │   out = func(*args, **kwargs)                                                │
│   128 │   │   │   self._function_call_args = None                                                │
│   129 │   │   │   return out                                                                     │
│   130                                                                                            │
│                                                                                                  │
│ /home/ubuntu/miniconda3/envs/alg/lib/python3.10/site-packages/nerfstudio/pipelines/base_pipeline │
│ .py:351 in get_average_eval_image_metrics                                                        │
│                                                                                                  │
│   348 │   │   self.eval()                                                                        │
│   349 │   │   metrics_dict_list = []                                                             │
│   350 │   │   assert isinstance(self.datamanager, VanillaDataManager)                            │
│ ❱ 351 │   │   num_images = len(self.datamanager.fixed_indices_eval_dataloader)                   │
│   352 │   │   with Progress(                                                                     │
│   353 │   │   │   TextColumn("[progress.description]{task.description}"),                        │
│   354 │   │   │   BarColumn(),                                                                   │
│                                                                                                  │
│ /home/ubuntu/miniconda3/envs/alg/lib/python3.10/site-packages/torch/nn/modules/module.py:1614 in │
│ __getattr__                                                                                      │
│                                                                                                  │
│   1611 │   │   │   modules = self.__dict__['_modules']                                           │
│   1612 │   │   │   if name in modules:                                                           │
│   1613 │   │   │   │   return modules[name]                                                      │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1615 │   │   │   type(self).__name__, name))                                                   │
│   1616 │                                                                                         │
│   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by yoker5262** [comment]
Updated the latest nerfstudio code to show that eval with lerf is missing this parameter.What does this parameter mean

**Comment by yoker5262** [comment]
hello ,Can you help me solve this problem?Thank you!

**Comment by yoker5262** [comment]
hello,Why git the latest code and get error messages instead

**Comment by ladvu** [comment]
I encountered the same error when using dn_splatter. I find a way around:

In /path/to/nerfstudio/viewer/utils.py:
```python
#before
    obj_props = [(k, getattr(obj, k)) for k in dir(obj) if not isinstance(getattr(type(obj), k, None), cached_property)]
#after
    obj_props = [(k, getattr(obj, k, None)) for k in dir(obj) if not isinstance(getattr(type(obj), k, None), cached_property)]
```
Hope this helpful.
