### ISSUE TITLE
Registering custom dataparser

### ISSUE THREAD

**Issue by samiragarwala** [nerfstudio-project/nerfstudio#2219]
Hi! Thank you for the great project! I was trying to register a custom dataparser and despite the package being installed, I don't see the data parser being registered in nerfstudio. I checked the package installation information in the egg-info directory and see that the dataparser is registered as an entry point in the following manner:

```
[nerfstudio.dataparser_configs]
my-data = myproject.config:my_dataparser
```
Thank you and I would appreciate any help!

**Comment by tancik** [comment]
Can you try running `pip install -e .` in the nerfstudio folder.

**Comment by samiragarwala** [comment]
Thank you for the answer! That fixed the issue!
