### ISSUE TITLE
metashape xml file can't be read correctly

### ISSUE THREAD

**Issue by LemonZhong** [nerfstudio-project/nerfstudio#2225]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/89432570/b8484a6a-6dbc-4d9f-a237-899038274e07)
it is weired to occur this kind of problems. I have tried multiple ways but just can't solve it.

**Comment by LemonZhong** [comment]
my agisoft metashape version is 2.0.1 and my nerfstudio can be run on other projects

**Comment by LemonZhong** [comment]
why there is just 0 frame??

**Comment by Jordan-Pierce** [comment]
@LemonZhong can you please provide information on how you solved it?

**Comment by ariannaferraris** [comment]
> I have solved it, thanks.

How have you solved it? I'm also struggling with the same issue
