### ISSUE TITLE
cannot import "shift_directions_for_tcnn"

### ISSUE THREAD

**Issue by dberga** [nerfstudio-project/nerfstudio#2226]
Some modules such as kplanes-nerfstudio and nerfplayer import "shift_directions_for_tcnn" which was removed in latest versions of nerfstudio, giving the error `ImportError: cannot import name 'shift_directions_for_tcnn' from 'nerfstudio.fields.base_field'`

Should this function be included (even if deprecated) to avoid crashing when using other models that import it?

**Comment by xiazhi1** [comment]
> 

Hi, Same Bug for me when I trying to install nerfplayer , have you solved it? Looking forward to your reply! thanks!

**Comment by xiazhi1** [comment]
@dberga

**Comment by dberga** [comment]
I think it is because of deprecated code (either functions removed or put on another place). The only solution is to revert the version of your repo or either copy them back..

**Comment by dberga** [comment]
Apparently it was discussed in 

will need to change the import to "get_normalized_directions"?
https://docs.nerf.studio/en/latest/reference/api/fields.html#nerfstudio.fields.base_field.get_normalized_directions

in the official (updated) API shows which functions are and aren't in the repo
https://docs.nerf.studio/en/latest/reference/api/index.html

**Comment by xiazhi1** [comment]
> get_normalized_directions

Thanks a lot, It works for me !!!

**Comment by lsongx** [comment]
👍 just updated this in nerfplayer

**Comment by takatoyamada** [comment]
Hi! How is it going on this now??
I still found the error below when I tried to run `ns-train kplanes`
my nerfstudio version for the experiment is the newest of the latest main branch , which is `9b6010ea0d20e7ca2a68496bb33d6dcd03bf9b91`

```shell
Traceback (most recent call last):
  File "/home/user/.local/bin/ns-train", line 5, in <module>
    from nerfstudio.scripts.train import entrypoint
  File "/workspace/nerfstudio/scripts/train.py", line 62, in <module>
    from nerfstudio.configs.method_configs import AnnotatedBaseConfigUnion
  File "/workspace/nerfstudio/configs/method_configs.py", line 607, in <module>
    all_methods, all_descriptions = merge_methods(all_methods, all_descriptions, *discover_methods())
  File "/workspace/nerfstudio/plugins/registry.py", line 43, in discover_methods
    spec = discovered_entry_points[name].load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/user/.local/lib/python3.10/site-packages/kplanes/kplanes_configs.py", line 13, in <module>
    from .kplanes import KPlanesModelConfig
  File "/home/user/.local/lib/python3.10/site-packages/kplanes/kplanes.py", line 57, in <module>
    from .kplanes_field import KPlanesDensityField, KPlanesField
  File "/home/user/.local/lib/python3.10/site-packages/kplanes/kplanes_field.py", line 33, in <module>
    from nerfstudio.fields.base_field import Field, shift_directions_for_tcnn
ImportError: cannot import name 'shift_directions_for_tcnn' from 'nerfstudio.fields.base_field' (/workspace/nerfstudio/fields/base_field.py)
```

**Comment by Freeverc** [comment]
It appears at commit 3dd162aae8ae7c166928e1f02bf97e7febe3a18e, 2023.10.19.
