### ISSUE TITLE
Is multi-GPU available during colmap's ns-process-data?

### ISSUE THREAD

**Issue by MrDavidYu** [nerfstudio-project/nerfstudio#2228]
According to the nerfstudio [documentation ](https://docs.nerf.studio/en/latest/reference/cli/ns_process_data.html), ns-process-data provides an option for GPU usage, but my understanding is this is limited to either `--gpu` or `--nogpu`.

Is it possible to provide an interface to specify the number of GPUs? Similar to how we can specify the parameter `--machine.num-gpus n` in `ns-train`?

**Comment by tancik** [comment]
That is unfortunately not supported.
