### ISSUE TITLE
when i traning my model how can i quit and error- export mesh

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2238]
how can i quit to write code  like export mesh 
when i started train, i can't write code
when i export mesh  FileNotFoundError: [Errno 2] No such file or directory: 'outputs\\fox_train\\nerfacto\\2023-07-17_212147\\config.yml'
but in my outputs folder there are fox_train\\nerfacto\\2023-07-17_212147\\config.yml'

**Comment by peta-peta** [comment]
I also have problems to use ns-export. So far I have not succeeded to export any mesh or pointcloud with nerfstudio. Can someone of you confirm that this is working and share the following information:

- System:
- Grafic card:
- CUDA Version:
- Nerfstudio version
- Open3d version

Cheers Peter

**Comment by REMvisual** [comment]
same issue, when i run the viewer it doesnt create a new config...
