### ISSUE TITLE
Tinycudann Hashtable Size Mismatch 

### ISSUE THREAD

**Issue by iszihan** [nerfstudio-project/nerfstudio#2241]
**Describe the bug**
I'm trying to export the hashtable in mlp_base used in training with tinycudann. The size of the param is 
`_model.field.mlp_base.0.tcnn_encoding.params
tensor([-0.1878,  2.0033, -1.8618,  ...,  0.7501,  2.0120,  1.2352])
torch.Size([12196240])`

The config for this hash grid is
```

 encoding_config = {
              "otype": "HashGrid",
              "n_levels": 16,
              "n_features_per_level": 2,
              "log2_hashmap_size": 19,
              "base_resolution": 16,
              "per_level_scale": np.exp((np.log(2048) - np.log(16)) / (16 - 1)),
          }
```
From my understanding of hashgrid, this hash map should have a size of 2^19 * 16 * 2 which is not 12196240. Would someone know why is the difference here?

**Comment by tancik** [comment]
The lower resolutions, ie 16x16x16 (4096), do not fully fill the hashmap (2^19), so they can be stored in less memory.

**Comment by iszihan** [comment]
Thank you for the reply! Is there a way to know the exact layout of this hashtable stored with tinycudann format?

If I don't count the last lowest resolution, it should still be 2^19 * 15 * 2 = 15728640 values, which is greater than 12196240. So I suppose the same thing applies to the last few resolutions -- is there a way to find out which resolutions are stored differently and how differently?

**Comment by tancik** [comment]
It would be something like: sum elements over each level, where the number of elements per level is `min(level_resolution^3, log2_hashmap_size^2))`

**Comment by iszihan** [comment]
With this formula, it counts up to 12131648.0, which is still off. :/

**Comment by tancik** [comment]
Not really sure then, maybe posting the question on https://github.com/NVlabs/tiny-cuda-nn/issues

**Comment by iszihan** [comment]
Thank you still!
