### ISSUE TITLE
Data preprocessing for 360 panorama image is failing

### ISSUE THREAD

**Issue by Akhila-ar** [nerfstudio-project/nerfstudio#2245]
**Describe the bug**
I want to train a nerf given input in the form of a 360 panorama image. I am trying to use the preprocessing support provided in nerfstudio for 360 panorama images (https://docs.nerf.studio/en/latest/quickstart/custom_dataset.html#data-equirectangular). But colmap pose estimation fails to do a sparse reconstruction.

**To Reproduce**
1. Using this 360 panorama image as input: 
<img width="1210" alt="Screenshot 2023-07-19 at 6 10 51 PM" src="https://github.com/nerfstudio-project/nerfstudio/assets/89100852/62da7292-1131-462c-bb8f-78edff5e0281">

2. Run this command to process the data:
    `ns-process-data images --camera-type equirectangular --images-per-equirect 14 --data <path_to_panorama_img> --output-dir <out_path>`

**Expected behavior**
preprocessing fails while running colmap with the error:
──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: colmap mapper --database_path data/360room/room4/output1/colmap/database.db --image_path 
data/360room/room4/output1/images --output_path data/360room/room4/output1/colmap/sparse 
--Mapper.ba_global_function_tolerance 1e-6
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ERROR: failed to create sparse model

**Questions**
1. Is this the expected format of input?
2. Is the preprocessing command (and the camera-type) correct for this input? 
3. Are there any hyperparameters I should experiment with?

**Comment by tancik** [comment]
How many panoramas do you have of the scene?

**Comment by Akhila-ar** [comment]
Just the one.

**Comment by tancik** [comment]
For NeRFs to work, you need viewpoint from multiple locations, a single panorama won't work. Ideally you have >50

**Comment by Akhila-ar** [comment]
Thank you, this information is very helpful.

If you don't mind, I'd like to ask a quick follow-up question. Is there a method to extract a mesh/nerf from single panorama?
