### ISSUE TITLE
How are camera poses found in transforms.json converted to the NeRF's frame of reference?

### ISSUE THREAD

**Issue by drags99** [nerfstudio-project/nerfstudio#2248]
I'm trying to render an image from a camera pose in the same coordinate system as the camera poses in transforms.json. I would appreciate help figuring out how camera poses are converted from the transforms.json to a NeRFs coordinate system.

**Comment by tancik** [comment]
The transformation parameters can be found in the output folder. They are called `dataparser_tranforms.json`.

**Comment by drags99** [comment]
Thank you!
