### ISSUE TITLE
Explanation of nerfacto/-big/-huge settings

### ISSUE THREAD

**Issue by MvWouden** [nerfstudio-project/nerfstudio#2249]
Going from nerfacto to nerfacto-big to nerfacto-huge, some setting tweaks do not seem intuitive.
I was wondering what the reasoning is for the following:

I will use the format for my explanation:
`parameter_name` : `nerfacto value` -> `nerfacto-big value` -> `nerfacto-huge value`

I would expect the changed parameters to increase from nerfacto to nerfacto-big to nerfacto-huge (big/bigger/biggest) like done for e.g.:
`max_res`: 2048 -> 4096 -> 8192

Instead, we find the following parameters changed like:
`appearance_embed_dim` : 32 -> 128 -> 32
`num_nerf_samples_per_ray` : 48 -> 128 -> 64

I would expect these nerfacto-huge parameters to be equal or larger than the nerfacto-big parameters, but instead they are smaller.
Why is this the case?

**Comment by qhdqhd** [comment]
mark

**Comment by kerrj** [comment]
Hm I don't think there's any particular reason for these, I think I just forgot to update nerfacto-big parameters after tuning nerfacto-huge and realizing that some didn't matter as much as I previously thought.
