### ISSUE TITLE
The problem of lerf algorithm in nerfstuido

### ISSUE THREAD

**Issue by yoker5262** [nerfstudio-project/nerfstudio#2253]
git clone nerfstudio code version 0.3.2

pip install nerfstudio == 0.3.2

Run the ns-eval command  ，error message ： AttributeError: "LERFDataManager" object has no attribute 'fix_indices_eval_dataloader'.

I want to know what caused this mistake.
I'm not modifying your code, I'm using the command line to run the script.

I hope you can respond to my question, even if there is no solution, or if you think the problem is too easy.

**Comment by yoker5262** [comment]
![0001](https://github.com/nerfstudio-project/nerfstudio/assets/103626455/145b1f51-1ff8-4e1d-ba09-49c1a7cc71ea)
![00002](https://github.com/nerfstudio-project/nerfstudio/assets/103626455/9e4dfd1d-f547-4003-856f-3a1ab0b74b9e)

**Comment by kerrj** [comment]
Hi! ns-eval isn't implemented inside LERF since ns-eval is for measuring PSNR/metrics which aren't really a relevant quantities for language, instead we just render everything in the viewer/ns-render. If you describe your end goal of what you're trying to do I could probably be more helpful.

**Comment by yoker5262** [comment]
Thank you very much for your reply to my message. The algorithm integrated in nerfstudio has a final evaluation index, {

"experiment_name": "video_large",

"method_name": "in2n",

"checkpoint":  "/opt/image-synthesis/algorithm_manage/model_zoo/video_large/in2n/2023-07-20_160958/nerfstudio_models/step-000014999.ckp t",

"results": {

"psnr": 11.093680381774902,

"ssim": 0.5761642456054688,

"lpips": 0.6939833164215088,

num_rays_per_sec": 593358.3125,

"fps": 0.6438350081443787

}

How can the lerf algorithm generate such a file?

**Comment by yoker5262** [comment]
It is similar to the evaluation index of lerf algorithm for this training model, and does not need to be the above file format.
