### ISSUE TITLE
Unable to Load Old NeRFacto Model using the Version it was Trained On

### ISSUE THREAD

**Issue by gn00217** [nerfstudio-project/nerfstudio#2263]
**Describe the bug**
I previously trained NeRFacto models using the project tagged at v0.3.0. When I use the same code to evaluate those models it flags an issue with loading the state dictionary due to unexpected parameters ("lpips.net.scaling_layer.shift" and "lpips.net.scaling_layer.scale").

**To Reproduce**
1. Clone the repo and checkout tag v0.30
2. Install NeRFStudio from source
3. Try and render out images using 'eval_setup' method, loading config from a model trained using v0.3.0

**Error**
File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for NerfactoModel:
	Unexpected key(s) in state_dict: "lpips.net.scaling_layer.shift", "lpips.net.scaling_layer.scale". 

**Additional context**
I have tried this with different minor versions of v0.3 that share the same issue.

**Comment by brentyi** [comment]
Maybe try older versions of `torchmetrics`? `pip install torchmetrics==0.11.4`

https://pypi.org/project/torchmetrics/#history

The `lpips` torch module is imported from there: https://github.com/nerfstudio-project/nerfstudio/blob/8682e481b16e4725681b95d9a449ee3cfe4a9e7f/nerfstudio/models/nerfacto.py#L29

Related: https://github.com/nerfstudio-project/nerfstudio/pull/2223

**Comment by gn00217** [comment]
@brentyi Thank you for your quick response, this worked perfectly!
