### ISSUE TITLE
Need help with CUDA OUT OF MEMORY ERROR

### ISSUE THREAD

**Issue by Shania-F** [nerfstudio-project/nerfstudio#2266]
**Describe the bug**
I've followed the setup instructions for Windows exactly as in the docs. The only difference I made was when when the building the nbody2022 version, I had to change cuda12.2 to cuda11.8 in the code. 
But when it comes to training a NeRF with the provided poster images data, I encounter the Cuda out of memory error. I've even run nvidia-smi in another terminal during training to check if my GPU is being used. 

**To Reproduce**
Running this in conda venv: -
```
ns-download-data nerfstudio --capture-name=poster
ns-train nerfacto --data data/nerfstudio/poster
```

**Screenshots**
<img width="568" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/101061656/24645dea-e038-46bd-87e4-534defef9232">

**Error Text**
It is a bit long...

> Caching all 204 images.
> Setting up evaluation dataset...
> Caching all 22 images.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> tiny-cuda-nn warning: FullyFusedMLP is not supported for the selected architecture 50. Falling back to CutlassMLP. For maximum performance, raise the target GPU architecture to 75+.
> C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torchmetrics\utilities\prints.py:61: FutureWarning: Importing `PeakSignalNoiseRatio` from `torchmetrics` was deprecated and will be removed in 2.0. Import `PeakSignalNoiseRatio` from `torchmetrics.image` instead.
>   _future_warning(
> ╭─────────────────────────────────────────── Viewer ───────────────────────────────────────────╮
> │        ╷                                                                                     │
> │   HTTP │ https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:7007   │
> │        ╵                                                                                     │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────╯
> [NOTE] Not running eval iterations since only viewer is enabled.
> Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
> No Nerfstudio checkpoint to load, so training from scratch.
> Disabled tensorboard/wandb event writers
> [10:34:47] Printing max of 10 lines. Set flag --logging.local-writer.max-log-size=0 to disable line        writer.py:408           wrapping.
> Step (% Done)       Train Iter (time)    ETA (time)
> --------------------------------------------------------------
> 0 (0.00%)           8 s, 727.996 ms      3 d, 0 h, 43 m, 59 s
> ----------------------------------------------------------------------------------------------------
> Viewer at: https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:7007
> Printing profiling stats, from longest to shortest duration in seconds
> Trainer.train_iteration: 4.8394
> VanillaPipeline.get_train_loss_dict: 4.0284
> Traceback (most recent call last):
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\Scripts\ns-train.exe\__main__.py", line 7, in <module>
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 261, in entrypoint
>     main(
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 246, in main
>     launch(
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 189, in launch
>     main_func(local_rank=0, world_size=world_size, config=config)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\scripts\train.py", line 100, in train_loop
>     trainer.train()
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 255, in train
>     loss, loss_dict, metrics_dict = self.train_iteration(step)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 127, in inner
>     out = func(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\engine\trainer.py", line 468, in train_iteration
>     _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\profiler.py", line 127, in inner
>     out = func(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\pipelines\base_pipeline.py", line 281, in get_train_loss_dict
>     model_outputs = self._model(ray_bundle)  # train distributed data parallel model if world_size > 1
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\base_model.py", line 142, in forward
>     return self.get_outputs(ray_bundle)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\models\nerfacto.py", line 277, in get_outputs
>     ray_samples, weights_list, ray_samples_list = self.proposal_sampler(ray_bundle, density_fns=self.density_fns)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\model_components\ray_samplers.py", line 50, in forward
>     return self.generate_ray_samples(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\model_components\ray_samplers.py", line 603, in generate_ray_samples
>     density = density_fns[i_level](ray_samples.frustums.get_positions())
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\fields\base_field.py", line 67, in density_fn
>     density, _ = self.get_density(ray_samples)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\fields\density_fields.py", line 105, in get_density
>     self.mlp_base(positions_flat).view(*ray_samples.frustums.shape, -1).to(positions)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
>     input = module(input)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\field_components\mlp.py", line 177, in forward
>     return self.tcnn_encoding(in_tensor)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\tinycudann\modules.py", line 186, in forward
>     output = _module_function.apply(
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\torch\autograd\function.py", line 506, in apply
>     return super().apply(*args, **kwargs)  # type: ignore[misc]
>   File "C:\Users\Shania\miniconda3\envs\nerfstudio\lib\site-packages\tinycudann\modules.py", line 98, in forward
>     native_ctx, output = native_tcnn_module.fwd(input, params)
> RuntimeError: C:/Users/Shania/AppData/Local/Temp/pip-req-build-gepsgbcu/include\tiny-cuda-nn/gpu_memory.h:592 cuMemSetAccess(m_base_address + m_size, n_bytes_to_allocate, &access_desc, 1) failed: CUDA_ERROR_OUT_OF_MEMORY
> 
>

**Comment by LemonZhong** [comment]
Your GPU memory  is not big enough. You can change your batch size or change to a more powerful GPU

**Comment by hariharan1412** [comment]
> Your GPU memory is not big enough. You can change your batch size or change to a more powerful GPU

could you please tell me how to change batch size ?

**Comment by LemonZhong** [comment]
it is very easy, you can read the code



发自我的iPhone


------------------ Original ------------------
From: hariharan141200 ***@***.***&gt;
Date: Sun,Nov 26,2023 8:18 PM
To: nerfstudio-project/nerfstudio ***@***.***&gt;
Cc: Ningze Zhong ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [nerfstudio-project/nerfstudio] Need help with CUDA OUT OF MEMORYERROR (Issue #2266)





  
Your GPU memory is not big enough. You can change your batch size or change to a more powerful GPU
  
could you please tell me how to change batch size ?
