### ISSUE TITLE
export pointcloud error

### ISSUE THREAD

**Issue by LemonZhong** [nerfstudio-project/nerfstudio#2269]
I have trained successfully about the model with nerfacto bulit with docker.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/89432570/176c6b35-feb4-47cd-a97a-a8bc58291669)
However ,when I try to export the pointcloud, there are some problems.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/89432570/a1fb512b-5e26-47ef-b7fb-c032a04556a7)
How can I solve this problem? Thank you soooooo much!

**Comment by MvWouden** [comment]
As is hinted in the warning, it tries to get the predicted normals from the model, but your model has not predicted the normals. 

You have two options:
1. You can extract the pointcloud with `ns-export pointcloud --normal-method open3d ...`.
2. You could train with `ns-train nerfacto --pipeline.model.predict-normals True ...` after which you could use the same `ns-export` command you initially used.

See https://docs.nerf.studio/en/latest/reference/cli/ns_export.html#pointcloud for more details

**Comment by LemonZhong** [comment]
Thanks, bro. I will try it.

**Comment by LemonZhong** [comment]
> As is hinted in the warning, it tries to get the predicted normals from the model, but your model has not predicted the normals.
> 
> You have two options:
> 
> 1. You can extract the pointcloud with `ns-export pointcloud --normal-method open3d ...`.
> 2. You could train with `ns-train nerfacto --pipeline.model.predict-normals True ...` after which you could use the same `ns-export` command you initially used.
> 
> See https://docs.nerf.studio/en/latest/reference/cli/ns_export.html#pointcloud for more details

It works, thanks.
