### ISSUE TITLE
How to rewrite the LERF Positives parameter in the nerfstudio viewer into the code implementation

### ISSUE THREAD

**Issue by yoker5262** [nerfstudio-project/nerfstudio#2275]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/103626455/2c50b6f6-da32-4cf2-9336-8ed7ef260b09)
Hello! Through the nerfstudio viewer, I can use the matching function of the lerf algorithm (shown in the figure).
I hope that I can do this in code, not in the pages of nerfstudio, which is the most important thing. For example, pass parameters as if you were implementing a method.
And I also hope I can render it like the video provided by your official website.
What should I do?
Thank you very much for your guidance.

**Comment by maturk** [comment]
In the lerf code, when you type something into the text box, the text is set as the self.positives variable in a callback here: [code](https://github.com/kerrj/lerf/blob/ee1e0a534326b2cd3bb74bcec72e17ef9ef53840/lerf/encoders/openclip_encoder.py#L79)

And then this is ran through the forward part of the network to get your embeddings here: [code](https://github.com/kerrj/lerf/blob/ee1e0a534326b2cd3bb74bcec72e17ef9ef53840/lerf/encoders/openclip_encoder.py#L54)

Hope this gives you some direction for your work. You could set the variable `self.positives = ["your chosen list of strings"]` if you want to hard code this into your project. 

Regarding the video, it is just a postprocessed video most likely made with blender or other software so you wont directly be able to recreate it. Good luck.

**Comment by kerrj** [comment]
For rendering a video, you can use the ns-render command, although it will be much much slower than normal NeRF rendering. For videos in the paper we optimized rendering to compute 1 global scale "using get_max_across" across a subset of frames, then render at that single scale for subsequent frames. This is not implemented in the public lerf repository, but should be straightforward to implement if you want to speed up rendering.

**Comment by yoker5262** [comment]
Thank you very much
