### ISSUE TITLE
ImportError: cannot import name 'GuiHandle' from 'nerfstudio.viewer.viser' (unknown location) 

### ISSUE THREAD

**Issue by Yukun66** [nerfstudio-project/nerfstudio#2280]
**Describe the bug**
When I use `ns-install-cli` to update my nerfstudio, it gives me an error: 
`File "/nerfstudio/nerfstudio/viewer/server/viewer_elements.py", line  28, in <module>`                                                                                                   

`from nerfstudio.viewer.viser import GuiHandle, GuiSelectHandle, ViserServer  `             
           
`ImportError: cannot import name 'GuiHandle' from 'nerfstudio.viewer.viser' (unknown location) `

While the `__init__.py` in viser is :
`from .message_api import GuiHandle as GuiHandle`
`from .message_api import GuiSelectHandle as GuiSelectHandle`
`from .messages import NerfstudioMessage as NerfstudioMessage`
`from .server import ViserServer as ViserServer`

I can't see where is wrong. Please help! Thank you so much~

**Comment by maturk** [comment]
Hmm, looks like something is wrong with the viser, maybe it needs to be updated in your install. Did you run `pip install -e .` also in the nerfstudio repo (after any git pull commands)? If that does not work, you can try  `pip install -e . --upgrade --force-reinstall`.

**Comment by Yukun66** [comment]
> 

Thanks! I re-install the whole nerfstudio environment, and the error has gone! Thank you so much~
