### ISSUE TITLE
ns-train: error:  invalid choice: 'tetra-nerf'

### ISSUE THREAD

**Issue by Mehi44** [nerfstudio-project/nerfstudio#2286]
I installed tetra-nerf as required with nerfstudio==0.2.2

but when I try to train the model I get the following 
![ns-train-tetra](https://github.com/nerfstudio-project/nerfstudio/assets/118313489/7b4a84c1-16f1-4372-935f-c02ec5e8f7e9)

The required version for tetra-nerf is 0.2.0 so I dont understand why it seems like its not added with 0.2.2

**Comment by tancik** [comment]
How did you install nerfstudio?
Can you paste the result of `pip list | grep nerfstudio`

**Comment by Mehi44** [comment]
I installed nerfstudio with pip

```
(nerfstudio) mehi@DGX3:/nas1/mehi/tetranerf$ pip list | grep nerfstudio
nerfstudio                0.2.2
```

**Comment by tancik** [comment]
Perhaps @jkulhanek has an idea?

**Comment by jkulhanek** [comment]
Sorry for my late response. The issue has been addressed in the tetranerf repo: https://github.com/jkulhanek/tetra-nerf/issues/19
