### ISSUE TITLE
[STUCK] Instant-NGP the training without appearing in the logs, without iterations and not viewer

### ISSUE THREAD

**Issue by thiagoholder** [nerfstudio-project/nerfstudio#2291]
**Describe the bug**
I'm training with instant-ngp and no iteration appears in the viewer and no logs. I did the same procedure for the nerfacto and it worked.

```
"gpu": "Tesla T4",
    "gpu_count": 1,
    "gpu_devices": [
        {
            "name": "Tesla T4",
            "memory_total": 16106127360
        }
    ],
    "memory": {
        "total": 7.278079986572266
    }
```

**To Reproduce**
`ns-train instant-ngp --vis viewer+wandb --data datasets/bootsminimal nerfstudio-data`

**Expected behavior**
Work with Instant-NGP using NerfStudio Viewer.

**Screenshots**
![image](https://github.com/nerfstudio-project/nerfstudio/assets/10951517/ceb70a87-509b-424f-a646-5254fba3b61b)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/10951517/8245f8c5-d898-4e6e-bed4-18f134ba1229)

![image](https://github.com/nerfstudio-project/nerfstudio/assets/10951517/ea864ef5-0949-4226-9567-1f99a6ca7896)

**Comment by Goulustis** [comment]
Try removing ~/.cache/torch_extensions. Its something gotta do with nerfacc's compiled cuda code or cuda in general. This sometimes works for me.

**Comment by tancik** [comment]
The first time it runs it can also take a few minutes to compile nerfacc.

**Comment by sraza-onshape** [comment]
Hello - not sure if this deserves a separate issue, but I'm also seeing a similar issue.

I'm training with TensoRF in [Google Colab](https://colab.research.google.com/drive/1Q9u6czNEtruDnJ2puTm-j7YnLldhp4tC?usp=sharing), and trying to log to WandB. I'm running with the following command:

```
$ ns-train tensorf --vis wandb nerfstudio-data --data data/nerfstudio/$scene --downscale-factor 4
```

Notably, I do see log files in the `outputs` directory. Is that expected behavior?

**Comment by iraj465** [comment]
Hey i'm facing similar error:

```
)
????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
[18:30:31] Saving config to: outputs/unnamed/nerfacto/2023-09-15_183031/config.yml              experiment_config.py:136
           Saving checkpoints to: outputs/unnamed/nerfacto/2023-09-15_183031/nerfstudio_models            trainer.py:135
           Auto image downscale factor of 2                                                 nerfstudio_dataparser.py:360
Setting up training dataset...
Caching all 320 images.
Setting up evaluation dataset...
Caching all 35 images.
/opt/conda/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/opt/conda/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=AlexNet_Weights.IMAGENET1K_V1`. You can also use `weights=AlexNet_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
cached file:  /root/.cache/torch/hub/checkpoints/alexnet-owt-7be5be79.pth
f is:  <_io.BufferedReader name='/opt/conda/lib/python3.8/site-packages/lpips/weights/v0.1/alex.pth'>
???????????????????????????????????????????? Viewer ????????????????????????????????????????????
?        ?                                                                                     ?
?   HTTP ? https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:7007   ?
?        ?                                                                                     ?
????????????????????????????????????????????????????????????????????????????????????????????????
[NOTE] Not running eval iterations since only viewer is enabled.
Use --vis {wandb, tensorboard, viewer+wandb, viewer+tensorboard} to run with eval.
No Nerfstudio checkpoint to load, so training from scratch.
Disabled tensorboard/wandb event writers
```

It has stopped after this for more than 5 hours. I have `nerfacc-0.5.2+pt112cu113` installed. What can be the issue here @tancik ?

**Comment by tancik** [comment]
Nerfacc likely failed to install. Try installing it manually, try following the direction here - https://github.com/KAIR-BAIR/nerfacc

**Comment by bariscankurtkaya** [comment]
@tancik Thank you for the help! It also worked on my problem too! I wasted 3 days on this issue.
