### ISSUE TITLE
Using true depth in DepthDataset is broken

### ISSUE THREAD

**Issue by niasie** [nerfstudio-project/nerfstudio#2300]
**Describe the bug**
Following up on PR #2284, attempting to train `depth-nerfacto` with true depth, it will try to use a depth ranking loss instead of a depth loss.

**To Reproduce**
Train `depth-nerfacto` with a dataset with true depths (using a `DepthDataset`). Then, observe that despite having true depths, in W&B it will show a depth ranking loss.

**Expected behavior**
A depth loss instead of a depth ranking loss should be used when training depth-nerfacto with true depths.

**Additional context**
The culprit can be found in [nerfstudio/nerfstudio/data/datasets/depth_dataset.py](https://github.com/nerfstudio-project/nerfstudio/blob/388fcb09e11c4bd191b4bd6c319e7e388ccef321/nerfstudio/data/datasets/depth_dataset.py#L49-L101):

https://github.com/nerfstudio-project/nerfstudio/blob/388fcb09e11c4bd191b4bd6c319e7e388ccef321/nerfstudio/data/datasets/depth_dataset.py#L49-L101

Observe that in both cases, no matter whether true depths are present in the dataset or not, `losses.DEPTH_METRIC = 0`.

Now observe that `depth-nerfacto` will always use a depth ranking loss instead of a depth loss with a `DepthDataset`, since in any case `losses.DEPTH_METRIC = 0`:
https://github.com/nerfstudio-project/nerfstudio/blob/388fcb09e11c4bd191b4bd6c319e7e388ccef321/nerfstudio/models/depth_nerfacto.py#L104-L109

I believe this can be fixed by simply changing `losses.DEPTH_METRIC = 0` to `losses.DEPTH_METRIC = 1` in the `else` statement in [nerfstudio/nerfstudio/data/datasets/depth_dataset.py](https://github.com/nerfstudio-project/nerfstudio/blob/388fcb09e11c4bd191b4bd6c319e7e388ccef321/nerfstudio/data/datasets/depth_dataset.py#L101), i.e. in the case where `DepthDataset` does indeed find true depths in the provided dataset.

**Comment by alexsax** [comment]
Yes, thank you @AdamRashid96 and @ethanweber for this feature. I can't wait to use it!

I'm afraid #2284 also breaks using SDFStudio datasets, where the `depth` and `normal` keys now don't make it into the batch. For example, `replica-room0`

BTW instead of the `DEPTH_METRIC` global in `losses.py`, a more straightforward approach would be to use `FORCE_DEPTH_RANKING_LOSS`. That should be a bool instead of an int and any modifications to this should be monotonic (False -> True but never the reverse).
Maybe also add the ranking loss as `DepthLossType.SPARSENERF_RANKING = 3` in the enum in `losses.py`

**Comment by pwais** [comment]
I think I have this bug too ...

@ethanweber  Why oh why is zoedepth in the DepthDataset instead of in a pre-processing step?  what if the user wants to plug in not-zoedepth prior etc etc etc

**Comment by AdamRashid96** [comment]
Thank you for bringing this to my attention. I fixed the issue of properly switching `losses.DEPTH_METRIC` when true depth is available. @alexsax I agree there is a better way of switch the loss than a global variable but for now so the code isn't broken I will stick to it. Also, thanks for pointing out the overlap in key names will work on standardizing the convention.

**Comment by alexsax** [comment]
@AdamRashid96 nice! Should we perhaps merge our two pull requests #2312 and #2315?

I like #2312 that it enables the ranking loss with sensor/GT depth. All that would be required to merge is to add the pixel sampler fixes #2315 -> #2312.
