### ISSUE TITLE
How to convert the "transforms.json" data for "instant-ngp-dataparser" into "meta_data.json" for "sdfstudio-dataparser"?

### ISSUE THREAD

**Issue by elenacliu** [nerfstudio-project/nerfstudio#2302]
**Describe the bug**
I have a manually-created dataset which can be correcly loaded by "instant-ngp-dataparser". Now I want to try the monocular depth prior loss, after thorough investigation I found I could only use sdfstudio-dataparser to support `monosdf` method in SDFStudio. So I wrote a script for that conversion, but the camera poses are not the same in the viewer.

**To Reproduce**
This is my scripts to convert the "transforms.json" data for "instant-ngp-dataparser" into "meta_data.json" for "sdfstudio-dataparser". 

```python
def convert_meta_json(transform_json_path, meta_json_path, scene_scale=0.33333):
    """https://github.com/autonomousvision/sdfstudio/blob/master/docs/sdfstudio-data.md#Customize-your-own-dataset

    Args:
        transform_json_path (str): the path of your nerfstudio transforms.json
        meta_json_path (str):the path of your sdfstudio meta_data.json
    """
    with open(transform_json_path, 'r') as f:
        d = json.load(f)
    meta_d = dict()
    meta_d['camera_model'] = 'OPENCV'
    meta_d['pairs'] = True
    meta_d['has_mono_prior'] = True
    meta_d['worldtogt'] = [[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
    meta_d['height'] = d['h']
    meta_d['width'] = d['w']
    
    # in x,y,z order
    # assumes that the scene is centered at the origin
    aabb_scale = 0.5 * d.get("aabb_scale", 1)
    meta_d['scene_box'] = {
            "aabb": [[-aabb_scale, -aabb_scale, -aabb_scale], [aabb_scale, aabb_scale, aabb_scale]],
            "near": 0.05,
            "far": 2.0,
            "radius": 1.0,
            "collider_type": "near_far",
        }
    meta_d['frames'] = list()
    
    K = [
        [d['fl_x'], 0, d['cx']],
        [0, d['fl_y'], d['cy']],
        [0,0,1],
    ]
    for frame in d['frames']:
        rgb_path = frame["file_path"].split('/')[-1].split('_')[0]+'_rgb.png'
        print(rgb_path)
        c2w = np.array(frame['transform_matrix'])
        # from blender/opengl to colmap/opencv
        c2w[0:3, 1:3] *= -1
        c2w[:3, 3] *= scene_scale
        c2w_colmap = c2w
        
        new_frame = {
            "rgb_path": rgb_path,
            "camtoworld": c2w_colmap.tolist(),
            "intrinsics": K,
            "mono_depth_path": rgb_path.replace("_rgb.png", "_depth.npy"),
            "mono_normal_path": rgb_path.replace("_rgb.png", "_normal.npy"),
            # "sensor_depth_path": rgb_path.replace("_rgb.png", "_sensor_depth.npy"),
        }
        meta_d['frames'].append(new_frame)
    with open(meta_json_path, "w", encoding="utf-8") as f:
        json.dump(meta_d, f, indent=2)
```
In fact the script just:

1. sets y to be -y and z to be -z (because "sdfstudio-dataparser" will do that, so I need to do an "inverse" calculation first to preserve the c2w):
https://github.com/nerfstudio-project/nerfstudio/blob/388fcb09e11c4bd191b4bd6c319e7e388ccef321/nerfstudio/data/dataparsers/sdfstudio_dataparser.py#L110-L122

2. scale the tranlation (the scaling process just as "instant-ngp-dataparser" do (here self.config.scene_scale=0.33333): https://github.com/nerfstudio-project/nerfstudio/blob/388fcb09e11c4bd191b4bd6c319e7e388ccef321/nerfstudio/data/dataparsers/instant_ngp_dataparser.py#L100-L103

**Expected behavior**
I think the script above can work well, at least for different dataparsers I can see the same camera poses in the viewer, but it didn't. 

**Screenshots**
The correct camera poses loaded by instant-ngp dataparser:

<img width="400" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/44845151/1402e1fa-aa70-470c-bdd1-25115f2a4176">

The camera poses loaded by sdfstudio dataparser:

<img width="389" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/44845151/bc30c526-58be-4fd5-9ef6-2a46d2e02c84">

**Additional context**
It seems that the rotation has some problems here, but I don't know exactly where the problems are.

**Comment by MvWouden** [comment]
I assume that you can close it since you've posted it on SDFStudio already https://github.com/autonomousvision/sdfstudio/issues/192
