### ISSUE TITLE
Try to use some component(VanillaDataManager) in my own project, but failed 

### ISSUE THREAD

**Issue by liuxiaozhu01** [nerfstudio-project/nerfstudio#2308]
I was trying to use the component `VanillaDataManager` in my own code to process minimal-parser data convention. But it seems that the VanillaDataManager object cannot be initialized successfully.
The debug info is shown below:
![M2)D6MRJKD$OHPJ9477 ZW2](https://github.com/nerfstudio-project/nerfstudio/assets/68947207/874a9a64-6064-46cc-a63d-efcc0a81fdce)

Has anyone met this question either?

**Comment by maturk** [comment]
Hi @liuxiaozhu01, the problem here is not necessarily unique to the VanillaDataManager. The problem here is essentially that you are trying to initialise a class which inherits from nn.Module (in this case the VanillaDataManager) within the initialisation of another class that inherits from nn.Module. 

Below I give a small example where I replicate this error message which is similar to the setup you have right now. 

```
from torch import nn
from nerfstudio.data.datamanagers.base_datamanager import (
    VanillaDataManager,
    VanillaDataManagerConfig,
)


# Replicating the issue with this small example
class MinimalPipeline(nn.Module):
    def __init__(self):
        self.my_config = VanillaDataManagerConfig()
        self.my_manager = self.my_config.setup()


if __name__ == "__main__":
    MinimalPipeline()
```

This throws the same error message. The problem here is that you are initialising self.my_manager which subclasses nn.Module before MinimalPipeline is initialised which itself subclasses nn.Module. To fix this issue, you have to ensure that you call super().__init__() in the parent class before you initialise any more nn.Module attributes within the parent. This is a strange quirk of PyTorch that I have also encountered before. Basically just add this to the code:

```
class MinimalPipeline(nn.Module):
    def __init__(self):
        super().__init__()
        self.my_config = VanillaDataManagerConfig()
        self.my_manager = self.my_config.setup()
```

Let me know if this helps you debug your code.

**Comment by liuxiaozhu01** [comment]
Awesome! That's really, really helpful!
Thank you so much for your help!

**Comment by liuxiaozhu01** [comment]
Sorry to bother again. I met a new question.
I was trying to implement my network as `base_model.py/class Model`. And as I tried to evaluate, the error occured
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
``` 
The code for the error reporting section is as follows
```
def get_geo_outputs(self, x, feature):
        x.requires_grad_(True)
        output = self.forward_geo_layers(x, feature)
        sdf = output[:, :1]
        
        feature_vectors = output[:, 1:]
        d_output = torch.ones_like(sdf, requires_grad=False, device=sdf.device)
        gradients = torch.autograd.grad(
            outputs=sdf,
            inputs=x,
            grad_outputs=d_output,
            create_graph=True,
            retain_graph=True,
            only_inputs=True)[0]

        return sdf, feature_vectors, gradients
```
And the call stack saved by vscode is
![image](https://github.com/nerfstudio-project/nerfstudio/assets/68947207/0b92736a-6c28-4077-a654-8754940e1774)

I guess that the error is due to `get_eval_image_metrics_and_images()` calling `self.model.eval()` and the `get_outputs_for_camera_ray_bundle()` with `@torch.no_grad()` context-manager that disabled gradient calculation.

How can i solve it?

**Comment by maturk** [comment]
> Sorry to bother again. I met a new question. I was trying to implement my network as `base_model.py/class Model`. And as I tried to evaluate, the error occured
> 
> ```
> RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
> ```
> 
> The code for the error reporting section is as follows
> 
> ```
> def get_geo_outputs(self, x, feature):
>         x.requires_grad_(True)
>         output = self.forward_geo_layers(x, feature)
>         sdf = output[:, :1]
>         
>         feature_vectors = output[:, 1:]
>         d_output = torch.ones_like(sdf, requires_grad=False, device=sdf.device)
>         gradients = torch.autograd.grad(
>             outputs=sdf,
>             inputs=x,
>             grad_outputs=d_output,
>             create_graph=True,
>             retain_graph=True,
>             only_inputs=True)[0]
> 
>         return sdf, feature_vectors, gradients
> ```
> 
> And the call stack saved by vscode is ![image](https://user-images.githubusercontent.com/68947207/258623237-0b92736a-6c28-4077-a654-8754940e1774.png)
> 
> I guess that the error is due to `get_eval_image_metrics_and_images()` calling `self.model.eval()` and the `get_outputs_for_camera_ray_bundle()` with `@torch.no_grad()` context-manager that disabled gradient calculation.
> 
> How can i solve it?

Hi, I dont believe the functions you mention should effect autograd in training. Why do you have requires_grad = False for d_output variable?
