### ISSUE TITLE
Training Nerfacto using 6-band images

### ISSUE THREAD

**Issue by Yaodizhao** [nerfstudio-project/nerfstudio#2309]
Hello, may I ask which part of the code would be better to modify if you want to train another 6 bands in addition to rgb。

**Comment by maturk** [comment]
There are a few modifications to make: [in the nerf field](https://github.com/nerfstudio-project/nerfstudio/blob/9b6010ea0d20e7ca2a68496bb33d6dcd03bf9b91/nerfstudio/fields/nerfacto_field.py#L197), in the [rgb renderer](https://github.com/nerfstudio-project/nerfstudio/blob/9b6010ea0d20e7ca2a68496bb33d6dcd03bf9b91/nerfstudio/model_components/renderers.py#L58), in the [viewer renderer](https://github.com/nerfstudio-project/nerfstudio/blob/9b6010ea0d20e7ca2a68496bb33d6dcd03bf9b91/nerfstudio/models/base_model.py#L165) and most likely also for your PSNR/image metrics [here](https://github.com/nerfstudio-project/nerfstudio/blob/9b6010ea0d20e7ca2a68496bb33d6dcd03bf9b91/nerfstudio/models/nerfacto.py#L330). You also have to modify the [input dataset](https://github.com/nerfstudio-project/nerfstudio/blob/9b6010ea0d20e7ca2a68496bb33d6dcd03bf9b91/nerfstudio/data/datasets/base_dataset.py#L60) to accomodate whatever new dataset you have.

**Comment by ParasPant** [comment]
@Yaodizhao  I am new to Nerf studio could you elaborate what 6 band mean. Are you talking about multiband images?
