### ISSUE TITLE
Monodepth PR broke `PatchPixelSampler`

### ISSUE THREAD

**Issue by pwais** [nerfstudio-project/nerfstudio#2313]
The old `PatchPixelSampler` respect the batch size (e.g. `--pipeline.datamanager.train-num-rays-per-batch` ) and adjusted accordingly:
https://github.com/nerfstudio-project/nerfstudio/blob/d542646c72e2f7c8cd03f6677b7489334c1d92c8/nerfstudio/data/pixel_samplers.py#L247C7-L247C24

But the monodepth PR https://github.com/nerfstudio-project/nerfstudio/pull/2284  made `PatchPixelSampler` no longer respect the parameter `batch_size` https://github.com/nerfstudio-project/nerfstudio/pull/2284/files#diff-b15e0d31bf4d84dbacd4ea2e0c44f597dea42d975f841a5cb47481e876185c4bR375

I tried to fix this but that PR actually appears to change the `PairPixelSampler` logic too, so I just removed `PairPixelSamplerConfig` from the depth-nerfacto config for now.

Nerfstudio might need to remove the separate `--pipeline.datamanager.pixel-sampler.num-rays-per-batch` that conflicts semantically with `--pipeline.datamanager.{train,eva}-num-rays-per-batch` ... that could be why setting the batch size inside the pixelsamplers got spaghetti'ed

Nerfstudio might also need some tests where the batch size params are varied, dunno if those can be added to CI

@ethanweber

**Comment by elenacliu** [comment]
I met a similar problem when export the point cloud result of depth-nerfacto:

> File "/nerfstudio/nerfstudio/data/pixel_samplers.py", line 176, in collate_image_dataset_batch
    assert collated_batch["image"].shape[0] == num_rays_per_batch
AssertionError

**Comment by alexsax** [comment]
Yes it looks like `PairPixelSampler.sample_method()` accepts `batch_size` but [never uses it](https://github.com/nerfstudio-project/nerfstudio/blob/cb2405d3eaa2b848acb82e6a8da780ac40b937ce/nerfstudio/data/pixel_samplers.py#L393-L422).

PR #2327 fixes this :)

**Comment by pwais** [comment]
Thank you so much !!!

**Comment by tancik** [comment]
> err, i don't think `batch_size` is ever Optional (it isn't in the base class) nor is it ever null
> 
> https://github.com/nerfstudio-project/nerfstudio/blob/61548ceba1af598a552710d8c4a6feb22645b7e1/nerfstudio/data/pixel_samplers.py#L395

Mind making a PR fix ;)

**Comment by pwais** [comment]
@tancik I've twice started making PRs attempting to fix this bug but:
 * I don't understand what the intention is with `PixelSampler` having `set_num_rays_per_batch()` as well as `self.config.num_rays_per_batch` as well as `sample_method()` _also_ taking in a batch size.  
 * And then there's also _separately_ `train_num_rays_per_batch` and `eval_rays_per_batch` which ... are supposed to override `PixelSampler.config.num_rays_per_batch` ? But what if the user sets both?  
 * And then there's `DynamicBatchPipeline` which is only used by instant-ngp ...

So @tancik to me it looks like the code / design got hacked up a bit here, and probably needs some un-hacking from the official maintainers.  Given that this got broken w/out a CI failure, I'm also unsure what the test coverage this is and what other dependent code might be impacted.  (altho now i see the samplers aren't part of the template / module API https://github.com/nerfstudio-project/nerfstudio-method-template/tree/main/method_template )

**Comment by hermosaaurora** [comment]
also expecting the answer
