### ISSUE TITLE
Camera optimizer indices are not num_cameras

### ISSUE THREAD

**Issue by lvmingzhe** [nerfstudio-project/nerfstudio#2323]
Hi, I noticed the captions in the forward function "indices: Int[Tensor, "num_cameras"],".
However, the indices seem to be the num of train_num_rays_per_batch=4096.
The captions make me confused, is it a typo?

```
class CameraOptimizer(nn.Module):
    """Layer that modifies camera poses to be optimized as well as the field during training."""

    config: CameraOptimizerConfig

    def __init__(
        self,
        config: CameraOptimizerConfig,
        num_cameras: int,
        device: Union[torch.device, str],
        non_trainable_camera_indices: Optional[Int[Tensor, "num_non_trainable_cameras"]] = None,
        **kwargs,
    ) -> None:
        super().__init__()
        self.config = config
        self.num_cameras = num_cameras
        self.device = device
        self.non_trainable_camera_indices = non_trainable_camera_indices
        
        print("self.num_cameras: ", self.num_cameras)
        ...
        
        def forward(
        self,
        indices: Int[Tensor, "num_cameras"],
    ) -> Float[Tensor, "num_cameras 3 4"]:
        """Indexing into camera adjustments.
        Args:
            indices: indices of Cameras to optimize.
        Returns:
            Transformation matrices from optimized camera coordinates
            to given camera coordinates.
        """
        outputs = []

        print("indices of cameras to optimize: ", indices)
        print("indices of cameras to optimize shape: ", indices.shape)
```

The prints are:
```
 self.num_cameras:  90
 indices of cameras to optimize:  tensor([36, 77, 17,  ...,  3, 58, 20])
 indices of cameras to optimize shape:  torch.Size([4096])
```

**Comment by maturk** [comment]
Right, maybe it is not the most clear. Indices here refers to the camera indices (from the original training dataset) that are optimised within a batch of RayBundles. So the indices refer to the camera IDs that the rays are generated from within that batch.

**Comment by brentyi** [comment]
Yeah, I think the problem here is that `num_cameras` is overloaded:
- `self.num_cameras` refers to the total number of cameras.
- `"num_cameras"` in the shape annotation is the number of transformation matrices that are being returned. (which each correspond to a camera)

Both are correctly a "number of cameras", but it's confusing... based on what @maturk described maybe we can rename the latter to `camera_indices`?

**Comment by maturk** [comment]
Sure, I have now renamed it. Hopefully this is more clear now.

**Comment by lvmingzhe** [comment]
Thanks a lot for your quick reply and clear answers.
I`m sorry to bother you guys with another question.
I`m trying to understand the logic behind the multiplication of camera poses adjustments in the outputs list.

```
...
outputs.append(exp_map_SO3xR3(self.pose_adjustment[indices, :]))
...
return functools.reduce(pose_utils.multiply, outputs)
```

Here are my observations and questions:

1. The variable 'INDICES' represents the indices of cameras corresponding to specific rays.
2. For each camera index, a pose adjustment is selected from self.pose_adjustment, transformed into a matrix using exp_map_SO3xR3, and then added to the outputs list.
3. In the end, all the matrices in the outputs list are consecutively multiplied using functools.reduce(pose_utils.multiply, outputs).

My confusion arises from the final multiplication step. If each matrix in outputs represents a pose adjustment for a different ray of a camera, what is the rationale behind multiplying all these matrices consecutively? It seems counterintuitive to multiply unrelated camera pose adjustments together.

Could you please clarify the purpose of this operation and whether this is the intended behavior?

Thank you for your time and assistance!

**Comment by brentyi** [comment]
There's no multiplication happening between transforms for different rays: outputs is a list of tensors, each of which should have shape `(num_rays, 3, 4)`. After the reduce, we end up with a single tensor of shape `(num_rays, 3, 4)`.

The reduce is ultimately just a way of multiplying the pose adjustment:

https://github.com/nerfstudio-project/nerfstudio/blob/4fe8e657d20520d96dfe94ef038e8717fa13e7ad/nerfstudio/cameras/camera_optimizers.py#L118-L125

with some optional initial pose noise (mostly used for testing):

https://github.com/nerfstudio-project/nerfstudio/blob/4fe8e657d20520d96dfe94ef038e8717fa13e7ad/nerfstudio/cameras/camera_optimizers.py#L130-L132

**Comment by lvmingzhe** [comment]
oh, I got it. When it is that without adding noise, outputs only have one element, which means it does not perform multiplication operations. If noise is added, the outputs will have two elements, which are multiplied to obtain the pose optimization amount with added noise.

**Comment by DankoPenko** [comment]
@maturk 
Hi!
Thank for you creating this topic and answers, that covered few of my questions :)
However, I still have few more questions:
1. Where does the implementation of `exp_map_SE3` comes from? Shouldn't it just be `torch.linalg.matrix_exp`?
2. If I created two separete noises for rotational and translational components and just added it straight up to the transform matrices, would it have been a correct implementation/does such implementation make sense?
