### ISSUE TITLE
ns-train in2n error

### ISSUE THREAD

**Issue by yoker5262** [nerfstudio-project/nerfstudio#2342]
ns-train in2n --data {/opt/image-synthesis/output_data/newvideo/} --load-dir {/opt/image-synthesis/algorithm_manage/model_zoo/newvideo/nerfacto/2023-08-15_153448/nerfstudio_models/} --pipline.prompt {"Turn the fighter into a white fighter"} --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 2.1 --pipeline.diffusion-steps 200 --output-dir /opt/image-synthesis/algorithm_manage/model_zoo/

error:
ns-train in2n: error: argument [{nerfstudio-data,minimal-parser,arkit-data,blender-data,instant-ngp-data,nuscenes-data,dnerf-data,phototourism-data,dycheck-data,scannet-data,sdfstudio-data,nerfosr-data,sitcoms3d-data}]: invalid choice: '{Turn the fighter into a white fighter}' (choose from 'nerfstudio-data', 'minimal-parser', 'arkit-data', 'blender-data', 'instant-ngp-data', 'nuscenes-data', 'dnerf-data', 'phototourism-data', 'dycheck-data', 'scannet-data', 'sdfstudio-data', 'nerfosr-data', 'sitcoms3d-data')

I want to know the reason of this error and how should I fix this error

**Comment by maturk** [comment]
Hi Yoker, could you please provide some further information, have you cloned the in2n repo and ran the install commands? In2n is not a default nerfstudio method, so you must install it from their repository for it to work with nerfstudio CLI.

**Comment by yoker5262** [comment]
ns-train in2n --data  {data-path}  This execution command will not be wrong, and the program will execute normally.

**Comment by yoker5262** [comment]
conda  list  in2n version 0.1.0

**Comment by maturk** [comment]
> ns-train in2n --data {data-path} This execution command will not be wrong, and the program will execute normally.

Wait, so this command works fine?

**Comment by yoker5262** [comment]
yes,sir. It can print out config information normally and perform training. So I think it's because I executed the wrong command, but I checked and found no error

**Comment by maturk** [comment]
> yes,sir. It can print out config information normally and perform training. So I think it's because I executed the wrong command, but I checked and found no error

I think you have a mispelling "pipline" instead of "pipeline". I tested by running the prompt command "ns-train in2n --data [PATH TO MY DATA] --pipeline.prompt "Turn the fighter into a white fighter"" and it worked fine.

**Comment by yoker5262** [comment]
ohhh! I was so careless, I am very sorry to cause you trouble. I have another question about pix2pix,   code:  pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained("timbrooks/instaruct-pix2pix",torch_dtype=torch.float16,safety_checker=None) , In this line of code, there is a download, access huggingface, and write to .cache/huggingface/hub. Why does it need to be accessed every time it is executed?

**Comment by maturk** [comment]
> ohhh! I was so careless, I am very sorry to cause you trouble. I have another question about pix2pix, code: pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained("timbrooks/instaruct-pix2pix",torch_dtype=torch.float16,safety_checker=None) , In this line of code, there is a download, access huggingface, and write to .cache/huggingface/hub. Why does it need to be accessed every time it is executed?

Please try to post your questions about in2in or pix2pix in their own repositories, this is the repo for the main nerfstudio project, and I don't think you will get help on specific method implementations external to nerfstudio here.
