### ISSUE TITLE
How does `ns-export pointcloud` work?

### ISSUE THREAD

**Issue by elenacliu** [nerfstudio-project/nerfstudio#2344]
**Describe the bug**
I'm trying to export a point cloud from nerfstudio, and I tried 2 methods.

1. render the depth by `ns-render camera-path` command, and the camera path is manually created using the outputs of `ns-export cameras` and convert the depth (with known camera intrinsics) into a point cloud.
2. just run `ns-export` command

**Expected behavior**
I'm not sure, but when I open the 2 point clouds in meshlab, I found desk in method 1's point cloud is not so flat, but the desk in method 2's point cloud is more flat and realistic.

**Screenshots**
1. method 1's point cloud:

<img width="384" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/44845151/7587beb1-e3b0-4ad4-8da8-309748f3c1a8">

2. method 2's point cloud:

<img width="378" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/44845151/fc852dd4-cf62-4796-9d27-827d9bcbe021">

So how does the `ns-export pointcloud` generate the points? Is there a given camera pose or is it fused by many results of different poses?

**Comment by brentyi** [comment]
This is one of the (many) parts of the code I don't know too well, but I did a skim of the [point cloud generation function](https://github.com/nerfstudio-project/nerfstudio/blob/6d51af1a24d692d073a9e0cda06278b6a9d44818/nerfstudio/exporter/exporter_utils.py#L77-L225) and:

1. Are you computing 3D points in the same way as the nerfstudio exporter does it?
   https://github.com/nerfstudio-project/nerfstudio/blob/6d51af1a24d692d073a9e0cda06278b6a9d44818/nerfstudio/exporter/exporter_utils.py#L154

   Notably, the "depth" value looks like it should be a distance from camera origin, as opposed to a traditional Z-depth.

2. > Is there a given camera pose or is it fused by many results of different poses?

    From the snippet, it looks like points are generated by rendering from the training views.

3. > by the way, the coordinates of results of `ns-export pointcloud` are world coordinates or camera space coordinates?

    It looks like world coordinates to me! (but the scaled NeRF ones)

**Comment by elenacliu** [comment]
thank you for your reply! I dig into the code and agree with what your opinion.
