### ISSUE TITLE
Add Neuralangelo

### ISSUE THREAD

**Issue by MohamedAliRashad** [nerfstudio-project/nerfstudio#2347]
**Is your feature request related to a problem? Please describe.**
I want to try out Neuralangelo

**Describe the solution you'd like**
Add the functionality

**Describe alternatives you've considered**
None

**Additional context**
https://github.com/NVlabs/neuralangelo

**Comment by maturk** [comment]
Hi @MohamedAliRashad, I believe the sister project [SDFStudio](https://github.com/autonomousvision/sdfstudio) has this implemented since their repo mainly targets SDF research similar to this paper.
