### ISSUE TITLE
Loading data batch killed

### ISSUE THREAD

**Issue by runningneverstop** [nerfstudio-project/nerfstudio#2370]
I try to use scannet dataset to train. But after "Loading data batch", thne the process is killed. 
How can i solve it?
![image](https://github.com/nerfstudio-project/nerfstudio/assets/86957090/285e50fb-bb8f-4411-b074-e50f46548972)

**Comment by maturk** [comment]
Hey, your dataset is too big with 1740 images, the program crashes because it cannot store so many images in cache. You should decrease the number of training images depending on your gpu VRAM amount.

**Comment by runningneverstop** [comment]
Yes, I found the problem afterwards. Thanks a lot!
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Matias&nbsp;Turkulainen"; 
Date: 2023年8月26日(星期六) 凌晨2:43
To: "nerfstudio-project/nerfstudio"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [nerfstudio-project/nerfstudio] Loading data batch killed (Issue #2370)

&nbsp;


 
Hey, your dataset is too big with 1740 images, the program crashes because it cannot store so many images in cache. You should decrease the number of training images depending on your gpu VRAM amount.

**Comment by elenacliu** [comment]
I'm just wondering will there be a plan to support stream data training? I mean the data is generated by sensor's on realtime. In this condition, `CacheDataLoader` may update consecutively and replace the old data in the cache?
