### ISSUE TITLE
is it possible to support stream data from sensors using something like `IterableDataset` in torch?

### ISSUE THREAD

**Issue by elenacliu** [nerfstudio-project/nerfstudio#2375]
**Is your feature request related to a problem? Please describe.**
Now the data loading logics are:

1. Users specify the input in a `transform.json` file, which contains all the training image filepaths
2. A dataparser instance parses the json, and stores the content in a `dataparser_output` dict
3. A dataset (such as `DepthDataset`) instance reads/loads the binary image data from the filenames in `dataparser_output` dict
4. `CacheDataloader` caches the binary image data in memory to speed up training

However, this process could not support stream data which is generated on the fly, or when cache is not enough for all the images (like issue #2370 )

**Describe the solution you'd like**
In this condition, `CacheDataloader` may update consecutively and replace the old data in the cache. Besides, if the training data is generated on the fly, it's like a "producer and consumer" problem, there should be a "buffer" in memory or in disk, which may be troublesome in a multi-thread environment.

**Describe alternatives you've considered**
I think there are no alternatives now. If there were, can you let me know?

**Comment by maturk** [comment]
Hi @elenacliu, currently there is no plan; however, there are some other open source implementations that add similar functionality using ros: https://github.com/javieryu/nerf_bridge. The main idea in this repo is that they create a new datamanager that reads new input poses / images from a ros node and stores and updates a preallocated image data tensor. I think this kind of feature is really interesting, but relying on ROS is a bit cumbersome for users (ROS installation for different users / platforms can be a pain) and it is always dependent on the user side configuration (e.g. slam system they are running) so it is difficult to incorporate into nerfstudio as a One-Size-Fits-All kind of solution for streaming, if that makes sense. It would be amazing to add some RPC API functionality where users could just send packets of images / poses and see those rendered in real time... but I think this might go beyond the scope of this library :D Unless someone is really knowledgable in this...

**Comment by elenacliu** [comment]
wow it seems that it's what I need.
