### ISSUE TITLE
The scale factor and orientation of pointcloud exported

### ISSUE THREAD

**Issue by jiangzhiwei2018** [nerfstudio-project/nerfstudio#2376]
Thanks for your awesome project. I'm a bit confuse about the result of pointcloud exported by `ns-export`.

**step 1.**   I obtained the  `transforms.json` colmap model folder (contains `cameras, points3D, images` in `sparse/0`)  after running  `ns-process-data`.

**step 2.**  train `nerfacto` with  `nerfstudio-data`

`ns-train nerfacto --pipeline.model.predict-normals True  --data  ${DATASETS} nerfstudio-data  --downscale-factor 1`

**step 3.**  `ns-export` to get pointcloud file

but pointclud didn't set the same orientation and scale factor  with COLMAP-Base method's result (eg. mvsnet) which reconstructed from  colmap model folder(got in step 1.), they shoud have the same camera `intrinsics` and `poses` .

The left result is `NERF`, right is `MVS`

![Screenshot from 2023-08-28 16-55-40](https://github.com/nerfstudio-project/nerfstudio/assets/40731305/5619cdf2-60f3-44f0-95f4-6b2134600790)

My doubts as below

1. I noticed that `Nerf` use the `OpenGL/Blender`coordinate (as show in [data-conventions](https://docs.nerf.studio/en/latest/quickstart/data_conventions.html)), so transforming the pointcloud to convert to the COLMAP coordinate after I export the pointcloud is required,  am I right? 
2. On the other hand, I confuse with this beacuse I thought the scale factor and orientation of the pointcloud should be fixed when the camera `intrinsics` and `poses` are same. 

 And then I found the  [issue#761](https://github.com/nerfstudio-project/nerfstudio/issues/761#issuecomment-1284165910), and use the command line 
`ns-train  ...  nerfstudio-data  - --orientation-method none --center-method none --auto-scale-poses False`
to "don't want  dataparser to change the poses at all". 

I thought I got the weird result(the left), which is  worse than before. as can see, it seems generated 'duplicated object'
and  don't obtain the actual scale factor I need.
![Screenshot from 2023-08-28 17-43-40](https://github.com/nerfstudio-project/nerfstudio/assets/40731305/f672d3e8-58be-4410-9a0f-d005ca7d678d)

**Comment by tancik** [comment]
The transformation info is located in the `dataparser_transforms.json` file in the outputs folder. It's on our list of TODOs, to have the option to export in the original coordinate frame.

**Comment by jiangzhiwei2018** [comment]
yeah, I found that . Thanks 

Zhiwei Jiang

**Comment by jiangzhiwei2018** [comment]
I have solved this,  and will close the issue
just transformed the exported pointcloud by the inversed  `transform`  and `scale` in `dataparser_transforms.json`.
Here is my python  script, maybe it will be helpful for someone who encounters the same trouble.
```python
import open3d as o3d
import numpy as np
from open3d import io as o3d_io
import json
import copy
import os
def transofrm_cloud(cloud_in_path:str, transforam_scale_json_path:str):
    pcd = o3d_io.read_point_cloud(cloud_in_path)
    with open(transforam_scale_json_path, "r") as fr:
        transforam_scale_json = json.load(fr)
    # transformation = torch.as_tensor(transforam_scale_json["transform"])[None]
    cloud_out_path = os.path.join(os.path.dirname(cloud_in_path), "transformed_point_cloud.ply")

    transformation = np.asarray(transforam_scale_json["transform"])
    # transformation[:, :3] = np.linalg.inv(transformation[:, :3])
    transformation = np.concatenate([transformation, np.array([[0, 0, 0, 1/transforam_scale_json["scale"]]])], 0)
    transformation = np.linalg.inv(transformation)
    # use numpy to scale
    # points = np.asarray(pcd.pcd_transformed)
    # centroid
    # centroid = points.mean(axis=0)
    # # scale
    # scaled_points = (points - centroid) * scale_factor + centroid
    # update point
    # pcd_transformed.points = o3d.utility.Vector3dVector(scaled_points)
    pcd_transformed = copy.deepcopy(pcd)
    # use open3d to scale and transform
    pcd_transformed.transform(transformation)
    # pcd_transformed.scale(scale_factor, center=pcd_transformed.get_center())
    o3d_io.write_point_cloud(cloud_out_path, pcd_transformed)

if __name__ == '__main__':
    transofrm_cloud("export/com_mypose/point_cloud.ply", "outputs/com_mypose/nerfacto/2023-08-28_160924/dataparser_transforms.json")
```
The original scale and position is fine. (bright is transformed)
![Screenshot from 2023-08-29 11-55-47](https://github.com/nerfstudio-project/nerfstudio/assets/40731305/5b6322cd-d568-4249-b34f-e57f94c841f9)
