### ISSUE TITLE
results from nerfacto/instant-ngp-bounded on blender data are bad

### ISSUE THREAD

**Issue by prakashknaikade** [nerfstudio-project/nerfstudio#2403]
This is sample image from blender data:
![r_16](https://github.com/nerfstudio-project/nerfstudio/assets/74629958/c1820d0b-c72b-41b6-90a0-c0d2ebc0dd37)

output using instant-ngp -bounded:
ns-train instant-ngp-bounded --data /HPS/ColorNeRF/work/nerfstudio/data/nerfstudio/perl_toaster --experiment-name=perl_toaster --vis wandb --pipeline.model.background-color white --pipeline.model.near-plane 2. --pipeline.model.far-plane 6. --pipeline.datamanager.camera-optimizer.mode off  --pipeline.model.disable-scene-contraction True blender-data
![image](https://github.com/nerfstudio-project/nerfstudio/assets/74629958/2046549f-faaa-4f75-af52-d2314c964041)

output using nerfacto:
ns-train nerfacto --data /HPS/ColorNeRF/work/nerfstudio/data/nerfstudio/perl_toaster --experiment-name=perl_toaster --vis tensorboard --pipeline.model.background-color white --pipeline.model.proposal-initial-sampler uniform --pipeline.model.near-plane 2. --pipeline.model.far-plane 6. --pipeline.datamanager.camera-optimizer.mode off --pipeline.model.use-average-appearance-embedding False --pipeline.model.distortion-loss-mult 0 --pipeline.model.disable-scene-contraction True blender-data
![image](https://github.com/nerfstudio-project/nerfstudio/assets/74629958/a69b02e5-6cb2-46e4-8412-6a9aa7ac5551)

Why is the rendered output has white noise in nerfacto and in both cases material does not look like as shiny as in the input data? The model does not learn the shadows reflected from material which is visible in input data? Also color reproduction is not good.
Are these limitations of these models? And if yes, what are these limitations? 
![img_29500_4850312d2fe55fd26e40](https://github.com/nerfstudio-project/nerfstudio/assets/74629958/e5e27c97-9c9f-4da0-94b0-5ad50c899c2d)

**Comment by tancik** [comment]
Scenes with strong reflections do not perform well using nerfacto or intant-ngp. Currently none of the provided nerfstudio methods perform well in this domain.

**Comment by prakashknaikade** [comment]
@tancik With mipnerf the scene learned is decent than nerfacto or intant-ngp, why is that? I also remember reading nerfacto uses techniques from mipnerf?
![image](https://github.com/nerfstudio-project/nerfstudio/assets/74629958/452c5999-6468-4ed0-b55b-4f4d32e584a9)
![img_149000_363db27a4ced22e6e460](https://github.com/nerfstudio-project/nerfstudio/assets/74629958/2c27c308-95fa-459d-a8f2-07fb30229023)

Do you know any external model/method which learns scene with strong reflections, Pearlescent/Iridescent material, structural colors? I will appreciate any guide in this regard.
