### ISSUE TITLE
Colmap fails to find poses for the image

### ISSUE THREAD

**Issue by IAM-P-LP** [nerfstudio-project/nerfstudio#2407]
Hi,
Thanks for the wonderful repo.
I was doing the data preprocessing step using colmap,specifically by using _ns-process-data images --data ./images_screw_5/ --output-dir ./processed_images_screw_5/_
command and **even if my images arent blurry**,I am getting warnings like this and the resultant point cloud looks bad.Can you please help me on this?Thanks in advance.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/54659792/cdb0abd6-41e0-4d74-bd59-eeddf8be3b5d)

**Comment by IAM-P-LP** [comment]
Closing this as it worked with images of lot more texture

**Comment by shenyehui** [comment]
> Closing this as it worked with images of lot more texture

May I ask how you solved this problem? I'm having the same problem.

**Comment by IAM-P-LP** [comment]
Colmap requires some texture also.Keep your object in textured background and try again.Hope that it helps
