### ISSUE TITLE
change colmap path in colmap dataparser  

### ISSUE THREAD

**Issue by jurek0** [nerfstudio-project/nerfstudio#2410]
**Is your feature request related to a problem? Please describe.**
I have been training some Nerfacto models and I have been noticing strange behavior regarding eval loss. Although I had not been warned after preprocessing, colmap seemed to not have found a lot of camera poses. When viewing the strange acting models in the web viewer only a handful of cameras showed up. I then looked into the colmap/sparse dir and found that there was not only one but two folders containing camera.bin files. When I imported them to colmap, one of the sparse reconstructions (in colmap/sparse/0) showed only a handful of cameras, whereas the other one (colmap/sparse/1) showed all the expected camera positions.

**Describe the solution you'd like**
Maybe one could alter the code in "colmap_dataparser.py" to use colmap/sparse/1 as colmap path if available. (Extend code in line 72:  'colmap_path: Path = Path("sparse/0")' to include sparse/1 as an option or choose sparse/1 by default.)

I don't know if this is a viable option because I don't know if 1 always contains better camera poses than 0 and why it sometimes exists at all.

**Comment by jurek0** [comment]
I am very sorry, I have only now found out about the possibility to skip colmap while processing and choosing an alternative colmap/sparse path by adding --skip-colmap --colmap-model-path PATH to ns-process-data.

**Comment by richardrevesz** [comment]
> I am very sorry, I have only now found out about the possibility to skip colmap while processing and choosing an alternative colmap/sparse path by adding --skip-colmap --colmap-model-path PATH to ns-process-data.

Thank you for this jurek0 :) If someone even more rookie looking into it and wondering how to skip colmap processing when processing the data:

ns-process-data images --skip-colmap --colmap-model-path [path to colmap data] --data [images] --output_dir [output]

where:
- path to colmap data: this is the sparse folder, that includes cameras.bin, images.bin and points3d.bin
- images: this is the images folder
- output: the folder to put the processed data to be used with ns-train
