### ISSUE TITLE
Windows 10 RuntimeWarning: Windows does not yet support torch.compile and the performance will be affected.

### ISSUE THREAD

**Issue by idontcare999a** [nerfstudio-project/nerfstudio#2426]
**Describe the bug**
C:\Users\User\AppData\Local\miniconda3\envs\nerfstudio\lib\site-packages\nerfstudio\utils\misc.py:184: RuntimeWarning: Windows does not yet support torch.compile and the performance will be affected.

Training seems to be working but it has poor performance.

**To Reproduce**
1. Install miniconda3
2. Install nerfstudio following https://docs.nerf.studio/en/latest/quickstart/installation.html
- a. Inside miniconda3 activated environment, run `"\Program Files\Microsoft Visual Studio\2022\Professional\vc\Auxiliary\Build\vcvars32.bat" x64` before installing tiny-cuda-nn
- b. Finish installing nerfstudio
- c. `set HOME=C:\Users\User`
- d. `ns-install-cli`
3. Follow training steps https://docs.nerf.studio/en/latest/quickstart/first_nerf.html
4. See warning

**Expected behavior**
Expected behavior is to utilize my GPU for training, and have good performance.

**Additional context**
`torch==2.0.1+cu118`

**Comment by tancik** [comment]
Not much we can do about this until `torch.compile` is supported by windows. There are some long standing [issues](https://github.com/pytorch/pytorch/issues/90768) on the pytorch github. One note, `torch.compile` doesn't seem to provide much improvement in this usecase so you aren't missing out on much performance.

**Comment by idontcare999a** [comment]
I ran the test case
`ns-train nerfacto --data data/nerfstudio/poster --machine.num-devices 1 --pipeline.datamanager.train-num-rays-per-batch 4096`
and it was taking 45+ minutes, so I wasn't sure if that was due to the torch.compile warning. Running the nerfacto-big I can definitely see the GPU being used. Running on a laptop with A2000 GPU.

**Comment by tancik** [comment]
That's expected for a mobile GPU.

**Comment by machenmusik** [comment]
Last time I checked, Windows without torch.compile was faster than Ubuntu WSL using it, FYI.
