### ISSUE TITLE
render image size not equal to train image size

### ISSUE THREAD

**Issue by Saixiaoma** [nerfstudio-project/nerfstudio#2439]
render image size not equal to train image size

**Comment by maturk** [comment]
You can change your desired rendered image width and height and resolution settings in the ns-render or ns-viewer settings.

**Comment by Saixiaoma** [comment]
where is the resolution setting in ns-render？I cannot find in render.py

**Comment by maturk** [comment]
So first you define the render width and height in ns-viewer or ns-train when you make your desired camera path. 
<img width="406" alt="image" src="https://github.com/nerfstudio-project/nerfstudio/assets/30566358/e5db9fef-9276-478a-b062-353b231caef5">
 If you want to also change this after making a camera path, you can open the camera_paths.json file and change the vars "render_width" and "render_height" there before running ns-render command.

**Comment by maturk** [comment]
Are you able to port forward from your server? If you run this command in your local computer `ssh -L 7007:localhost:7007 USER@YOUR_IP`

**Comment by Saixiaoma** [comment]
No, I cannot. permission denied.

**Comment by wanger-666** [comment]
How to change image size when use interpolated render?+1
