### ISSUE TITLE
"ns-download-data nerfstudio" not working properly

### ISSUE THREAD

**Issue by minghanqin** [nerfstudio-project/nerfstudio#2441]
I could not download any datasets from "ns-download-data nerfstudio".

2023-09-18 09:22:45 ERROR 404: File not found.

──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: wget https://data.nerf.studio/nerfstudio/person.zip -O 
/nerfstudio/person.zip
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by tancik** [comment]
The data was moved to a google drive. You need to use the latest version of nerfstudio for the correct urls.

https://github.com/nerfstudio-project/nerfstudio/blob/b0e700137bd8bde21fbc7867f433dd36b2905e1e/nerfstudio/scripts/downloads/download_data.py#L116-L139
