### ISSUE TITLE
Better qualitative result but lower PSNR with camera pose optimiser on my custom dataset

### ISSUE THREAD

**Issue by Cerf-Volant425** [nerfstudio-project/nerfstudio#2469]
Thanks for your great work!

I use nerfacto to train my model with the default parameters, except for the pose refinement.

- With the SO3xR3 pose refinement 
![on](https://github.com/nerfstudio-project/nerfstudio/assets/79494908/d307c4d8-6ef6-4328-9b57-8af110742acf)
PSNR: 15.74045467376709

- Without the pose refinement 
 ![off](https://github.com/nerfstudio-project/nerfstudio/assets/79494908/6201b5ca-a4da-476c-bfe7-30f7f57f0b32)
PSNR: 16.429622650146484

I was wondering why the rendered results are much better when applying the camera optimiser, but leading to a lower PSNR.

Any help would be highly appreciated!

**Comment by tancik** [comment]
The eval camera positions aren't optimized so if the training cameras move a lot, the underlying trained nerf won't align well with the eval images.

**Comment by Cerf-Volant425** [comment]
Thank you so much.

**Comment by Cerf-Volant425** [comment]
By the way, I would like to know is there a pertinent evaluation way aiming at this case, like optimising the training and testing camera poses simultaneously?

**Comment by Binyr** [comment]
> Thanks for your great work!
> 
> I use nerfacto to train my model with the default parameters, except for the pose refinement.
> 
> * With the SO3xR3 pose refinement
>   ![on](https://user-images.githubusercontent.com/79494908/270520988-d307c4d8-6ef6-4328-9b57-8af110742acf.gif)
>         
>           [
>             
>           
>               ![on](https://user-images.githubusercontent.com/79494908/270520988-d307c4d8-6ef6-4328-9b57-8af110742acf.gif)
>             ](https://user-images.githubusercontent.com/79494908/270520988-d307c4d8-6ef6-4328-9b57-8af110742acf.gif)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://user-images.githubusercontent.com/79494908/270520988-d307c4d8-6ef6-4328-9b57-8af110742acf.gif)
>           
>         
>   PSNR: 15.74045467376709
> * Without the pose refinement
>   ![off](https://user-images.githubusercontent.com/79494908/270520581-6201b5ca-a4da-476c-bfe7-30f7f57f0b32.gif)
>         
>           [
>             
>           
>               ![off](https://user-images.githubusercontent.com/79494908/270520581-6201b5ca-a4da-476c-bfe7-30f7f57f0b32.gif)
>             ](https://user-images.githubusercontent.com/79494908/270520581-6201b5ca-a4da-476c-bfe7-30f7f57f0b32.gif)
>           
>           
>             
>               
>                 
>               
>               
>                 
>                 
>               
>             
>             [
>               
>                 
>               
>             ](https://user-images.githubusercontent.com/79494908/270520581-6201b5ca-a4da-476c-bfe7-30f7f57f0b32.gif)
>           
>         
>   PSNR: 16.429622650146484
> 
> I was wondering why the rendered results are much better when applying the camera optimiser, but leading to a lower PSNR.
> 
> Any help would be highly appreciated!

Hi, how to see the test PSNR
