### ISSUE TITLE
About the export point-cloud

### ISSUE THREAD

**Issue by yinfan98** [nerfstudio-project/nerfstudio#2470]
Hi, I just train my first model and export it to point-cloud. It works well, and I want to know how it works.
Can you tell me how to convert the model to a point cloud, or tell me where the code is?
thanks!

**Comment by vijendra1125** [comment]
@yinfan98 It simply takes the points in space for which opacity is higher than 0.5 as point cloud. rays are sampled till set number of points are collected. You could check "generate_point_cloud" function in nerfstudio/exporter/exporter_utils.py

**Comment by yinfan98** [comment]
@vijendra1125 thanks a lot, I will check that
