### ISSUE TITLE
versioned docs no longer available?

### ISSUE THREAD

**Issue by drewgilliam** [nerfstudio-project/nerfstudio#2480]
Are versioned docs no longer available?  Apologies if this has already been asked, I can't find an issue or PR relating to the change.

Docs for the latest main used to be available at 
https://docs.nerf.studio/en/latest
But now docs only appear to be available at 
https://docs.nerf.studio 
with no version options

Clicking this badge in the README
![image](https://github.com/nerfstudio-project/nerfstudio/assets/17988826/3cefeb40-0f9c-452e-95ff-9a3e2dc0a417)
Takes me to a 404 error, as the versioned latest docs no longer exist.

This affects projects using intersphinx, as the location of the `objects.inv` file has been moved.

**Comment by drewgilliam** [comment]
Adding on to this - is looks like many recent PRs are failing to build docs.  Not sure if this is related
```
  /usr/bin/git push origin --force gh-pages
  remote: Permission to nerfstudio-project/nerfstudio.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/nerfstudio-project/nerfstudio.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"
```

**Comment by drewgilliam** [comment]
@tancik @brentyi - I think your docs build system might be broken?  See comments above

**Comment by tancik** [comment]
We moved away from using readthedocs which offered the versioning and switched to hosting our own docs. We didn't feel that paying $150 a month was justified to keep with the service.

**Comment by brentyi** [comment]
> @tancik @brentyi - I think your docs build system might be broken? See comments above

Yeah, I think this is because the action was trying to deploy to the `gh-pages` branch for every pull request. We can probably do more here in the future, but I added a PR with a quick fix.

**Comment by drewgilliam** [comment]
Thanks for the info and the fix!
