### ISSUE TITLE
ERROR while runnning ns-process-data video，Running COLMAP feature matcher...

### ISSUE THREAD

**Issue by Reloof** [nerfstudio-project/nerfstudio#2507]
**Describe the bug**
──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: colmap vocab_tree_matcher --database_path data/nerfstudio/laptop/colmap/database.db 
--SiftMatching.use_gpu 1 --VocabTreeMatching.vocab_tree_path "/root/.local/share/nerfstudio/vocab_tree.fbow"
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
OMP: Error #34: System unable to allocate necessary resources for OMP thread:
OMP: System error #11: Resource temporarily unavailable
OMP: Hint Try decreasing the value of OMP_NUM_THREADS.
*** Aborted at 1696997226 (unix time) try "date -d @1696997226" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x591b) received by PID 22811 (TID 0x7f1aa1ffb000) from PID 22811; stack trace: ***
    @     0x7f2187acd197 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f2185bc4420 (unknown)
    @     0x7f218526300b gsignal
    @     0x7f2185242859 abort
    @     0x7f218547093f __kmp_abort_process
    @     0x7f218546cceb __kmp_fatal
    @     0x7f21854cb5cb __kmp_create_worker
    @     0x7f2185474c9d __kmp_allocate_thread
    @     0x7f2185473a48 __kmp_allocate_team
    @     0x7f2185478308 __kmp_fork_call
    @     0x7f21854d0066 __kmp_GOMP_fork_call
    @     0x7f21854d765f __kmp_api_GOMP_parallel
    @     0x55a791ef1bec flann::NNIndex<>::knnSearch()
    @     0x55a791f08019 colmap::retrieval::VisualIndex<>::FindWordIds()
    @     0x55a791f0c840 colmap::retrieval::VisualIndex<>::QueryAndFindWordIds()
    @     0x55a791f1211b colmap::retrieval::VisualIndex<>::Query()
    @     0x55a79202d52d 
_ZZN6colmap12_GLOBAL__N_134MatchNearestNeighborsInVisualIndexEiiiiiiRKSt6vectorIjSaIjEEPNS_6ThreadEPNS_19FeatureMatcherC
acheEPNS_9retrieval11VisualIndexIhLi128ELi64EEEPNS_18SiftFeatureMatcherEENKUljE_clEj
    @     0x55a79202dbaf 
_ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_
ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFZN6colmap12_GLOBAL__N_134MatchNearestNeighborsInVisualIndexEiiiiiiRKSt6vector
IjSaIjEEPNSC_6ThreadEPNSC_19FeatureMatcherCacheEPNSC_9retrieval11VisualIndexIhLi128ELi64EEEPNSC_18SiftFeatureMatcherEEUl
jE_jEESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0x55a791ebc9f9 std::__future_base::_State_baseV2::_M_do_set()
    @     0x7f2185bc14df __pthread_once_slow
    @     0x55a7920173ae 
_ZNSt17_Function_handlerIFvvEZN6colmap10ThreadPool7AddTaskIRZNS1_12_GLOBAL__N_134MatchNearestNeighborsInVisualIndexEiiii
iiRKSt6vectorIjSaIjEEPNS1_6ThreadEPNS1_19FeatureMatcherCacheEPNS1_9retrieval11VisualIndexIhLi128ELi64EEEPNS1_18SiftFeatu
reMatcherEEUljE_JRKjEEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSQ_DpOSR_EUlvE_E9_M_invokeERKSt9_Any_data
    @     0x55a79217c564 colmap::ThreadPool::WorkerFunc()
    @     0x7f2185751e95 execute_native_thread_routine
    @     0x7f2185bb8609 start_thread
    @     0x7f218533f133 clone
    @                0x0 (unknown)
Aborted (core dumped)

**Comment by Simplegram** [comment]
Hello I'm having the same problem. How do you solve this?

**Comment by Reloof** [comment]
> Hello I'm having the same problem. How did you solve this?

I switched to a CPU with larger memory.
