### ISSUE TITLE
tiny-cuda-nn install fails, different error than in the notes

### ISSUE THREAD

**Issue by Iliceth** [nerfstudio-project/nerfstudio#2518]
When I run "pip install ninja git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch" I get this error. 

Collecting git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
  Cloning https://github.com/NVlabs/tiny-cuda-nn/ to c:\users\andy\appdata\local\temp\pip-req-build-3eo2lr_w
  Running command git clone --filter=blob:none --quiet https://github.com/NVlabs/tiny-cuda-nn/ 'C:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w'
  Resolved https://github.com/NVlabs/tiny-cuda-nn/ to commit bd1f7272eda2bb6047c3dcfb253086dbf41bc593
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Collecting ninja
  Obtaining dependency information for ninja from https://files.pythonhosted.org/packages/b6/2f/a3bc50fa63fc4fe9348e15b53dc8c87febfd4e0c660fcf250c4b19a3aa3b/ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata
  Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl.metadata (5.4 kB)
Using cached ninja-1.11.1.1-py2.py3-none-win_amd64.whl (312 kB)
Building wheels for collected packages: tinycudann
  Building wheel for tinycudann (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      C:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w\bindings/torch\setup.py:5: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_version
      Building PyTorch extension for tiny-cuda-nn version 1.7
      Obtained compute capability 61 from PyTorch
      nvcc: NVIDIA (R) Cuda compiler driver
      Copyright (c) 2005-2022 NVIDIA Corporation
      Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
      Cuda compilation tools, release 11.8, V11.8.89
      Build cuda_11.8.r11.8/compiler.31833905_0
      Detected CUDA version 11.8
      Targeting C++ standard 17
      running bdist_wheel
      C:\Users\Andy\Anaconda3\envs\nerfstudio\lib\site-packages\torch\utils\cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\tinycudann
      copying tinycudann\modules.py -> build\lib.win-amd64-cpython-38\tinycudann
      copying tinycudann\__init__.py -> build\lib.win-amd64-cpython-38\tinycudann
      running egg_info
      creating tinycudann.egg-info
      writing tinycudann.egg-info\PKG-INFO
      writing dependency_links to tinycudann.egg-info\dependency_links.txt
      writing top-level names to tinycudann.egg-info\top_level.txt
      writing manifest file 'tinycudann.egg-info\SOURCES.txt'
      reading manifest file 'tinycudann.egg-info\SOURCES.txt'
      writing manifest file 'tinycudann.egg-info\SOURCES.txt'
      copying tinycudann\bindings.cpp -> build\lib.win-amd64-cpython-38\tinycudann
      running build_ext
      building 'tinycudann_bindings._61_C' extension
      creating build\dependencies
      creating build\dependencies\fmt
      creating build\dependencies\fmt\src
      creating build\src
      creating build\temp.win-amd64-cpython-38
      creating build\temp.win-amd64-cpython-38\Release
      creating build\temp.win-amd64-cpython-38\Release\tinycudann
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -IC:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w/include -IC:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w/dependencies -IC:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w/dependencies/cutlass/include -IC:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w/dependencies/cutlass/tools/util/include -IC:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w/dependencies/fmt/include -IC:\Users\Andy\Anaconda3\envs\nerfstudio\lib\site-packages\torch\include -IC:\Users\Andy\Anaconda3\envs\nerfstudio\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\Andy\Anaconda3\envs\nerfstudio\lib\site-packages\torch\include\TH -IC:\Users\Andy\Anaconda3\envs\nerfstudio\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\Andy\Anaconda3\envs\nerfstudio\include -IC:\Users\Andy\Anaconda3\envs\nerfstudio\Include /EHsc /Tp../../dependencies/fmt/src/format.cc /Fobuild\temp.win-amd64-cpython-38\Release\../../dependencies/fmt/src/format.obj /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc /std:c++17 -DTCNN_PARAMS_UNALIGNED -DTCNN_MIN_GPU_ARCH=61 -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_61_C -D_GLIBCXX_USE_CXX11_ABI=0
      format.cc
      C:\Users\Andy\AppData\Local\Temp\pip-req-build-3eo2lr_w/dependencies/fmt/include\fmt/format-inl.h(11): fatal error C1083: Cannot open include file: 'algorithm': No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\Hostx64\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tinycudann
  Running setup.py clean for tinycudann
Failed to build tinycudann
ERROR: Could not build wheels for tinycudann, which is required to install pyproject.toml-based projects

I'm quite new to this all and it seems a different error than those mentioned in the notes, so I hope some can interpret what the problem(s) is/are to get me further. Thanks!

**Comment by ShaYito** [comment]
hi, i met this error too. How did you solve it?

**Comment by Iliceth** [comment]
@ShaYito If I remember it well, I put in the command `export LIBRARY_PATH="/usr/lib/wsl/lib:$LIBRARY_PATH` just before I did the tiny-cuda-nn install and that fixed it for me.

**Comment by parth-psd-009** [comment]
I get the same bug in windows. What is the solution for it?

**Comment by chocolateriderx** [comment]
> @ShaYito If I remember it well, I put in the command `export LIBRARY_PATH="/usr/lib/wsl/lib:$LIBRARY_PATH` just before I did the tiny-cuda-nn install and that fixed it for me.

I have this exact problem. How did you get it solve?

I put this command but it wasn't recognize

**Comment by RebekkaBaertheleTHWS** [comment]
same problem, also in windows and the export LIBRARY_PATH did not work as well

**Comment by chocolateriderx** [comment]
> same problem, also in windows and the export LIBRARY_PATH did not work as well

I already solve this problem but I don't remember exactly how. But looks like if you follow the clip. it won't work since there's update in the installation instruction page. SO you need to follow instruction in the page not clip. Good luck

**Comment by RebekkaBaertheleTHWS** [comment]
@chocolateriderx what do you mean by "not clip"? if you could provide a link that would be great!

**Comment by RebekkaBaertheleTHWS** [comment]
it worked for me now using WSL2 and this link: https://gist.github.com/SharkWipf/0a3fc1be3ea88b0c9640db6ce15b44b9 without any problems:))
