### ISSUE TITLE
How to find which image is used as test set while training nerfacto?

### ISSUE THREAD

**Issue by mylee95** [nerfstudio-project/nerfstudio#2520]
After training nerfacto, we can get test result with ns-eval, but I cannot find which images are used for evaluation.
Is there any way to check which images are used for ns-eval, and check how do they get rendered?

**Comment by vijendra1125** [comment]
@mylee95 One idea is to run ns-eval with argument --render-output-path then it will save the rendered images at given path and hence you will be able to check the name of the images used for evaluation.

**Comment by mylee95** [comment]
> @mylee95 One idea is to run ns-eval with argument --render-output-path then it will save the rendered images at given path and hence you will be able to check the name of the images used for evaluation.

Thank you for suggestion! However, it seems like ns-eval with argument --render-output-path saves rendered images with datamanager's index number as name, not using image's original name.

I just modified the "get_average_eval_image_metrics" function in nerfstudio/nerfstudio/pipelines/base_pipeline.py to save each image's evaluation results with its name together.
