### ISSUE TITLE
How to use gaussian splatting code

### ISSUE THREAD

**Issue by cdcseacave** [nerfstudio-project/nerfstudio#2528]
I'm trying to run the [gaussian-splatting](https://github.com/nerfstudio-project/nerfstudio/tree/gaussian-splatting) branch with the mip360 data and the following command:
```
ns-train gaussian-splatting --vis wandb --experiment-name gsplats colmap --colmap_path sparse/0 --data data/mip360/bicycle
```
but I hit the error:
```
File "/home/ubuntu/nerfstudio/nerfstudio/models/gaussian_splatting.py", line 475, in get_outputs
    assert camera.shape[0] == 1, "Only one camera at a time"
```

Could you please provide an example how to use the code?

**Comment by kerrj** [comment]
Currently the eval pipeline isn't supported (wandb/tensorboard), only the live viewer. If you try with the viewer does it work? We're working on integrating the rest of the eval pipelines still.

**Comment by cdcseacave** [comment]
thanks for the quick reply
with your suggestion I get farther but I get an other error:
```
140 (0.47%)         21.996 ms            10 m, 56 s           31.26 M
150 (0.50%)         16.357 ms            8 m, 8 s             40.02 M
160 (0.53%)         15.673 ms            7 m, 47 s            41.53 M
170 (0.57%)         15.583 ms            7 m, 44 s            41.86 M
180 (0.60%)         15.556 ms            7 m, 43 s            41.93 M
190 (0.63%)         17.369 ms            8 m, 37 s            38.20 M
----------------------------------------------------------------------------------------------------
Viewer Beta at: https://viewer.nerf.studio/versions/23-05-15-1/?websocket_url=ws://localhost:7007
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.0223
VanillaPipeline.get_train_loss_dict: 0.0146
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/ubuntu/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.train()
  File "/home/ubuntu/nerfstudio/nerfstudio/engine/trainer.py", line 252, in train
    loss, loss_dict, metrics_dict = self.train_iteration(step)
  File "/home/ubuntu/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/home/ubuntu/nerfstudio/nerfstudio/engine/trainer.py", line 472, in train_iteration
    _, loss_dict, metrics_dict = self.pipeline.get_train_loss_dict(step=step)
  File "/home/ubuntu/nerfstudio/nerfstudio/utils/profiler.py", line 127, in inner
    out = func(*args, **kwargs)
  File "/home/ubuntu/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 301, in get_train_loss_dict
    loss_dict = self.model.get_loss_dict(model_outputs, batch, metrics_dict)
  File "/home/ubuntu/nerfstudio/nerfstudio/models/gaussian_splatting.py", line 603, in get_loss_dict
    Ll1 = torch.abs(gt_img - outputs["rgb"]).mean()
RuntimeError: The size of tensor a (411) must match the size of tensor b (410) at non-singleton dimension 0
```

**Comment by kerrj** [comment]
Try pulling from the repo, there's a commit that might fix this there.

**Comment by cdcseacave** [comment]
cool, it works now (you are working around the clock, I did pull 1h ago also) :)

**Comment by kerrj** [comment]
Great thanks!

**Comment by cdcseacave** [comment]
stupid question: the training is complete, I only have a check point file, how do I see the GS model?

**Comment by ChongjianGE** [comment]
Hi @cdcseacave @kerrj 
I wonder if there is anyway that I can render a circular video without the online viewer to create camera-path?

**Comment by antonzub99** [comment]
> stupid question: the training is complete, I only have a check point file, how do I see the GS model?

You probably should load the checkpoint file and parse its contents in a .ply file. Ckpt contains all necessary information about gaussians (mean, covariances, SHs, opacity)

**Comment by hariharan1412** [comment]
> > stupid question: the training is complete, I only have a check point file, how do I see the GS model?
> 
> You probably should load the checkpoint file and parse its contents in a .ply file. Ckpt contains all necessary information about gaussians (mean, covariances, SHs, opacity)

Btw how to export it into Pointcloud ?

**Comment by maturk** [comment]
@hariharan1412 check the [ns-export](https://docs.nerf.studio/reference/cli/ns_export.html) command and relevant code in the [pr](https://github.com/nerfstudio-project/nerfstudio/blob/9e33b437dff6df5a9579c04b1eba46640df88a96/nerfstudio/scripts/exporter.py#L480)

**Comment by hariharan1412** [comment]
Thanks I exported successfully, I have some doubts regarding the outputs, for the same sparse from the colmap the NERF output is very good but GS output is not, The GS output is yellow and green only. to add on the NERF output is 250MB but GS output is only 13Mb. Do you have any idea why this is happening ? ? It'll be very helpfull for me

**Comment by maturk** [comment]
@hariharan1412 check the source code for the exporter from nerf, also compare the number of points in both ply files. The nerf one most likely just exports more points than what the GS model has, so this results in a better looking pc.
