### ISSUE TITLE
odm parsing error

### ISSUE THREAD

**Issue by hnj5247** [nerfstudio-project/nerfstudio#2562]
**Describe the bug**
I did gitpull, reinstalling but have odm parsing error.

(nerfstudio) ssllab12@ssllab12-Inspiron-16-Plus-7630:~/nerfstudio$ ns-process-data odm

╭─ Parsing error ─────────────────────╮
│ Argument {images,video,polycam,metashape,realitycapture,record3d}: invalid choice: 'odm' (choose from   │
│ 'images', 'video', 'polycam', 'metashape', 'realitycapture', 'record3d')                                │
│ ──────────────────────────────────
│ For full helptext, run ns-process-data --help                                                           │
╰─────────────────────────────────
(nerfstudio) ssllab12@ssllab12-Inspiron-16-Plus-7630:~/nerfstudio$ git pull
Already up to date.

I can see "odm" is not added to the arguments list.

I checked odm is added and works in other computer.
Can't figure out why odm is not added in this laptop while all files are up to date. Thank you.

This was done in
Ubuntu 22.04
python 3.8
NVIDIA-SMI 535.113.01            
 Driver Version: 535.113.01
torch 2.0.1 Cuda 11.8

![Screenshot from 2023-10-26 16-45-14](https://github.com/nerfstudio-project/nerfstudio/assets/140051608/480ef6cb-9d0b-4c22-b5c8-cf3d4b69ea19)

**Comment by ichsan2895** [comment]
How about reinstalling nerfstudio from `pip install nerfstudio==0.3.4` ?

**Comment by hnj5247** [comment]
> How about reinstalling nerfstudio from `pip install nerfstudio==0.3.4` ?

I tried it again and doesn't works.
I see the odm in nerfstudio/process_data/odm_utils.py
But can't find out why not listing up.
Thank you for your reply

**Comment by ichsan2895** [comment]
How about this?
```
git clone https://github.com/nerfstudio-project/nerfstudio/
cd nerfstudio
pip install -e .
```

**Comment by hnj5247** [comment]
> How about this?
> 
> ```
> git clone https://github.com/nerfstudio-project/nerfstudio/
> cd nerfstudio
> pip install -e .
> ```
 Sorry for late reply.
 That worked for me in a new environment.
 Thank you.
