### ISSUE TITLE
Error training 

### ISSUE THREAD

**Issue by DEVECLOVER** [nerfstudio-project/nerfstudio#2579]
After configuring the environment according to the tutorial, the following error occurs when testing the training example.
### My training setting and command is as: 
![image](https://github.com/nerfstudio-project/nerfstudio/assets/42308974/900efc76-6882-42bc-9762-298f7d6d8643)
![image](https://github.com/nerfstudio-project/nerfstudio/assets/42308974/6d9ab28e-4194-44f4-962a-d43133ad609f)

### When code are ready to start training from scratch, the following error occurs:

![image](https://github.com/nerfstudio-project/nerfstudio/assets/42308974/7e5600d7-3950-45ca-94f0-193561aeb8c1)
![image](https://github.com/nerfstudio-project/nerfstudio/assets/42308974/8491c282-3bb7-4060-8164-861cc03f796b)
![image](https://github.com/nerfstudio-project/nerfstudio/assets/42308974/549c0088-3c0a-482c-8601-c8a9e0047a24)

Thank you!!!

**Comment by kerrj** [comment]
We'll look into it, in the meantime in method_config.py if you change "ParallelDataManager" to "VanillaDataManager" it should temporarily stop the error

**Comment by lqz28** [comment]
same problem here, master branch.
I solve this problem by swithing to tag v.0.3.3

**Comment by DEVECLOVER** [comment]
> same problem here, master branch. I solve this problem by swithing to tag v.0.3.3
Thanks a  lot! It did work by switching to v0.3.3.

**Comment by DEVECLOVER** [comment]
@kerrj  Thanks a lot.  I test your method. After compiling  v0.3.3, the training can be successful regardless of whether the method_config.py is changed.
