### ISSUE TITLE
How to create circular camera path?

### ISSUE THREAD

**Issue by Yoonho-Na** [nerfstudio-project/nerfstudio#2587]
I want to create camera path where the center is the target object.
How can I do this?

**Comment by ChongjianGE** [comment]
@Yoonho-Na
Hi, have you solved the problem? I'm currently facing the same issue.

**Comment by Yoonho-Na** [comment]
@ChongjianGE 
No I haven't.
I think we have to define the coordinate of object center first and then calculate the transformation matrix or camera parameter based on that point.
I'm not sure about it.

**Comment by Yoonho-Na** [comment]
Using Blender solved issue

**Comment by 7Kuku7** [comment]
> 使用 Blender 已解决问题

Hi, after I import the rendered results into blender, I keep getting mold penetration when I set the path manually. Is there a specific tutorial on setting up the blender clock? Would appreciate if you could reply.
