### ISSUE TITLE
ERROR: failed to create sparse model  in `ns-process-data`

### ISSUE THREAD

**Issue by fanzz1208** [nerfstudio-project/nerfstudio#2604]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/120933924/c4f22110-3edf-4db0-96cb-2c4950c8002f)

**Describe the bug**
 Running COLMAP bundle adjustment... (This may take a while)──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: colmap mapper --database_path /workspace/nerfdata/068/colmap/database.db --image_path
/workspace/nerfdata/068/images --output_path /workspace/nerfdata/068/colmap/sparse --Mapper.ba_global_function_tolerance
1e-6
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
ERROR: failed to create sparse model

**Comment by audiocommander** [comment]
I stumbled upon this error, too. I'm on a MacBook Air M2 AARCH64, PyTorch with mps support for silicon. I tried installing COLMAP by downloading a precompiled release, which runs, but I couldn't make it work for python scripts. So I installed COLMAP via brew and it seems to kinda work. Now I got exactly this error, too.

**Comment by tudorjnu** [comment]
I have the same error. Any solutions found so far?

**Comment by camolina2** [comment]
I have this error too :( any solutions?

**Comment by rexainn** [comment]
same problem

**Comment by AlexanderVoldby** [comment]
I am also getting this error, I'm just not getting the "ERROR: failed to create sparse model" message. Have you tried running this with the --verbose flag to see extended logs? I personally don't get any extra information from this though...

**Comment by AlexanderVoldby** [comment]
Did you fix the error by using more video data?

**Comment by rexainn** [comment]
I used different videos for different scenes, so I got this error. Once I changed one video like shooting arround the same scene, the error is fixed.

**Comment by AlexanderVoldby** [comment]
Okay, I am currently just using a single video but maybe I was moving the camera too fast, I guess I’ll try with another video

**Comment by AryamanSharma17** [comment]
Not sure if this is helpful but for me, CUDA was out of memory. I was able to get feature matching and sparse point cloud by closing other memory-consuming scripts.

**Comment by Tiangj9178** [comment]
Have you ever encountered this situation? How to deal with it?
nerfstudio) root@autodl-container-8b8a4382f2-a9434246:/#  ns-process-data images --data /root/autodl-tmp/mtree3-305/images --output-dir /nerfstudio/data1/mtree3 
[16:13:59] 🎉 Done copying images with prefix 'frame_'.                                        process_data_utils.py:340
[16:15:38] 🎉 Done extracting COLMAP features.                                                       colmap_utils.py:137
[16:23:40] 🎉 Done matching COLMAP features.                                                         colmap_utils.py:151
[16:39:49] 🎉 Done COLMAP bundle adjustment.                                                         colmap_utils.py:173
           🎉 Done refining intrinsics.                                                              colmap_utils.py:184
           einsum(): the number of subscripts in the equation (2) does not match the number of       process_data.py:526
           dimensions (1) for operand 1 and no ellipsis was given

**Comment by abysee** [comment]
I encountered the same error, at first I thought it was because of the data or that colmap didn't extract features. But after several experiments I found it was because that I didn't set up visible cuda devices. For me using instructions like ```export CUDA_VISIBLE_DEVICES=0``` works. You could try debugging to see if the feature is correctly extracted using ```colmap feature_extractor --database_path processed_data_path/database.db --image_path processed_data_path``` (change the corresponding processed_data_path to your directory). If no matches were found, try ```colmap exhaustive_matcher --database_path processed_data_path/colmap/database.db``` to further locate the problem and it is where I found that colmap couldn't find the proper devices.

**Comment by AntonioMacaronio** [comment]
How many images are in your dataset? This can appear if the number of images are too few <10

**Comment by Songxinlei** [comment]
same issue! have you fixed it?
