### ISSUE TITLE
ns-render spiral does not work.

### ISSUE THREAD

**Issue by Yoonho-Na** [nerfstudio-project/nerfstudio#2631]
**Describe the bug**
I want to make a video that renders spiral path but there is an assertion error

**To Reproduce**
1. execute the below line in terminal
`ns-render spiral --load-config your/path/to/config_file/config.yml --output-path renders/custom/output_filename.mp4`

**Expected behavior**
render a video with spiral camera path

**Screenshots**
<img width="1146" alt="스크린샷 2023-11-27 오후 5 55 32" src="https://github.com/nerfstudio-project/nerfstudio/assets/53941554/dc741ffd-e9fe-41b2-ba32-47337232b317">

**Comment by kerrj** [comment]
#2637 should fix
