### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by hariharan1412** [nerfstudio-project/nerfstudio#2636]
``` ns-train gaussian-splatting colmap --data ./data/ ```

File "/home/ubuntu/conda/envs/nerfstudio/lib/python3.8/site-packages/gsplat/sh.py", line 39, in forward
    assert coeffs.shape[-2] == num_sh_bases(degree)
AssertionError

why am i keep getting this error ? i even tried different data

My data folder:

data 
    - images
        - images 0
        - images 1
    - colmap
        - sparse
            - 0

**Comment by maturk** [comment]
please `git clone --recurse-submodules` and `pip install -e .` the latest gsplat repo from https://github.com/nerfstudio-project/gsplat/
