### ISSUE TITLE
Ability to set project and run name for WandB

### ISSUE THREAD

**Issue by kurtjcu** [nerfstudio-project/nerfstudio#2645]
Hi I would love to be able to set the WandB project and run name via commandline args.

Current method defaults to "nerfstudio-project", defaulting to "nerfstudio-<network name>" would also be appreciated.

**Comment by kurtjcu** [comment]
Nerf Studio "experiment_name" should probably align with the wandb - run name.

**Comment by MartinEthier** [comment]
This is already implemented. You can use the --project-name arg to set the project and --experiment-name arg to set the run name.

**Comment by kurtjcu** [comment]
My apologies, This is not functional is the latest "release" branch or in the latest container
