### ISSUE TITLE
Licensability of Gaussian Splatting

### ISSUE THREAD

**Issue by ringohoffman** [nerfstudio-project/nerfstudio#2684]
I have been really excited about commercial applications of NeRFs and especially 3D Gaussian Splatting, but I have been wondering about how [the license for the original 3D Gaussian Splatting](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/LICENSE.md) applies to `nerfstudio`'s implementation. I know that `nerfstudio` uses the Apache 2.0 license, but how do you reconcile this with these sections from the original 3DGS repository's license:

> Software means the original work of authorship made available under this License ie [**`gaussian-splatting`**](https://github.com/graphdeco-inria/gaussian-splatting).
>
> Work means the Software and any additions to or derivative works of the Software that are made available under this License.
>
> 4.1 Redistribution. You may reproduce or distribute the Work only if (a) you do so under this License, (b) you include a complete copy of this License with your distribution, and (c) you retain without modification any copyright, patent, trademark, or attribution notices that are present in the Work.
>
> 4.2 Derivative Works. You may specify that additional or different terms apply to the use, reproduction, and distribution of your derivative works of the Work ("Your Terms") only if (a) Your Terms provide that the use limitation in Section 2 applies to your derivative works, and (b) you identify the specific derivative works that are subject to Your Terms. Notwithstanding Your Terms, this License (including the redistribution requirements in Section 3.1) will continue to apply to the Work itself.

I don't see [**`gaussian-splatting`**](https://github.com/graphdeco-inria/gaussian-splatting)'s license included anywhere in `nerfstudio`. Does `nerfstudio`'s implementation of 3DGS not constitute a derivative work? It seems like ["derivative work" as it relates to software is somewhat open to legal interpretation](https://bpb-us-e1.wpmucdn.com/sites.suffolk.edu/dist/5/1153/files/2018/02/Heineman_Note-zkty8u.pdf). IANAL, but it seems that `gaussian-splatting`'s license does allow for derivative works to be commercially licensable, but subject to their license's limitations, namely section 4.2. Have any lawyers been consulted in relation to the commercial licensability of `nerfstudio`?

I appreciate any additional assurance or understanding that you can offer. I would really love to work towards using `nerfstudio` commercially with confidence.

And thank you so much for your work!

**Comment by akanazawa** [comment]
Hi, 

Thanks for your question. We have consulted our Office of Technology Licensing, who have confirmed that we can license the codebase under Apache. 

It seems like you're asking for freedom to operate analysis, UC does not offer this since we are a public entity. If you are concerned about commercial use, please consult your own counsel.

Best,

Angjoo
