### ISSUE TITLE
Rendering results for Nerfacto don't match the original image on training set.

### ISSUE THREAD

**Issue by halo2718** [nerfstudio-project/nerfstudio#2686]
I was doing experiments on SPIn-NeRF dataset using Nerfacto provided by Nerfstudio. The experiment steps are listed as follows (Take scene1 in the dataset as example):

1. Run `ns-process-data images --data spin_nerf/scene_1/images_4 --output-dir ./scene_1_processed` to use COLMAP to get camera poses for images.

2. Run `ns-train nerfacto --data ./scene_1_processed --pipeline.datamanager.camera-optimizer.mode off` to train.

3. After the radiance field is converged, run `ns-export cameras --load-config /path/to/config.yml --output-dir scene_1_poses` to export camera poses for training views.

4. Then run `python a.py` for the program `a.py`, which could generate `camera_path_scene_1.json`:
``` python
import json
import numpy as np
from pathlib import Path
import argparse

def ind(c2w):
    if len(c2w) == 3:
        c2w += [[0, 0, 0, 1]]
    return c2w

parser = argparse.ArgumentParser(')
parser.add_argument("--scene", type=str, required=True)
args = parser.parse_args()   

scene = args.scene
train_transforms = json.loads(open('poses_{}/transforms_train.json'.format(scene)).read())
# eval_transforms = json.loads(open('poses/transforms_eval.json').read())
# transforms = train_transforms + eval_transforms
transforms = train_transforms
transforms = sorted(transforms, key=lambda x: Path(x['file_path']).stem)

out = {
        'camera_type': 'perspective',
        'render_height': 567,
        'render_width': 1008,
        'seconds': len(transforms),
        'camera_path': [
            {'camera_to_world': ind(pose['transform']), 'fov': 50, 'aspect': 1, 'file_path': pose['file_path']}
            for pose in transforms
            ]
        }

outstr = json.dumps(out, indent=4)
with open('camera_path_{}.json'.format(scene), mode='w') as f:
    f.write(outstr)
```

5. Finally, combining the camera path and the trained Nerfacto, run `ns-render camera-path --load-config /path/to/config.yml --rendered-output-names rgb --camera-path-filename camera_path_scene_1.json --output-format images --output-path scene_1_rgb

6. All the training views could be rendered by command in step 5. But something wrong happened:

<img width="1022" alt="1" src="https://github.com/nerfstudio-project/nerfstudio/assets/47494256/e15e2043-0b16-415f-b8f7-e4303b9cbe18">

Result: It's obvious that the rendered image doesn't match the corresponding image in training set, even the view is exactly same as the training view. 

I don't know what is the cause of this mismatch. Is there any argument or parameter which could be set to avoid this result? Thank you!

**Comment by brentyi** [comment]
Hi! To confirm: does the value of `fov` (which it looks like you set to `50`) match the FOV of your training camera intrinsics?

**Comment by halo2718** [comment]
@brentyi Thank you! I noticed that the value of `fov` in rendering process is different from that in `COLMAP` process. By changing it to correct value, the problem is solved.

**Comment by Whit3Snow** [comment]
How can you check the value of 'fov' in rendering process? Can you explain more details? I have a same problem! 
Thank you!
