### ISSUE TITLE
What does `num_train_data` represent?

### ISSUE THREAD

**Issue by ShuzhaoXie** [nerfstudio-project/nerfstudio#2697]
What does `num_train_data` represent?

Line 327 in [nerfstudio/models/gaussian_splatting.py](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/models/gaussian_splatting.py#L327)

```python
self.step % reset_interval > self.num_train_data + self.config.refine_every
```

**Comment by maturk** [comment]
@ShuzhaoXie the number of training images in the dataset. Here we want to refine after seeing all the images.
