### ISSUE TITLE
colmap feature extractor error

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2706]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/125524043/e4498003-fa5c-4503-8784-3a511ffdf394)
i encounterd this error. so i tried 
ns-process-data images --data images/fox --output-dir output/fox5 --no-gpu   this works well but much slower how can i use gpu??

**Comment by dberga** [comment]
Same error here

F0124 17:45:50.528501 967920 opengl_utils.cc:56] Check failed: context_.create() 
*** Check failure stack trace: ***                                                                   
    @     0x7ff41d56c1c3  google::LogMessage::Fail()                     
    @     0x7ff41d57125b  google::LogMessage::SendToLog()             
    @     0x7ff41d56bebf  google::LogMessage::Flush()                          
    @     0x7ff41d56c6ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x55e513a0430c  colmap::OpenGLContextManager::OpenGLContextManager()
    @     0x55e513909d45  colmap::internal::SiftFeatureExtractorThread::SiftFeatureExtractorThread()
    @     0x55e51390c126  colmap::SiftFeatureExtractor::SiftFeatureExtractor()                                                                                                                             
    @     0x55e513806615  RunFeatureExtractor()
    @     0x55e5137f2eaf  main
    @     0x7ff41b754083  __libc_start_main
    @     0x55e5137f6f6e  _start
Aborted

**Comment by dberga** [comment]
> ![image](https://private-user-images.githubusercontent.com/125524043/292817625-e4498003-fa5c-4503-8784-3a511ffdf394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjYxMDgsIm5iZiI6MTcwNzgyNTgwOCwicGF0aCI6Ii8xMjU1MjQwNDMvMjkyODE3NjI1LWU0NDk4MDAzLWZhNWMtNDUwMy04Nzg0LTNhNTExZmZkZjM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWFhOTA0NDNkYWU1MDE1ODIwN2Q3MmE0ZjgxMDFjMmFlNjI3OTc2ZDdlODc3MDI4OTMzNjcyMTIxYWYzOTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F3QcCqxrLpMMXHi-2JXvJpMEyUPn_4rIY9RaCpIoTT0) i encounterd this error. so i tried ns-process-data images --data images/fox --output-dir output/fox5 --no-gpu this works well but much slower how can i use gpu??

I could manage to fix this. What you should do is to compile the colmap on your device. (make sure if you use conda to be on your base environment):
```
git clone https://github.com/colmap/colmap.git
cd colmap
mkdir build
cd build
cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
sudo chown -R $(whoami) .
ninja
sudo ninja install
```

**Comment by hanjoonwon** [comment]
> > ![image](https://private-user-images.githubusercontent.com/125524043/292817625-e4498003-fa5c-4503-8784-3a511ffdf394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjYxMDgsIm5iZiI6MTcwNzgyNTgwOCwicGF0aCI6Ii8xMjU1MjQwNDMvMjkyODE3NjI1LWU0NDk4MDAzLWZhNWMtNDUwMy04Nzg0LTNhNTExZmZkZjM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWFhOTA0NDNkYWU1MDE1ODIwN2Q3MmE0ZjgxMDFjMmFlNjI3OTc2ZDdlODc3MDI4OTMzNjcyMTIxYWYzOTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F3QcCqxrLpMMXHi-2JXvJpMEyUPn_4rIY9RaCpIoTT0) i encounterd this error. so i tried ns-process-data images --data images/fox --output-dir output/fox5 --no-gpu this works well but much slower how can i use gpu??
> 
> I could manage to fix this. What you should do is to compile the colmap on your device. (make sure if you use conda to be on your base environment):
> 
> ```
> git clone https://github.com/colmap/colmap.git
> cd colmap
> mkdir build
> cd build
> cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
> sudo chown -R $(whoami) .
> ninja
> sudo ninja install
> ```

Thanks! I have one question addtionally, my desktop colmap version 3.7 and laptop is 3.10 dev  when i process custom images, desktop match 88 % but laptop matches 3%... is it normal?

**Comment by dberga** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/125524043/292817625-e4498003-fa5c-4503-8784-3a511ffdf394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjYxMDgsIm5iZiI6MTcwNzgyNTgwOCwicGF0aCI6Ii8xMjU1MjQwNDMvMjkyODE3NjI1LWU0NDk4MDAzLWZhNWMtNDUwMy04Nzg0LTNhNTExZmZkZjM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWFhOTA0NDNkYWU1MDE1ODIwN2Q3MmE0ZjgxMDFjMmFlNjI3OTc2ZDdlODc3MDI4OTMzNjcyMTIxYWYzOTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F3QcCqxrLpMMXHi-2JXvJpMEyUPn_4rIY9RaCpIoTT0) i encounterd this error. so i tried ns-process-data images --data images/fox --output-dir output/fox5 --no-gpu this works well but much slower how can i use gpu??
> > 
> > 
> > I could manage to fix this. What you should do is to compile the colmap on your device. (make sure if you use conda to be on your base environment):
> > ```
> > git clone https://github.com/colmap/colmap.git
> > cd colmap
> > mkdir build
> > cd build
> > cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
> > sudo chown -R $(whoami) .
> > ninja
> > sudo ninja install
> > ```
> 
> Thanks! I have one question addtionally, my desktop colmap version 3.7 and laptop is 3.10 dev when i process custom images, desktop match 88 % but laptop matches 3%... is it normal?

That might be related to the version or parametization defining how strict is the matching. Low matching (3%) shown in colmap is not wrong. 

Did you try hloc? Apparently it has a higher matching probability.

**Comment by hanjoonwon** [comment]
> > > > ![image](https://private-user-images.githubusercontent.com/125524043/292817625-e4498003-fa5c-4503-8784-3a511ffdf394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjYxMDgsIm5iZiI6MTcwNzgyNTgwOCwicGF0aCI6Ii8xMjU1MjQwNDMvMjkyODE3NjI1LWU0NDk4MDAzLWZhNWMtNDUwMy04Nzg0LTNhNTExZmZkZjM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWFhOTA0NDNkYWU1MDE1ODIwN2Q3MmE0ZjgxMDFjMmFlNjI3OTc2ZDdlODc3MDI4OTMzNjcyMTIxYWYzOTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F3QcCqxrLpMMXHi-2JXvJpMEyUPn_4rIY9RaCpIoTT0) i encounterd this error. so i tried ns-process-data images --data images/fox --output-dir output/fox5 --no-gpu this works well but much slower how can i use gpu??
> > > 
> > > 
> > > I could manage to fix this. What you should do is to compile the colmap on your device. (make sure if you use conda to be on your base environment):
> > > ```
> > > git clone https://github.com/colmap/colmap.git
> > > cd colmap
> > > mkdir build
> > > cd build
> > > cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
> > > sudo chown -R $(whoami) .
> > > ninja
> > > sudo ninja install
> > > ```
> > 
> > 
> > Thanks! I have one question addtionally, my desktop colmap version 3.7 and laptop is 3.10 dev when i process custom images, desktop match 88 % but laptop matches 3%... is it normal?
> 
> That might be related to the version or parametization defining how strict is the matching. Low matching (3%) shown in colmap is not wrong. Try same version of colmap to make sure that it is not something related to the computer.
> 
> Did you try hloc? Apparently it has a higher matching probability.

Oh is it campatible with nerfstudio? Thanks

**Comment by dberga** [comment]
> > > > > ![image](https://private-user-images.githubusercontent.com/125524043/292817625-e4498003-fa5c-4503-8784-3a511ffdf394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjYxMDgsIm5iZiI6MTcwNzgyNTgwOCwicGF0aCI6Ii8xMjU1MjQwNDMvMjkyODE3NjI1LWU0NDk4MDAzLWZhNWMtNDUwMy04Nzg0LTNhNTExZmZkZjM5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMjAzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWFhOTA0NDNkYWU1MDE1ODIwN2Q3MmE0ZjgxMDFjMmFlNjI3OTc2ZDdlODc3MDI4OTMzNjcyMTIxYWYzOTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F3QcCqxrLpMMXHi-2JXvJpMEyUPn_4rIY9RaCpIoTT0) i encounterd this error. so i tried ns-process-data images --data images/fox --output-dir output/fox5 --no-gpu this works well but much slower how can i use gpu??
> > > > 
> > > > 
> > > > I could manage to fix this. What you should do is to compile the colmap on your device. (make sure if you use conda to be on your base environment):
> > > > ```
> > > > git clone https://github.com/colmap/colmap.git
> > > > cd colmap
> > > > mkdir build
> > > > cd build
> > > > cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=native
> > > > sudo chown -R $(whoami) .
> > > > ninja
> > > > sudo ninja install
> > > > ```
> > > 
> > > 
> > > Thanks! I have one question addtionally, my desktop colmap version 3.7 and laptop is 3.10 dev when i process custom images, desktop match 88 % but laptop matches 3%... is it normal?
> > 
> > 
> > That might be related to the version or parametization defining how strict is the matching. Low matching (3%) shown in colmap is not wrong. Try same version of colmap to make sure that it is not something related to the computer.
> > Did you try hloc? Apparently it has a higher matching probability.
> 
> Oh is it campatible with nerfstudio? Thanks

yes, check https://docs.nerf.studio/reference/cli/ns_process_data.html

the `--sfm-tool` parameter is for selecting either colmap or hloc
