### ISSUE TITLE
Gaussian Splat export failing due to assertion error

### ISSUE THREAD

**Issue by Anirudh-Kakarlapudi** [nerfstudio-project/nerfstudio#2708]
1. The `data` folder contains `images` and `colmap/sparse/0` folder. I trained a gaussian splatting model using the following commands.
`ns-train gaussian-splatting --output-dir ./output --data ./data`

2. When I tried to export the pointcloud, using the following commands, `ns-export pointcloud --load-config output/gaussian-splatting/2023-12-28_155035/config.yml --output-dir ./gauss --normal-method open3d` I am getting the following error. 

![Screenshot from 2023-12-28 21-49-57](https://github.com/nerfstudio-project/nerfstudio/assets/43009364/9e536c61-a9d4-429a-9ef2-ad2558313de5)

Did anyone else face the same issue? How to resolve it? Any pointers or guidance would help me a great deal as I am stuck at this point.

**Comment by maturk** [comment]
i think ns-export pointcloud for gaussian-splatting models doesnt work right now. You can try exporting the gaussians as a ply file with `ns-export gaussian-splat ...`

**Comment by Anirudh-Kakarlapudi** [comment]
Thanks, it works now.

**Comment by maturk** [comment]
> Thanks, it works now.

which method did you try?

**Comment by rowellz** [comment]
I am getting a similar issue but when i try to export as a gaussian-splat .ply. Both recommended export commands for pcd & meshs work, however
