### ISSUE TITLE
ZeroDivisionError in Viewer

### ISSUE THREAD

**Issue by vincenzorin** [nerfstudio-project/nerfstudio#2724]
**Describe the bug**
After the training, while viewing the generated model via ns-view on my browsers, the visualisation is interrupted with the following error showing in the console:

```
Exception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\miniconda3\envs\nerfstudio\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\GIT\nerfstudio\nerfstudio\viewer\server\render_state_machine.py", line 190, in run
    outputs = self._render_img(action.cam_msg)
  File "C:\GIT\nerfstudio\nerfstudio\viewer\server\render_state_machine.py", line 171, in _render_img
    name=EventName.VIS_RAYS_PER_SEC, duration=num_rays / render_time, step=step, avg_over_steps=True
ZeroDivisionError: float division by zero
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Train using nerfacto-big or nerfacto-huge with a decently sized set of images.
2. At training time or after the training is completed through the ns-view, walk through the scene for a few seconds (rotating+WASD)
3. See an error in the console when the viewer in the browser freezes.

**Expected behaviour**
Not dividing by zero/not freezing the viewer.

**Additional context**
The dataset is composed of 520 photos, each having 4240x2832 pixels. 

Trained and viewed on:

- CPU 13th Gen Intel(R) Core(TM) i7-13700K 
- 128 GB RAM DDR4
- NVIDIA GeForce RTX 4090
Driver version:	31.0.15.4633
Driver date:	06/12/2023
DirectX version:	12 (FL 12.1)
Physical location:	PCI bus 1, device 0, function 0
Dedicated GPU memory	14.4/24.0 GB
Shared GPU memory	0.2/63.9 GB
GPU Memory	14.7/87.9 GB

Error reproduced on Firefox 121.0 and Chrome Version 120.0.6099.131 on Winver 23H2 22631.2861.

The error appears to be similar to https://github.com/nerfstudio-project/nerfstudio/issues/436 (solved)

---

On a side note, thank you for your excellent work!

**Comment by leifvan** [comment]
Hi, I experienced this bug as well using nerfacto-big and a dataset of 470 photos (3456x4608). The nerfstudio version I used is 0.3.4.  However, the bug seems to be fixed in the latest development version, as a check to prevent a division by zero was added here:

https://github.com/nerfstudio-project/nerfstudio/blob/c27b5cb65feb9b4f3c1689392297fb3bffd55c65/nerfstudio/viewer/render_state_machine.py#L193

**Comment by vincenzorin** [comment]
Thanks for the feedback. I tried yesterday with a newer version (not on my current computer, so I can't check the version) but it appeared to be fixed in one of the latest versions.
I'll close it for now.
