### ISSUE TITLE
Cache images in byte instead of float32 in GS training/eval

### ISSUE THREAD

**Issue by jb-ye** [nerfstudio-project/nerfstudio#2735]
**Is your feature request related to a problem? Please describe.**
When training GS with large number of images (>1000), caching images consumes a lot memory even for CPU mem. It is because the current cached images are preprocessed as float32 tensors. See `InputDataset.get_image()` function. If those images are cached as bytes, we would be 4x more memory efficient and allow to run GS on lower end machines. 

**Describe the solution you'd like**
Add a feature to allow caching images in bytes and do `image / 255.` only fly during training.

**Describe alternatives you've considered**
No.

**Additional context**
for an image with 1600x1600x3, caching 1000 images in bytes consumes about 7.7GB, while caching them in float32 consumes 4 times more.

**Comment by kerrj** [comment]
Sounds good to me, my only worry would be a slowdown having to cast every image back to float for training. It shouldn't be that expensive but would be good to measure before merging

**Comment by ichsan2895** [comment]
> Sounds good to me, my only worry would be a slowdown having to cast every image back to float for training. It shouldn't be that expensive but would be good to measure before merging

Maybe we can trigger this function if the dataset is too Big?
When data is small, its using default float32. But, if they are potentially OOM CUDA caused by large dataset, it automatically cache the image by bytes.

IMO, Its better slowdown training (in large dataset) instead of OOM CUDA.
