### ISSUE TITLE
how to improve mesh quailty?

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2747]
I trained with these pipelines, but the surface mesh quality was poor. How can I get a better quality mesh?
ns-train nerfacto --pipeline.model.predict-normals True --data output/scan --pipeline.datamanager.train-num-rays-per-batch 2000

**Comment by anniezhang2288** [comment]
One way to get a better quality mesh is to try out [Nerf2Mesh](https://nerf2nerf.github.io/). It takes the density field of the NeRF and applies the marching cubes algorithm to obtain a coarse surface mesh. Utilizing iterative mesh refinement, it converts the coarse mesh to a fine mesh, creating a higher resolution output
