### ISSUE TITLE
How to train a Gaussian model using a background-removed dataset?

### ISSUE THREAD

**Issue by GuoFengYung** [nerfstudio-project/nerfstudio#2764]
**Describe**
I use the GS model to train the transparency dataset, but the trained background has many clouds.
**Screenshots**
![Screenshot from 2024-01-15 14-14-17](https://github.com/nerfstudio-project/nerfstudio/assets/43314406/ddee90e5-0df3-4a5d-8f09-ac57086e8232)

**Comment by brentyi** [comment]
Not my area of expertise, but https://github.com/nerfstudio-project/gsplat/pull/70 seems relevant!

**Comment by GuoFengYung** [comment]
thank you for your reply！
I will researching it

**Comment by KevinXu02** [comment]
A fast but inelegant method is to directly inject white bg colour into GS model, I've test it with LEGO dataset in #2704. I think the main problem is that when training GS model the bg colour is ramdomly picked, we may need a alpha for the bg and add it into the BP and FP I think? https://github.com/nerfstudio-project/gsplat/pull/70 seems only apply alpha output to gaussians? but may immediately work with a little modification.

**Comment by GuoFengYung** [comment]
Yes, I currently use a white background to run training
