### ISSUE TITLE
Can nerfstudio's implementation of gaussian splatting pass gradients to the camera pose, thus optimizing the camera pose like nerfacto does?

### ISSUE THREAD

**Issue by Bin-ze** [nerfstudio-project/nerfstudio#2766]
Very great implementation！

I noticed that 3dgs is supported by nerfstudio, so wanted to know if the posture optimization method provided by nerfstudio is also supported on 3dgs？

I try to train 3dgs like this:

      CUDA_VISIBLE_DEVICES=1 ns-train gaussian-splatting --data colmap_data --pipeline.model.camera-optimizer.mode SE3

Although there is a configuration for camera posture optimization in the configuration file, I don't know how to observe such an impact from the results. For example, can I observe the camera's position movement trajectory in the viewer?

**Comment by akristoffersen** [comment]
You currently cannot observe the optimized cameras in the viewer, though that would be a great addition. Gradients are also not computed for the parameters generated from the camera parameters in [gsplat.project_gaussians](https://github.com/nerfstudio-project/gsplat/blob/e8696bd7d7669f84e1add2733d3798f96c800919/gsplat/project_gaussians.py#L195), so I don't think pose optimization would work without updating gsplat code.

**Comment by brentyi** [comment]
> You currently cannot observe the optimized cameras in the viewer

Optimized cameras are now actually visualized in the new viewer! Thanks to efforts from @kerrj :)
