### ISSUE TITLE
Nerfstudio to MLflow: Challenges in Instantiating Nerfacto Models

### ISSUE THREAD

**Issue by andygma567** [nerfstudio-project/nerfstudio#2768]
**Description:**

I'm currently exploring ways to integrate Nerfstudio and its resulting Nerfacto models into an MLflow workflow for model registration purposes. My approach involves reloading the trained model weights into a PyTorch model instance using `torch.load` and subsequently logging the model via the PyTorch model flavor in MLflow ([MLflow PyTorch Model flavor documentation](https://mlflow.org/docs/latest/models.html#pytorch-pytorch)).

However, I'm encountering a stumbling block. To instantiate a Nerfacto model, it seems necessary to supply a "config," a "scene box," and a value for "num_train_data" (for reference: [NerfactoModel class definition](https://github.com/nerfstudio-project/nerfstudio/blob/3e2271a6563d76d06c0fc27c8e23440914e6020f/nerfstudio/models/nerfacto.py#L134C28-L135C1), [Model class definition](https://github.com/nerfstudio-project/nerfstudio/blob/3e2271a6563d76d06c0fc27c8e23440914e6020f/nerfstudio/models/base_model.py#L58)). Post-training, the Nerfstudio's output directory provides a `config.yml` but lacks explicit references to a "scene box" or "num_train_data." These elements don't appear to be in the `config.yml` either.

Here’s the structure of the `outputs/` directory post-training:
```
outputs
└── nerfacto
    └── 2024-01-06_073408
        ├── config.yml
        ├── dataparser_transforms.json
        └── nerfstudio_models
            └── step-000029999.ckpt
```

I've drafted a loading script, but it's currently raising errors because I don't know how to provide the "scene_box" and "num_train_data" arguments:
```python
import yaml
from pathlib import Path
import torch.optim.adam  # for Adam optimizer

# Nerfstudio imports
from nerfstudio.engine.trainer import TrainerConfig, Trainer
from nerfstudio.configs.base_config import LoggingConfig, LocalWriterConfig, MachineConfig, ViewerConfig
from nerfstudio.utils.writer import LocalWriter, EventName
from nerfstudio.engine.optimizers import AdamOptimizerConfig
from nerfstudio.engine.schedulers import ExponentialDecayScheduler, ExponentialDecaySchedulerConfig
from nerfstudio.pipelines.base_pipeline import VanillaPipelineConfig, VanillaPipeline
from nerfstudio.data.datamanagers.base_datamanager import VanillaDataManagerConfig, VanillaDataManager
from nerfstudio.cameras.camera_optimizers import CameraOptimizerConfig, CameraOptimizer
from nerfstudio.data.utils.nerfstudio_collate import nerfstudio_collate
from nerfstudio.data.dataparsers.nerfstudio_dataparser import NerfstudioDataParserConfig, Nerfstudio
from nerfstudio.data.pixel_samplers import PixelSamplerConfig, PixelSampler
from nerfstudio.models.nerfacto import NerfactoModelConfig, NerfactoModel


# Load the YAML file
with open('path/to/config.yml', 'r') as file:
    nerf_config = yaml.load(file, Loader=yaml.Loader)

# Now `nerf_config` should be an instance of the deserialized Python object
print(nerf_config)

# Access the `pipeline` section of the config
nerfacto_model_config = nerf_config.pipeline.model
print(nerfacto_model_config)

# This doesn't work. I get the following error message:
# ---------------------------------------------------------------------------
# TypeError                                 Traceback (most recent call last)
# Cell In[9], line 1
# ----> 1 model = NerfactoModel(nerfacto_model_config)

# TypeError: Model.__init__() missing 2 required positional arguments: 'scene_box' and 'num_train_data'
model = NerfactoModel(nerfacto_model_config)
```
---
The error is a `TypeError`, indicating missing arguments for 'scene_box' and 'num_train_data'.

I'm seeking guidance on two fronts:
1. How to correctly instantiate a Nerfacto model with the available information.
2. Suggestions for a more streamlined method of logging a trained Nerfacto model into MLflow's model registry.

Any insights or alternative strategies would be greatly appreciated. :pray: :slightly_smiling_face:

**Comment by brentyi** [comment]
These are both dataset-dependent.

How they're computed in the typical Nerfstudio pipeline might be helpful: https://github.com/nerfstudio-project/nerfstudio/blob/3e2271a6563d76d06c0fc27c8e23440914e6020f/nerfstudio/pipelines/base_pipeline.py#L271-L272

If you want to instantiate the model without the full pipeline, perhaps you could save these values at the start of training?

For example, you could add a few lines below where the `dataparser_transforms.json` is saved:
https://github.com/nerfstudio-project/nerfstudio/blob/3e2271a6563d76d06c0fc27c8e23440914e6020f/nerfstudio/engine/trainer.py#L227-L233
