### ISSUE TITLE
[GaussianSplat] Default GS option `load_3D_points=True` was not set when colmap subcommand is triggered

### ISSUE THREAD

**Issue by jb-ye** [nerfstudio-project/nerfstudio#2789]
**Describe the bug**

For gaussian splat training config, we have `load_3D_points=True` set as this line: https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/configs/method_configs.py#L603

However, this option is by default as [False](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/dataparsers/colmap_dataparser.py#L90) in ColmapDataparser, and when user trigger `colmap` subcommand to configure the loader, the user may not be aware that he must set this option to True to get the best results. Otherwise, random point initialization is used instead.

I found for people who are not familiar how GS works, this is very tricky to configure the loader properly. 

**To Reproduce**
Run `ns-train gaussian-splatting --data <...> ` which loads 3D points properly and
Run `ns-train gaussian-splatting --data <...> colmap --downscale_factor=1` which doesn't load 3D points from colmap data.

**Expected behavior**
Throw a warning message in gaussian-splatting to indicate user to set `--load_3D_points=True` when he is training gaussian splatting or prompt the user to load it.

**Comment by brentyi** [comment]
actually, not sure that this is fixed...
