### ISSUE TITLE
Add Zip-Nerf

### ISSUE THREAD

**Issue by MohamedAliRashad** [nerfstudio-project/nerfstudio#2803]
Google has released the code of Zip-Nerf here:
https://jonbarron.info/zipnerf/

**Comment by maturk** [comment]
@MohamedAliRashad it is usually pretty hard reimplementing papers, see how long gsplat took xD

**Comment by MohamedAliRashad** [comment]
@maturk I don't think reimplementation will be required because they released the codes.

**Comment by maturk** [comment]
There is a branch in nerfstudio that has tried to implement the full zip-nerf algorithm [here](https://github.com/nerfstudio-project/nerfstudio/pull/2242). This was before the code release a few months ago. I am not sure if it will be updated now that the code is public.

**Comment by MohamedAliRashad** [comment]
@maturk The link in the project directs to a repo created two days ago:
https://github.com/jonbarron/camp_zipnerf

Maybe its a new (simpler) code.

**Comment by jb-ye** [comment]
It would be worthwhile to put a thin wrapper around camp_zipnerf and create a method external to nerfstudio following https://github.com/nerfstudio-project/nerfstudio-method-template 

So for anyone who might be interested in trying camp_zipnerf in the same framework as nerfstudio, it is easier.

**Comment by ichsan2895** [comment]
I want that be implemented too, but I don't understand coding which is too technical. 

BTW, Imagine,
we have `ns-process-data camp` for better result instead of `ns-processed-data images`. `ns-train splatfacto` with `--load-3D-points=True` itself is already good. What happen if we use it with Camp?

**Comment by michaelpayne02** [comment]
[Jon says](https://x.com/jon_barron/status/1748931869083914667?s=46) CamP’s poses can be exported, meaning that portion could be easy to plug in.

**Comment by jb-ye** [comment]
https://docs.nerf.studio/nerfology/methods/zipnerf.html
