### ISSUE TITLE
Can not train nerfacto-big

### ISSUE THREAD

**Issue by ewrfcas** [nerfstudio-project/nerfstudio#2809]
When I run the command ```ns-train nerfacto-big --data xxxx```, it shows 
```
Argument {nerfacto,instant-ngp,mipnerf,semantic-nerfw,vanilla-nerf,tensorf}: │
│ invalid choice: 'nerfacto-big' (choose from 'nerfacto', 'instant-ngp',       │
│ 'mipnerf', 'semantic-nerfw', 'vanilla-nerf', 'tensorf')
```

But when I change ```nerfacto-big``` back to ```nerfacto```, everything is right.

**Comment by brentyi** [comment]
Hi! Can you confirm which version/commit of nerfstudio you're on?

**Comment by ewrfcas** [comment]
> Hi! Can you confirm which version/commit of nerfstudio you're on?

Sure. My system is Centos7 and the nerfacto version is 0.1.8. It seems that nerfacto could not be updated to the latest version because open3d>=0.16 is not supported in Centos7.

**Comment by ewrfcas** [comment]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/12042259/2d0de3fd-caa3-4d16-8b0a-44c7cdc077da)

**Comment by brentyi** [comment]
Hm, maybe try Python 3.9 or 3.10? Alternatively, you can try installing from source with `open3d` removed from the dependencies for now, it's not critical for most operations.

**Comment by ewrfcas** [comment]
Thanks. I force to install nerfstudio==1.0.0 without open3d>=0.16.0. It works well now!
