### ISSUE TITLE
Background color in splatfacto renders can be random if no crop is set

### ISSUE THREAD

**Issue by kerrj** [nerfstudio-project/nerfstudio#2815]
**Describe the bug**
When rendering splatfacto, if a crop isn't set the background color will be random

**To Reproduce**
`ns-render` any splatfacto model where the background is poorly defined (ie underreconstructed)

**Expected behavior**
same color as viewer will be in background

**Screenshots**
See orange in background of this scene
<img width="500" alt="Screenshot 2024-01-23 at 4 56 26 PM" src="https://github.com/nerfstudio-project/nerfstudio/assets/15806475/f3b33cb8-7364-46b1-9cc9-53bd3a6903c3">

**Additional context**
in render.py, BACKGROUND_COLOR_OVERRIDE is only set if the crop is set, this should be set whether the crop is used or not.

**Comment by KevinXu02** [comment]
Hi! Could you check #2827 with the "flip" bg option on?

**Comment by brentyi** [comment]
@KevinXu02 my understanding of the problem here is that the background is randomized during rendering for both training and exporting/evaluating, whereas we only want the former. This seems a bit different from what the `flip` option you're proposing tries to do, right?

**Comment by KevinXu02** [comment]
Oh I know. Maybe we should just set the the background color to white or the viser color besides training to fix this.

**Comment by KevinXu02** [comment]
> Oh I see. Maybe we should just set the the background color to viser color besides training to fix this. PR is updated to set the initialized background color the same as viser. The should won't affect training.

Tested and it should be working.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/50019703/fda4c50d-858e-4d7a-b242-a1cdca890421)

**Comment by kerrj** [comment]
#2831 patched this
