### ISSUE TITLE
Why nerfstudio support viewer and viewer_legacy?

### ISSUE THREAD

**Issue by zjcs** [nerfstudio-project/nerfstudio#2836]
When I read the nerfstudio code, there are two different viewer:
1. Viewer in viewer subdirectory
2. ViewerLegacyState in viewer_legacy subdirectory

It seems like ViewerLegacyState is similar to Viewer and have same UI. But viewer_legacy has extra NodeJS projection under the viewer_legacy/app subdirectory.

My Question is that:
1. The difference between Viewer and ViewerLegacyState, their design for what?
2. NodeJS project under viewer_legacy/app subdirectory is for what?

**Comment by tancik** [comment]
With the release of version 1.0, we shifted the viewer to use [viser](https://github.com/nerfstudio-project/viser) which was redesigned from the ground up to be more modular and extendable. The original viewer provided in nerfstudio was hacked together by a group of us that had minimal background in web development 😄. We've kept the original for now as `viewer_legacy` for folks that aren't ready to move to the new viewer yet.

**Comment by zjcs** [comment]
Thanks for you reply, very clear. Nice Project!
