### ISSUE TITLE
Which model can extract good mesh??

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2837]
I want to get mesh better than instant ngp..
I tried to Sdfstudio but got bad mesh
Object is combined with others
<img width="502" alt="1706277534968" src="https://github.com/nerfstudio-project/nerfstudio/assets/125524043/9b9b23fc-8e50-4c15-b004-742e6352d06a">

**Comment by maturk** [comment]
try [SuGaR](https://github.com/Anttwo/SuGaR)
