### ISSUE TITLE
AttributeError when training 

### ISSUE THREAD

**Issue by ZahyElgendy** [nerfstudio-project/nerfstudio#2839]
**Describe the bug**
Error when training , Attribute Error

**To Reproduce**

1. conda activate nerfstudio
2. cd nerfstudio
3. ns-train nerfacto --data data/nerfstudio/poster

**Expected behavior**
I am trying to train the poster data however this attribute error always rises for me.
AttributeError: 'NoneType' object has no attribute 'terminate'
What could be the reason, please?

**Screenshots**
![AttributeError](https://github.com/nerfstudio-project/nerfstudio/assets/145224435/ff9099c0-6423-47e7-a44a-ef0574eea300)

**Additional context**
I have downloaded the poster data before training.

**Comment by Parmisian** [comment]
I am getting the same problem as well, both for training and viewing my former trainings. It is a new problem, I was not getting this wih the old verison of NS

**Comment by Parmisian** [comment]
Now tried with the previous version of nerfstudio by pip install nerfstudio==0.3.4; it is working without any problems

**Comment by ZahyElgendy** [comment]
> Now tried with the previous version of nerfstudio by pip install nerfstudio==0.3.4; it is working without any problems
