### ISSUE TITLE
cant connect web viewer

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2845]
windows 10, anaconda
I don't know if it's because I moved Anaconda's startup to eDrive, but I can't get into the web viewer. How do I fix it?
![image](https://github.com/nerfstudio-project/nerfstudio/assets/125524043/701e4e1f-6f4b-4738-ae18-a487ebca7c37)

**Comment by kerrj** [comment]
If you're on a remote machine make sure you're forwarding the port which the viewer is using.

**Comment by hanjoonwon** [comment]
> If you're on a remote machine make sure you're forwarding the port which the viewer is using.

I'm using local
