### ISSUE TITLE
Building the new Python viewer on a local server

### ISSUE THREAD

**Issue by itaidotan** [nerfstudio-project/nerfstudio#2869]
Hi!
Thanks for the new 1.0.0 version, looks awesome.

I'm trying to build the new viewer on a local server, as written in [the website documentation](https://docs.nerf.studio/developer_guides/viewer/local_viewer.html) but since the new viewer is written in Python, I assume the build should be done differently. The instructions are not suitable for the new version, so I would be grateful if new guide would be written in the documentation in your website, or here for starters.

Thanks a lot in advance!

**Comment by brentyi** [comment]
Hi!

Yes, this doc looks out of date; I can update it. The new viewer is actually hosted locally by default, so most of the things on that doc (like connecting to `viewer.nerf.studio` or needing Safari support) no longer apply.

There's no longer a nerfstudio-specific viewer to build. Instead, we use a pre-built version of `viser`.
There are build docs for `viser` here: https://viser.studio/development/

**Comment by itaidotan** [comment]
Thanks for the quick answer!

First of all, a new doc would be amazing.
Secondly, I ran into the viser documentation you send here, and tried to follow the instructions by going to
/nerfstudio/nerfstudio/viewer and running `python3 viewer.py` and it didn't succeed - I assume i'm doing something wrong, just don't know why. 

It's important to clarify - i'm trying to build the site on a closed network, on which I have a remote server which is not connected to the internet. I passed the docker to said network, and I want to build the site "locally" on the nerfstudio container (which is running on the server), and expose it to my local computer. With the old version it was very easy, now i'm not sure how to do it.

Thanks a lot in advance!

**Comment by brentyi** [comment]
For the doc: to clarify, the main update to make is probably just to delete that doc page. The nerfstudio viewer is now always hosted locally, there's no alternative, so "Local Server"-specific documentation just doesn't apply any more.

On `viewer.py`: unfortunately yeah, that's not a script which can be run in a standalone way like that. The usual ways we run the viewer are via `ns-train` or `ns-viewer`, both of which should work on a closed network.

I may be misunderstanding but to me it sounds like you are overcomplicating things a bit, to clarify in the old version we had:
- the viewer server @ `https://viewer.nerf.studio/...`
- the nerf server @ `ws://<your_ip>:7007`

What you seem to be trying to do is build parts of the viewer server. However, that no longer exists in the same way. In the new version of the viewer, everything is hosted at `<your_ip>:7007`:
- the viewer server @ `http://<your_ip>:7007`
- the nerf server @ `ws://<your_ip>:7007`

**Comment by itaidotan** [comment]
So, I should be able to run the website manually via "ns-viewer" or with "ns-train" from my container, and expose port 7007 to MYPORT and then I'd be able to connect to the viewer via my local chrome on: 
`http://<your_ip>:MYPORT/?websocket_url=ws://localhost:MYPORT` ?

**Comment by brentyi** [comment]
Just `http://<your_ip>:MYPORT` should work!
