### ISSUE TITLE
Splat .ply export not supported by multiple viewers

### ISSUE THREAD

**Issue by robinsonkwame** [nerfstudio-project/nerfstudio#2909]
**Describe the bug**

Documentation [here](https://docs.nerf.studio/nerfology/methods/splat.html#exporting-splats) states
---
Nerfstudio’s splat export currently supports multiple third-party splat viewers:

[Polycam Viewer](https://poly.cam/tools/gaussian-splatting)

[Playcanvas SuperSplat](https://playcanvas.com/super-splat)

[WebGL Viewer by antimatter15](https://antimatter15.com/splat/)

[Spline](https://spline.design/)

[Three.js Viewer by mkkellogg](https://github.com/mkkellogg/GaussianSplats3D)
---

but an [exported splat .ply](https://drive.google.com/file/d/1l-w5KoCviKfA3y5knl00vLPCKmFA2FrZ/view?usp=sharing) generated from a sample Lion statue video ([here](https://replicate.delivery/mgxm/42fc2c94-74c0-4eee-b7ed-727a9b611c24/LionStatue.MOV)) on 2/9 fails to be viewed properly in all 3rd party viewers but Polycam.

**To Reproduce**
1. Download sample Lion statue video ([here](https://replicate.delivery/mgxm/42fc2c94-74c0-4eee-b7ed-727a9b611c24/LionStatue.MOV))
2. run `ns-process`, `ns-train splatfacto`, and `ns-export`
3. Go to each viewer listed above
4. Upload the .ply file, compare results to polycam

**Expected behavior**
All viewers at least approximately look similar

**Screenshots**
e.g.,

Polycam
![image](https://github.com/nerfstudio-project/nerfstudio/assets/8014151/e982749f-a258-42bd-95e4-df9ff7010477)

Supersplat
![image](https://github.com/nerfstudio-project/nerfstudio/assets/8014151/c9142ae6-0aa8-436f-b5dd-ca8c318ed6e5)

**Additional context**
Even if Nerfstudio can't support the listed viewer, it would be helpful to describe any transformations and changes to exported splat .ply files that are typically required to be viewable in, say, Supersplat and other viewers. This would support frontend UI development against NerfStudio splat output.

**Comment by jb-ye** [comment]
Your splat can by rendered in supersplat ( you need to set splat size to 0 on the left panel). You just need to rotate and room a bit to see the lion ... 

The applied transform was lost in PLY exporter, if you use nerfstudio viewer, it will restore properly and see the lion on the startup frame. 

![Screenshot from 2024-02-13 16-55-22](https://github.com/nerfstudio-project/nerfstudio/assets/132313008/7d69aaf0-23f5-461a-b795-0c6701c95898)

**Comment by jb-ye** [comment]
But I agree that one should be able to see the "applied transform" and "scale" as metadata from exporter such that, one can use them to generate proper renders in external viewers.

@brentyi Do you think this is worthwhile to add a metadata json to document those information aside PLY exporter.
