### ISSUE TITLE
how to get real size mesh??

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2922]
I tried to get the same mesh as the real size and print it with 3d printer but it comes out too small unlike the real size..

**Comment by maturk** [comment]
Have you tried to rescale it back with the dataparser_transforms.json. Please see #1606

**Comment by hanjoonwon** [comment]
> Have you tried to rescale it back with the dataparser_transforms.json. Please see #1606

thank you for answer I'll check it. 
++I don't think I can see the bbox with the current viewer, what if I want to crop only the objects I want?
I can't see the bbox prediction, so should I export it while still adjusting the numbers?

**Comment by maturk** [comment]
> > Have you tried to rescale it back with the dataparser_transforms.json. Please see #1606
> 
> thank you for answer I'll check it. ++I don't think I can see the bbox with the current viewer, what if I want to crop only the objects I want? I can't see the bbox prediction, so should I export it while still adjusting the numbers?

@hanjoonwon , when exporting mesh with ns-export poisson ... just check all the other possible commands with --help. There are many options for bounding box and other filtering methods. Check the options below this line https://github.com/nerfstudio-project/nerfstudio/blob/45db2bcfabe6e0644a3a45a50ed80a9a685ddc34/nerfstudio/scripts/exporter.py#L282

**Comment by hanjoonwon** [comment]
> > > Have you tried to rescale it back with the dataparser_transforms.json. Please see #1606
> > 
> > 
> > thank you for answer I'll check it. ++I don't think I can see the bbox with the current viewer, what if I want to crop only the objects I want? I can't see the bbox prediction, so should I export it while still adjusting the numbers?
> 
> @hanjoonwon , when exporting mesh with ns-export poisson ... just check all the other possible commands with --help. There are many options for bounding box and other filtering methods. Check the options below this line
> 
> https://github.com/nerfstudio-project/nerfstudio/blob/45db2bcfabe6e0644a3a45a50ed80a9a685ddc34/nerfstudio/scripts/exporter.py#L282

Yes I have seen it and used it and exported it. I'm afraid my English is not very good, so I must have miscommunicated. I mean, I don't see the range of bboxes in the viewer or something that corresponds to the number I specified, so I don't know what number I should use to export only the part I want.

**Comment by smart4654154** [comment]
Thank you very much for your work. My question seems to be related to this job. What is the meaning of the crop scale value in the new version of viewer? I found that the value of the crop scale cannot match the coordinate values of the world coordinate system. For example, when the crop scale is set to 4, 4, 4, it is approximately equivalent to a square with a side length of 40 in the world coordinate system
![image](https://github.com/nerfstudio-project/nerfstudio/assets/152783898/cf264588-8b0c-47ed-8046-85e2f0054f8e)
What are the meanings of "crash max" and "crash min" in Viewer_legacy?
![image](https://github.com/nerfstudio-project/nerfstudio/assets/152783898/e3651e95-5706-40f7-ba87-a75ab83a1ecc)
