### ISSUE TITLE
mesh is too small

### ISSUE THREAD

**Issue by hanjoonwon** [nerfstudio-project/nerfstudio#2924]
![image](https://github.com/nerfstudio-project/nerfstudio/assets/125524043/2ffd3b03-bbbc-4f5c-871c-bc3a48cd900a)
 
  #1606 
  I saw that the mesh was too small as a result of reconstruction and rescaled it to the actual size with the following code. However, even after doing this, the mesh came out too small for the actual size. How can I solve it? My object is an 18650 lithium-ion battery.

  import json
import numpy as np
import open3d as o3d

# load transform information from dataparser_transforms.json
with open('/home/joonwon/nerfstudio/outputs/ngpbat/tensorf/2024-02-11_173437/dataparser_transforms.json', 'r') as f:
    data = json.load(f)
transform_matrix = np.array(data["transform"])
# expand a 3x4 matrix to a 4x4 matrix
transform_matrix = np.vstack((transform_matrix, [0, 0, 0, 0, 1]))
scale = data["scale"]

# load the final mesh file
mesh = o3d.io.read_triangle_mesh("/home/joonwon/nerfstudio/exports/mesh/tensorf/poisson_mesh.ply")

# Apply scale inverse transformation
mesh.scale(1 / scale, center=(0, 0, 0))

# Apply the inverse of the transform matrix to convert to the original coordinate system
transform_matrix_inv = np.linalg.inv(transform_matrix)
mesh.transform(transform_matrix_inv)

# Save the transformed mesh
o3d.io.write_triangle_mesh("/home/joonwon/nerfstudio/exports/rescale_mesh/rescale_tensorf.ply", mesh)
[dataparser_transforms.json](https://github.com/nerfstudio-project/nerfstudio/files/14318792/dataparser_transforms.json)

++ As a side note, when I first open the mesh, it restores too many dirty meshes around the object together, is there any way to fix this automatically? I've tried adjusting the bbox, but I can't see it directly in the viewer, so I don't know what value is appropriate.

**Comment by maturk** [comment]
instead of dividing by scale what happens if you multiply by scale

**Comment by maturk** [comment]
There is no bb in the viewer so you have to do some trial and error, sorry

**Comment by hanjoonwon** [comment]
> instead of dividing by scale what happens if you multiply by scale

Thank you for answer :)

When I compare the size before and after rescsle, it looks like the scale factor is applied correctly, but the size is still ridiculously small, like 0.7mm 3.5mm. Is this an intrinsic issue with the old colmap or an issue with the old process?

**Comment by maturk** [comment]
If you are using colmap to process your data, it is impossible to ever even know the true scale of the scene. Colmap does not output poses in the correct scale of the real world, everything is in an arbitrary coordinate system. This is because it is impossible to ever even obtain ground truth scale from only RGB images. The only way you can know the true scale if you use some kind of VSLAM algorithm that has real world depth data when generating your pose estimates.

**Comment by hanjoonwon** [comment]
> If you are using colmap to process your data, it is impossible to ever even know the true scale of the scene. Colmap does not output poses in the correct scale of the real world, everything is in an arbitrary coordinate system. This is because it is impossible to ever even obtain ground truth scale from only RGB images. The only way you can know the true scale if you use some kind of VSLAM algorithm that has real world depth data when generating your pose estimates.

For Instant ngp, it seems to come out close to the actual size, but since I can't get the ground truth with ns-process of a typical image, do I need to resize it with a tool like meshlab?

**Comment by maturk** [comment]
> > If you are using colmap to process your data, it is impossible to ever even know the true scale of the scene. Colmap does not output poses in the correct scale of the real world, everything is in an arbitrary coordinate system. This is because it is impossible to ever even obtain ground truth scale from only RGB images. The only way you can know the true scale if you use some kind of VSLAM algorithm that has real world depth data when generating your pose estimates.
> 
> For Instant ngp, it seems to come out close to the actual size, but since I can't get the ground truth with ns-process of a typical image, do I need to resize it with a tool like meshlab?

It is not possible to reconstruct correct metric poses with colmap. You need some additional information. You can manually resize it if you want (scale it by some numbers to match whatever size you desire in the real world).

**Comment by maturk** [comment]
@hanjoonwon please dont make more issues about this same problem. The problem is that when you just take photos using your camera, there is no way to know the real scale of the scene from only RGB images. The scale ambiguity is a fundamental characteristic of perspective projection (i.e. how 3D world makes 2D images), and it means that the reconstructed scene can be scaled uniformly without changing the projected image, which means it is impossible to get the metric scale of the 3D world from just 2D images without any other prior information about the scene. You can manually rescale the mesh if you want, but it is not physically possible to get metric scales by just using colmap dataprocessing.

**Comment by maturk** [comment]
If you want metric scaled exports, you need metric scaled poses. To do this, you need to use RGBD SLAM or some other technique that uses **depth** data when estimating camera poses.

**Comment by hanjoonwon** [comment]
> @hanjoonwon please dont make more issues about this same problem. The problem is that when you just take photos using your camera, there is no way to know the real scale of the scene from only RGB images. The scale ambiguity is a fundamental characteristic of perspective projection (i.e. how 3D world makes 2D images), and it means that the reconstructed scene can be scaled uniformly without changing the projected image, which means it is impossible to get the metric scale of the 3D world from just 2D images without any other prior information about the scene. You can manually rescale the mesh if you want, but it is not physically possible to get metric scales by just using colmap dataprocessing.

I'm sorry, I think I misused issues due to my lack of basic knowledge. Thank you for your kind reply. 
I guess it was a coincidence or mistake that I thought the Instanr ngp mesh was life-size.

**Comment by maturk** [comment]
> > @hanjoonwon please dont make more issues about this same problem. The problem is that when you just take photos using your camera, there is no way to know the real scale of the scene from only RGB images. The scale ambiguity is a fundamental characteristic of perspective projection (i.e. how 3D world makes 2D images), and it means that the reconstructed scene can be scaled uniformly without changing the projected image, which means it is impossible to get the metric scale of the 3D world from just 2D images without any other prior information about the scene. You can manually rescale the mesh if you want, but it is not physically possible to get metric scales by just using colmap dataprocessing.
> 
> I'm sorry, I think I misused issues due to my lack of basic knowledge. Thank you for your kind reply. I guess it was a coincidence or mistake that I thought the Instanr ngp mesh was life-size.

It is most likely just a considence that the poses in instant-ngp happened to line up with the real world poses. Colmap outputs arbitrary scaled poses so it is possible that they closely line up sometimes, but this is not generally the case.

**Comment by smart4654154** [comment]
Thank you very much for your work. My question seems to be related to this job. What is the meaning of the crop scale value in the new version of viewer? I found that the value of the crop scale cannot match the coordinate values of the world coordinate system. For example, when the crop scale is set to 4, 4, 4, it is approximately equivalent to a square with a side length of 40 in the world coordinate system
![image](https://github.com/nerfstudio-project/nerfstudio/assets/152783898/cf264588-8b0c-47ed-8046-85e2f0054f8e)
What are the meanings of "crash max" and "crash min" in Viewer_legacy?
![image](https://github.com/nerfstudio-project/nerfstudio/assets/152783898/e3651e95-5706-40f7-ba87-a75ab83a1ecc)
