### ISSUE TITLE
ns-eval eyefultower dataset issue

### ISSUE THREAD

**Issue by LinijaVP** [nerfstudio-project/nerfstudio#2933]
When using ns-eval on a instant-ngp model trained on the eyeful dataset office_view2, this error shows. I can find the splits.json file in the folder above the quality of image folder from eyeful tower dataset but it does nothing, even when moved. 

The error:
raise RuntimeError(f"The dataset's list of filenames for split {split} is missing.")
RuntimeError: The dataset's list of filenames for split test is missing.

**Comment by liuyuex97** [comment]
> When using ns-eval on a instant-ngp model trained on the eyeful dataset office_view2, this error shows. I can find the splits.json file in the folder above the quality of image folder from eyeful tower dataset but it does nothing, even when moved.
> 
> The error: raise RuntimeError(f"The dataset's list of filenames for split {split} is missing.") RuntimeError: The dataset's list of filenames for split test is missing.

Were yo uable to train on fisheye scenes like table?

**Comment by LinijaVP** [comment]
Yes there was nothing wrong with the training. I figured out what the issue was. The eyefultower dataset transforms.json does not include "test_filenames:{...}", however in the splits.json file the test filenames are given and they are the same as the "val_filenames:{...}" in transforms.json so I just copied the val section and renamed it and it worked.

**Comment by 7Kuku7** [comment]
> > 在 eyeful 数据集 office_view2 上训练的 instant-ngp 模型上使用 ns-eval 时，会显示此错误。我可以在 eyeful tower 数据集中 quality of image 文件夹上方的文件夹中找到 splits.json 文件，但即使移动了，它也没有任何作用。
> > 错误：raise RuntimeError（f“The dataset's list of filenames for split {split} is missing.”）RuntimeError：缺少用于拆分测试的数据集文件名列表。
> 
> 嗨，您能够在桌子等鱼眼场景上进行训练吗？

Hi, I was barely able to complete the reconstruction on the table scene, but not on the other scenes shot with the v1 fisheye camera, can you do the same? Have you solved this problem yet?
