### ISSUE TITLE
Out of memory using ns-render with splatfacto for large datasets

### ISSUE THREAD

**Issue by sweeneychris** [nerfstudio-project/nerfstudio#2971]
**Describe the bug**
I'm running the splatfacto method with Project Aria data using 1408x1408 images as input from a long video sequence. This trains fine using out-of-core sampling of the dataset and I can visualize the results in the Viser viewer perfectly. However, when I try to use ns-render to render out the dataset cameras it runs out of memory.  cc @brentyi 

**To Reproduce**
1. Train splatfactor with a large dataset (1000s of high res images)
2. Call ns-render dataset to render the dataset images with the trained model
3. CPU memory should explode and the process will be killed or your machine will freeze

**Expected behavior**
Here's what I think might be happening -- the ns-render seems to use the FullImagesDatamanager which attempts to cache *all* undistorted images in memory. This unnecessarily causes memory to explode during the rendering process.

A better solution would be to only load a fixed # of images at a time before rendering out, or otherwise manage the cache in FullImagesDataManager to proactively read batches of images into memory with a fixed memory budget.

**Additional context**
I'm happy to try and work on this, I just probably need a few pointers on the path of least resistance since there are probably multiple ways to do this (some more intrusive than others)

**Comment by sweeneychris** [comment]
In general, something a bit wonky is happening for the ns-render dataset command. I can see that the images are loaded and undistorted twice. But to render the dataset, you shouldn't even need to load the input images at all?

**Comment by brentyi** [comment]
Just to confirm: your out-of-core sampling is something custom, right?

I've also needed a bunch of hacks for when I've tried larger Aria / splatfacto datasets, and have noticed the dataset undistortion happening when rendering, exporting, etc. 

For avoiding the full dataset undistortion that happens when `ns-render`, `ns-export`, etc are called: perhaps resident Nerfstudio dataloading/splatfacto expert @kerrj can provide some thoughts when he has a chance? My initial thought is we can make this lazy. Instead of happening at setup/instantiation time for the training pipeline, which is loaded from the checkpoint, it can happen only when the first training batch is pulled.

For memory issues, it's also _plausible_ that the threading changes in #2969 will improve things.

**Comment by sweeneychris** [comment]
By "out-of-core sampling of the dataset" I just mean the sampling mechanism in the training that allows only loading N images for training every M iterations.

For now, I've simply gone through the code and removed loading the images in order to get ns-render dataset to simply spit out the rgb and depth renderings. This of course would break other pipelines that use the FullImageDataManager but it unblocks my own use case for the time being

**Comment by sweeneychris** [comment]
I've pulled #2969 but it doesn't affect this issue

**Comment by kerrj** [comment]
One thing that might help is adding ` cache_images_type="uint8",` in the `FullImageDatamanagerConfig`, this reduces memory footprint by around 4x

**Comment by nekoshadow1** [comment]
I'm a bit confused by the behavior too. The 'ns-render' and 'ns-viewer' commands seem to load all training images unnecessarily. Actually, this has been dealt with in a previous pull request: https://github.com/nerfstudio-project/nerfstudio/pull/2051. But I don't understand why nerfstudio still loads all the images into CPU memory during inference time (ns-viewer, ns-render) now.

**Comment by zhumorui** [comment]
> In general, something a bit wonky is happening for the ns-render dataset command. I can see that the images are loaded and undistorted twice. But to render the dataset, you shouldn't even need to load the input images at all?

I do think that we don't need to cache all images while we have an existed camera path. Have you managed to solve this issue?

**Comment by jb-ye** [comment]
@sweeneychris Did you solve your issue?
