### ISSUE TITLE
export zipnerf

### ISSUE THREAD

**Issue by Seven-Circles** [nerfstudio-project/nerfstudio#2974]
Hi~everybody! Did anyone export zipnerf model with point cloud or mesh? 
I noticed that when I ran 
`ns-export pointcloud --load-config xxx/xxx...`
`NotImplementedError: get_rgba_image is not implemented for model ZipNerfModel`
and check the code, it was occured in nerfstudio/nerfstudio/models/base_model.py, but other model such as instant_ngp will run in nerfstudio/nerfstudio/models/instant_ngp.py. I wonder weather zipnerf is allowed to be export. QAQ

**Comment by aeskandari68** [comment]
I have the same problem in extracting zipnerf results mesh. Have you managed to find a solution for that?

**Comment by ATing0203** [comment]
I also have the same problem...

**Comment by Moreland-cas** [comment]
same issue when extracting from nerf using tsdf

**Comment by Moreland-cas** [comment]
> same issue when extracting from nerf using tsdf

but still return a usable ply file though..

**Comment by Tiangj9178** [comment]
我也遇到同样的问题，请问您解决了吗？该如何导出
