### ISSUE TITLE
 How to obtain point cloud

### ISSUE THREAD

**Issue by Lizhinwafu** [nerfstudio-project/nerfstudio#2975]
How to obtain point cloud  (splatfacto)

**Comment by peasant98** [comment]
You can get a point cloud by running this command:
```
ns-export gaussian-splat [-h] --load-config PATH --output-dir PATH
```

which can be found here: https://docs.nerf.studio/reference/cli/ns_export.html#gaussian-splat

**Comment by peasant98** [comment]
@Lizhinwafu were you able to get it solved? I believe a .ply will be exported. You can view the Gaussians in a viewer like https://antimatter15.com/splat/.
