### ISSUE TITLE
blender datasets - json file 

### ISSUE THREAD

**Issue by hex41434** [nerfstudio-project/nerfstudio#2990]
Hi
I downloaded blender datasets for training, for each dataset there are 3 json files : train_transform.json, as well as json files for test and val. 

but ns-train searches for one "transforms.json" file for each dataset (the nerfstudio datasets has one json file for each dataset) 

any ideas?

**Comment by benoitmaillard** [comment]
Hi,
You need to use the appropriate data parser. For the blender dataset this would look like this:
```
ns-train splatfacto blender-data --data data/blender/lego
```

**Comment by samadbarrikhojasteh** [comment]
Hi,
You need to choose one of these data configurations according to your dataset. However, all data configurations must go at the end.
![Screenshot from 2024-03-25 10-30-56](https://github.com/nerfstudio-project/nerfstudio/assets/50359880/f5f6b181-94f0-401e-8bfb-fae7b1f5ca61)

**Comment by hex41434** [comment]
> Hi, You need to use the appropriate data parser. For the blender dataset this would look like this:
> 
> ```
> ns-train nerfacto blender-data --data data/blender/lego
> ```

Thanks a lot!

**Comment by hex41434** [comment]
> Hi, You need to choose one of these data configurations according to your dataset. However, all data configurations must go at the end. ![Screenshot from 2024-03-25 10-30-56](https://private-user-images.githubusercontent.com/50359880/316453503-f5f6b181-94f0-401e-8bfb-fae7b1f5ca61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NTAxNjIsIm5iZiI6MTcxMTQ0OTg2MiwicGF0aCI6Ii81MDM1OTg4MC8zMTY0NTM1MDMtZjVmNmIxODEtOTRmMC00MDFlLThiZmItZmFlN2IxZjVjYTYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDEwNDQyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMjNhYzgyMWRmYTcxMGVhZGY3Y2UxODAwMjYzNWI5NzUxNjlkZDc1YzRlM2Q0NmFhNzhlY2UzYzY3NWQ4OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mAzL8j76UZWtmCEwB3iv3Oh9Y65FCiBn8czrmRU7aBk)

Thank you!
