### ISSUE TITLE
Train model from custom data without COLMAP

### ISSUE THREAD

**Issue by fedeceola** [nerfstudio-project/nerfstudio#2998]
Hi, I'm trying to build some NeRF models from images acquired with the [PyRep](https://github.com/stepjam/PyRep) simulator and I cannot use COLMAP to extract camera intrinsics and extrinsics.

I'm currently filling a transform.json with intrinsic and extrinsic parameters from the simulator, but I don't manage to train a model with such data. I attach a screenshot of a trained model, which presents several inconsistencies.
![Screenshot from 2024-03-12 11-24-46](https://github.com/nerfstudio-project/nerfstudio/assets/32268209/77363bfd-a6da-4f1d-a5ee-8d52ce9e982a)

I rendered the images from PyRep in the OpenGL mode, so according to the [documentation](https://docs.nerf.studio/quickstart/data_conventions.html) the data should be in the right format.

I attach [here](https://github.com/nerfstudio-project/nerfstudio/files/14571277/pyrep_images.zip) the data that I am using for training.

Thanks in advance for the support.

**Comment by xtchen96** [comment]
I came up with the same issue. The scene is scattered. How did you fix that?

**Comment by fedeceola** [comment]
I don't remember if I managed to fix it for nerfstudio, but I did it for instant-ngp. Was due to a strange parameterization in the extrinsics.
