### ISSUE TITLE
AssertionError: block_width must be between 2 and 16

### ISSUE THREAD

**Issue by ichsan2895** [nerfstudio-project/nerfstudio#3025]
**Describe the bug**
`AssertionError: block_width must be between 2 and 16` when I run `ns-train splatfacto`

**To Reproduce**
```
# make sure you uninstall the previous gsplat and nerfstudio
pip uninstall gsplat nerfstudio

# install it from pip the LATEST commit as 27th of March 2024
pip install git+https://github.com/nerfstudio-project/gsplat.git@2d69aaf704cc7208b0d7a90794d286c49d758e70
pip install git+https://github.com/nerfstudio-project/nerfstudio.git@71de07163a9642016c9bde1d3705e3fb62babd69

ns-train splatfacto --logging.steps-per-log 200 --vis viewer+wandb --viewer.websocket-port 7007 \
    --pipeline.model.resolution-schedule 3000 \
    --pipeline.model.num-downscales 2 \
    nerfstudio-data \
    --data path/to/scene --downscale-factor 1
```

**Expected behavior**
It runs **without** problem in previous version (`pip install nerfstudio==1.0.2` & `pip install gsplat==0.1.8`)

**Screenshots**
![image](https://github.com/nerfstudio-project/nerfstudio/assets/60387342/1826342e-d0dc-4cd2-9fc0-50eb70c2ed03)

**Additional context**
```
Runpod Environment
Ubuntu 22.04 LTS
Torch 2.0.1+cu118
Python 3.10
RTX A6000
```

**Comment by jb-ye** [comment]
gsplat main branch are unstable as we are making a few API changes recently. Use the latest release version if you can. I believe @kerrj will follow up PR to adapt the API changes to nerfstudio.

**Comment by kerrj** [comment]
This PR https://github.com/nerfstudio-project/nerfstudio/pull/3019 incorporates changes for 0.1.9

**Comment by jb-ye** [comment]
#3019 merged.
