### ISSUE TITLE
ns-train gaussian-splatting parsing error

### ISSUE THREAD

**Issue by Haderob** [nerfstudio-project/nerfstudio#3029]
I installed nerf studio today and want to build gaussian splat using 
ns-train gaussian-splatting method but it didn't recognize the command. Why is that and what can i do?
![Screenshot from 2024-03-29 08-54-25](https://github.com/nerfstudio-project/nerfstudio/assets/81700890/403e3cb0-29c9-4f6d-996a-daec0d6616c9)

**Comment by maturk** [comment]
The name is changed to splatfacto

**Comment by Haderob** [comment]
Thanks
