### ISSUE TITLE
Scene Center in splatfacto

### ISSUE THREAD

**Issue by luk-jok** [nerfstudio-project/nerfstudio#3030]
Hello
I have a question.
Is there a way to keep center of scene from colmap in splatfacto ?

**Comment by jb-ye** [comment]
yes, when loading with the colmap parser, use option `--center-method=none`
https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/dataparsers/colmap_dataparser.py#L63C5-L63C18

**Comment by luk-jok** [comment]
> yes, when loading with the colmap parser, use option `--center-method=none` https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/data/dataparsers/colmap_dataparser.py#L63C5-L63C18

Thank you. <3
