### ISSUE TITLE
ns-eval --render-output-path gives error NotImplementedError("Saving images is not implemented yet")

### ISSUE THREAD

**Issue by pimpilim** [nerfstudio-project/nerfstudio#3058]
**Describe the bug**
In Version v0.3.4 the option --render-output-path for ns-eval saved the evaluation images, from which the evaluation metrics are calculated to a folder. In the actual nerfstudio version, this does not work anymore, instead a NotImplementedError is raised. This error happens in base_pipeline.py, line 380. Some of the variables seem to have changed in between the two versions, which makes the old approach for saving the images not possible anymore.

**To Reproduce**
activate the nerfstudio environment, and call ns-eval --load-config /path/config.yml --output-path /path/eval.json --render-output-path /path/

**Expected behavior**
I would expect, that the parameter --render-output-path saves the rendered and evaluation images in a folder.

![error](https://github.com/nerfstudio-project/nerfstudio/assets/138764168/5d938379-e896-404d-9b84-7db5f7c2d0af)

**Comment by kerrj** [comment]
I believe https://github.com/nerfstudio-project/nerfstudio/pull/3070 should fix this, feel free to re-open if not!
