### ISSUE TITLE
More than expected RAM consumption of parallel datamanager

### ISSUE THREAD

**Issue by hyperzy** [nerfstudio-project/nerfstudio#3061]
**Describe the bug**
This may not be regarded as a bug #3060 . The DataProcessor init consumes lots of RAM, and I suspect it's due to the data copying during the mp object instantiation. This behavior is mitigated when image caching is moved to after the process starts. If anyone more familiar with Python mp can explain such behavior, it would be much helpful.

**Comment by kerrj** [comment]
#3060 fixes this
