### ISSUE TITLE
What do users see in the viewer?Is a photo?

### ISSUE THREAD

**Issue by smart4654154** [nerfstudio-project/nerfstudio#3090]
Thank you for your work. What do users see in the viewer? Is the content seen by the user a photo or something else?
This is not point cloud or mesh data. This seems to be related to volume rendering，I guess this is a photo rendered in volume from the current perspective, do I understand correctly?
thank you.
![image](https://github.com/nerfstudio-project/nerfstudio/assets/152783898/6366e621-8e46-4d05-b9b0-c6b99030525d)

**Comment by kerrj** [comment]
Yes, the viewer shows a rendered image from the underlying NeRF at that current perspective

**Comment by smart4654154** [comment]
Thank you very much for your reply
I am currently studying NERF and 3DGS, and I have some new question
1. What does "at that current perspective" mean, and how does nerfstudio obtain current perspective ?
2. the viewer shows a rendered image from the 3DGS result at that current perspective，Is this right? 
thank you
