### ISSUE TITLE
ns-train won't halt the execution after finished training

### ISSUE THREAD

**Issue by MatteoFusconi** [nerfstudio-project/nerfstudio#3091]
**Describe the bug**
Maybe I am missing something, but when I run ns-train, the execution of it won't halt unless I press ctrl+C to exit the process in the terminal. This behavior is undesired since I would like to do an end-to-end implementation with less supervision.

I encounter this "bug" when I run `ns-train splatfacto --load-config config.yml`.
The only parameters I changed are in the viewer, and are these ones:
`make-share-url true`
`websocket-port 7007`
`quit-train-after-completion true`

Even thought the quit train after completion is true, still the process won't halt. I think that the problem is the make share url set to true, but how can I solve this?

**Comment by brentyi** [comment]
Hi @MatteoFusconi, thanks for filing this issue! This was indeed a share URL bug, I just made a PR to fix it.

If you want a short-term fix you can install viser from source once that's merged, otherwise we'll get this into the next release.
