### ISSUE TITLE
Error retrieving public link during file download using gdown in nerfstudio environment

### ISSUE THREAD

**Issue by Jqliany** [nerfstudio-project/nerfstudio#3099]
When attempting to download data using gdown in a nerfstudio environment, an error occurs stating that the public link of the file cannot be retrieved. The error suggests checking if the file's sharing settings are set to 'Anyone with the link' and mentions the possibility of too many accesses to the file. Further, attempting to access the provided Google Drive URL directly in a browser results in a 404 error.

Environment
Operating System: Windows
Python version: [version used in nerfstudio environment]
gdown version: [version used]
Command Executed:
ns-download-data nerfstudio --capture-name=poster
Error Message
Traceback (most recent call last):
  File "\.conda\envs\nerfstudio\lib\site-packages\gdown\download.py", line 253, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "\.conda\envs\nerfstudio\lib\site-packages\gdown\download.py", line 54, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.
...
Steps to Reproduce
Set up nerfstudio environment on Windows.
Run the command ns-download-data nerfstudio --capture-name=poster.
Observe the error output.
Expected Behavior
The file should download without any errors regarding the retrieval of the public link.

Actual Behavior
The download fails with an error about not being able to retrieve the public link of the file. Additionally, accessing the file directly via the provided Google Drive URL results in a 404 error.

**Comment by michaelybecker** [comment]
[ping]
what does "not planned" mean here? This is still a sample operation in the docs, basically the Nerfstudio Hello World; if the link is no longer available, shouldn't the docs be changed?

**Comment by Jqliany** [comment]
> [ping] what does "not planned" mean here? This is still a sample operation in the docs, basically the Nerfstudio Hello World; if the link is no longer available, shouldn't the docs be changed?

Since I found the issue, I realized that I didn't download the latest development version but installed it directly from pip. In the latest development version, the link is valid. Therefore, I would like to close the issue I raised.

**Comment by michaelybecker** [comment]
thanks for the clarification!
