### ISSUE TITLE
Floater Free Gaussian Splats

### ISSUE THREAD

**Issue by abrahamezzeddine** [nerfstudio-project/nerfstudio#3104]
**Is your feature request related to a problem? Please describe.**
This is not really an issue because it might be an inherent problem in the initial development of gaussian splats but I am wondering if there is any plan to implement a floater free functionality for gaussian splats? When rendering a room for example, there is a lot of free floaters in the air. Culling this depending on alpha helps a little bit, but there are still plenty. Providing such solution would really put this application at the forefront of developing good gaussian splats.

**Describe the solution you'd like**
Perhaps delete floaters that have no "semantic" meaning? Such as automatically removing outliers in the point cloud before creating the splat itself?

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered.

](https://github.com/ingra14m/floater-free-gaussian-splatting) Perhaps this could be an inspiration?

**Additional context**

**Comment by jb-ye** [comment]
Could you try this? https://github.com/nerfstudio-project/nerfstudio/pull/3113
