### ISSUE TITLE
[Question] How do I combine colmap dataparser parameters with splatfacto training?

### ISSUE THREAD

**Issue by Filocava99** [nerfstudio-project/nerfstudio#3107]
Hi, I just have a quick question. I am currently training a model using splatfacto, but the orientation is messed up. I wanted to use 
`--orientation_method=none --center_method=none --assume_colmap_world_coordinate_convention=False`  to attempt at fixing it, but unfortunately those works only when using the colmap subcommand of splatfacto.

Is there any way I could use the parameters of `ns-train splatfacto colmap` while also using the pipeline parameters of `ns-train splatfacto`?

**Comment by jb-ye** [comment]
you can try to convert your colmap project to nerfstudio format using ns-process-data ([without rerunning the colmap](https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py#L76-L83)) and load it into ns-train.

**Comment by Filocava99** [comment]
I was already processing the images using ns-process-data, but those parameters where missing, they were only availble using ns-train. I used comlmap2nerf script in the past but I was hoping for a more compact solution. Gonna use that then, thanks anyway!

**Comment by Filocava99** [comment]
What's the actual purpose of ns-train splatfacto colmap tought? Cause the processing is done through ns-process-data and the train with ns-train splatfacto --data etc. I can't understand how does it fell in between

**Comment by jb-ye** [comment]
@Filocava99 yeah if you have a colmap project already and doesn’t want to convert it to nerfstudio format, you can still quick start training the model using colmap parser.

**Comment by Filocava99** [comment]
Ok but here's the thing: ns-process-data creates a colmap project and converts it to nerfstudio format. It lacks the orientation method parameter, resulting in the final model being slighty tilted.
If instead I use ns-train splatfacto colmap, all the parameters of ns-train splatfacto are missing, even the --viewer.quit-on-train-completion=True parameter, which is actually kind of important if you want to create an automated pipeline

**Comment by Filocava99** [comment]
Holy I feel so stupid rn ahah, thanks :D
