### ISSUE TITLE
Gaussian Splat does not export to PLY when sh-degree is set to 0

### ISSUE THREAD

**Issue by sam598** [nerfstudio-project/nerfstudio#3110]
When sh-degree is set to 0 the exporter script tries to convert all of the color values to uint8, which is a great idea and should be implemented this way

https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/scripts/exporter.py#L576

However this is incompatible with the write_ply function, which requires all data types to be float

https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/scripts/exporter.py#L516

One or the other should change, as it is it will never export.

**Comment by jb-ye** [comment]
@mathijshenquet Could you help address this issue which is due to the change of https://github.com/nerfstudio-project/nerfstudio/pull/3005/

**Comment by mathijshenquet** [comment]
Actually I'm already working on a fix

**Comment by mathijshenquet** [comment]
@sam598 the linked branch should fix it. I wrote as simple test but it would be best if you could check that this also fixes it for you.
