### ISSUE TITLE
How to enable depth supervision in splatfacto with depth images

### ISSUE THREAD

**Issue by samcao0416** [nerfstudio-project/nerfstudio#3127]
Hi there, I want to know whether depth supervision is enabled in splatfacto. This issue [https://github.com/nerfstudio-project/nerfstudio/issues/2832](url) seems to claim that depth supervision has been integrated. However, I follow the instruction on https://docs.nerf.studio/quickstart/data_conventions.html and trained, finding out no depth image was loaded. After reading the code, if I didn't make any mistakes, the same conclusion can be made. Thus, I want to make sure, is there any way to enbale depth supervision in splatfacto with depth images?

**Comment by maturk** [comment]
@samcao0416, you can consider using my project [dn-splatter](https://github.com/maturk/dn-splatter) which incorporates depth supervision for both real sensor depths or monocular depth estimates. It also support normal rendering, normal supervision, and some basic mesh extraction. It's based on splatfacto.

**Comment by samcao0416** [comment]
Thanks a lot! I will give it a try!
