### ISSUE TITLE
Legacy tensor construction 

### ISSUE THREAD

**Issue by gtangg12** [nerfstudio-project/nerfstudio#3135]
https://github.com/nerfstudio-project/nerfstudio/blob/7ba02be8cf6e81c96fab412bdafae44708623afa/nerfstudio/cameras/cameras.py#L173

Can we change this to torch.tensor() instead, since on some torch versions, this does not allow construction on GPU

https://discuss.pytorch.org/t/cannot-construct-tensor-directly-on-gpu-in-torch-1-10-1/153751/2

**Comment by jb-ye** [comment]
Yes! Could you send a PR to change it? It looks like a simple fix.

**Comment by gtangg12** [comment]
See https://github.com/nerfstudio-project/nerfstudio/pull/3145#issue-2295952284
