### ISSUE TITLE
COLMAP GUI finds poses while nerfstudio COLMAP settings does not?

### ISSUE THREAD

**Issue by abrahamezzeddine** [nerfstudio-project/nerfstudio#3137]
**Describe the bug**
COLMAP via NerfStudio  does not find enough poses although COLMAP GUI finds the poses correctly. Using sequential for this.

**To Reproduce**
Steps to reproduce the behavior:Perform ns preprocess data with COLMAP with sequential image frames. Fails.
Perform automatic reconstruction sparse data with COLMAP with high or low quality and sequential image frames. Successful.

**Expected behavior**
The nerfstudio preprocess data should pass accordingly, just like COLMAP GUI should do.

**Screenshots**
![Skärmbild 2024-05-11 002303](https://github.com/nerfstudio-project/nerfstudio/assets/142085947/30f7f954-c6f2-44e6-88bf-feff6b9f8b19)
![Skärmbild 2024-05-11 002410](https://github.com/nerfstudio-project/nerfstudio/assets/142085947/541501a8-9664-4379-81d5-d2804f0c3d30)

**Additional context**

**Comment by KevinXu02** [comment]
Hi! The pose matching process in COLMAP is random, so you may need to try a few more times for it to match successfully.

**Comment by abrahamezzeddine** [comment]
Quite a time consuming process to be honest to do such guessing game... Especially for large datasets... 

Currently using COLMAP GUI with high success rate actually. Then I import them to nerfstudio via this command below;


ns-process-data images --verbose --skip-colmap --colmap-model-path sparse/0 --num-downscales x --data folder/images --output-dir folder/test.

I need however to create two new folders, "sparse" and "0" and export the COLMAP model into folder 0 in order for nerfstudio to detect the model.
