### ISSUE TITLE
A question about number of frames to extract

### ISSUE THREAD

**Issue by shenyehui** [nerfstudio-project/nerfstudio#3173]
How is number of frames to extract determined? Does it increase automatically as the video length increases?

**Comment by KevinXu02** [comment]
It is determined in the config of processing data and I think it's always 300 if you don't set it manually.

**Comment by shenyehui** [comment]
> It is determined in the config of processing data and I think it's always 300 if you don't set it manually.

How to set it manually?

**Comment by brentyi** [comment]
You can see the help message for `ns-process-data`, eg `ns-process-data video --help`. The `--num-frames-target` argument is what you're looking for!
