### ISSUE TITLE
Processing data taking too long (more than 12hours have passed)

### ISSUE THREAD

**Issue by parth-psd-009** [nerfstudio-project/nerfstudio#3181]
**Hi! I am trying to process my custom data for a balgle video to make a gaussian splat. I use this command for it**:

*ns-process-data video --camera-type simple_pinhole --images-per-equirect 8  --crop-factor 0.1 0.1 0.25 0.25 --verbose True --num-downscales 4 --num-frames-target 2160  --data C:\Users\Administrator\nerfstudio\data\video\bangle.mp4  --output-dir C:\Users\Administrator\nerfstudio\processed\bangle_new*

It is being processed for over 12 hours. I left it overnight only the frames images are formed and the colmap folder is being formed that to not complete.
In the default nerfstudio "poster" video there are other files also.

**[Image of the default folder]**:
*https://github.com/nerfstudio-project/nerfstudio/assets/110755500/3544cd61-68fc-45a7-8ff2-f3118f56acae*

**Comment by maturk** [comment]
colmap is slow, there is nothing suprising about this, and 2k frames is a lot... you do not need this many frames for your nerf/gs models, trust me.
