### ISSUE TITLE
License of the gsplat 

### ISSUE THREAD

**Issue by sumanttyagi** [nerfstudio-project/nerfstudio#3184]
can you share the lic of the gsplat model ?

**Comment by brentyi** [comment]
it's Apache! https://github.com/nerfstudio-project/gsplat/blob/main/LICENSE

**Comment by maturk** [comment]
@sumanttyagi, `splatfacto` is based on the wholly open-source reimplementation (Apache-2.0 license) of gaussian splatting called [gsplat](https://github.com/nerfstudio-project/gsplat/).
