### ISSUE TITLE
Color Artifacts in Preview with Custom Template Using Trained Nerfacto Model

### ISSUE THREAD

**Issue by Zacharie06** [nerfstudio-project/nerfstudio#3205]
Describe the bug
I created a custom template using Nerfstudio and employed a pre-trained Nerfacto model. However, when previewing the results, the colors appear very strange and do not match the expected output.

To Reproduce

Screenshots
![1717997551973](https://github.com/nerfstudio-project/nerfstudio/assets/50125565/89a245b7-4fd2-4592-8414-de37efbddf53)

Additional context

The pre-trained model was validated before and produced accurate results with the default templates.
The issue only arises when using the custom template.
I have verified that the model weights and parameters are correctly loaded.
There might be a problem with the way the custom template handles the color outputs from the model.

**Comment by maturk** [comment]
@Zacharie06 , what custom template are you referring to?

**Comment by Zacharie06** [comment]
> @Zacharie06 , what custom template are you referring to?

SA3D. The problem is sovled after I adding average_init_density=0.01 to ModelConfig. Thank you :)
