### ISSUE TITLE
Large Gauassians trained by Splatfacto are not culled

### ISSUE THREAD

**Issue by Sunnyhong0326** [nerfstudio-project/nerfstudio#3208]
**Describe the bug**
I was training a scene of park using splatfacto + gsplat v1.0. However, when I view the scene using viser viewer, I founded out that large gaussians are not properlly culled.

**To Reproduce**
1. ns-train splatfacto-big --logging.local-writer.stats-to-track TOTAL_TRAIN_TIME --data {MY_DATA} colmap --colmap-path sparse/0 --downscale-factor 4

**Expected behavior**
I expected large gaussians are culled because of [this line of implementation ](https://github.com/nerfstudio-project/nerfstudio/blob/d220600b8bb9cddb6f53a0a1ec9fd2f13d420b87/nerfstudio/models/splatfacto.py#L525), it seems like the threshold is set too big in this [line](https://github.com/nerfstudio-project/nerfstudio/blob/d220600b8bb9cddb6f53a0a1ec9fd2f13d420b87/nerfstudio/models/splatfacto.py#L139)
Although the official gaussian splatting repo [didn't implement large gaussian culling](https://github.com/graphdeco-inria/gaussian-splatting/issues/123), their default [culling threshold is 0.1 * scene_scale ](https://github.com/graphdeco-inria/gaussian-splatting/blob/472689c0dc70417448fb451bf529ae532d32c095/scene/gaussian_model.py#L399)

**Screenshots**
![image](https://github.com/nerfstudio-project/nerfstudio/assets/66857678/749424b5-2307-46e7-9f80-6ea6cc8efd06)

**Additional context**
Also, the [duplicating condition](https://github.com/nerfstudio-project/nerfstudio/blob/d220600b8bb9cddb6f53a0a1ec9fd2f13d420b87/nerfstudio/models/splatfacto.py#L458), [splitting condition](https://github.com/nerfstudio-project/nerfstudio/blob/d220600b8bb9cddb6f53a0a1ec9fd2f13d420b87/nerfstudio/models/splatfacto.py#L453) and [culling condition](https://github.com/nerfstudio-project/nerfstudio/blob/d220600b8bb9cddb6f53a0a1ec9fd2f13d420b87/nerfstudio/models/splatfacto.py#L518) might be wrong when user set [auto_scale_poses](https://github.com/nerfstudio-project/nerfstudio/blob/d220600b8bb9cddb6f53a0a1ec9fd2f13d420b87/nerfstudio/data/dataparsers/colmap_dataparser.py#L68) to False (since the scene scale is not = 1 anymore)
In the official implementation of gaussian splatting, the conditions above is multiplied by [scene_extent](https://github.com/graphdeco-inria/gaussian-splatting/blob/472689c0dc70417448fb451bf529ae532d32c095/scene/gaussian_model.py#L378)

**Comment by jb-ye** [comment]
fixed by https://github.com/nerfstudio-project/nerfstudio/pull/3211
