### ISSUE TITLE
setuptools need to fix to 69.5.1

### ISSUE THREAD

**Issue by louhz** [nerfstudio-project/nerfstudio#3215]
Some time i face this error:ImportError: cannot import name 'packaging' from 'pkg_resources

follow this link:
https://github.com/aws-neuron/aws-neuron-sdk/issues/893

roll back to 69.5.1 fix it

I am not sure this is a common bug or just happens to me

So mark it here

**Comment by abrahamezzeddine** [comment]
Please see #3159
