### ISSUE TITLE
Docker failure 

### ISSUE THREAD

**Issue by efyphil** [nerfstudio-project/nerfstudio#3228]
I'm trying to run docker, but I get this error at the very end. 

8.464                from dn_splatter.dn_model import DNSplatterModelConfig                                                   
8.464              File "/home/user/nerfstudio/dn_splatter/dn_model.py", line 24, in <module>                                 
8.464                from gsplat._torch_impl import quat_to_rotmat                                                            
8.464            ModuleNotFoundError: No module named 'gsplat._torch_impl'                                                    
8.464                                                                                                                         
------
Dockerfile:181
--------------------
 179 |     # Switch to workspace folder and install nerfstudio cli auto completion
 180 |     WORKDIR /workspace
 181 | >>> RUN ns-install-cli --mode install
 182 |     
 183 |     # Bash as default entrypoint.
--------------------
ERROR: failed to solve: process "/bin/sh -c ns-install-cli --mode install" did not complete successfully: exit code: 1

I added RUN pip install gsplat==0.1.11 and now I get this error

7.589                from gsplat.cuda_legacy._torch_impl import quat_to_rotmat                                                
7.589            ModuleNotFoundError: No module named 'gsplat.cuda_legacy'                                                    
7.589                                                                                                                         
------
Dockerfile:182
--------------------
 180 |     WORKDIR /workspace
 181 |     RUN pip install gsplat==0.1.11
 182 | >>> RUN ns-install-cli --mode install
 183 |     
 184 |     # Bash as default entrypoint.
--------------------
ERROR: failed to solve: process "/bin/sh -c ns-install-cli --mode install" did not complete successfully: exit code: 1

**Comment by maturk** [comment]
@efyphil, I am currently working on updating the repo to support the latest gsplat repo.

Currently, the requirements for the dn-splatter project are as follows:

```
nerfstudio <= 1.1.0
gsplat  <= 0.1.11
```

Stay tuned, I will update the repo with speed and memory improvements from gsplat 1.0 (more details [here](https://x.com/ruilong_li/status/1799156694527909895) and [here](https://docs.gsplat.studio/main/))

**Comment by maturk** [comment]
@efyphil, please uninstall dn-splatter from your docker container.

**Comment by efyphil** [comment]
Yeah, it's true, sorry, but i write to dn-splatter to fix it

**Comment by maturk** [comment]
@efyphil , I am the author of dn-splatter, I am aware of the issue, hence why I sent the previous message.
