### ISSUE TITLE
Splat quality decrease after upgrading to gsplat 1.0.0

### ISSUE THREAD

**Issue by rowellz** [nerfstudio-project/nerfstudio#3230]
Splat quality significantly decreases after upgrading nerfstudio & gplat. I am using nerfstudio in a docker container based off of the nerfstuido/nerfstudio image after I ran into problems using the dromni/nerfstudio image a few months back.

Upgrade nerfstudio & gplat with `pip install -U nerfstudio`
Process images with `ns-process-data images`
Process Splat with `ns-train splatfacto`
Observe splat model in viewer. The statue is not recognizable 

**Expected behavior**
The statue should be easily noticeable after loading the splat model

Statue splat before upgrading gsplat & nerfstudio
<img width="1382" alt="Screenshot 2024-06-14 at 2 15 21 PM" src="https://github.com/nerfstudio-project/nerfstudio/assets/42854069/e9ebff0a-da0b-428a-af04-e306ff619319">

Statue splat after upgrading gsplat & nerfstudio
<img width="1386" alt="Screenshot 2024-06-14 at 2 16 00 PM" src="https://github.com/nerfstudio-project/nerfstudio/assets/42854069/8252f1f9-adbf-4d97-b8d8-0fe42c698eff">

Both of these splats used the same source video, which can be viewed when clicking on the "Download Original Video" button in the splat viewer, which is at https://ez3d.nyc. 

Thanks again to all the folks at nerfstudio for all of your awesome work. Please let me know if there is any more information I might need to provide to help resolve this issue.

**Comment by maturk** [comment]
What torch version are you using? There are problems with Torch 2.0.1. If so, you could upgrade to 2.1.2.

**Comment by rowellz** [comment]
You absolute genius! I was indeed on Torch 2.0.1. After running `pip install -U torch==2.1.2` it worked! Training did seem to be a bit faster, but tough to notice due to colmap still :/ That said, what was most impressive was that the splat took up half the disk space than the one produced from the previous nerfstudio version. Literally went from 5.4 MB to 2.7 MB which is so huge when trying to render these splats on the client. Congrats on the awesome work, I am looking forward to regenerating all of my splats now, lol

**Comment by maturk** [comment]
Closing this one for the related issue #3235
