### ISSUE TITLE
Implement Gaussian Surfels

### ISSUE THREAD

**Issue by gchhablani** [nerfstudio-project/nerfstudio#3236]
**Is your feature request related to a problem? Please describe.**

I want to implement Gaussian Surfels for nerfstudio as I am struggling with different dataparsers. I use nerfstudio for most of my algos, so would be nice to have.

**Describe the solution you'd like**

Implement Gaussian Surfels method. I would love to do it myself but need guidance.

**Describe alternatives you've considered**

Changing the dataset I am using to work with original Gaussian Surfels code, but it leads to breaking code and illegal cuda access.

**Comment by Ambrosiussen** [comment]
Where did you find a surfels implementation for nerfstudio?
