### ISSUE TITLE
Nerfstudio release v1.1.3 for breaking bugs

### ISSUE THREAD

**Issue by maturk** [nerfstudio-project/nerfstudio#3239]
@brentyi @liruilong940607 

I do not know how to update a Nerfstudio release, but I noticed that #3211 is a very important addition that the current v1.1.2 does not have (i.e. v1.1.2 is actually a broken Nerfstudio release). Can we make a new release asap (need it for my project xD)?

With much thanks... 
maturk

**Comment by brentyi** [comment]
Sure, I can bump it!

**Comment by brentyi** [comment]
Done: https://github.com/nerfstudio-project/nerfstudio/releases/tag/v1.1.3

Docs build seems broken though 🤔
