### ISSUE TITLE
@torch_compile()  for  function get_viewmat() cause the bad training results.

### ISSUE THREAD

**Issue by Miaosheng1** [nerfstudio-project/nerfstudio#3242]
**Describe the bug**
I've been testing SplatFacto on my device and encountered a peculiar issue. When I follow the original code and apply `@torch_compile()`, my results end up in local minima and fail to achieve good outcomes. However, when I comment out `@torch_compile()`, my code works correctly. I'm not sure why this happens, but I suggest avoiding the use of this decorator for speed optimization until it becomes more stable.

https://github.com/nerfstudio-project/nerfstudio/blob/9b3cbc79bf239eb3c69e7c288632aab02c4f0bb1/nerfstudio/models/splatfacto.py#L99-L115

**Training PSNR** ( add the decorator ):
![image](https://github.com/nerfstudio-project/nerfstudio/assets/111415805/4a29ebf0-530e-4eb1-bba4-ffe98044a184)

**Training PSNR** (Not add the decorator ):
![image](https://github.com/nerfstudio-project/nerfstudio/assets/111415805/f96550a8-8680-4113-bd65-9d24eaaa73b6)

**My running environment is as follows:**
* Device: NVIDIA GeForce RTX3090
* Driver Version: 525.116.03   
* CUDA Version: 11.7
* torch version: 2.0.1+cu117

**Comment by maturk** [comment]
torch version 2.0.1 is known to have issues. Can you upgrade to torch 2.1.2+. See #3235, #3230
