### ISSUE TITLE
Error in training the model: CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by alesolenne** [nerfstudio-project/nerfstudio#3292]
``Hi everyone, I recently installed nerfstudio but when I go to try to train a model I always get the usual error:
RuntimeError: C:/Users/aleso/AppData/Local/Temp/pip-req-build-jz__nwp9/include\tiny-cuda-nn/gpu_memory.h:592 cuMemSetAccess(m_base_address + m_size, n_bytes_to_allocate, &access_desc, 1) failed: CUDA_ERROR_OUT_OF_MEMORY

The input command is:
`ns-train nerfacto --data data/nerfstudio/poster`
The output:
![1](https://github.com/nerfstudio-project/nerfstudio/assets/156725495/665b19b5-c19c-45f1-ba6e-08681f7e2a0d)
![2](https://github.com/nerfstudio-project/nerfstudio/assets/156725495/7705761a-4974-441b-b6c9-23dc8fe76a79)
![3](https://github.com/nerfstudio-project/nerfstudio/assets/156725495/1e4d82d1-0578-4806-953a-6d36477b95e6)

I'm on Windows 10 with GPU NVIDIA GeForce MX130
![sc](https://github.com/nerfstudio-project/nerfstudio/assets/156725495/efc002db-db61-49b6-8f4b-df660a5c8e1d)

Thanks for help

**Comment by abrahamezzeddine** [comment]
You have only 2GB VRAM. That is not enough. You might need between 8-16 GB if VRAM for this.

**Comment by alesolenne** [comment]
Thank you!
