### ISSUE TITLE
Memory accumulation on the GPU - and a Fix!

### ISSUE THREAD

**Issue by Jovp** [nerfstudio-project/nerfstudio#3335]
I experienced OOM with very big datasets and realised the images were accumulating on the GPU. After a lot of digging I found that here:

https://github.com/nerfstudio-project/nerfstudio/blob/702886b213a5942b64250b3c4dc632e62237a511/nerfstudio/data/datamanagers/full_images_datamanager.py#L347

Because a deepcopy of the original tensor is not made, the cpu_cached images are transferred to the GPU and left there taking up memory quickly. Modifying the data dictionary does modify the underlying cached_train.

Interestingly a deepcopy is performed here: https://github.com/nerfstudio-project/nerfstudio/blob/702886b213a5942b64250b3c4dc632e62237a511/nerfstudio/data/datamanagers/full_images_datamanager.py#L373

I would argue that we don't want the dataset to accumulate on the GPU and a deepcopy should be added.

**Comment by imkanghan** [comment]
I experienced the same problem of accumulated GPU memory on large dataset. The deepcopy solution you provided solves it. Thanks.

**Comment by jb-ye** [comment]
@brentyi can you take a look at this issue? I think it could be a bug.
