### ISSUE TITLE
Nerfacto could not render rgb when disabling the scene contraction

### ISSUE THREAD

**Issue by hoanhle** [nerfstudio-project/nerfstudio#3360]
**Describe the bug**
When I train nerfacto on my own dataset without using the scene contraction, I could not get it to render rgb even though based on accumulation rendered view it seems that training is working fine.

**To Reproduce**
Data: https://drive.google.com/drive/folders/1SVv-SICZabnG10OabsYDVJW6JIY7h56_?usp=sharing
`ns-train nerfacto --output-dir /home/leh19/workspace/experiment/outputs/base_line --vis viewer  --experiment-name painting_2  nerfstudio-data --data /home/leh19/test_run_1/JPG/painting_2/processed --downscale_factor 4 `

I also set: `near_plane = 0.5`, `far_plane = 3.0`, `background_color = "random"` in `NerfactoModelConfig`. If I don't set near plane and far plane, it seems that the model just get "stucked" very close to the cameras. Like the image below
![image](https://github.com/user-attachments/assets/91ae1106-8e68-4fa0-9803-b9b4c601d345)

**Expected behavior**
View in `rgb renderer` in `viewer`
![image](https://github.com/user-attachments/assets/fb74b852-8566-470e-abde-e615cd1429c6)

View in `accumulation renderer` in `viewer`
![image](https://github.com/user-attachments/assets/c79d4595-b106-4b5d-8b35-51fdf1081daf)

**Comment by maturk** [comment]
Did you mean to run `instant-ngp` model or `nerfacto`?

**Comment by hoanhle** [comment]
@maturk I copied the wrong command opps fixed it. `instant-ngp` works fine when disabling the scene contraction. i'm suspecting there is something off with the proposal network

**Comment by hoanhle** [comment]
related issue: https://github.com/nerfstudio-project/nerfstudio/issues/2114
