### ISSUE TITLE
AttributeError: 'RandomCamerasDataManager' object has no attribute 'train_dataparser_outputs'

### ISSUE THREAD

**Issue by xiaoyaolovlife** [nerfstudio-project/nerfstudio#3380]
**Describe the bug**
When running ns-train generfacto --pipeline.model.diffusion_model "stablediffusion" --prompt "a high quality photo of a pineapple" --pipeline.model.sd-version "2-1" returns
 /xiaoyao_home/anaconda3/envs/MBstable/lib/python3.8/site-packages/nerfstudio/engine/trainer.py:2 │
│ 32 in train                                                                                      │
│                                                                                                  │
│   229 │   │   """Train the model."""                                                             │
│   230 │   │   assert self.pipeline.datamanager.train_dataset is not None, "Missing DatsetInput   │
│   231 │   │                                                                                      │
│ ❱ 232 │   │   self.pipeline.datamanager.train_dataparser_outputs.save_dataparser_transform(      │
│   233 │   │   │   self.base_dir / "dataparser_transforms.json"                                   │
│   234 │   │   )                                                                                  │
│   235                                                                                            │
│                                                                                                  │
│ /xiaoyao_home/anaconda3/envs/MBstable/lib/python3.8/site-packages/torch/nn/modules/module.py:161 │
│ 4 in __getattr__                                                                                 │
│                                                                                                  │
│   1611 │   │   │   modules = self.__dict__['_modules']                                           │
│   1612 │   │   │   if name in modules:                                                           │
│   1613 │   │   │   │   return modules[name]                                                      │
│ ❱ 1614 │   │   raise AttributeError("'{}' object has no attribute '{}'".format(                  │
│   1615 │   │   │   type(self).__name__, name))                                                   │
│   1616 │                                                                                         │
│   1617 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'RandomCamerasDataManager' object has no attribute 'train_dataparser_outputs'

**Comment by jb-ye** [comment]
fixed in https://github.com/nerfstudio-project/nerfstudio/pull/3378
