### ISSUE TITLE
Export pointcloud from splatfacto

### ISSUE THREAD

**Issue by synaldoh** [nerfstudio-project/nerfstudio#3480]
When I export pointcloud from splatfacto I get this error:

```
"/nerfstudio/scripts/exporter.py", line 149, in main
AttributeError: 'FullImageDatamanager' object has no attribute 'train_pixel_sampler'
```
what I see is: splatfacto uses `FullImageDatamanager` which has no `train_pixel_sampler`.

I would love to have a pointcloud sampled from the gaussian splatting.

Thanks!

**Comment by Tavish9** [comment]
> When I export pointcloud from splatfacto I get this error:
> 
> ```
> "/nerfstudio/scripts/exporter.py", line 149, in main
> AttributeError: 'FullImageDatamanager' object has no attribute 'train_pixel_sampler'
> ```
> 
> what I see is: splatfacto uses `FullImageDatamanager` which has no `train_pixel_sampler`.
> 
> I would love to have a pointcloud sampled from the gaussian splatting.
> 
> Thanks!

Hi, currently pointcloud export are not supported for splatfacto, please refer to [Exporting splats](https://docs.nerf.studio/nerfology/methods/splat.html#exporting-splats) for more details.
