### ISSUE TITLE
Weird CPU Memory Usage

### ISSUE THREAD

**Issue by suptimq** [nerfstudio-project/nerfstudio#3511]
I am running nerfstudio on a server with 8 Nvidia A6000 GPUs. I am pretty sure I could use all for training and everything was fine. However, recently, I noticed the training time increases significantly (from 10-ish minutes to 2-ish hours) when I submitted the 3rd training job.

I am using single GPU without masks in the training.

I am wondering if anyone has encountered such behavior before.

![image](https://github.com/user-attachments/assets/7206fc66-a8f3-4393-9b8e-0d8a56c168ba)

![image](https://github.com/user-attachments/assets/8f72d161-cbf6-4b50-ae83-0d6fcfb0f23a)

The training script:

```sh
ns-train nerfacto \
        --vis wandb \
        --experiment-name ""  \
        --max-num-iterations 30000 \
        --pipeline.model.camera-optimizer.mode off \
        nerfstudio-data --data 
```

**Comment by suptimq** [comment]
Resolved the issue by setting

```sh
export OMP_NUM_THREADS=32
export NUMEXPR_NUM_THREADS=32
export MKL_NUM_THREADS=32
```

**Comment by Mariusmarten** [comment]
I had a similar issue when training Nerfacto in a similar setup. Setting the number of threads to 8 as described worked. Thanks.
