### ISSUE TITLE
Error when training with ns-train: "IndexError: too many indices for tensor of dimension 1"

### ISSUE THREAD

**Issue by DuVogel87** [nerfstudio-project/nerfstudio#3558]
When attempting to train a Gaussian Splat model using the ns-train command and specifying an output directory, the training process fails with the following error:
IndexError: too many indices for tensor of dimension 1.

1. Convert data from Metashape using the following command (this step works successfully):
ns-process-data metashape --data /home/ubu/Schreibtisch/fristingen_nerf --xml /home/ubu/Schreibtisch/fristingen_nerf/xml.xml --output-dir /home/ubu/Schreibtisch/fristingen_nerf/output_dir

2. Attempt to train the model using the command:
ns-train splatfacto --data /home/ubu/Schreibtisch/fristingen_nerf/output_dir

3. Observe the console output (see below for full details).

Additional context
1. The dataset was successfully processed using the ns-process-data metashape command, as shown above.
2. The error appears to occur when parsing or processing the training data.
3. PyTorch deprecation warnings are displayed but seem unrelated to the primary error.

I am using Linux/Ubuntu and did clone nerfstudio from it's official repo here: https://github.com/nerfstudio-project/nerfstudio

Please help :-) 

Console Output:

```(nerfstudio) ubu@ubu-System-Product-Name:~/nerfstudio$ ns-train splatfacto --data /home/ubu/Schreibtisch/fristingen_nerf/output_dir
/home/ubu/nerfstudio/nerfstudio/field_components/activations.py:32: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @custom_fwd(cast_inputs=torch.float32)
/home/ubu/nerfstudio/nerfstudio/field_components/activations.py:39: FutureWarning: `torch.cuda.amp.custom_bwd(args...)` is deprecated. Please use `torch.amp.custom_bwd(args..., device_type='cuda')` instead.
  def backward(ctx, g):
[21:08:19] Using --data alias for --data.pipeline.datamanager.data                                          train.py:240
<... Configuration details ...>
Traceback (most recent call last):
  File "/home/ubu/anaconda3/envs/nerfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubu/nerfstudio/nerfstudio/scripts/train.py", line 272, in entrypoint
    main(
  File "/home/ubu/nerfstudio/nerfstudio/scripts/train.py", line 257, in main
    launch(
  File "/home/ubu/nerfstudio/nerfstudio/scripts/train.py", line 190, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/ubu/nerfstudio/nerfstudio/scripts/train.py", line 100, in train_loop
    trainer.setup()
  File "/home/ubu/nerfstudio/nerfstudio/engine/trainer.py", line 158, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/ubu/nerfstudio/nerfstudio/configs/base_config.py", line 53, in setup
    return self._target(self, **kwargs)
  File "/home/ubu/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 254, in __init__
    self.datamanager: DataManager = config.datamanager.setup(
  File "/home/ubu/nerfstudio/nerfstudio/configs/base_config.py", line 53, in setup
    return self._target(self, **kwargs)
  File "/home/ubu/nerfstudio/nerfstudio/data/datamanagers/full_images_datamanager.py", line 121, in __init__
    self.train_dataparser_outputs: DataparserOutputs = self.dataparser.get_dataparser_outputs(split="train")
  File "/home/ubu/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 165, in get_dataparser_outputs
    dataparser_outputs = self._generate_dataparser_outputs(split, **kwargs)
  File "/home/ubu/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py", line 237, in _generate_dataparser_outputs
    poses, transform_matrix = camera_utils.auto_orient_and_center_poses(
  File "/home/ubu/nerfstudio/nerfstudio/cameras/camera_utils.py", line 587, in auto_orient_and_center_poses
    origins = poses[..., :3, 3]
IndexError: too many indices for tensor of dimension 1

**Comment by Tavish9** [comment]
Hi, @DuVogel87, could you please check the content in `/home/ubu/Schreibtisch/fristingen_nerf/output_dir/transforms.json`, especially the key `transform_matrix`?

**Comment by DuVogel87** [comment]
Thats the input of my transform.json file:

```
{
    "camera_model": "OPENCV",
    "frames": [],
    "applied_transform": [
        [
            0.0,
            0.0,
            1.0,
            0.0
        ],
        [
            1.0,
            0.0,
            0.0,
            0.0
        ],
        [
            0.0,
            1.0,
            0.0,
            0.0
        ]
    ]
}

**Comment by DuVogel87** [comment]
![Bildschirmfoto vom 2024-12-30 08-56-56](https://github.com/user-attachments/assets/802816c1-8ca4-4531-8804-44ab0bdb89b4)

**Comment by Tavish9** [comment]
> Thats the input of my transform.json file:
> 
> ```
> {
>     "camera_model": "OPENCV",
>     "frames": [],
>     "applied_transform": [
>         [
>             0.0,
>             0.0,
>             1.0,
>             0.0
>         ],
>         [
>             1.0,
>             0.0,
>             0.0,
>             0.0
>         ],
>         [
>             0.0,
>             1.0,
>             0.0,
>             0.0
>         ]
>     ]
> }
> 
> I also attache a screeshot of the dir structure. 
> 
> I would appreciate any further help here. Thanks. 
> ```

what's the content in `frames["transform_matrix"] `

**Comment by DuVogel87** [comment]
I do not have such a file. It wasn't created during the conversion from Metashape to Nerfstudio 

So am i missing a file here?

**Comment by Tavish9** [comment]
I mean, in your `/home/ubu/Schreibtisch/fristingen_nerf/output_dir/transforms.json`, what's the content in the key `frames`?

**Comment by DuVogel87** [comment]
I am sorry. Maybe i misunderstood you before.

I copied the whole content of transforms.json here. There is nothing more, thats why its hard for me to relate to your request.

The image folders (image, image_2, image_4, image_8) are full of frames, starting with the original resolution size and then getting smaller and smaller.

So it sounds that i am missing a file or some input in the transforms.json file, or?

**Comment by DuVogel87** [comment]
I see! That's strange.

Any chance that you could have a look at my data if i upload it on wetransfer? Its not a big data set. 

Or any other idea what could have went wrong or how to make sure that the conversion works right?

Again, nerfstudio did not show any error message when it completed the conversion.

**Comment by Tavish9** [comment]
Have you tried [these two steps](https://docs.nerf.studio/quickstart/custom_dataset.html#metashape)?

**Comment by DuVogel87** [comment]
Yes, I’ve done that.

However, the information provided is somewhat unclear. When selecting "Export Cameras" and then choosing the XML export format, an XML file is generated, but no dataset of images is included. The instructions explicitly state that the alignment should be run before exporting the XML, but the guide doesn’t clearly explain how to export the arranged images.

To address this, I followed the workflow for PostShot and exported the images by selecting "Export Cameras" again and choosing "COLMAP" as the export format. This generated an image folder and a sparse folder.

Based on my approach, I ended up with an images folder and an XML file, which I used for the conversion.

Could the issue be that the exported dataset (COLMAP) and the exported XML are incompatible with each other?

**Comment by DuVogel87** [comment]
Solved it! 

Indeed the error appeared because of the dataset that i exported via "export cameras" and then choosed colmap. 

You must choose the option "convert images" and export the image dataset from that. Then it works!

**Comment by Tavish9** [comment]
Glad to hear!

**Comment by ariannaferraris** [comment]
> Solved it!
> 
> Indeed the error appeared because of the dataset that i exported via "export cameras" and then choosed colmap.
> 
> You must choose the option "convert images" and export the image dataset from that. Then it works!

@DuVogel87 Hello, would you be able to share the settings you used for exporting? I'm struggling with the same issue you have, but for some reason I'm not really able to solve it just by using the "Convert images" export setting

**Comment by DuVogel87** [comment]
Sure!

I am currently not at my desktop so i hope I can remember correctly. 

You want to export --> export cameras. There you choose export format xml. Name it as you wish. But xml as format is important. 

(Not sure: maybe you have to do the same export --> export cameras again and then choose colmap as file format. In the export settings uncheck images. I am not completely sure right now if you need the sparse too, but would make sense)

Then you go to export again and choose convert images. Make sure that you have not checked any of the options which say initial or something like that. You want the "raw" image dataset. Maybe it would be possible to use the original images in first place and its unnecessary to do the convert images process. Havent checked that.

When you have done all of that you proceed as mentioned here under the point metashape:

https://docs.nerf.studio/quickstart/custom_dataset.html#metashape

Sorry for my bad English. I hope it works. Otherwise reply here and i verify everything when i am back home this evening. 

Also, would be good if it works to let us all know :-)
