### ISSUE TITLE
help running process_data.py  !!

### ISSUE THREAD

**Issue by akanazawa** [nerfstudio-project/nerfstudio#524]
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/924632/191877134-d7098c76-b0ad-4845-97fe-d8d6ced59dc6.png">

**Comment by Kai-46** [comment]
If you install colmap via `sudo apt install colmap` on a machine without display, then you can run a fake Xorg server to make colmap work:
```
export DISPLAY=:1
sudo apt install xvfb
Xvfb :1 -screen 0 1024x768x16 &
```
But it seems that `sudo apt install colmap` doesn't use GPU.

**Comment by Tang31098** [comment]
> If you install colmap via `sudo apt install colmap` on a machine without display, then you can run a fake Xorg server to make colmap work:如果你在没有显示器的机器 `sudo apt install colmap` 上安装了 colmap，那么你可以运行一个假的 Xorg 服务器来使 colmap 工作：
> 
> ```
> export DISPLAY=:1
> sudo apt install xvfb
> Xvfb :1 -screen 0 1024x768x16 &
> ```
> 
> But it seems that `sudo apt install colmap` doesn't use GPU, which can be checked by:但似乎 `sudo apt install colmap` 不使用 GPU，可以通过以下方式进行检查：
> 
> ```
> colmap patch_match_stereo --help
> ```
> 
> The command will complain that "ERROR: Dense stereo reconstruction requires CUDA, which is not available on your system.", if cuda is not enabled.如果未启用 CUDA，则该命令将抱怨“错误：密集立体声重建需要 CUDA，这在您的系统上不可用。
I have encountered Dense Stereo Reconstruction Requirements CUDA, which is not available on your system. Can you tell me how to solve this situation? thanks
