### ISSUE TITLE
hide camera numbers when the scene is hidden

### ISSUE THREAD

**Issue by ethanweber** [nerfstudio-project/nerfstudio#567]
This looked funky when rendering with a NeRF because there were numbers in the background. We should hide the numbers when we hide the three.js scene.

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/16965789/192647407-1f565578-e319-4940-b41f-d3b089e23229.png">

**Comment by mcallisterdavid** [comment]
#1031

**Comment by mcallisterdavid** [comment]
#1031
