### ISSUE TITLE
Google Colab

### ISSUE THREAD

**Issue by ethanweber** [nerfstudio-project/nerfstudio#698]
Let's get this repo working in Google Colab.

**Comment by ethanweber** [comment]
@akristoffersen @TheQuantumFractal @jake-austin who are working on this right now.

**Comment by akristoffersen** [comment]
WIP [Google Colab](https://colab.research.google.com/drive/18w7FsHTgkd8FTJD74RPVcXFZAF9-DtOd?usp=sharing) link. This will be cleaned up in the future.

**Comment by Maki9009** [comment]
> [colab_ssh](https://github.com/WassimBenzarti/colab-ssh) works for port fowarding, it can be used to get `--viz=viewer` instead of tensorboard. Just tried and it works.

how would i implement it into the colab thats above in work in progress?

**Comment by venatiodecorus** [comment]
So I tried running this, but the tensorboard command just gives me a 403 error, any suggestions?

**Comment by jhzgjhzg** [comment]
> [colab_ssh](https://github.com/WassimBenzarti/colab-ssh) works for port fowarding, it can be used to get `--viz=viewer` instead of tensorboard. Just tried and it works.

Google banned the lab_ ssh, what should I do in such a situation

**Comment by venatiodecorus** [comment]
Oh I think the 403 error was because of browser settings, apparently cookie settings can cause that. I switched to Chrome and Tensorboard is working
