### ISSUE TITLE
Step "Setting up Cuda" on Win10 for training with instant-ngp shows errors

### ISSUE THREAD

**Issue by nosy-b** [nerfstudio-project/nerfstudio#701]
I can train on my own data using **nerfacto** but when I want to use **instant-ngp** it crashes at the step "Setting up cuda"

> RuntimeError: Error building extension 'nerfacc_cuda': [1/6] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc --generate-dependencies-with-compile --dependency-output contraction.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xc

My command: `ns-train instant-ngp --data .\data\nerfstudio\nighttest\colmap\`

**Additional context**
- I use instant-ngp without problems on Win10 but I had to follow _https://github.com/bycloudai/instant-ngp-Windows_
- I have cuda 11.6

Thank you and congrats for this brillant project! :)

**Comment by Hamapy** [comment]
I had the same problem.

**Comment by tancik** [comment]
This was likely a nerfacc issue. Nerfacc has been updated a number of times since this issue was raised so this is now out of date.
