### ISSUE TITLE
Server and render show disconnected when running training locally

### ISSUE THREAD

**Issue by ethanweber** [nerfstudio-project/nerfstudio#703]
**Server and render show disconnected when running training locally**

All the developers have been using remote compute and have not experienced this issue. This interferes with being able to pause the training!

**To Reproduce**
Run a training job locally and open the viewer.

**Expected behavior**
The "server" and "render" text should highlight green when it's working.

**Screenshots**
![image](https://user-images.githubusercontent.com/16965789/194182140-f72e04e2-1f3d-4f9d-b2e9-bad47484735f.png)

**Comment by satpalsr** [comment]
I am facing the same problem. Server Disconnected, Render Disconnected.

**Comment by satpalsr** [comment]
I realised I was using Brave browser so it was blocking the things. I turned down the shields and it's working now.

**Comment by satpalsr** [comment]
Also fixed, Render disconnected issue using the [comment](https://github.com/nerfstudio-project/nerfstudio/issues/765#issuecomment-1370854325)

**Comment by tancik** [comment]
No longer relevant
