### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/blender/lego/transforms_train.json'

### ISSUE THREAD

**Issue by catid** [nerfstudio-project/nerfstudio#705]
Running `ns-train vanilla-nerf` fails with this error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'data/blender/lego/transforms_train.json'
```

I opted to not use W&B option (3) Don't visualize my results.

**Comment by catid** [comment]
Nevermind was not set up properly

**Comment by suptimq** [comment]
Hi, I ran into the same error. would you mind explaining what was wrong with the setup?
