### ISSUE TITLE
qt.qpa.screen: QXcbConnection: Could not connect to display

### ISSUE THREAD

**Issue by 2feet6inches** [nerfstudio-project/nerfstudio#709]
$ ns-process-data --data room.mov --output-dir data/
```
Number of frames in video: 1616
[07:47:09] 🎉 Done converting video to images.                                                       process_data.py:433
[07:47:21] 🎉 Done downscaling images.                                                               process_data.py:451
──────────────────────────────────────────────  💀 💀 💀 ERROR 💀 💀 💀  ───────────────────────────────────────────────
Error running command: colmap feature_extractor --database_path data/colmap/database.db --image_path data/images
--ImageReader.single_camera 1 --ImageReader.camera_model OPENCV --SiftExtraction.use_gpu 1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.
```

**Comment by 2feet6inches** [comment]
Probably the same issue as this. I was able to run it by adding the --no-gpu flag.
https://github.com/colmap/colmap/issues/18

**Comment by Wushuangpin** [comment]
> 应该是和这个一样的问题。我可以通过添加 --no-gpu 标志来运行它。 [colmap/colmap#18](https://github.com/colmap/colmap/issues/18)
This is fine, but the preprocessing time is too long without gpu acceleration.Also with other solutions: Use gpu acceleration without opening the colmap graphics window.

**Comment by paudom** [comment]
Hi @Wushuangpin do you know if the solution of using GPU without opening graphics window is possible as the quoted message notes? How can be done? Thanks in advance!

**Comment by Zunhammer** [comment]
This issue (re)occured a few days ago to me in some testing environment which is most likely to changes in the dev branch of colmap. You should always use defined versions, optimally a release like 3.7 and you should be fine again. See [Colmap v3.7](https://github.com/colmap/colmap/releases/tag/3.7)

**Comment by tancik** [comment]
Closing as it appears to be stale. Feel free to reopen if needed.

**Comment by ZixunHuang1997** [comment]
I came across the same problem when I tried to use my custom data with COLMAP. 
1. Running it by adding the `--no-gpu` flag works for me.
2. Here is another solution using gpu acceleration without opening the COLMAP graphics window. 
> vim ~/.bashrc
> export QT_QPA_PLATFORM='offscreen'
> source ~/.bashrc

**Comment by ZixunHuang1997** [comment]
> Hi @Wushuangpin do you know if the solution of using GPU without opening graphics window is possible as the quoted message notes? How can be done? Thanks in advance!


I came across the same problem when I tried to use my custom data with COLMAP.
1. Running it by adding the --no-gpu flag works for me.
2. Here is another solution using gpu acceleration without opening the COLMAP graphics window.
`vim ~/.bashrc`
`export QT_QPA_PLATFORM='offscreen'`
`source ~/.bashrc`
