### ISSUE TITLE
Weird results with nerfacto and blender dataset, disconnected render

### ISSUE THREAD

**Issue by salykovaa** [nerfstudio-project/nerfstudio#711]
Hi Nerfstudio developers! I read the documentation, but there is no information how to run nerfacto with blender dataset. So my first assumption was ```ns-train nerfacto --vis viewer blender-data --data ./data/blender/lego ```, but rendering results are weird (see image below). It also says **Disconnected renderer**. I run it locally.

However, with ```poster``` dataset nerfacto works perfectly: renderings are good and both server and render are **connected**.

Rendered after 1000 steps.
![image](https://user-images.githubusercontent.com/63703454/194336896-9f34e904-7ee5-4dfb-855c-eff4eb3ffbf1.png)

**Comment by tancik** [comment]
The blender scene has quite different requirements than real scenes. The `near` and `far` planes need to be adjusted (also the sampling patter should be adjust to uniform which currently can't be done via cli). Note, we have not tuned the nerfacto model to perform well on blender scenes as we don't believe they are representative of most real world scenes.

Try this command, you will need to zoom out a little (we shouldn't be applying the near clipping plane during eval.
`ns-train nerfacto --pipeline.model.near-plane 2 --pipeline.model.far-plane 10  blender-data --data data/blender/lego/`

Clipping plane bug tracked here - #714

**Comment by salykovaa** [comment]
Thank you for the answer!
