### ISSUE TITLE
custom dataset for semantic-nerf

### ISSUE THREAD

**Issue by vahidEttehadi** [nerfstudio-project/nerfstudio#725]
Hi, Thanks for the great nerfstudio work. I am looking for some document/code to understand how to feed my semantic data to semantic-nerf. I looked at [sitcoms3D](https://github.com/ethanweber/sitcoms3D) to find out how to create the dataset but I couldn't find any pre-processing code there. Can you provide more details on how we can feed a custom semantic dataset? Thanks

**Comment by cezarbbb** [comment]
Same question:(

**Comment by ethanweber** [comment]
Responded in Issue #1395 and #1275 so will close this thread.

**Comment by MoZhenJ** [comment]
> Responded in Issue #1395 and #1275 so will close this thread.

love you
