### ISSUE TITLE
Viewport turns black at around 5-7% of training on nerfacto

### ISSUE THREAD

**Issue by dokluch** [nerfstudio-project/nerfstudio#730]
No matter the dataset, the viewport turns black at around 5-7% and does not go back again.
How to monitor the training in this case?

(Windows 10)

Only the cameras are left

<img width="1856" alt="image" src="https://user-images.githubusercontent.com/135181/194630211-b84c8612-e1b0-4f5f-949d-fd61e416fde7.png">

<img width="1825" alt="image" src="https://user-images.githubusercontent.com/135181/194630867-9956bdd5-81a6-4bf3-8fc2-13be964126be.png">

**Comment by tancik** [comment]
When training `nerfacto` for a very long time >50k iterations, it can sometime diverge causing the entire scene to turn black. The latest version of the code now sets the max iteration count to 30k (before it was 1million). Our recommendation is to either update to the latest version, or pause training around 2-3%.

**Comment by ethanweber** [comment]
Right, you can install the latest version and this should be fixed. 20K iterations (see the left column during training) is plenty long to train for. You should be able to start making a camera path and rendering a video after even 5 minutes or so.

**Comment by cyhhhhhhit** [comment]
@ethanweber  hi, i faced the same issue when train the robustNerf( the latest version), can you tell me the reason why it happened(the viewport turns black ) or the detail changes in the latest version about how to solving this issue
