### ISSUE TITLE
What is nerfacto?

### ISSUE THREAD

**Issue by kwea123** [nerfstudio-project/nerfstudio#742]
> This guide is coming soon. This is our flagship method that we encourage creators to use when making videos. It uses techniques from [Mip-NeRF 360](https://jonbarron.info/mipnerf360/) and [Instant-NGP](https://nvlabs.github.io/instant-ngp/).

What exactly are the techniques that you combined?

**Comment by tancik** [comment]
We plan to add a more comprehensive guide to the docs, but here is a brief description.
Nerfacto first samples the scene uniformly up to a distance of 1 then samples linear in disparity up to a distance of 1000. These samples are fed into a small proposal network (from mipnerf360) to predict weights. Using these weights we use a PDF sampler to generate a new set of samples in locations that scene content is predicted to exist. These samples are passed into a different "nerf" network to predict rgb and density which are rendered into a predicted color the same way as NeRF. The proposal network is supervised on the weights from the "nerf" network (same as mipnerf360). We also use the distortion loss and interval loss from mipnerf360. To better reconstruct far objects we use scene contraction to map the scene to a bounded region (mipnerf360). To handle variations in appearance (like exposure and lighting) we use appearance embeddings (from nerf-w). For speed, we use the hash encoding and fused MLPs that were proposed in Instant-NGP.

**Comment by kwea123** [comment]
Got it, makes sense, will wait for your documentation!

**Comment by kwea123** [comment]
One more question: 
> For speed, we use the hash encoding and fused MLPs that were proposed in Instant-NGP

So this means that you don't use integrated positional encoding (or positional encoding) anymore?

**Comment by qhdqhd** [comment]
> @tancik 还有一个问题：
> 
> > 为了提高速度，我们使用了 Instant-NGP 中提出的哈希编码和融合 MLP
> 
> 那么这意味着您不再使用集成位置编码（或位置编码）了吗？

https://docs.nerf.studio/en/latest/_images/models_nerfacto_field-light.png
According to this, it does not use PE or IPE.

**Comment by Serenitysmk** [comment]
> We plan to add a more comprehensive guide to the docs, but here is a brief description. Nerfacto first samples the scene uniformly up to a distance of 1 then samples linear in disparity up to a distance of 1000. These samples are fed into a small proposal network (from mipnerf360) to predict weights. Using these weights we use a PDF sampler to generate a new set of samples in locations that scene content is predicted to exist. These samples are passed into a different "nerf" network to predict rgb and density which are rendered into a predicted color the same way as NeRF. The proposal network is supervised on the weights from the "nerf" network (same as mipnerf360). We also use the distortion loss and interval loss from mipnerf360. To better reconstruct far objects we use scene contraction to map the scene to a bounded region (mipnerf360). To handle variations in appearance (like exposure and lighting) we use appearance embeddings (from nerf-w). For speed, we use the hash encoding and fused MLPs that were proposed in Instant-NGP.

Hi! I would like to ask what is the unit of 1 here in UniformLinDispPiecewiseSampler here? 1 meter or something else?

**Comment by tancik** [comment]
The dataset images get scaled in to a unit 2 cube. So a unit of 1 is roughly half the distance between the two furthest camera positions.

**Comment by Serenitysmk** [comment]
> The dataset images get scaled in to a unit 2 cube. So a unit of 1 is roughly half the distance between the two furthest camera positions.

Thank you very much!

**Comment by wanger-666** [comment]
Hi!This sampler allocates half of the samples uniformly up to a distance of 1 from the **camera**.Why not allocates half of the samples uniformly up to a distance of 1 from the **near**?

**Comment by tancik** [comment]
@wanger-666 It does start at the near plane.
