### ISSUE TITLE
Unable to load a previous checkpoint (inputdata is from Record3d)

### ISSUE THREAD

**Issue by Wushuangpin** [nerfstudio-project/nerfstudio#754]
My problem is similar to the question#743
I trained a dataset（from Record3d） but the training is not over 100%. Now I want to build on my previous training results. But it says something wrong.
Command：“ns-train nerfacto --trainer.load-dir /root/autodl-tmp/project/outputs/-root-autodl-tmp-project-EXR_RGBD/nerfacto/2022-10-11_121534 --data /root/autodl-tmp/project/EXR_RGBD”
Result：“FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/project/EXR_RGBD/transforms.json'”
It seems that because data using the Record3d type isn't preprocessed by colmap, it doesn't have the transforms.json file.

**Comment by tancik** [comment]
`ns-train` defaults to using the `nerfstudio-data` dataset format. For record3d you need to use the `record3d-data` dataparser.

Try the following command:
`ns-train nerfacto --trainer.load-dir /root/autodl-tmp/project/outputs/-root-autodl-tmp-project-EXR_RGBD/nerfacto/2022-10-11_121534 record3d-data --data /root/autodl-tmp/project/EXR_RGBD`

**Comment by ethanweber** [comment]
Closing since it's resolved.

**Comment by Wushuangpin** [comment]
> `ns-train`默认使用`nerfstudio-data`数据集格式。对于record3d，您需要使用`record3d-data`数据解析器。
> 
> 尝试以下命令： `ns-train nerfacto --trainer.load-dir /root/autodl-tmp/project/outputs/-root-autodl-tmp-project-EXR_RGBD/nerfacto/2022-10-11_121534 record3d-data --data /root/autodl-tmp/project/EXR_RGBD`

Yes, thank you.
