### ISSUE TITLE
Get the viewer server to listen to 0.0.0.0

### ISSUE THREAD

**Issue by alexandrumeterez** [nerfstudio-project/nerfstudio#755]
Is there any way to launch the viewer on 0.0.0.0? I have to run it on a machine that I can't ssh to (so I can't port forward), but if I could get the viewer to listen for connections from any address then I could open it. Thanks!

**Comment by ethanweber** [comment]
Hi! I'll be fixing this with PR #698! You can take a look already. It's close but quite done.
