### ISSUE TITLE
Bug in instant ngp data parser?

### ISSUE THREAD

**Issue by feixh** [nerfstudio-project/nerfstudio#759]
Should the line below
https://github.com/nerfstudio-project/nerfstudio/blob/f14fbb91538451b982028263277badfe6d757f2f/nerfstudio/data/dataparsers/instant_ngp_dataparser.py#L80

be something like
```
poses[:, :3, 3] *= self.config.scene_scale 
```
to scale the translational component of *each* pose?

And similarly,
https://github.com/nerfstudio-project/nerfstudio/blob/f14fbb91538451b982028263277badfe6d757f2f/nerfstudio/data/dataparsers/instant_ngp_dataparser.py#L82

->

```
camera_to_world = torch.from_numpy(poses[:, :3, :4]) 
```
?

**Comment by akristoffersen** [comment]
Thank you for finding this!
