### ISSUE TITLE
Docs Pipeline graphic doesn't show well on darkmode.

### ISSUE THREAD

**Issue by akristoffersen** [nerfstudio-project/nerfstudio#764]
**Describe the bug**
On https://docs.nerf.studio/en/latest/nerfology/methods/nerf.html, the graphics don't always show up well on browsers with dark mode. I think it's a transparency issue?

**Screenshots**
<img width="804" alt="Screen Shot 2022-10-12 at 12 33 07 PM" src="https://user-images.githubusercontent.com/24887690/195431956-7c51f90b-03a8-4f6f-817e-8e51b5c84386.png">

**Comment by tancik** [comment]
This section is just trying to highlight the fields. But perhaps that is confusing and needs some tweaking.

**Comment by akristoffersen** [comment]
Oh I mean its not easily visible, because of the color choices

**Comment by enginksz** [comment]
I guess we can't expect it to produce any results in a dark or low-light environment, right?
