### ISSUE TITLE
Can "Upgrade" only to "WebSocket when running viewer 

### ISSUE THREAD

**Issue by snarb** [nerfstudio-project/nerfstudio#772]
I have a clean install on the Ubuntu 22. When running viewer with `ns-train nerfacto --vis viewer` in the browser on localhost:7007 I see only_:` Can "Upgrade" only to "WebSocket".`_ message

**Comment by tancik** [comment]
Not sure at first thought, some questions to help get to the bottom of this:
1. What url are you navigating to? Is it the one provided in the terminal?
2. Is the error in the terminal or printed directly in the browser, or in the browser console?
3. Is training running, or is it frozen?

**Comment by snarb** [comment]
Hm. In the beginning, I enabled port forwarding and got this error on the remote machine. Then I used 'localhost:7007' URL locally and got this error.  The suggested URL 'https://viewer.nerf.studio/versions/22-10-07-0/?websocket_port=7007'  is working fine.

**Comment by tancik** [comment]
Just to clarify, it is working now? Can I close this issue?

**Comment by tancik** [comment]
If you want to use a remote machine, the setup should be the following:

Remote Machine (with GPU):
+ has nerfstudio installed
+ Where training takes place

Local Machine (for viewing):
+ has open port
`ssh -L 7007:localhost:7007 USER@REMOTE.SERVER.IP`
+ Navigate to url specified in the training job on the remote server.

**Comment by snarb** [comment]
Thanks

**Comment by paudom** [comment]
Hi @tancik, I'm getting the same problem as @snarb. Training gives me  the following url: `https://viewer.nerf.studio/versions/22-10-13-0/?websocket_url=ws://localhost:7007` but I get the following page:

<img width="380" alt="Screenshot 2022-10-26 at 12 07 25" src="https://user-images.githubusercontent.com/37597137/197999041-c66bd64b-89d3-40ab-9adc-b962ef03aa85.png">

The page is blank and this does not connect to my training. I'm running this from a remote machine and I've done the tunnel earlier using the port 7007, but keeps saying `Server Disconnected`

Thanks in advance!

**Comment by paudom** [comment]
I was using Safari and did not work, same URL on google chrome works as expected, don't know why. Solved. Sorry to bother.

**Comment by paudom** [comment]
I finally solved, by using Google Chrome instead of Safari. Don't know why it does not work on Safari
