### ISSUE TITLE
open a localhost webserver

### ISSUE THREAD

**Issue by Wushuangpin** [nerfstudio-project/nerfstudio#779]
I remember the old version before nerfstudio in training on two address, https://viewer.nerf.studio/versions/22-10-07-0/xxxx and https://localhost:5000/xxxxxxxx, I would like to ask whether the local service of localhost is still available and how to open it.

**Comment by ethanweber** [comment]
Is this what you are looking for? https://docs.nerf.studio/en/latest/developer_guides/viewer/viewer_overview.html#installing-and-running-locally It will run by default on port 4000.

**Comment by Wushuangpin** [comment]
Yes, that's right! Thank you
