### ISSUE TITLE
Camera view jumps when using side panel

### ISSUE THREAD

**Issue by tancik** [nerfstudio-project/nerfstudio#789]
**Describe the bug**
Clicking buttons anywhere in the control panel can cause the camera to jump.

**To Reproduce**
1. Zoom in very close to the training data
2. Click on the right panel anywhere
3. The camera jumps

**Expected behavior**
The camera should not jump. I'm guessing the training image is "selected" and when it sees a "click" event it fires.

**Screenshots**
https://user-images.githubusercontent.com/3310961/196059592-67454ca8-9b87-485e-b0bd-8c124a61ab34.mp4

**Comment by mcallisterdavid** [comment]
Ah, sorry about these bugs. This one is an easy fix at least
