### ISSUE TITLE
Unable to run Semantic-NerfW

### ISSUE THREAD

**Issue by Drakael** [nerfstudio-project/nerfstudio#805]
**Describe the bug**
Launching semantic-nerfw training throws the error:

AttributeError: 'NoneType' object has no attribute 'stuff_classes'
at line 96 of nerfstudio\models\semantic_nerfw.py

            num_semantics_stuff_classes=len(self.semantics.stuff_classes),

**To Reproduce**
either command : ns-train semantic-nerfw --data data\nerfstudio\poster nerfstudio-data
or even : ns-train semantic-nerfw --data data\blender\lego --pipeline.model.near-plane 2. --pipeline.model.far-plane 6. blender-data

**Comment by tancik** [comment]
Hi,
The problem is that the blender dataset does not contain semantic information. Only the friends dataset does.
