### ISSUE TITLE
Documentation for camera coordinate frames and creating the json

### ISSUE THREAD

**Issue by akshay-krishnan** [nerfstudio-project/nerfstudio#810]
**Is your feature request related to a problem? Please describe.**
What is the camera coordinate frame used by nerfstudio? Colmap uses +x -> right, +y -> down, +z -> forward. 
The code at [this line](https://github.com/nerfstudio-project/nerfstudio/blob/863fc77ab5f247ff3ce3c80f192173063529b036/scripts/process_data.py#L438) makes me think that nerfstudio uses +x -> right, +y -> up, +z -> behind camera, like blender? 

I would like to use camera poses from a different pipeline (synthetic images). I could create the json file that you create after pre-processing the colmap output, but I am confused what the coordinate system is. Specifically the [ lines 439-440 here](https://github.com/nerfstudio-project/nerfstudio/blob/863fc77ab5f247ff3ce3c80f192173063529b036/scripts/process_data.py#L439) show that the X and Y axes are being swapped, and z is flipped (again) ? 

Some explanation of the camera coordinate frame would be very useful! Please point me to it if it exists already.

**Comment by ethanweber** [comment]
Hey @akshay-krishnan, you are correct in your interpretation. I'm adding the docs in PR #889.

**Comment by akshay-krishnan** [comment]
Thank you @ethanweber !
