### ISSUE TITLE
Depth normalization inconsistent for packed vs. nonpacked samples

### ISSUE THREAD

**Issue by kevinddchen** [nerfstudio-project/nerfstudio#811]
**Describe the bug**
When the raymarching samples are packed, the depth is calculated according to `sum_i w_i t_i`: https://github.com/nerfstudio-project/nerfstudio/blob/863fc77ab5f247ff3ce3c80f192173063529b036/nerfstudio/model_components/renderers.py#L236

When the raymarching samples are not packed, the depth is calculated with a normalization factor dividing by the total accumulation, `(sum_i w_i t_i) /  (sum_i w_i)`: https://github.com/nerfstudio-project/nerfstudio/blob/863fc77ab5f247ff3ce3c80f192173063529b036/nerfstudio/model_components/renderers.py#L238

**To Reproduce**
N/A

**Expected behavior**
For consistency, the calculation for packed samples should also divide by the total accumulation.

**Screenshots**
N/A

**Additional context**
If this is desired, I can implement the change.

**Comment by tancik** [comment]
Great catch! If you make a PR I can accept it!
