### ISSUE TITLE
rounding error in camera generation

### ISSUE THREAD

**Issue by dozeri83** [nerfstudio-project/nerfstudio#814]
Hi, 
I having an issue where the rendered camera width/height is not equal to the original width/height.

It happens since the height is odd:

https://github.com/nerfstudio-project/nerfstudio/blob/6f4fb506e2155bcf6bffedc157055e40f7931b48/nerfstudio/cameras/cameras.py#L182

can you replace the above line with this line?  (multiplication should be preformed before conversion)

`            h_w = torch.Tensor((c_x_y*2).to(torch.int64).to(self.device)).broadcast_to((self._num_cameras))
`

Thanks

**Comment by tancik** [comment]
Good catch, thank for the find!
