### ISSUE TITLE
Using known camera positions

### ISSUE THREAD

**Issue by Borknab** [nerfstudio-project/nerfstudio#819]
Hello!

Thanks for building this application! Seems like a perfect tool for prototyping & studying how different are NeRF techniques between each other in reconstructing the same scenes.

We were wondering if you already have any idea on how to use known camera poses instead of COLMAP (for example, camera data from the datasets of autonomous vehicles)? Seems like `cameras.bin` and `images.bin` need to be manually created based on known camera intrinsics and frame positions. Do you guys have any suggestions and has there been any work already done towards supporting known camera positions?

**Comment by akristoffersen** [comment]
Hi Borknab, there are currently two ways to do this: you could either convert your data into one of our supported formats (Blender, InstantNGP, Nerfstudio, etc.) then run the training command from there, or you could write a custom dataparser for your use-case. Check out [the current dataparsers code](https://github.com/nerfstudio-project/nerfstudio/tree/main/nerfstudio/data/dataparsers) for more info if you'd be interested in trying that!

`cameras.bin` and `images.bin` are artifacts of COLMAP, and aren't used in `ns-train`.

**Comment by tancik** [comment]
Here are the data conventions for using your own poses.
https://docs.nerf.studio/en/latest/quickstart/data_conventions.html
