### ISSUE TITLE
How to BAKE the nerf scene like MobileNerf or BakeNerf?

### ISSUE THREAD

**Issue by cyz2727327** [nerfstudio-project/nerfstudio#836]
This is really awesome work! 

I have a quick question, can nerfstudio bake the nerf renderers like BakeNerf (https://phog.github.io/snerg/) and MobileNerf (https://mobile-nerf.github.io/) ? That would be super helpful to my current project! Thank you in advance

**Comment by tancik** [comment]
This is currently not something supported by nerfstudio. It is something we hope to incorporate, but it is not something we are actively working on at the moment.

**Comment by cyz2727327** [comment]
thank you for the reply !
