### ISSUE TITLE
ns command not working

### ISSUE THREAD

**Issue by MntRushmore** [nerfstudio-project/nerfstudio#837]
how to run ns command

**Comment by fuzRodahh** [comment]
i have the same problem

**Comment by Tobe2d** [comment]
looks like the instructions are mixed with linux

**Comment by tancik** [comment]
Here are instructions for getting to the windows terminal (where you enter the ns commands) - https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/#:~:text=Press%20Win%20%2B%20R%20to%20open,PowerShell%20or%20Windows%20Terminal%20instead.

**Comment by fuzRodahh** [comment]
> Here are instructions for getting to the windows terminal (where you enter the ns commands) - https://www.makeuseof.com/tag/a-beginners-guide-to-the-windows-command-line/#:~:text=Press%20Win%20%2B%20R%20to%20open,PowerShell%20or%20Windows%20Terminal%20instead.

why you showing us how to get cmd??

**Comment by tancik** [comment]
Hi, sorry I misunderstood the question. Do you mind explaining what you have tried and what errors you are receiving? I haven't used windows in over a decade so I am probably missing some of the subtleties.  You should be able to run directly in windows, windows subsystem linux shouldn't be necessary. Maybe @terrancewang can chime in with how he runs training as he as been developing with windows.

**Comment by tancik** [comment]
Have you installed with `pip install nerfstudio`?

**Comment by tancik** [comment]
Can you post the output to the following two commands,
`pip list`
And
`ns-train --help`

**Comment by fuzRodahh** [comment]
> Can you post the output to the following two commands, `pip list` And `ns-train --help`

'ns-train' is not recognized as an internal or external command,
operable program or batch file.

**Comment by tancik** [comment]
What is the output to `pip list`?

**Comment by tancik** [comment]
@WolfGamer2 It doesn't seem like your image was properly linked.

**Comment by tancik** [comment]
I still only see `[image: image.png]`
Can you copy and paste the text output?

**Comment by tancik** [comment]
That list should include `nerfstudio`. Since it doesn't it means that `nerfstudio` was not successfully installed. Can you paste the output to `pip install nerfstudio`.

**Comment by fuzRodahh** [comment]
> That list should include `nerfstudio`. Since it doesn't it means that `nerfstudio` was not successfully installed. Can you paste the output to `pip install nerfstudio`.

im already have nerfstudio, but still cant do ns command

**Comment by tancik** [comment]
@fuzRodahh 
Can you run `python` in the command prompt. Then run `import nerfstudio` and see if there are any errors.

**Comment by fuzRodahh** [comment]
> 

i can , and no error

**Comment by fuzRodahh** [comment]
> @fuzRodahh Can you run `python` in the command prompt. Then run `import nerfstudio` and see if there are any errors.

i think @Tobe2d was right, it mixed with linux tutorial

**Comment by tancik** [comment]
Hmm, I'm at a bit of a loss. It seems like this must be an issue with your particular windows setup. Maybe try installing from from source.
```
pip uninstall nerfstudio
git clone https://github.com/nerfstudio-project/nerfstudio.git
cd nerfstudio
pip install --upgrade pip setuptools
pip install -e .
```

**Comment by tancik** [comment]
Ok, well if you have the folder downloaded, you can run
`python scripts/train.py` instead of `ns-train`
All the other aliases are listed here
https://docs.nerf.studio/en/latest/reference/cli/index.html

**Comment by terrancewang** [comment]
Hello sorry that the commands aren't working for you :(

I'm working on Windows 10 and usually use Git-Bash instead of powershell, but I just ran through the [Quickstart ](https://github.com/nerfstudio-project/nerfstudio) steps on powershell to try to reproduce your error, but I was unable to do so. My best guess is that it has something to do with your setup as well. Hopefully in the meantime you can run the scripts directly. 


![Capture](https://user-images.githubusercontent.com/19509183/198930557-c30e30d8-a404-46b4-86aa-d8d308a85778.PNG)

**Comment by tancik** [comment]
@WolfGamer2  can you post the entire error

**Comment by tancik** [comment]
I don't think you need any of these extra packages. If it doesn't let you continue without selecting one, try selecting the "Desktop development with C++"

**Comment by tancik** [comment]
@WolfGamer2 Do you have an nvidia GPU? It is required for using nerfstudio. Assuming you do, you will need to install CUDA - https://docs.nvidia.com/cuda/cuda-quick-start-guide/index.html

**Comment by tancik** [comment]
Nerfstudio won't work without an nvidia gpu. An alternative is to use colab for compute - https://colab.research.google.com/github/nerfstudio-project/nerfstudio/blob/main/colab/demo.ipynb
