### ISSUE TITLE
Add record3d -> nerfstudio dataset conversion

### ISSUE THREAD

**Issue by tancik** [nerfstudio-project/nerfstudio#854]
For consistency, we should add an option in `ns-process-data` that takes in a record3d dataset. We can then remove the record3d dataparser and only use the nerfstudio dataset format.

**Comment by kevinddchen** [comment]
I can do this.

To clarify, this would involve modifying [scripts/process_data.py](scripts/process_data.py) by adding a `tyro.conf.subcommand(name="record3d")`, which creates a suitable `transforms.json` file. Correct?

**Comment by akristoffersen** [comment]
> I can do this.
> 
> 
> 
> To clarify, this would involve modifying [scripts/process_data.py](scripts/process_data.py) by adding a `tyro.conf.subcommand(name="record3d")`, which creates a suitable `transforms.json` file. Correct?

Yep! Unfortunately I just started on this and will be pushing the PR  in the next couple hours. Sorry about that! I should have assigned it earlier

**Comment by kevinddchen** [comment]
Ah! I have been scooped!

**Comment by tancik** [comment]
@kevinddchen You have been active on this repo. If you send your email to tancik@berkeley.edu I can add you to our slack.
