### ISSUE TITLE
wrong path format in sf_street/transforms.json

### ISSUE THREAD

**Issue by monniert** [nerfstudio-project/nerfstudio#874]
**Describe the bug**

image paths in `sf_street/transforms.json` are badly formatted, triggering an error during data loading.
E.g. `images\\frame_00001.png` should be `images/frame_00001.png`

**To Reproduce**

`ns-download-data --dataset nerfstudio --capture sf_street` and look at `sf_street/transforms.json`

**Comment by kevinddchen** [comment]
This is due to a change I made in #832. I will fix this.

**Comment by monniert** [comment]
Alright closing the issue then, thanks for the quick reply!
