### ISSUE TITLE
Equirectangular Camera Support

### ISSUE THREAD

**Issue by akristoffersen** [nerfstudio-project/nerfstudio#888]
**Is your feature request related to a problem? Please describe.**
Currently, 360 data must be taken from the raw Insta360 format, and then the inner rectangle is cropped to get out a usable part of the image. We could solve this either through masking, or by converting the data into another format, like equirectangular.

**Describe the solution you'd like**
This might be difficult, as the sampling from the image has to be updated for equirectangular. Normal uniform sampling over pixels will result in biases around the poles of the image. The viewer may also need updating, as each of the cameras is no longer a flat plane, but a textured sphere (might be fine to just do an equirectangular though).

**Comment by kevinddchen** [comment]
This sounds interesting. I don't mind helping out with this. I even have a Insta360 camera to test as well.
