### ISSUE TITLE
Bug in exporting depth images using `ns-render`

### ISSUE THREAD

**Issue by Karbo123** [nerfstudio-project/nerfstudio#900]
**Describe the bug**
I found exporting RGB images works well, but when it comes to depth images, it may fail.
I think the error comes from [the code for saving depth](https://github.com/nerfstudio-project/nerfstudio/blob/71601f304f3e194a2c359d476385d84c73123a46/scripts/render.py#L83).
When we save RGB images, variable `image` is a numpy array with shape `(H, W, 3)`, and its range is 0~1, so it works well.
However, when we are saving depth images, `image` is a numpy array with shape `(H, W, 1)`, and its range is >0 (but may larger than 1).
I think maybe we could save depth by scaling up real depth values by a large factor (e.g. 1000), and then save it in uint16 format?

**To Reproduce**
I checked this error by inspecting the `image` variable as shown below:
![image](https://user-images.githubusercontent.com/42935526/200101498-1f4e40a0-cf92-4a64-b64f-2031693a46f8.png)

An example:
```python
device=0
attr = "depth"
ckpt_dir = "reproduce_output"

CMD_RENDER = f"""CUDA_VISIBLE_DEVICES={device} ns-render \
--load-config {ckpt_dir}/config.yml \
--rendered-output-name {attr} \
--traj filename \
--camera-path-filename ./experiments_nerfs/scannet_blender/cameras.json \
--output-path {ckpt_dir}/render_{attr}/output.mp4 \
--output-format images"""
```

**Comment by Karbo123** [comment]
I found adding `image = image.squeeze()` before saving may temporarily address the issue, but it saves in uint8 and losses the precision. Maybe we should write extra codes for saving depth images??

**Comment by tancik** [comment]
Duplicate #862
