### ISSUE TITLE
when train,stuck 99.97%

### ISSUE THREAD

**Issue by bobbyning** [nerfstudio-project/nerfstudio#906]
**Describe the bug**
hello,when train a model 
ns-download-data --dataset=nerfstudio --capture=poster
then ,when progress 99.97%,it stuck for a very long time
![image](https://user-images.githubusercontent.com/38188009/200164044-382d7be5-de00-49a9-9d9b-9e4a16105999.png)

and then 
use "strace -p pid[id]"，at ubuntu20 PC
find
![image](https://user-images.githubusercontent.com/38188009/200164208-a6a1ced4-0cb8-4fd0-8d63-ce858adeee70.png)
what is wrong?
it may be a very big bug!

**Comment by jhzgjhzg** [comment]
Have you solved the problem? I encountered the same error. I can only use ctrl+c to forcibly stop the command.

**Comment by bobbyning** [comment]
> 

no,this problem appear again and again
it must be a very big bug!

**Comment by riven314** [comment]
I encountered the same issue when I was running the provided colab notebook
<img width="1462" alt="Screenshot 2022-11-08 at 1 35 06 AM" src="https://user-images.githubusercontent.com/21143399/200376996-1921b370-b688-42c3-9996-285ea5e4b2fa.png">

**Comment by tancik** [comment]
Fixed in #914 Will be included in next pip package. Note that the code is the same, now it just reports that training is finished and tells users to use ctrl+c to quit. In colab you should press the stop button.
