### ISSUE TITLE
Getting nan in ns-render results in semantic-nerfw

### ISSUE THREAD

**Issue by FarahSaeed** [nerfstudio-project/nerfstudio#911]
Thank you for this project!

I am running semantic-nerfw. I have trained using `ns-train semantic-nerfw`. I  try to render using 
`ns-render --load-config outputs/data-friends-TBBT-big_living_room/semantic-nerfw/2022-10-31_082619/config.yml --traj filename --camera-path-filename outputs/data-friends-TBBT-big_living_room/semantic-nerfw/2022-10-31_082619/camera_path.json --output-path renders/output.mp4`

I have seen the output image has nan values in the code. The output video is showing plain images without anything in it. I used P100 GPU.

I have tried other methods on custom data. They work fine in ns-render. I may be missing something in ns-render in semantic-nerfw.

Would really appreciate if you can support regarding this. 

Thanks

**Comment by kevinhangoat** [comment]
I had the same issue with semantic-nerfw. I tried several datasets and they all rendered NaN in outputs. I was sure that I pulled the latest commit and also tried different datasets, but still cannot make it work. Really hope to hear from anyone who succeed with this pipeline. Thank you so much!

**Comment by tancik** [comment]
Fixing it  in #910

**Comment by FarahSaeed** [comment]
Thanks!
