### ISSUE TITLE
Deleting Cameras doesn't work properly

### ISSUE THREAD

**Issue by gateway** [nerfstudio-project/nerfstudio#918]
**Describe the bug**

I set up 14 cameras for an animation, I deleted camera 2 out of the list which removed it from the right side bar, however the camera was still listed in the 3d view, and when I click on camera 3 from the right side panel it selects camera 2..

See Screen shot..

![image](https://user-images.githubusercontent.com/519563/200441378-115ea6cd-d1be-4acd-a71e-e782b73b8d47.png)

**Comment by mcallisterdavid** [comment]
https://github.com/nerfstudio-project/nerfstudio/pull/920
