### ISSUE TITLE
Failed to parse options: unrecognised option '--output_path'

### ISSUE THREAD

**Issue by simicvm** [nerfstudio-project/nerfstudio#919]
**Describe the bug**
```bash
ns-process-data images --data DATA_PATH --output-dir PROCESSED_DATA_DIR --no-gpu
```
throws `Failed to parse options: unrecognised option '--output_path'` error at the `colmap mapper` step.

Issue seems to be that colmap uses `--export-path` instead of `--output-path`. Running manually 
```bash
colmap mapper --database_path path/to/database/database.db --image_path path/to/images --export_path path/to/colmap/sparse
```
produces the desired output without errors.

**Additional context**
Ubuntu 18.04 LTS
CUDA 11.3
PT 1.12
COLMAP 3.4
nerfstudio 0.1.8

COLMAP installed via `sudo apt install colmap` so it does not have GPU support.

**Comment by simicvm** [comment]
colmap 3.8 uses `--output-path` indeed. colmap 3.4 uses `--export-path`.

My bad, sorry! Closing.

**Comment by penguinflys** [comment]
Is it already solved but not relaased yet? should anyone make a PR for it?

**Comment by simicvm** [comment]
> Is it already solved but not relaased yet? should anyone make a PR for it?

The fix for this is to update the Colmap to the lates release, 3.8. Although I tested with 3.7 too, and it works. 

I assume there will be no fix for this, because it's not really an issue. However, they should set the version requirement explicitly, so people know.

**Comment by iker-lluvia** [comment]
> colmap 3.8 uses `--output-path` indeed. colmap 3.4 uses `--export-path`.
> 
> My bad, sorry! Closing.

Sorry, but it expects `--export_path`, with underscore. Just in case someone wants to modify the source code.

**Comment by ZixunHuang1997** [comment]
`--export_path` works for COLMAP3.4. 
1. In file nerfstudio/process_data/colmap_utils.py, you can replace `--output_path`  into `--export_path` for colmap 3.4.
2. Or just manually run `colmap mapper --database_path path/to/database/database.db --image_path path/to/images --export_path path/to/colmap/sparse` after you got error in data processing.
![image](https://user-images.githubusercontent.com/106426767/232184288-9824f701-52cd-4fb1-91e8-04f531a16fff.png)
