### ISSUE TITLE
NuScenes Dataset

### ISSUE THREAD

**Issue by zmurez** [nerfstudio-project/nerfstudio#921]
I think it would be valuable to the research community to support the NuScenes dataset (https://www.nuscenes.org/nuscenes). This is a relatively large real world multi camera driving dataset popular in many areas within computer vision. This type of dataset presents many interesting challenges (notably dynamic objects) and exciting applications.

I think it would be relatively straightforward to add a dataparser to support this dataset. I am happy to open a PR if there is interest?

cc @nikmo33

**Comment by tancik** [comment]
I think that would be a great addition. Feel free to create a PR.
