### ISSUE TITLE
subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Dy111111** [nerfstudio-project/nerfstudio#923]
When I tried to install tiny-cuda-nn, I met an error, and I don't know how to resolve it, does anyone know how to solve this problem? I would appreaciate it if somebody can give me some advice.
![image](https://user-images.githubusercontent.com/54992494/200573753-b7b86e39-cc8e-4799-b2ba-2b3cae604670.png)

**Comment by kevinddchen** [comment]
What does running `which g++` do on your machine?

**Comment by kevinddchen** [comment]
Also `gcc --version` while youre at it

**Comment by Dy111111** [comment]
thank you very much, I guess maybe there's something wrong with my original g++ version, after I reinstalled g++ and gcc, this problem is solved.

**Comment by qua1121** [comment]
If you are using ubuntu, try 
sudo apt update
sudo apt install gcc
sudo apt install g++
