### ISSUE TITLE
circular imports

### ISSUE THREAD

**Issue by jake-austin** [nerfstudio-project/nerfstudio#928]
**Describe the bug**
This is specifically for interactive / command line python when I try to import any kind of data parser, I encountered it while debugging a custom dataparser. To be clear: this *isn't* an error that occurs when using something like ns-train, it happens when you try and import from nerfstudio in command line python

It is fixed when you comment out everything below this line in the base_configs.py file https://github.com/nerfstudio-project/nerfstudio/blob/c5c980dd4dbf7e35bd94e54bf5d39709e0d40398/nerfstudio/configs/base_config.py#L183 where the circular import is stemming from

**To Reproduce**
1. activate nerfstudio venv
2. start up python

```
>>> from nerfstudio.data.dataparsers.nerfstudio_dataparser import Nerfstudio, NerfstudioDataParserConfig
[Error occurs]
```

**Expected behavior**
Should import without issue in command line

**Screenshots**
```
>>> from nerfstudio.data.dataparsers.nerfstudio_dataparser import Nerfstudio, NerfstudioDataParserConfig
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jake-austin/nerfstudio/nerfstudio/data/dataparsers/nerfstudio_dataparser.py", line 31, in <module>
    from nerfstudio.data.dataparsers.base_dataparser import (
  File "/home/jake-austin/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py", line 27, in <module>
    import nerfstudio.configs.base_config as cfg
  File "/home/jake-austin/nerfstudio/nerfstudio/configs/base_config.py", line 185, in <module>
    from nerfstudio.pipelines.base_pipeline import VanillaPipelineConfig
  File "/home/jake-austin/nerfstudio/nerfstudio/pipelines/base_pipeline.py", line 40, in <module>
    from nerfstudio.data.datamanagers.base_datamanager import (
  File "/home/jake-austin/nerfstudio/nerfstudio/data/datamanagers/base_datamanager.py", line 36, in <module>
    from nerfstudio.data.dataparsers.blender_dataparser import BlenderDataParserConfig
  File "/home/jake-austin/nerfstudio/nerfstudio/data/dataparsers/blender_dataparser.py", line 27, in <module>
    from nerfstudio.data.dataparsers.base_dataparser import (
ImportError: cannot import name 'DataParser' from partially initialized module 'nerfstudio.data.dataparsers.base_dataparser' (most likely due to a circular import) (/home/jake-austin/nerfstudio/nerfstudio/data/dataparsers/base_dataparser.py)
>>> 
```

**Additional context**
This isn't pressing, just would be a quality of life upgrade to make using command line python easier for debugging and testing things out.

**Comment by javieryu** [comment]
I ran into this while debugging too!

As a short-term solution you can use the following workflow:
![Screenshot from 2022-11-10 12-55-21](https://user-images.githubusercontent.com/17129398/201204003-0ff4d05d-d51d-4de4-a410-8cfd433c8889.png)
