### ISSUE TITLE
Viewer documentation out of date?

### ISSUE THREAD

**Issue by paulmelis** [nerfstudio-project/nerfstudio#943]
**Describe the bug**

Is the documentation on self-hosting the viewer on https://docs.nerf.studio/en/latest/developer_guides/viewer/viewer_overview.html up to date? It mentions `scripts/viewer/run_bridge_server.py`, but I don't see that anywhere in the repo (main branch).

One reason to want to fully self-host the viewer is because https://viewer.nerf.studio/ appears to return 404 with the link shown by ns-train.

**Comment by tancik** [comment]
Yea, the documentation is a little out of date, we will update. For running the viewer locally, you can skip that section, once the dependencies are setup (node, yarn), you can just run `yarn start` in the `nerfstudio/viewer/app` folder.

Also the 404 error should now be fixed. For some reason the github action build script timed out
