### ISSUE TITLE
Render fails silently traj="interp" mode (with custom data)

### ISSUE THREAD

**Issue by ManuConcepBrito** [nerfstudio-project/nerfstudio#951]
**Describe the bug**
When using ns-render (in google colab) and with custom images, the render "finishes" (cell executes successfully without any error), however, there's no output. The same command works well with traj="spiral"

**To Reproduce**
Executing the following command fails to output any video/rendering:
`!ns-render --load-config $config_filename --traj=interp --output-path renders/output.mp4`

However, changing the trajectory mode to spiral produces a correct video:
`!ns-render --load-config $config_filename --traj=spiral --output-path outputs/renders/output.mp4`

**Additional context**
I've checked the documentation for some pre-requisites to run the interpolation mode, but I didn't find anything.

Thanks!

**Comment by ManuConcepBrito** [comment]
I just checked in https://github.com/nerfstudio-project/nerfstudio/blob/main/scripts/render.py (line 140) that the method is not implemented. However, the error does not get propagated in colab.

**Comment by tancik** [comment]
Yea, colab unfortunately fails to propagate the logs. I'm going to just remove this option from the script to avoid this confusion in the future.

**Comment by ManuConcepBrito** [comment]
Quick question, is there a plan to implement this/open to contribution? I could take a look cause it would be quite helpful for the project I am currently working on.

**Comment by tancik** [comment]
Adding this isn't in the short term plans. We will happily take contributions though!
