### ISSUE TITLE
How to reload training results in web page？

### ISSUE THREAD

**Issue by kamen007** [nerfstudio-project/nerfstudio#955]
Hi,when I close my training tenminal, How to reload training results in web page? Now,the way
 I used is to retrain the data ,and it cost much time.

**Comment by Claudio9701** [comment]
Hi, I found this flag in the help info for ns-train nerfacto command:

$ ns-train nerfacto -h

```
...
--viewer.no-start-train                                                                             │
│     whether to immediately start training upon loading viewer if False, will just visualize dataset │
│     but you can toggle training in viewer (sets: start_train=False)
...
```
After training your model you can run the ns-train nerfacto command with this flag to visualize the scene without training the model. See the example bellow:

```sh
$ ns-train nerfacto --data {data-dir} --trainer.load_dir {output-dir}/nerfacto/{timestamp}/nerfstudio_models --viewer.no-start-train
```

In the viewer sidebar you should see the "Resume training" button as shown in the figure:

![image](https://user-images.githubusercontent.com/24416566/202184105-ec13a6ff-37b4-47aa-a899-4aca47373002.png)

This indicates the model is not training. Hope this helps!

**Comment by kamen007** [comment]
I found it.  thanks a lot
