### ISSUE TITLE
Where should I download the show page data？

### ISSUE THREAD

**Issue by kamen007** [nerfstudio-project/nerfstudio#970]
Hi, I want to replicate the result in your show page, Where should I download the data？
By the way, what is your method for training the data, Instant-NGP or nerfacto? 
![image](https://user-images.githubusercontent.com/38774126/202410963-3bcffbe7-19ac-4048-86d8-f96865121c0c.png)

**Comment by tancik** [comment]
This result is using the nerfacto method (this is our recommended model). We have not yet made that data public.

**Comment by kamen007** [comment]
I use nerfacto train my uav dataset, the scene just like the figure below, but the result is so blur, the parameters are all by default. Can you give me some proposals to develop my result?  Many thanks
![image](https://user-images.githubusercontent.com/38774126/202608013-88174256-2f84-457e-a463-f50e9456c081.png)

**Comment by tancik** [comment]
My first instinct is that the camera viewpoints arn't varied enough. Ideally you are looking at the scene from many different angles.

Also, consider the [discord](https://discord.gg/uMbNqcraFc), it is easier to help debug "bad result" issues there.
