### ISSUE TITLE
How to view trained model?

### ISSUE THREAD

**Issue by HrsPythonix** [nerfstudio-project/nerfstudio#979]
I have trained model, how can I launch viewer but not to train?

**Comment by tancik** [comment]
Use the same training call, but add the following arguments, `--trainer.load_dir outputs/data-nerfstudio-{data}/{model}/{timestamp}/nerfstudio_models --viewer.start-train False`

**Comment by segments-tobias** [comment]
Is it `load_dir` (as in the docs) or `load-dir` as in the CLI help?

**Comment by brentyi** [comment]
> Is it `load_dir` (as in the docs) or `load-dir` as in the CLI help?

These will produce the same behavior, but the latter is preferred.
