### ISSUE TITLE
Perspective camera model rays?

### ISSUE THREAD

**Issue by paulmelis** [nerfstudio-project/nerfstudio#983]
Not sure this is a bug, but I noticed the visualization of camera rays (pixel centers?) on https://docs.nerf.studio/en/latest/nerfology/model_components/visualize_cameras.html:

![image](https://user-images.githubusercontent.com/1408287/202854890-53c222fa-fbf3-4fcd-9d15-a2e90a92a8f7.png)

To me this doesn't make much sense, with each ray (or pixel center) apparently having a fixed angular offset compared to its neighbors. Shouldn't this be a perspective projection that assumes a flat image plane in front of the camera, with a uniform pixel width, causing varying angles between the rays? 

The current visualization for the perspective camera is pretty much the same as for the fisheye model, which should not be the case. But maybe I'm misunderstanding what that visualization is supposed to show and/or you're doing some form of weighting per ray based on the pixel it contributes to. Also, I did notice the CamerasV2 branch, so maybe this is something that's being worked on.

**Comment by devernay** [comment]
Place the viewpoint at the camera center: it should look like a square grid, and it does.
<img width="730" alt="image" src="https://user-images.githubusercontent.com/3778071/202868566-ee5b3d73-d1b4-441f-9b08-24b09b4d7224.png">
The angular density is not even at all, as can be seen below: less density in the center, more density in the corners
<img width="545" alt="image" src="https://user-images.githubusercontent.com/3778071/202868605-dbc7e901-552a-4736-8df0-8e8ca14a6752.png">
You were misled by the fact that this visualizes the directions, not the pixel positions in the image plane. Besically, this visualization takes the vector from the camera center to the pixel center, and normalizes it to unit length.

This issue should be closed

**Comment by paulmelis** [comment]
You're right, I wasn't convinced myself actually that the projection wasn't correct. But the plot is indeed misleading, especially for the vertical direction the angular steps seems constant. The lack of an orthographic view in the plotly plot doesn't help. Just dumped the ray data to a file Blender can read, and now the regular pixel spacing shows clearly:

![image](https://user-images.githubusercontent.com/1408287/202870529-68fe2785-75fa-4a57-93c9-5c1cd8996da4.png)

![image](https://user-images.githubusercontent.com/1408287/202870582-ab857330-9894-4455-8a2b-a6af6997ef65.png)

Will close this one, sorry for the noise...
