### ISSUE TITLE
Render fails silently (in google colab)

### ISSUE THREAD

**Issue by Abdessamad-Taoufiq** [nerfstudio-project/nerfstudio#984]
When rendering a 20 seconds video in google colab and with custom images, the render "finishes" (cell executes successfully without any error), however, there's no output. 
But when video length is set to <4 seconds. the render works well and produces an output.

**Comment by akristoffersen** [comment]
I will take a look at this-- unfortunately there is a bug in Google Colab at the moment where not all of the cell output is being shown, so it is a bit difficult to debug.

By chance, did you notice that the memory usage was getting high? I doubt that was the issue but maybe the cell ran out of memory and failed to complete.

**Comment by akristoffersen** [comment]
Ah, I think it did run out of memory then. Currently, all frames are stored in memory before they are written out to a full video. 

For now I think you'd have to limit the length of the videos on Colab-- I can add an issue about possibly writing the frames to a temporary directory during rendering so the length of the video wouldn't matter.

**Comment by tojiboyevf** [comment]
Hi! I also have a similar issue. Rendering code executes without error in colab. But no any output at the end. In my case it didn't run out of memory. I run `instant-gpt` model. I didn't change the default parameters: video duration, fps and others
