### ISSUE TITLE
Error running command: colmap

### ISSUE THREAD

**Issue by Imzachjohnson** [nerfstudio-project/nerfstudio#985]
While running "ns-process-data video" in a Codna environment I get the error:

"Error running command: colmap"

**Screenshots**
![Screenshot 2022-11-19 143940](https://user-images.githubusercontent.com/7493422/202874330-cd42e7e0-b319-4e29-887b-71dfc2a1b04a.png)

**Additional context**
Colmap installed via the method here:

https://github.com/conda-forge/colmap-feedstock

**Comment by Imzachjohnson** [comment]
This was being caused by missing DLLs in the Windows System32 folder. In this case "mpr.dll" and "mpir.dll". Not sure why, when or how those were missing but fixed by building those via `vcpkg` and placing them in System32.

`vcpkg install mpir mpir:x64-windows`
`vcpkg install mpr mpir:x64-windows`

**Comment by Sinicyn78** [comment]
I have the same problem. But when I try to install colmap or mipir I get the following error
![image](https://user-images.githubusercontent.com/93261532/216047441-c1d1a4ba-1b44-487b-ac9c-5910ac3b6261.png)

**Comment by oliviano** [comment]
I had the same issue, my system didn't have mpir.dll, followed [Imzachjohnson](https://github.com/Imzachjohnson) instruction and I can use colmap. Inside your nerfstudio env, simply running colmap will tell you if you are missing those dl's.

**Comment by Randomblock1** [comment]
You can also install `mpir` from conda-forge.
