### ISSUE TITLE
Where is transforms_train.json

### ISSUE THREAD

**Issue by yukaariki** [nerfstudio-project/nerfstudio#987]
**Describe the bug**
I just do following 
# Download some test data:
ns-download-data --dataset=nerfstudio --capture=poster
# Train model
ns-train nerfacto --data data/nerfstudio/poster

I have error
FileNotFoundError: [Errno 2] No such file or directory: 'data/nerfstudio/poster/transforms_train.json'

I I've searched through the data set.
I have looked for "transforms_train.json" file in the dataset, but it doesn't seem to be there.
How to do that

**Comment by Srgr0** [comment]
I have the same problem, and it also happens in the storefront model.

**Comment by tancik** [comment]
Does the folder `data/nerfstudio/poster` exist? If so what files are in side of it? If it does not exist, when running the download script, when is the file path you see above the downloading bar?
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/3310961/202920615-90a24510-4674-448e-9a3f-136f21d5d915.png">

**Comment by jingweim** [comment]
`pip install tyro==0.3.33` solved the problem for me. 

Previously the version was `tyro==0.3.34`. Somehow with `0.3.34` the `nerfacto` option loads the DNeRF dataparser instead of the nerfstudio dataparser (the prior loads `transforms_train.json` instead of `transforms.json`)

**Comment by brentyi** [comment]
Sorry for the trouble + thanks for the report; I just yanked `tyro==0.3.34` from PyPI. Still working on reproducing and won't re-release until it's fixed.

**Comment by yukaariki** [comment]
Thank you for all comment.
All my problems were solved by  jingweim suggestions.
Thank you!
