### ISSUE TITLE
Error occurred when training mipnerf on custom data

### ISSUE THREAD

**Issue by lhj9512** [nerfstudio-project/nerfstudio#996]
FileNotFoundError: [Errno 2] No such file or directory: '/Data/lhj/chongqing_nerf/transforms_train.json.
So, may I ask how to solve this problem?

**Comment by tancik** [comment]
Can you first check that you, are not running `tyro==0.3.34`, this was throwing the same error #987 
Next, does the transforms.json file exist in that directory?

**Comment by VelocityRa** [comment]
This happens for me too, and I did run `pip install tyro==0.3.33` which completed successfully.

@tancik Are you sure that workaround works for mipnerf too?

I'm training on the 'poster' dataset if that matters. 
And what about training our own data from ie. Polycam, - is there a way of generating `transforms_train.json` using something like COLMAP?

**Comment by tancik** [comment]
Add `nerfstudio-data` to the end of your command. The mipnerf model defaults to using the blender dataparser.
